### ISSUE TITLE
LDAP mail field is not configurable

### ISSUE THREAD

**Issue by thomascate** [chef/chef-server#1000]
Hi,

Currently when LookupFields is populated with a users ldap information it pulls "email" for the "mail" attribute. However some organizations use custom fields for email causing the ldap account mappings to be non-functional. Ideally a user should be able to modify this field. 

Here's where the mail attribute is currently being hard set.
https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/oc_chef_wm/src/oc_chef_wm_authn_ldap.erl#L198-L206

Thanks,
Thomas Cate

**Comment by stevendanna** [comment]
@thomascate I'm close this because I think it is already covered by this older issue here: https://github.com/chef/chef-server/issues/104

If I've misunderstood, let me know and we can reopen it.
