### ISSUE TITLE
failed to upload environment setting - FFI_Yajl::ParseError:

### ISSUE THREAD

**Issue by swade1987** [chef/chef-server#101]
Hi all,

I am trying to update a cookbook version on my Chef 12.0.3 environment file.

The source code for this is [here](http://hastebin.com/imabewafes.pl)

However, when it comes to uploading I obtain the following error

    ERROR: FFI_Yajl::ParseError: lexical error: invalid char in json text.
                                       ???{"name":"ci","description":"
                     (right here) ------^

Any anyone shed some light on how to resolve this please?

**Comment by stevendanna** [comment]
This looks the same as #100.  I'm going to close this one out, let me know if I was mistaken.
