### ISSUE TITLE
execute("initctl status private-chef-runsvdir") do

### ISSUE THREAD

**Issue by SingerWang** [chef/chef-server#1015]
Note that per https://docs.chef.io/release/server_12-8/install_server_pre.html Ubuntu 16.04LTS is a supported platform...

I tried to install Reporting and when I run the

```
opscode-reporting-ctl reconfigure
```

I get the following error:
```
  * execute[initctl status private-chef-runsvdir] action run

    ================================================================================
    Error executing action `run` on resource 'execute[initctl status private-chef-runsvdir]'
    ================================================================================

    Errno::ENOENT
    -------------
    No such file or directory - initctl

    Cookbook Trace:
    ---------------
    /opt/opscode-reporting/embedded/cookbooks/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /opt/opscode-reporting/embedded/cookbooks/cache/cookbooks/enterprise/recipes/runit_upstart.rb

     28: execute "initctl status private-chef-runsvdir" do
     29:   retries 30
     30: end
     31:

    Compiled Resource:
    ------------------
    # Declared in /opt/opscode-reporting/embedded/cookbooks/cache/cookbooks/enterprise/recipes/runit_upstart.rb:28:in `from_file'

    execute("initctl status private-chef-runsvdir") do
      action [:run]
      retries 30
      retry_delay 2
      default_guard_interpreter :execute
      command "initctl status private-chef-runsvdir"
      backup 5
      returns 0
      declared_type :execute
      cookbook_name "enterprise"
      recipe_name "runit_upstart"
    end


Running handlers:
[2016-11-15T21:55:25+00:00] ERROR: Running exception handlers

```
Ubuntu 16.04 runs systemd, not upstart. So it won't work. Is there a way to fix it? 

I found this related ticket (https://github.com/chef/chef-manage-issues/issues/88) but at that time Ubuntu 15.04 with systemd wasn't a supported platform. Now Ubuntu 16.04 with systemd is offically supported.

**Comment by stevendanna** [comment]
@SingerWang Thanks for taking the time to report this issue.  It is true that chef-server supports 16.04, but it appears that the Reporting add-on has not yet been updated to support 16.04 as well.  

Since this is a problem with the reporting plugin, would you mind filing an issue with Chef's support team via support@chef.io.  We try to keep the issue list here related to issues in the Chef Server code base.  Apologies for the extra work.

**Comment by msnorman343** [comment]
@stevendanna , was this resolved?

**Comment by fourth-barryleonard** [comment]
@msnorman343 I raised a case with Chef support at the end of December 2016 and was told that this was still a known issue and that the development team were working on it. I was offered a workaround (which we haven't tried as we'd rather wait for the support to be there) which was:

Install upstart using 'sudo apt-get install upstart-sysv'
Run 'sudo update-initramfs -u'
Reboot the box.
After this, 'sudo opscode-reporting-ctl reconfigure' should work

(please note that this permanently replaces systemd with upstart)

**Comment by stevendanna** [comment]
Apologies for the delay, as @fourth-barryleonard indicated, this is still open as far as I know.

**Comment by msnorman343** [comment]
Thank you @fourth-barryleonard  and @stevendanna, for this info.  I will give it a go and see if it is worth, otherwise i will revert

**Comment by rbarna1** [comment]
Tried to swap to upstart-sysv on Ubuntu 16.0.4, oper @fourth-barryleonard , no dice.
How frustrating that this was closed but is clearly an issue
