### ISSUE TITLE
Unify log rotation with chef-server-ctl

### ISSUE THREAD

**Issue by pburkholder** [chef/chef-server#102]
I've been asked about this and it seems reasonable to include log rotation as a feature. Since there are so many logs, maybe a 'chef-server-ctl rotate-logs' command.

@obazoud @GolubevV note this replaces https://github.com/opscode-cookbooks/chef-server/issues/63

**Comment by stevendanna** [comment]
Chef-server already does setup log rotation for its log files.  It would be great if we could include some more detail on what people are looking for.  As some background, here is how log rotation is currently handled in Chef Server:

- A logrotate configuration file and a cron-job to run the rotation is configured on installation:

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/recipes/log_cleanup.rb#L28-L40

- Services that require log rotation place additional log rotation configuration on disk:

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/recipes/nginx.rb#L180-L191

- The settings for this rotation are configurable on a per-service basis via attributes (and thus in chef-server.rb):

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/attributes/default.rb#L294-L296

- Erlang services rotate their logs internally (via the logging library they use); however, rotation is configurable using the same type of parameters:

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/attributes/default.rb#L165-L167

For the logs that are rotated using logrotate, you can force a rotation by using:

   logrotate -f /etc/opscode/logrotate.conf

If there are existing logs that aren't being rotated via these mechanisms, we should make sure those get filed as bugs (in addition to this report).

(cc @jtimberman who was also on the original ticket)

**Comment by obazoud** [comment]
And what about Chef Server OSS 11 ?

**Comment by stevendanna** [comment]
@obazoud As far as I know, Chef Server 11 does not have the logrotate configuration built-in (based on your terse question I'm assuming you have discovered this already?). 

If it was sufficient, the same log rotation setup present in Chef 12 could likely be added to 11.  However, I can't speak to how likely it is that Chef Software, Inc employees would work on such a feature (new work typically happens on 11 and in this case the user can easily setup logrotate like they would for most other services they run).

**Comment by stevendanna** [comment]
I'm going to close this ticket out as it appears that log rotation is Chef Server 12 is relatively centralized and Chef Server 11 work is primarily focused on critical bug fixes and security patches.  If there are specific log rotation issues, we will certainly tackle those.
