### ISSUE TITLE
Implementing RFC 67 - Cookbook Segment Deprecation

### ISSUE THREAD

**Issue by thommay** [chef/chef-server#1023]
https://chef.github.io/chef-rfc/rfc067-cookbook-segment-deprecation.html

Wanted to drop a proposal for how this work might look, since it's relatively involved. 

Presently, the metadata for a cookbook contains segments:
```json
"recipes": [ {"name": "default.rb", "checksum":"...", "path":"recipes/default.rb", "specificity": "..." } ],
"templates": [ {"name": "default.erb", "checksum":"...", "path":"templates/default/default.erb", "specificity": "..." } ], 
"root_files": [ {"name": "metadata.rb", "checksum":"...", "path":"metadata.rb", "specificity": "..." }]
```

deprecating the segments would, per the RFC, result in a json object like:
```json
"all_files": [ 
  {"name": "recipes/default.rb", "checksum":"...", "path":"recipes/default.rb", "specificity": "..." }, 
  {"name": "templates/default.erb", "checksum":"...", "path":"templates/default/default.erb", "specificity": "..." }
  {"name": "metadata.rb", "checksum":"...", "path":"metadata.rb", "specificity": "..."}
]
```
Note that this adds the segment path in to the name.

The implementation then might be:

- [ ] Migrate all cookbook_version objects to the new format
- [ ] v0 uploads get rewritten to the new format
- [ ] v0 GETs rewrite `all_files` to the set of segments, ignoring any files that are in places not supported by current segments
- [ ] add v2 as new max API version
- [ ] implement v2 uploads and downloads

Thoughts @chef/chef-server-maintainers @lamont-granquist ?

**Comment by lamont-granquist** [comment]
yeah that was the intended thing.  i think there's supposed to be an intermediate case where we ship both of those, but can't recall if we can avoid that with server api versioning or not, haven't read the RFC in awhile...

**Comment by thommay** [comment]
Thinking more and talking to @stevendanna , we probably don't want to do a migration, since this will be very expensive. 
Instead:

- v0 requests of old cookbooks get v0 responses.
- v2 requests of old cookbooks get transformed responses, and - maybe - store the v2 version in a new column
- v2 uploads of new cookbooks get stored (in a new column? or do we just set a flag that says that this is a v2 upload?)
- v2 downloads of new cookbooks get v2 responses
- v0 downloads of new cookbooks get transformed responses, and - maybe - store the v0 version in the old column (this is the case where the user upgrades their workstation to a new chefdk but is still running chef 10 in production).

the v2 -> v0 transformation is lossy - any files that can't be lined up with a segment will simply be dropped on the floor, which is fine since the client won't know what to do with them anyway.

**Comment by stevendanna** [comment]
> v2 requests of old cookbooks get transformed responses, and - maybe - store the v2 version in a new column

A possible alternative to a new column is for the serialized_object to contains a version field.  If the field is missing you can assume it is the old format, if the version is 1, assume it is the new format. Since v0 -> v2 isn't lossy, I don't think there is harm in storing v0 uploads using the v2 format. v2->v0 is only lossy if someone uploads something from a new segment, which won't be the case if the original uploader was using v0.

**Comment by marcparadise** [comment]
I'd prefer to keep things that aren't under the control of the chef client out of `serialized_object`.  Adding a new nullable column is a routine partybus/sqitch upgrade case, and i think it's the right way to go here.

**Comment by stevendanna** [comment]
> I'd prefer to keep things that aren't under the control of the chef/knife client out of serialized_object.

Good call.

**Comment by btm** [comment]
This was implemented in https://github.com/chef/chef-server/pull/1034.
