### ISSUE TITLE
Add knife-ec-backup to core

### ISSUE THREAD

**Issue by vinyar** [chef/chef-server#1036]
## Description

* Presently, knife-ec-backup is the only way to create a backup of a running system with zero downtime.
* Chef server can run with external data base, and the only way to back it up is with knife-ec-backup (https://docs.chef.io/server_backup_restore.html#id1)

## Chef Version

all chef server versions are missing knife-ec-backup from install.

## Platform Version

Ubuntu/CentOS

## Replication Case

On chef server, execute root@default-ubuntu-1404: /opt/chef/embedded/bin/gem list knife

Internal references:
https://getchef.zendesk.com/agent/tickets/13022
https://getchef.zendesk.com/agent/#/tickets/9379
https://chefio.atlassian.net/browse/TRI-118

**Comment by stevendanna** [comment]
knife-ec-backup is include in Chef Server: https://github.com/chef/chef-server/blob/master/omnibus/config/software/knife-ec-backup-gem.rb

It should be in the list if you run `/opt/opscode/embedded/bin/gem list`
