### ISSUE TITLE
Mapping Capability Between LDAP and Chef Server 12 Attributes

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#104]
As a customer, I would like the Chef Server 12 LDAP module to be able to map between attributes appearing in an LDAP user record, and the required attributes like "mail:"

For example, having the Chef Server 12 LDAP module understand a mapping like this between the required attribute "mail:" and the attribute that I have in my LDAP user record "UserPrincipalName:" would be extremely helpful

```
mail: -> UserPrincipalName:
```

Making this capability available for all required fields would be ideal.

Zendesk 3083

**Comment by pburkholder** [comment]
On a related issue:

> It looks like the GroupDN filter in oc_erchef/apps/oc_chef_wm/src/oc_chef_wm_authn_ldap.erl breaks on nested groups. At first glance, it seems like enumerating GroupDN's nested groups' members would be the most rudimentary fix. That would also (probably) keep our Windows admins from putting a hit out on me.

**Comment by stevendanna** [comment]
For the group issue, I think another possible solution is to use the LDAP_MATCHING_RULE_IN_CHAIN matching rule.  We'd have to look at how widely that is supported.

**Comment by stevendanna** [comment]
I've opened https://github.com/chef/chef-server/issues/153 for the issue that @pburkholder mentioned
