### ISSUE TITLE
chef-server-ctl user-create misleading error message.

### ISSUE THREAD

**Issue by ricksebak** [chef/chef-server#1043]
Using chef-server-ctl, if you try to create a user, and that user has the same email address as another already-existing user, you will get an error saying that the user you are trying to create already exists. This is misleading because the user you are trying to create doesn't already exist, you just need to use a unique email address for the new user.

```
[root@ip-10-177-178-11 ec2-user]# chef-server-ctl user-list
john_robison
pivotal
[root@ip-10-177-178-11 ec2-user]# chef-server-ctl user-show john_robison | grep email
email:        john.robison@cloudreach.com
[root@ip-10-177-178-11 ec2-user]# chef-server-ctl user-create other_user Other User john.robison@cloudreach.com somepassword
ERROR: Conflict
Response: User 'other_user' already exists
```

This is chef-server-core-12.11.1-1.el7.x86_64 on RHEL 7.

**Comment by stevendanna** [comment]
Apologies that you hit this.  I've opened an issue for this bug here: https://github.com/chef/chef-server/issues/59 so I'm going to close this one as a duplicate.  However, thank you for taking the time to report the issue!
