### ISSUE TITLE
Publicly exposed bifrost port (9683) 

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#1060]
Chef Server currently exposes bifrost via reverse proxy from nginx on port 9683. This is leftover from the separation between internal/external LB.

Determine if this is still used  - a cursory glance suggests that it no longer is. 

If it's completely unused, remove the configuration from nginx; if it is still used internally, update it so that it listens only on localhost.

**Comment by stevendanna** [comment]
It might also be nice to consider whether we can remove the erchef internal_lb port.  If we could get rid of both, then I think in the default installation, 443 and 80 are the only ports we would listen on externally by default.

**Comment by jashaik** [comment]
PR - #2352
Build tag - 14.2.23+20210406060210
