### ISSUE TITLE
A Chef Server Backup System Should Be Productized and Bundled

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#107]
As a customer, I would like something more integrated and comprehensive than http://docs.chef.io/server_backup_restore.html

In OPC and EC11, we had access to the drbd-backups script https://github.com/chef/opscode-omnibus/blob/11.1-stable/files/private-chef-scripts/drbd-backups, which made an attempt to make a consistent backup of the DRBD data area with no downtime through LVM snapshotting. Currently, in Chef Server 12, there is no such provision.

This addition will give more peace of mind in disaster situations.

**Comment by stevendanna** [comment]
@ryancragun Mind if I assign this one to you?  Would love to see the work you were doing on `chef-server-ctl backup` as a PR if it is close to ready.  Even if it doesn't have every feature you want, it is probably better to get it in and iterate.

**Comment by sean-horn** [comment]
Thanks, @stevendanna Good thought.

**Comment by ryancragun** [comment]
Sounds good @stevendanna & @sean-horn.  It's just about ready to ship.  I"ll make it a priority when I'm back from onsite work next week.

**Comment by irvingpop** [comment]
The PR for this issue is still labelled WIP and is currently failing Travis tests.  We should get that fixed up. cc: @ryancragun https://github.com/chef/opscode-omnibus/pull/739

**Comment by ryancragun** [comment]
Hey Irving,

I yanked the WIP label and I'm 99% sure that the travis tests were failing
at the time because of other things on master and not the bits that I
changed.  I'll rebase and kick off a travis run to be sure.

- Ryan

On Wed, Apr 29, 2015 at 9:58 AM, Irving Popovetsky <notifications@github.com

**Comment by ryancragun** [comment]
Yep, it's all good to merge

**Comment by stevendanna** [comment]
This has been merged as a support feature for a few releases now.
