### ISSUE TITLE
Partial Search Invalid JSON

### ISSUE THREAD

**Issue by dolvany** [chef/chef-server#1071]
chef-server 12.11.1

The partial search request body suggested in [chef-web-docs](https://docs.chef.io/api_chef_server.html#id76) results in the chefapi responding with an invalid json error.
```
$ ./chefapi POST "/search/node" "{'name' => [ 'name' ]}"
{"error":["invalid JSON"]}
```

**Comment by stevendanna** [comment]
@dolvany Thank you for pointing this out! This appears to be a documentation issue in which the documentation is not being clear in its usage of the ruby representation of the POST body versus the actual JSON that needs to be sent over the wire.

The POST body provided in your example is a Ruby hash that would need to be converted to its equivalent valid JSON:

    {"name": [ "name" ]}

**Comment by dolvany** [comment]
Thx, I created a pull request to correct the doc.
