### ISSUE TITLE
Chef rotate all keys -- rotates a deleted key

### ISSUE THREAD

**Issue by mo-martin** [chef/chef-server#1079]
A vault item was once created with as ‘xxxx_keys’ in the name. Once this was encrypted as a data bag it created ‘xxxx_keys_keys’, realizing this was a problem we deleted any trace of it in the data bag’s and vaults. But now when we run the command `knife vault rotate all keys’ it will try to rotate the now delete ‘xxxx_keys’ vault item.

**Comment by stevendanna** [comment]
@mo-martin Do you have reason to think this is a server-side issue?  Perhaps this bug would be better filed against chef/chef-vault.  One thought is whether chef-vault is using search to populate the list of items to rotate; however, from what I can see in that code base, it is not using search to get the list of vaults to rotate.  If you do move this to chef/chef-vault, I would be sure to run the command with `-VV` and provide the debug output so we can see what is going on.

**Comment by mo-martin** [comment]
I've found the issue.. So if '_keys' is anywhere in the name of the vault item, the rotate vault keys command will dismiss the rest of the vault item name and attempt to rotate a key on an invalid name... 
Example :
Test_keystore - is read as - Testtore_keys_keys. 
And
Test_keystore2 - is read as - Testtore2_keys_keys. 

It wasn't attempting to read a deleted vault item, it just seems to escape the string as soon as '_keys'  is read. 

Solution - don't use '_keys'  anywhere in the name.

**Comment by stevendanna** [comment]
@mo-martin Thanks for digging into this further, I've opened move this issue here: https://github.com/chef/chef-vault/issues/257
