### ISSUE TITLE
sudo chef-server-ctl reconfigure

### ISSUE THREAD

**Issue by jigishmehta86** [chef/chef-server#108]
Hi,

Can someone help me solve this issue?

-------------------

Recipe: private-chef::postgresql

* user[opscode-pgsql] action create

Error executing action create on resource 'user[opscode-pgsql]'

Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
STDOUT: 
STDERR: usermod: user opscode-pgsql is currently logged in
---- End output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
Ran ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] returned 8

Resource Declaration:

In /opt/opscode/embedded/cookbooks/private-chef/recipes/postgresql.rb

27: user node['private_chef']['postgresql']['username'] do
28: system true
29: shell node['private_chef']['postgresql']['shell']
30: home node['private_chef']['postgresql']['home']
31: end
32:

Compiled Resource:

Declared in /opt/opscode/embedded/cookbooks/private-chef/recipes/postgresql.rb:27:in `from_file'

user("opscode-pgsql") do
action :create
supports {:manage_home=>false, :non_unique=>false}
retries 0
retry_delay 2
guard_interpreter :default
username "opscode-pgsql"
home "/var/opt/opscode/postgresql"
shell "/bin/sh"
system true
cookbook_name :"private-chef"
recipe_name "postgresql"
end

Running handlers:
[2015-02-23T18:10:13+00:00] ERROR: Running exception handlers
Running handlers complete

[2015-02-23T18:10:13+00:00] ERROR: Exception handlers complete
[2015-02-23T18:10:13+00:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 5 resources updated in 165.203813884 seconds
[2015-02-23T18:10:13+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: useropscode-pgsql had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
STDOUT: 
STDERR: usermod: user opscode-pgsql is currently logged in
---- End output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
Ran ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] returned 8

**Comment by mmzyk** [comment]
I'm going to close this out for now, as it's not clear what has gone on with @jigishmehta86's setup, but something odd is going on. In other tickets I've informed them the best course of action is to wipe clean and start over, ideally with Chef server 12 (see here https://github.com/chef/chef/issues/2972 for instance).

@jigishmehta86 Should you run into more issues, please feel free to open a new issue and we'll work with you to get through it.

**Comment by jigishmehta86** [comment]
cool. Thanks
