### ISSUE TITLE
Error installing opensource Chef

### ISSUE THREAD

**Issue by phanikumar1210** [chef/chef-server#1084]
I am trying to install OpenSource chef instead of opscode chef server. I would like to know what are the configuration changes that I need to make in the source cloned from the git repo. It would be great help to me if I could get some information around it.

I am getting the following error while trying to install opensource chef while running the command ./bin/rake test:csc
[ERROR] Credential rotation failed
[ERROR] Shared credential rotation failed

**Comment by stevendanna** [comment]
Hi @phanikumar1210 As of Chef Server 12, there is only 1 Chef Server and it is completely open source. The packages available from here: https://downloads.chef.io/chef-server/12.12.0 are build from this repository and are the open source chef server.

If you are still interested in building the chef-server from source, the place to start is our test-kitchen based omnibus build environment.  This environment helps ensure you have a clean build setup.  You a process like this should work:

```
cd omnibus/
kitchen converge ubuntu-1204
kitchen login ubuntu-1204
sudo -i
cd /home/vagrant
source ./load-omnibus-toolchain.sh
cd chef-server/omnibus
bundle install 
bundle exec omnibus build chef-server
``

**Comment by phanikumar1210** [comment]
I assume that if we install from the packages provided by Chef https://downloads.chef.io/chef-server/12.12.0 we will have a restriction to 25 nodes it seems.  So, I would like to go with OpenSource Chef instead opscode chef. I would like to install and manage the chef server completely on the OS directly intead of using kitchen and install it on vagrant or docker. Could you please suggest me how I should proceed in this case.

**Comment by danielsdeleo** [comment]
The restriction (25 node limit) only applies to proprietary add-ons such as the manage console (web GUI) and reporting. Chef Server provides an API which those products use to check if you're over the limit, but has no such limit on its own, regardless of whether you download a pre-built package or build your own package.

Is there text on the Chef website that gave you a different impression?
