### ISSUE TITLE
Upgrade embedded Java to Java 8

### ISSUE THREAD

**Issue by tfitch** [chef/chef-server#109]
End of Public Updates for Java 1.7 is coming in April 2015.  http://www.oracle.com/technetwork/java/eol-135779.html

We need the Java embedded in Chef Server to be updated to a Java 8 (1.8).

Currently it is `/opt/opscode/embedded/jre - java version "1.7.0_25"`

Thanks!

**Comment by oferrigni** [comment]
https://github.com/chef/omnibus-software/pull/363 <-- took a quick swing at it.

**Comment by stevendanna** [comment]
This has been merged and should be available in the next release.

**Comment by stevendanna** [comment]
I'm going to close this out.  It is currently available in 12.1.0 RC 1 and will be available in the final 12.1.0 release.
