### ISSUE TITLE
 POST action on ACL endpoint doesn't work

### ISSUE THREAD

**Issue by Thercy** [chef/chef-server#1127]
Hi,

I am creating a wrapper for the ChefServer endpoint. At the moment, I need, after creating a new client (apiclient) to add it under the admins group (either directly under clients or under a custom group with rights). However, I have found no way whatsover to make any of the following work:
 - POST to /groups <-- to create a new group from the API
 - POST to /organizations/ORG/OBJECT_TYPE/OBJECT_NAME/_acl/PERM <-- to add a user/client under on of the defaults or custom groups

I have tried all the above on knife raw/xxx  with no luck either.
Could I get any confirmation on whether this is currently feasible or not?

Many thanks in advance for your help. Regards,
 Thercy

**Comment by stevendanna** [comment]
@Thercy I wonder if you might be hitting this regression currently: https://github.com/chef/chef-server/issues/1127

**Comment by Thercy** [comment]
Hi @stevendanna, I'm afraid you linked it to my own issue #1127. Which one in particular should I refer to? Thanks!!

**Comment by stevendanna** [comment]
@Thercy D'oh! THanks I meant https://github.com/chef/chef-server/issues/938

**Comment by Thercy** [comment]
Hi @stevendanna, I can confirm my client (apiclient) is under the organization (I have created using this endpoint POST /organizations/ORGANIZATIONNAME/clients), but in order to create new objects using this apiclient (instead of pivotal), I need to it be either under the admins group or have CREATE permissions. I have tried both approaches but none of the endpoints seems to work for actions POST.

Any hint on how I could target this please? I have tried every possible way I could think of. I have reproduce what I want to achieve using knife-acl, but I do need to do it from an endpoint.

Many thanks.

**Comment by stevendanna** [comment]
@Thercy You should be able to make the client and admin user via a PUT to /organizations/ORGNAME/groups/admins with the new client added to the group.  If you can accomplish your goal with knife-acl, one thing you can do is append `-VV` to every command you need to run in your procedure.  That will show you (amongst other debug information) which exact endpoints are being posted to.

**Comment by Thercy** [comment]
Hi @stevendanna, thanks for the advise.
I have run knife group add client myclient admins -VV and confirmed it does call as follows: 
- GET for clients/myclient
- GET for groups/admins
- PUT for groups/admins

And this is exactly how I am proceeding currently. I call the GET for groups/admins, and the response is what I used as body for the PUT groups/admins. I have tried to do a PUT with exactly the same response received, without adding my client under clients, with no luck. On every attempt I get  " "Response status code does not indicate success: 400 (Bad Request).", this is why I thought these calls may not be supported.

Many thanks for your time.

**Comment by stevendanna** [comment]
@Thercy Apologies you are having trouble with this.  I'll try to dig into this a bit later tonight and I need to refresh my memory on the current state of these endpoints.

**Comment by Thercy** [comment]
Hi @stevendanna,
I have finally managed to bypass the 400 (Bad Request) error when calling PUT /organizations/ORGNAME/groups/admins, however the changes do not persist.
I will try and elaborate on this below:

I call GET /organizations/ORGNAME/groups/admins, and the response I get is as follows:

> {
>   "actors": [
>     "pivotal"
>   ],
>   "groups": [],
>   "users": [
>     "pivotal"
>   ],
>   "clients": [
>   ],
>   "orgname": "mytestorganization",
>   "name": "admins",
>   "groupname": "admins"
> }

Then I deserialized the JSON into a Custom object and edit it as follows:
_{
  "actors": [
    "pivotal",
    **"mytestorganization_client"**
  ],
  "groups": [],
  "users": [
    "pivotal"
  ],
  "clients": [
    **"mytestorganization_client"**
  ],
  "orgname": "mytestorganization",
  "name": "admins",
  "groupname": "admins"
}_

The endpoint call successes and it responds with exactly the same JSON content I sent as "body" in the request, which it would make me think everything went find. However, no changes have happened to "admins" group. If I perform another GET action, I would get the same initial response (without my changes).

I really apologise for being such a pain, but I have tried really hard to find any documentation on these matters for the last days.

Many thanks.

**Comment by stevendanna** [comment]
@Thercy I /think/ what might be happening is that the PUT body is (confusingly) not the same as what you get back from GET I think.  Check out:

https://github.com/chef/knife-acl/blob/master/lib/chef/knife/acl_base.rb#L164:
```
        new_group = {
          "groupname" => existing_group["groupname"],
          "orgname" => existing_group["orgname"],
          "actors" => {
            "users" => existing_group["users"],
            "clients" => existing_group["clients"],
            "groups" => existing_group["groups"]
          }
        }
```

That is, the body of your PUT should be something like:

```
{
  "actors": {
    "groups": [],
    "users": [
      "pivotal"
    ],
    "clients": [
    "mytestorganization_client"
    ]
  }
  "orgname": "mytestorganization",
  "groupname": "admins"
}
```

Re documentation, this might help: https://chef-server-api-docs.chef.io/#organizations__organization__groups__group__put

**Comment by Thercy** [comment]
@stevendanna can't thank you enough for your help!
As per your last message, I have now successfully performed the PUT /organizations/ORGNAME/groups/admins using exactly the same body format you sent me over, and the changes persisted.

Please take into consideration the required body format for the PUT is not the same format from the GET, which is as follows (from the endpoint):
`{
"actors": [
"pivotal"
],
"groups": [],
"users": [
"pivotal"
],
"clients": [
],
"orgname": "mytestorganization",
"name": "admins",
"groupname": "admins"
}`

You can also check it with knife raw as follows:
`PS C:\opscode\chefdk> knife raw /groups/admins
{
  "actors": [
    "mytestorganization_client",
    "pivotal"
  ],
  "users": [
    "pivotal"
  ],
  "clients": [
    "mytestorganization_client"
  ],
  "groups": [

  ],
  "orgname": "mytestorganization",
  "name": "admins",
  "groupname": "admins"
}`

It would be fantastic if this information could be made available under https://docs.chef.io/api_chef_server.html#groups-group-name
I will thank you once more for all your useful and timely help and close this issue.
Regards,
 Thercy
