### ISSUE TITLE
chef-sync broken since chef-server-core 12.0.4

### ISSUE THREAD

**Issue by jwestboston** [chef/chef-server#113]
The chef-sync system (as a client) is broken when used in conjunction with chef-server-core 12.0.4 and 12.0.5.

This is being done on RHEL 6 (CentOS 6) .. as I'm still waiting for chef-server to work on CentOS 7.

I can post logs if needed, but just try a fresh setup and you will see it does not work. The ec_sync_client process fails to run and logs ruby errors regarding bundle.

**Comment by stevendanna** [comment]
Hi @jwestboston.  Our apologies for this.  I'll get a release soon with a fix.  To get this back up now edit this file:

    /opt/chef-sync/embedded/service/ec_sync_client/bin/ec_sync_client

and change the first line to:

    #!/opt/chef-sync/embedded/bin/ruby

**Comment by jwestboston** [comment]
Excellent, thanks.  This did the trick.

I appreciate the quick response and turnaround.

On a side note, where is the git repository containing the chef-sync code?  And chef-server code?  I'd like to follow them just to get to know the internals better.
