### ISSUE TITLE
Would like a way/instructions to rotate/reset pivotal and webui pems

### ISSUE THREAD

**Issue by chilicheech** [chef/chef-server#1130]
Currently, the recommended way to reset or rotate the pivotal and webui pems is to do a fresh install of Chef Server. It would be very useful from a security standpoint to be able to regularly rotate/reset those keys.

A simple `chef-server-ctl reset-pivotal-pem` and `chef-server-ctl reset-webui-pem` would be awesome. Even just instructions on how to manually do the database surgery for the key rotation/reset would be awesome. I suspect the instructions would be similar to: https://github.com/chef/chef-server/issues/544#issuecomment-142966484

Cheers,

**Comment by stevendanna** [comment]
@chilicheech There is actually a set of features going into the Chef Server right now that might lay the ground-work for some of this.  I agree this would be a good feature to have.

**Comment by PrajaktaPurohit** [comment]
@chilicheech Thank you for reporting this. The secrets rotation work happened in the 12.14.0 release. Please feel free to reopen if needed.
