### ISSUE TITLE
`chef-server-ctl cleanse` removes plugin config, breaking reconfigure

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#115]
After running `chef-server-ctl cleanse` a user in an HA configuration will get the following error on reconfigure:

```
RuntimeError

------------

could not find plugins: ["chef-ha-drbd"]
```

`chef-server-ctl cleanse` removes /var/opt/opscode.  Unfortunately, the plugin loading code here: 

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/recipes/plugins.rb#L1 

looks for the configuration for the plugins in /var/opt/opscode/plugins.  Typically, this is populated via the postinst script:

https://github.com/chef/opscode-omnibus/blob/master/package-scripts/chef-server/postinst#L16-L17

But nothing repopulates the directory after a cleanse.

**Comment by irvingpop** [comment]
Experienced this while working with a customer,  the workaround (via postinst) got us past this:

```bash
mkdir -p /var/opt/opscode/plugins
ln -sf /opt/opscode/chef-server-plugin.rb /var/opt/opscode/plugins/chef-ha-drbd.rb
```

**Comment by stevendanna** [comment]
I think we fixed this in

https://github.com/chef/chef-server/pull/490

since we now load try to explicitly load the two plugins using this system if we don't find any plugins in /var/opt/opscode/plugins:

https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/recipes/plugin_discovery.rb#L18-L19
