### ISSUE TITLE
chef-server-ctl reconfigure requires HOME to be set

### ISSUE THREAD

**Issue by mfdii** [chef/chef-server#116]
When running `chef-server-ctl reconfigure` from a context where $HOME may not be set by the parent process, the reconfigure fails as shown below.

```
[2015-03-03T18:56:48-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid] (private-chef::rabbitmq line 90) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
STDOUT: 
STDERR: erlexec: HOME must be set
```

**Comment by Scythril** [comment]
I also just started seeing this issue 2 days ago. I've got my Chef server as a node on itself (I know...), so if I run chef-client on the machine, it works; if the Chef server initiates the run, it fails with this error.

**Comment by luckymike** [comment]
Any ETA on a fix for this? I just hit it trying to build a chef-server via CloudFormation using the exact same config that worked with a bootstrap template.

**Comment by yhuang** [comment]
@luckymike I got hit with the same issue.  The same script that worked when invoked from the console would fail would called from CloudFormation.  Here is a script from a ChefConf 2015 talk that should help you move forward:

https://github.com/awshat/chefcon2015/blob/master/install-chef-aws.sh

Basically, you have to wrap all your chef-server-tcl calls and opscode-manage-ctl calls with `su -l -c`.  If you do that, the HOME environment variable would be set.

**Comment by mconigliaro** [comment]
Looks like this has been an issue since at least 2013. More info here: https://tickets.opscode.com/browse/COOK-3325

The `su -l -c` workaround worked for me.

**Comment by stevendanna** [comment]
I think this has been fixed by accident since chef-server-ctl now does a `require 'chef'` which ends up requiring `net-ssh` which sets HOME if it isn't set.  However, I'm going to keep this open until a real fix is committed.

**Comment by haidangwa** [comment]
@stevendanna this hasn't been fixed. I just ran into this while deploying a new EC2 instance where my user-data script instals and configures Chef Infra Server 14.11.31.

```
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: Chef Infra Client failed. 27 resources updated in 21 seconds
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: [2022-02-02T20:55:21+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: [2022-02-02T20:55:21+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: [2022-02-02T20:55:21+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[cookbook migration] (infra-server::bookshelf line 51) hadan error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: ---- Begin output of /opt/opscode/embedded/bin/cookbook_migration.sh ----
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: STDOUT:
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: STDERR: erlexec: HOME must be set
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: ---- End output of /opt/opscode/embedded/bin/cookbook_migration.sh ----
Feb  2 20:55:21 ip-10-153-192-92 cloud-init: Ran /opt/opscode/embedded/bin/cookbook_migration.sh returned 1
```

**Comment by tas50** [comment]
@haidangwa I'm merging all the issues that would benefit from a pre-flight check into one issue. This is one of those.

**Comment by tas50** [comment]
Closing in favor of https://github.com/chef/chef-server/issues/4
