### ISSUE TITLE
Create encrypted data bag items from API REST

### ISSUE THREAD

**Issue by Thercy** [chef/chef-server#1164]
Hi all,

I am currently at the point of creating encrypted data bag items using the API Rest endpoint:
PUT /organizations/{organization}/data/{data_bag}/{data_bag_item}

I have been shuffling all around the available documentacion but I had no luck to find anyone doing a similar task. Is this possible at all?

I do create data bags and data items into them using the API Rest, but unfortunately not able to create them encrypted (by using a "secret"). Although, I have done it using Knife as follows:

![image](https://cloud.githubusercontent.com/assets/25326912/24143178/25c042bc-0e29-11e7-896e-676ee3cf8697.png)

Many thanks in advance.

**Comment by Thercy** [comment]
Hi again,

Is there anyone who managed to do this at all??? How could we possible pass the 'secret' to create/get encrypted dataitems using the endpoint:  /organizations/{organization}/data/{data_bag}/{data_bag_item}?

Many thanks!!

**Comment by thommay** [comment]
Hi,
the encryption happens at the client, not the server - you need to send the bag item pre-encrypted. 
In general, you should ask questions like this on our mailing lists at https://discourse.chef.io , where more people will see your question and be able to help you.
Please post your question there, and I'll be closing this ticket.
Thanks,
-Thom

**Comment by Thercy** [comment]
Many thanks @thommay
