### ISSUE TITLE
Chef server import tools do not gracefully handle cookbooks with invalid metadata

### ISSUE THREAD

**Issue by jonlives** [chef/chef-server#118]
Chef-server 12 requires that all cookbooks contain the "name" metadata attribute - I've fixed all of our cookbooks to now contain this attribute, but our current practice is to keep 5 historical versions of each cookbook on our Chef 11 server.

This means that when I dump data from our Chef 11 server and try to import data into our new Chef 12 server, the import fails with a message like:

`ERROR: Chef::Exceptions::MetadataNotValid: Cookbook loaded at path(s) [/tmp/d20150304-2573-1c8d86a/apache] has invalid metadata: The`name' attribute is required in cookbook metadata`

Because some of the historical apache cookbooks downloaded from the Chef 11 server don't have that metadata. It'd be awesome if this was not a fatal error, because currently the only way for me to complete the import is to manually go through and delete the historical versions of each cookbook from prior to the metadata fix....since I suspect you might not want this to be a non-fatal error in all cases, a --continue-on-fail flag or something to allow me to optionally continue past failed cookbook uploads might be a good option here.

**Comment by jblaine** [comment]
I hit this during 11 -> 12 upgrade via the official documented process. My vote here is to sanity check for this issue (perhaps 1 or 2 others) on initial download to /tmp and fail early, but I don't know the specifics of how hard/easy that would be to implement.

**Comment by yulrizka** [comment]
I have the same issue, and thanks @mmzyk for pointing out in #250 that the chef-server is running is available in parallel, So i can start chef-server 11. I thought lost everything.

**Comment by PrajaktaPurohit** [comment]
Closing this since it looks like an upgrade issue and Chef Infra Server 11 is EOL'ed.
