### ISSUE TITLE
Installing opscode-reporting on chef-server v12.17.44 breaks chef irreparably

### ISSUE THREAD

**Issue by kreeuwijk** [chef/chef-server#1208]
Installing opscode-reporting mangles the /etc/opscode/private-chef-secrets.json file

**Comment by marcparadise** [comment]
Hi @kreeuwijk.  As per the instructions in the announcements and releaae notes, it is necessary to upgrade chef server to 12.14 before upgrading any add-on, including Reporting.   

The newly released add-ons are not backwards compatible with 12.13 and earlier.
