### ISSUE TITLE
Bookshelf doesn't work with Amazon S3 in regions other than us-east-1

### ISSUE THREAD

**Issue by structurefall** [chef/chef-server#1237]
Bookshelf breaks when configured to use S3 in any region other than us-east-1.

For a bucket in us-west-2, the following configuration:

```
opscode_erchef['s3_bucket']         = "<BUCKET NAME>"
bookshelf['enable']                 = false
bookshelf['external_url']           = "https://<BUCKET NAME>.s3-us-west-2.amazonaws.com"
bookshelf['vip']                    = "<BUCKET NAME>.s3-us-west-2.amazonaws.com"
bookshelf['storage_type']           = "s3"
```

...returns a response like this on a knife cookbook upload:

`Response:  <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>`

In the S3 logs, you get a message like this:

`HTTP/1.1" 403 SignatureDoesNotMatch 1239 - 5 - "-" "Chef Knife/12.17.44 (ruby-2.3.1-p112; ohai-8.22.0; x86_64-linux; +https://chef.io)" `

If the bucket name is not explicitly specified in the vip and external_url, a different error comes up:

`The AWS Access Key Id you provided does not exist in our records.`

For a bucket in us-east-1, using the s3.amazonaws.com endpoint, everything works fine.

[Issue 1229](https://github.com/chef/chef-server/issues/1229) is probably related to this, although I'm not certain it's identical.

My chef server is on an Amazon Linux host, running chef-server-core-12.14.0-1.el7.x86_64.

**Comment by srenatus** [comment]
For reference: [S3 endpoints and supported signature versions](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) says that in us-west-2, V2 *and* V4 would be supported.

**Comment by codeadict** [comment]
I will implement V4 signature on https://github.com/chef/mini_s3, i think that will fix it all, right @srenatus ?

**Comment by codeadict** [comment]
also related to https://github.com/chef/chef-server/issues/1013

**Comment by stevendanna** [comment]
@codeadict Implementing the require signature algorithm is definitely the place to start.

**Comment by codeadict** [comment]
nice, i already started it.

**Comment by structurefall** [comment]
Hey guys, any movement on this?

**Comment by PrajaktaPurohit** [comment]
@structurefall sorry for the delay in responding to this. This issue is being tracked at: https://github.com/chef/chef-server/issues/1783 And we will start working on it shortly. Closing this issue for now.
