### ISSUE TITLE
Chef 13/14 deprecated functionality used

### ISSUE THREAD

**Issue by iennae** [chef/chef-server#1243]
Noticed a number of issues when using chef-server-ctl that look like they need to get resolved:
<details>

> Deprecated features used!
>   Property `sensitive` of resource `apt_repository` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
>     - /var/opt/opscode/local-mode-cache/cookbooks/apt/resources/repository.rb:60:in `class_from_file'
>    See https://docs.chef.io/deprecations_property_name_collision.html for further details.
>   Property `sensitive` of resource `yum_repository` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
>     - /var/opt/opscode/local-mode-cache/cookbooks/yum/resources/repository.rb:59:in `class_from_file'
>    See https://docs.chef.io/deprecations_property_name_collision.html for further details.
>   node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence) at 7 locations:
>     - /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:57:in `from_file'
>     - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:21:in `from_file'
>     - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:22:in `from_file'
>     - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:23:in `from_file'
>     - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:24:in `from_file'
>     - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:25:in `from_file'
>     - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:26:in `from_file'
>    See https://docs.chef.io/deprecations_attributes.html for further details.
>   An attempt was made to change sysvinit_id from "SV" to nil by calling sysvinit_id(nil). In Chef 12, this does a get rather than a set. In Chef 13, this will change to set the value to nil. at 1 location:
>     - /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:31:in `block in from_file'
>    See https://docs.chef.io/deprecations_custom_resource_cleanups.html for further details.
>   Cloning resource attributes for runit_service[redis_lb] from prior resource
> Previous runit_service[redis_lb]: /var/opt/opscode/local-mode-cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'
> Current  runit_service[redis_lb]: /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/redis_lb.rb:83:in `from_file' at 1 location:
>     - /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/redis_lb.rb:83:in `from_file'
>    See https://docs.chef.io/deprecations_resource_cloning.html for further details.
>   Cloning resource attributes for directory[/var/opt/opscode/nginx/etc/addon.d] from prior resource
> Previous directory[/var/opt/opscode/nginx/etc/addon.d]: /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/oc_id.rb:187:in `from_file'
> Current  directory[/var/opt/opscode/nginx/etc/addon.d]: /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:35:in `block in from_file' at 1 location:
>     - /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:35:in `block in from_file'
>    See https://docs.chef.io/deprecations_resource_cloning.html for further details.
>   Chef::Platform.find_provider_for_node is deprecated at 1 location:
>     - /opt/opscode/embedded/lib/ruby/2.2.0/forwardable.rb:188:in `execute_each_resource'
>    See https://docs.chef.io/deprecations_chef_platform_methods.html for further details.
>   Chef::Platform.find_provider is deprecated at 1 location:
>     - /opt/opscode/embedded/lib/ruby/2.2.0/forwardable.rb:188:in `execute_each_resource'
>    See https://docs.chef.io/deprecations_chef_platform_methods.html for further details.
>   Chef::Platform.find is deprecated at 1 location:
>    See https://docs.chef.io/deprecations_chef_platform_methods.html for further details.

</details>

**Comment by stevendanna** [comment]
Thanks for reporting this @iennae.  I'm going link to this ticket over in https://github.com/chef/chef-server/issues/265 and close this one out.  This is an ongoing battle that we occasionally make progress on.  I that upgrading to Chef 13 will hopefully be a forcing function to get some of these cleaned up:

https://github.com/chef/chef-server/pull/1327
