### ISSUE TITLE
Foslom graphite causes erchef to restart over and over if graphite becomes inaccessible

### ISSUE THREAD

**Issue by mivok** [chef/chef-server#126]
If folsom_graphite is enabled, and the graphite server becomes unavailable, erchef exits, and fails to start, causing runit to restart erchef over and over until the graphite server comes back.

Reproduction case with chef 12.0.5 on ubuntu 12.04:

* Install chef-server
* Run an initial chef-server-ctl reconfigure
* Run `sudo chef-server-ctl status opscode-erchef` and verify it's running ok
* Add the following to /etc/opscode/chef-server.rb:

        folsom_graphite['enabled'] = true
        folsom_graphite['host'] = '127.0.0.1'
        folsom_graphite['send_interval'] = 10

* Re-run chef-server-ctl reconfigure
  * There should be changes to `/var/opt/opscode/opscode-erchef/etc/app.config`
  * The opscode-erchef service should be restarted at the end of the reconfigure run.
* Run `sudo chef-server-ctl status opscode-erchef`
  * The time running will say 0s or 1s, implying it's restarting over and over
  * See /var/log/opscode/opscode-erchef/current or crash.log for info, it will say folsom_graphite can't connect to the graphite server.
* In a new window, run `nc -l 8080` (i.e. start a fake server listening on port 8080)
* Run `sudo chef-server-ctl status opscode-erchef` after a little while, and it's now no longer restarting over and over (time running should say several seconds to a few minutes)
* Run `sudo chef-server-ctl test` - this is just to generate some activitiy against the API. You should start seeing stats spewing in the netcat window.
* Press CTRL-C in the netcat window
* The tests should start failing with 500 errors.
* Re run `sudo chef-server-ctl status opscode-erchef` and verify that the server is restarting over and over once more.

This also affects hosted if folsom_graphite is enabled.

Ideally we would want folsom_graphite not to take down erchef if it can't connect to graphite, and just retry connecting every so often until it can connect.

**Comment by marcparadise** [comment]
Fix is here: 
https://github.com/chef/folsom_graphite/pull/12

It will get pulled into the next release of chef-server. 

Note that you can also simulate a graphite server to test connection loss via `nc -l -p 8080`in the test vm. 

Leaving this open for now until the necessary opscode-omnibus config changes are done.
.

**Comment by marcparadise** [comment]
Fix for chef-server is here: https://github.com/chef/opscode-omnibus/pull/763

**Comment by marcparadise** [comment]
Closing, this will be in the next master build of opscode-omnibus for chef server.
