### ISSUE TITLE
not install chef server in my ubuntu. pls helpme as early as possible

### ISSUE THREAD

**Issue by kartheek0007** [chef/chef-server#1268]
root@chefserver:~# ls
chef-server-core_12.15.6-1_amd64.deb  opscode-cleanse-2017-05-11T22:06
root@chefserver:~# chef-server-ctl reconfigure
Starting Chef Client, version 12.19.36
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - enterprise (0.10.3)
  - apt (6.1.0)
  - yum (3.13.0)
  - openssl (7.0.1)
  - runit (3.0.5)
  - packagecloud (0.3.0)
  - yum-epel (2.1.1)
  - compat_resource (12.19.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: private-chef::default
  * directory[/etc/opscode] action create
    - create new directory /etc/opscode
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
  * directory[/etc/opscode/logrotate.d] action create
    - create new directory /etc/opscode/logrotate.d
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'

  ================================================================================
  Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb
  ================================================================================

  Chef::Exceptions::ValidationFailed
  ----------------------------------
  common_name is required

  Cookbook Trace:
  ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:60:in `block in from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:59:in `from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:149:in `block in from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:132:in `each'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:132:in `from_file'

  Relevant File Content:
  ----------------------
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/nginx.rb:

   53:  if (node['private_chef']['nginx']['ssl_certificate'].nil? &&
   54:      node['private_chef']['nginx']['ssl_certificate_key'].nil?)
   55:
   56:     ssl_keyfile = File.join(nginx_ca_dir, "#{node['private_chef']['nginx']['server_name']}.key")
   57:     ssl_crtfile = File.join(nginx_ca_dir, "#{node['private_chef']['nginx']['server_name']}.crt")
   58:
   59:     openssl_x509 ssl_crtfile do
   60>>      common_name node['private_chef']['nginx']['server_name']
   61:       org node['private_chef']['nginx']['ssl_company_name']
   62:       org_unit node['private_chef']['nginx']['ssl_organizational_unit_name']
   63:       country node['private_chef']['nginx']['ssl_country_name']
   64:       key_length node['private_chef']['nginx']['ssl_key_length']
   65:       expire node['private_chef']['nginx']['ssl_duration']
   66:       owner 'root'
   67:       group 'root'
   68:       mode '0644'
   69:     end

  Platform:
  ---------
  x86_64-linux

  Running handlers:
  Running handlers complete
  Chef Client failed. 2 resources updated in 03 seconds
[2017-05-11T22:07:29+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2017-05-11T22:07:29+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-11T22:07:29+00:00] FATAL: Chef::Exceptions::ValidationFailed: common_name is required
root@chefserver:~# ^C

**Comment by stevendanna** [comment]
My hunch is that your machine doesn't have a hostname correctly configured.  You can check this with the following commands:

```
hostname
hostname --fqdn
/opt/opscode/embedded/bin/ohai hostname
```

**Comment by kartheek0007** [comment]
hostname displayed but 
hostname --fqdn which purpose and what can i change in the fallowing path /opt/opscode/embedded/bin/ohai hostname

**Comment by kartheek0007** [comment]
when i give the hostname -fqdn name or service not know like this

**Comment by kartheek0007** [comment]
root@chefserver:~# hostname
chefserver
root@chefserver:~# hostname --fqdn
hostname: Name or service not known
#!/opt/opscode/embedded/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'ohai' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.activate_bin_path('ohai', 'ohai', version)
~
~
~
~
~
~
~
~
"/opt/opscode/embedded/bin/ohai" 22L, 489C

**Comment by trickyearlobe** [comment]
@kartheek0007 , the 3 individual commands suggested by @stevendanna show the hostname just fine on my Ubuntu 16.10 so maybe you have some package missing.

I can reproduce your problem if I create a machine which is unable to resolve (look up) it's hostname via DNS and the local hosts file.

Try adding an entry in `/etc/hosts` that looks something like this (using your own host/domain names): -
```
127.0.0.1   ubuntuhost001.mydomain.com   ubuntuhost001   localhost
```

**Comment by cheeseplus** [comment]
This is a hostname problem and the workarounds/suggestions are exactly what is needed to help solve the problem. As there hasn't been any response in some time I'm closing this but if you need more real time assistance in the future please join the [Chef Community Slack](https://community-slack.chef.io/)

**Comment by gthakuria** [comment]
Even I am getting below error while trying to run command: chef-server-ctl reconfigure

I am getting below error while trying to install Chef Server on CentOS, Would you be able to help on this? 


*********************************************************************************************
***********************************************************************************

Starting Chef Client, version 12.21.31
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.1)
  - enterprise (0.11.0)
  - openssl (8.1.2)
  - runit (4.0.4)
  - packagecloud (0.3.0)
  - yum-epel (2.1.2)
  - compat_resource (12.19.1)
Installing Cookbook Gems:
Compiling Cookbooks...
/var/opt/opscode/local-mode-cache/cookbooks/packagecloud/resources/repo.rb:10: warning: constant ::Fixnum is deprecated
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)

  ================================================================================
  Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb
  ================================================================================

  Chef::Exceptions::NoSuchResourceType
  ------------------------------------
  Cannot find a resource for component_runit_supervisor on cento version 6.8

  Cookbook Trace:
  ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:28:in `from_file'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:108:in `from_file'

  Relevant File Content:
  ----------------------
  /var/opt/opscode/local-mode-cache/cookbooks/enterprise/recipes/runit.rb:

   21:  node.override['runit']['sv_bin']       = "#{install_path}/embedded/bin/sv"
   22:  node.override['runit']['svlogd_bin']   = "#{install_path}/embedded/bin/svlogd"
   23:  node.override['runit']['chpst_bin']    = "#{install_path}/embedded/bin/chpst"
   24:  node.override['runit']['service_dir']  = "#{install_path}/service"
   25:  node.override['runit']['sv_dir']       = "#{install_path}/sv"
   26:  node.override['runit']['lsb_init_dir'] = "#{install_path}/init"
   27:
   28>> component_runit_supervisor node['enterprise']['name'] do
   29:    ctl_name node[node['enterprise']['name']]['ctl_name'] ||
   30:             "#{node['enterprise']['name']}-ctl"
   31:    sysvinit_id node[node['enterprise']['name']]['sysvinit_id']
   32:    install_path node[node['enterprise']['name']]['install_path']
   33:  end
   34:

  System Info:
  ------------
  chef_version=12.21.31
  platform=cento
  platform_version=6.8
  ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
  program_name=/opt/opscode/embedded/bin/chef-client
  executable=/opt/opscode/embedded/bin/chef-client


  Running handlers:
  Running handlers complete
  Chef Client failed. 0 resources updated in 15 seconds
[2018-05-02T15:41:41+01:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2018-05-02T15:41:41+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-05-02T15:41:41+01:00] FATAL: Chef::Exceptions::NoSuchResourceType: Cannot find a resource for component_runit_supervisor on cento version 6.8
[root@gb2infpupd19 chef]#

************************************************************************************
*******************************************************************************************

**Comment by karthiupnr** [comment]
hi, i got the same error when i tried to install on centos. tried to un-install & install. no luck.
this issue, we might not updated the domain name in /etc/hosts file.
i have updated as like below,
echo "127.0.0.1 chef_server chef_server.com">> /etc/hosts
then, i have run "chef-server-ctl reconfigure". it was success. (please try this method, it will work).
