### ISSUE TITLE
not install chefserver in my ubuntu, when i tried to install like following below

### ISSUE THREAD

**Issue by kartheek0007** [chef/chef-server#1269]
root@chefserver:~# ls
chef-server-core_12.15.6-1_amd64.deb 
root@chefserver:~# dpkg -i chef-server-core_12.15.6-1_amd64.deb
(Reading database ... 114190 files and directories currently installed.)
Preparing to unpack chef-server-core_12.15.6-1_amd64.deb ...
Unpacking chef-server-core (12.15.6-1) over (12.15.6-1) ...
Setting up chef-server-core (12.15.6-1) ...
root@chefserver:~# dpkg -l chef-server-ctl
dpkg-query: no packages found matching chef-server-ctl

**Comment by stevendanna** [comment]
`chef-server-ctl` is part of the `chef-server-core` package and does not need to be installed separately.
