### ISSUE TITLE
Issue with sqint and bifrost schema: "User name may not contain "<" or start with "[""

### ISSUE THREAD

**Issue by dkuntz2** [chef/chef-server#1280]
I cannot get `chef-server-ctl reconfigure` to finish a run successfully, on either CentOS or Debian.

## Expected Behavior

`chef-server-ctl reconfigure; echo $?` == `0`. Or for the reconfigure run to not fail out on the bifrost migration step.

## Current Behavior

Each time I've run `chef-server-ctl reconfigure`, it errors out with

```
[2017-05-24T21:07:51+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2017-05-24T21:07:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-24T21:07:51+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: private_chef_pg_sqitch[/opt/opscode/embedded/service/oc_bifrost/db] (private-chef::bifrost_database line 42) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[sqitch_deploy_/opt/opscode/embedded/service/oc_bifrost/db] (/var/opt/opscode/local-mode-cache/cookbooks/private-chef/providers/pg_sqitch.rb line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 1], but received '2'
---- Begin output of sqitch --engine pg --db-name bifrost --db-host 127.0.0.1 --db-port 5432 --db-user opscode-pgsql --top-dir /opt/opscode/embedded/service/oc_bifrost/db deploy --verify ----
STDOUT: Adding metadata tables to bifrost
STDERR: User name may not contain "<" or start with "["
---- End output of sqitch --engine pg --db-name bifrost --db-host 127.0.0.1 --db-port 5432 --db-user opscode-pgsql --top-dir /opt/opscode/embedded/service/oc_bifrost/db deploy --verify ----
Ran sqitch --engine pg --db-name bifrost --db-host 127.0.0.1 --db-port 5432 --db-user opscode-pgsql --top-dir /opt/opscode/embedded/service/oc_bifrost/db deploy --verify returned 2
```

## Steps to Reproduce (for bugs)

1. Spin up a base debian or base CentOS image
2. Install the latest package from https://downloads.chef.io/chef-server
   - In both cases it's been 12.15.7.
3. Run `chef-server-ctl reconfigure`

In both cases, the servers were created using an AMI I created that was provisioned with chef solo to create a single user account for myself. I have tried running `chef-server-ctl reconfigure` both before and after uninstalling the `chef` package, with no change.

## Your Environment

* Chef Server Version: 12.15.7
* Total/free RAM and disk space: In both cases an AWS m4.large
* Operating System and Version: Debian Jessie 8.7 / CentOS 7.3.1611
* If upgrading, previous Chef Server version: n/a
* Running in a container? No

**Comment by PrajaktaPurohit** [comment]
@dkuntz2 We are sorry you are experiencing this issue and apologies for the late reply. We have a couple of questions for you.
- Does the issue persist with the latest version of chef-server?
- Do you have any env variables set up that contain those special symbols?
- Is there a pre-existing database that contains user names with those special characters?
We do not have enough information to be able to reproduce this issue at this point. Closing this issue for now. Please feel free to reopen if you still see it.

**Comment by dkuntz2** [comment]
I have not used chef in over two years so i have absolutely no idea.
