### ISSUE TITLE
Elasticsearch 5 Support Will Break External Solr

### ISSUE THREAD

**Issue by sdelano** [chef/chef-server#1308]
We still support the use of external search via Solr, but the changes with https://github.com/chef/chef-server/pull/1287 will break this.

The helper ([link](https://github.com/chef/chef-server/blob/fea4447c5ddcc31047576db6052b635e9316cbf7/omnibus/files/private-chef-cookbooks/private-chef/libraries/helper.rb#L66)) only checks whether we've configured external search, but not that the engine is Elasticsearch. If we're using Solr, this will break.

**Comment by lancewf** [comment]
I will be looking into this problem today. I will run the pedant tests with an external solr service and see what breaks.

**Comment by lancewf** [comment]
The only change that is needed is to add a check for node['private_chef']['opscode_erchef']['search_provider']` == `elasticsearch` [here](https://github.com/chef/chef-server/blob/fea4447c5ddcc31047576db6052b635e9316cbf7/omnibus/files/private-chef-cookbooks/private-chef/libraries/helper.rb#L66)

I am writing some tests and adding to the dev environment the option of an external solr.
