### ISSUE TITLE
Disallow Editing of Admins Group ACLs

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#131]
Along with https://github.com/chef/chef-server/issues/123 to avoid deletion of required groups , we want to tightly control the ability to change perms on the Admins group.

Changing these perms can disable the ability to manage the organization.

**Comment by stevendanna** [comment]
This is mitgated by:

https://github.com/chef/chef-server/pull/248

**Comment by PrajaktaPurohit** [comment]
Closing, since looks like it is not an issue anymore. Please feel free to reopen if the issue persists.
