### ISSUE TITLE
UIDs for critical users (opscode, opscode-pgsql) may differ in HA pair

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#132]
When setting up a server cluster using the HA topology, nothing in our installation process guarantees that critical users have the same UIDs across backend nodes.  This is problematic because DRBD replicates at the block device layer.  The "opscode" user on the backend node might not actually have permissions on the files needed to service requests.

**Comment by pburkholder** [comment]
Should this be in chef-server-cluster cookbook? Or do we expect chef-server project to be multinode aware at this level?

**Comment by jtimberman** [comment]
This should not be in chef-server-cluster. That cookbook doesn't affect the configuration of the system that is handled by the cookbooks in the chef-server-core package's cookbooks managed with `chef-server-ctl reconfigure`.

**Comment by vinyar** [comment]
I just hit this issue actually. Here are a couple of thoughts I had while untangling that ball of wax - 

* I think user configuration & check & enforcement should be performed as part of reconfigure.
* reconfigure should have a default UID for opscode* users
* if that UID is not available, reconfigure should fail.
* if default UID is not available it should be explicitly specified in chef-server.rb

Side note: 
* I think it's reasonable to expect a clean system and default behavior of reconfigure should be able to assume that. Also, our docs should encourage a clean system (im on that).
* It would be awesome to perform a cross-server check for user (and general ha/drbd functionality validation) as part of reconfigure or test.

**Comment by PrajaktaPurohit** [comment]
Closing since we do not support the DRBD, HA topology.
