### ISSUE TITLE
chef-server-ctl tail fails on centos 7.3

### ISSUE THREAD

**Issue by billmeyer** [chef/chef-server#1333]
When executing:

```
chef-server-ctl tail
```
Appears as though a bad argument is being passed to the underlying `find` utility:

```
[root@chefserver01 opscode]# chef-server-ctl tail
rpm -find: paths must precede expression: bookshelf/sasl/2
Usage: find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
tail: cannot follow ‘-’ by name
```

## Expected Behavior

Expect the chef server logs to get tailed.

## Current Behavior

Error running the `find` command.

## Steps to Reproduce (for bugs)

`chef-server-ctl tail`

## Your Environment

[root@chefserver01 opscode]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

chef-gate-1.9.26-1.x86_64
chef-manage-2.5.4-1.el7.x86_64
chef-server-core-12.15.8-1.el7.x86_64

**Comment by stevendanna** [comment]
I've proposed a fix here: https://github.com/chef/omnibus-ctl/pull/60

The upshot of that is that the command will likely work if you change to a different directory first.  Thanks for reporting this!

**Comment by stevendanna** [comment]
This should be fixed in the next version of Chef Server that gets released.

**Comment by cheeseplus** [comment]
Closing as fixed, please open a new issue if this is still an issue.
