### ISSUE TITLE
`chef-server-ctl reconfigure` fails in Docker re: IPv6 loopback

### ISSUE THREAD

**Issue by phrz** [chef/chef-server#1337]
I am on a Ubuntu 16.04 EC2 instance, running Docker with a CentOS 7 container. The Dockerfile simply installs the official RPM, and runs `chef-server-ctl reconfigure`. I get an error about misconfigured IPv6. I've tried editing `/etc/hosts`, disabling IPv6 in privileged mode in the container, and most recently, disabling IPv6 on the host. 

```
Step 4/4 : RUN chef-server-ctl reconfigure
 ---> Running in f751db9f662a
[2017-07-20T14:14:22+00:00] FATAL:

-----------------------------------------------------------------------
Your system has IPv6 enabled but its loopback interface has no IPv6
address.

You must either pass `ipv6.disable=1` to your kernel command line,
to completely disable IPv6, or ensure the loopback interface has an
`::1` address by running

    sysctl net.ipv6.conf.lo.disable_ipv6=0
-----------------------------------------------------------------------
ERROR: Service 'chef-server' failed to build: The command '/bin/sh -c chef-server-ctl reconfigure' returned a non-zero code: 1
```

I have certainly exhausted any fixes I can think of. For reference, `ping6 ::1` never worked in the container, so I'm not disagreeing with the claim in the error message, I just don't know how to fix it.

## Expected Behavior
Disabling IPv6 completely on the host/guest should fix this error about partially-configured IPv6, or Chef Server should treat IPv6 as disabled when it is "misconfigured" as such.

## Current Behavior
I receive the above error message and Docker build phase fails.

## Steps to Reproduce (for bugs)

1. Use a Linux (preferably Ubuntu 16.04) host machine that has IPv6 *enabled* (test with `ping6 ::1` on host)
2. Run `docker build .` while in a directory with the Dockerfile as follows:

```
FROM centos:7
RUN rpm -ivh https://packages.chef.io/files/stable/chef-server/12.15.8/el/7/chef-server-core-12.15.8-1.el7.x86_64.rpm
RUN chef-server-ctl reconfigure
```

### Host
- Ubuntu 16.04 AWS EC2 t2.micro instance
- 8GB SSD
- Docker v 17.06.0-ce, build 02c1d87
- Docker Compose v 1.14.0, build c7bdf9e
### Container
- CentOS 7 (`centos:7`)

**Comment by phrz** [comment]
Enabling IPv6 with:
```
sudo su 
echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6
```
on CentOS (with docker `--privileged`) fixed the IPv6 issue, but Chef Server was still not content with running in Docker, so I am trying to use an alternative like Chef Zero or Goiardi.

**Comment by stevendanna** [comment]
@phrz Apologies you hit this.  The underlying problem that led us to put this check in was resolved by @srenatus, so it should be fixed in the upcoming release.

**Comment by phrz** [comment]
@stevendanna I really appreciate you following up, I'm a complete beginner testing Chef out for a project at my work and it means a lot that this project is so active!
