### ISSUE TITLE
Chef-sync should sync users

### ISSUE THREAD

**Issue by dreamnite** [chef/chef-server#134]
Currently using chef-sync across multiple data-centers, where each datacenter has a chef-server that has been sync'd from a master chef server. Currently users are created on the master chef-server, and we would like to see them (and their keys) sync'd to the datacenter servers for ease of management/use. (IE: being able to use knife just by specifying the end data-center server with "knife -s <server> command, instead of needing a separate config/key for each server, or being able to use a single validation key organization wide, etc.)

(originally submitted as support ticket 3489, in case you cross-reference.)

**Comment by stevendanna** [comment]
Thank you for trying chef-sync and taking the time to file this
ticket. I am sorry you haven't received more feedback on this
issue before now.

Chef sync is no longer an actively developed product as it saw
very little adoption in our user base.  No further development is
planned for Chef sync.

I am closing this ticket. However, if you already have a Chef
sync deployment and still require further assistance, please
contact support at support@chef.io.
