### ISSUE TITLE
chef-server-ctl reconfigure hangs

### ISSUE THREAD

**Issue by frlod** [chef/chef-server#1341]
When trying to create a highly available chef cluster, consisting of 3 backend servers and 1 frontend. I followed the steps as described here: https://docs.chef.io/install_server_ha.html
The backend servers are successful and their status is good:
`Service        Local Status        Time in State  Distributed Node Status
leaderl        running (pid 9379)  0d 1h 31m 53s  leader: 1; waiting: 0; follower: 2; total: 3
etcd           running (pid 9318)  0d 1h 32m 0s   health: green; healthy nodes: 3/3
postgresql     running (pid 9430)  0d 1h 31m 52s  leader: 1; offline: 0; syncing: 0; synced: 2
elasticsearch  running (pid 9285)  0d 1h 32m 2s   state: green; nodes online: 3/3`

Trying to install the chef frontend:

```
chef-server-ctl reconfigure
Starting Chef Client, version 12.19.36
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - enterprise (0.10.3)
  - openssl (7.1.0)
  - runit (3.0.5)
  - packagecloud (0.3.0)
  - yum-epel (2.1.2)
  - compat_resource (12.19.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create
    - create new directory /etc/opscode/logrotate.d
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
```
And this is where it stops forever.

Stack trace: 

`NameError: No resource, method, or local variable named `e' for `Chef::Recipe "haproxy"'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/dsl/method_missing.rb:70:in `rescue in method_missing'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/dsl/method_missing.rb:65:in `method_missing'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:64:in `rescue in from_file'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:54:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:114:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:187:in `load'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/client.rb:511:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/client.rb:281:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:253:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'

>>>> Caused by NameError: undefined local variable or method `e' for #<Chef::Recipe:0x0000000670d770>
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/dsl/method_missing.rb:66:in `method_missing'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:64:in `rescue in from_file'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:54:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:114:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:187:in `load'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/2.2.0/forwardable.rb:188:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/client.rb:511:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/client.rb:281:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:253:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'

>>>> Caused by SystemExit: exit
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:368:in `exit'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:368:in `fatal!'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:64:in `block in setup_signal_handlers'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:879:in `call'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:879:in `open'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
/opt/opscode/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
/opt/opscode/embedded/lib/ruby/2.2.0/timeout.rb:98:in `call'
/opt/opscode/embedded/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:878:in `connect'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:852:in `start'
/opt/opscode/embedded/lib/ruby/2.2.0/net/http.rb:1375:in `request'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:70:in `request'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http.rb:340:in `block in send_http_request'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http.rb:372:in `block in retrying_http_errors'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `loop'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `retrying_http_errors'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http.rb:333:in `send_http_request'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http.rb:148:in `request'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/http.rb:115:in `get'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_backend.rb:26:in `etcd_get'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_backend.rb:17:in `etcd_members'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:43:in `block in get_chef_backend_cluster_members'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:41:in `each'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:41:in `get_chef_backend_cluster_members'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/haproxy.rb:56:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:294:in `block in include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:293:in `include_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/default.rb:114:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:338:in `load_recipe'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/run_context.rb:187:in `load'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/2.2.0/forwardable.rb:188:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/client.rb:511:in `setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/client.rb:281:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:253:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application/client.rb:427:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:22:in `load'
/opt/opscode/embedded/bin/chef-client:22:in `<main>'`

## Your Environment
Using AWS instances (t2.xlarge).

Chef-server version: 12.15.8
Chef backend version: 1.3.2
16 GB ram, 4 cores. 6 GB available on frontend

`Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial`

**Comment by stevendanna** [comment]
The immediate stacktrace is the result of a bug in the error handling code (proposed fix here: https://github.com/chef/chef-server/pull/1342).  However, that doesn't tell us much about how you got into the error handler in the first place.

You may be able to get more information with `chef-server-ctl --verbose` (warning: it produces a LOT of output).
