### ISSUE TITLE
opscode-omnibus: Write Logs in Alternative Locations

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#137]
Zendesk 3571

As a customer running a Chef Server, I would like to be able to write logs to a directory other than `/var/log/opscode`. The world permissions on my `/var/log` directory are blank and it is owned by root:root. Because of this, the runit svlogd processes running as the `opscode` user are unable to traverse down into `/var/log/opscode` to write and read.

Currently, the opscode-omnibus, chef-manage, and several other repos have hardcoding of `/var/log/opscode` . Tools like `gather-logs` depend on this location as well.

**Comment by PrajaktaPurohit** [comment]
Closing for now. Please feel free to reopen is the issue is still relevant.
