### ISSUE TITLE
Chef Server Stats Endpoint

### ISSUE THREAD

**Issue by jaym** [chef/chef-server#1385]
The purpose of this issue is to discuss which metrics people would like to see in the stats endpoint for Chef Server. I've started working on this endpoint in PR #1384, basing it off of what is available in https://github.com/facebook/chef-utils/blob/master/chef-server-stats/chef-server-stats. The PR currently implements the following metrics:

## Erchef Pooler Metrics
All of these are of type gauge, so they will provide the value at the time the `_stats` endpoint is hit. These will be provided for each pool.
- erchef_pooler_members_in_use:  Number of pool members currently being used
- erchef_pooler_members_free:  Number of pool members currently available
- erchef_pooler_pooler_members_max: Max number of pool members allowed in the pool
- erchef_pooler_queued_requestors: Number of requestors blocking to take a pool member
- erchef_pooler_queued_requestors_max: Max number of requestors allowed to block on taking pool member

## Erlang Metrics
These are provided by default in the library we use. They seemed useful:
- erlang_vm_memory_atom_bytes_total The total amount of memory currently allocated for atoms. This memory is part of the memory presented as system memory.
- erlang_vm_memory_bytes_total The total amount of memory currently allocated. This is the same as the sum of the memory size for processes and system.
- erlang_vm_dets_tables Erlang VM DETS Tables count
- erlang_vm_ets_tables Erlang VM ETS Tables count
- erlang_vm_memory_processes_bytes_total The total amount of memory currently allocated for the Erlang processes.
- erlang_vm_memory_system_bytes_total The total amount of memory currently allocated for the emulator that is not directly related to any Erlang process. Memory presented as processes is not included in this memory.
- erlang_vm_statistics_context_switches Total number of context switches since the system started
- erlang_vm_statistics_garbage_collection_number_of_gcs Garbage collection: number of GCs
- erlang_vm_statistics_garbage_collection_words_reclaimed Garbage collection: words reclaimed
- erlang_vm_statistics_garbage_collection_bytes_reclaimed Garbage collection: bytes reclaimed
- erlang_vm_statistics_bytes_received_total Total number of bytes received through ports
- erlang_vm_statistics_bytes_output_total Total number of bytes output to ports
- erlang_vm_statistics_reductions_total Total reductions
- erlang_vm_statistics_run_queues_length_total Total length of the run-queues
- erlang_vm_statistics_runtime_milliseconds The sum of the runtime for all threads in the Erlang runtime system. Can be greater than wall clock time
- erlang_vm_statistics_wallclock_time_milliseconds Information about wall clock. Same as erlang_vm_statistics_runtime_milliseconds except that real time is measured
- erlang_vm_ets_limit The maximum number of ETS tables allowed.
- erlang_vm_logical_processors The detected number of logical processors configured in the system.
- erlang_vm_logical_processors_available The detected number of logical processors available to the Erlang runtime system.
- erlang_vm_logical_processors_online The detected number of logical processors online on the system.
- erlang_vm_port_count The number of ports currently existing at the local node.
- erlang_vm_port_limit The maximum number of simultaneously existing ports at the local node.
- erlang_vm_process_count The number of processes currently existing at the local node.
- erlang_vm_process_limit The maximum number of simultaneously existing processes at the local node.
- erlang_vm_schedulers The number of scheduler threads used by the emulator.
- erlang_vm_schedulers_online The number of schedulers online.
- erlang_vm_smp_support 1 if the emulator has been compiled with SMP support, otherwise 0.
- erlang_vm_threads 1 if the emulator has been compiled with thread support, otherwise 0.
- erlang_vm_thread_pool_size The number of async threads in the async thread pool used for asynchronous driver calls.
- erlang_vm_time_correction 1 if time correction is enabled, otherwise 0.

## PostgreSQL
These are sums for all tables:
- pg_stat_seq_scan Number of sequential scans initiated
- pg_stat_seq_tup_read Number of live rows fetched by sequential scans
- pg_stat_idx_scan Number of index scans initiated
- pg_stat_tup_fetch Number of live rows fetched by index scans
- pg_stat_n_tup_ins Number of rows inserted
- pg_stat_n_tup_upd Number of rows updated
- pg_stat_n_tup_del Number of rows deleted
- pg_stat_n_live_tup Estimated number of live rows
- pg_stat_n_dead_tup Estimated number of dead rows
- pg_stat_heap_blocks_read Number of disk blocks read
- pg_stat_heap_blocks_hit Number of buffer hits
- pg_stat_idx_blks_read Number of disk blocks read from all indexes
- pg_stat_idx_blks_hit Number of buffer hits in all indexes
- pg_stat_toast_blks_read Number of disk blocks read from TOAST tables
- pg_stat_toast_blks_hit Number of buffer hits in TOAST tables
- pg_stat_tidx_blks_read Number of disk blocks read from TOAST tables
- pg_stat_tidx_blks_hit Number of buffer hits in TOAST table indexes
- pg_stat_n_conns Number of connections
- pg_stat_n_active_conns Number of active connections

# Unimplemented:

## Rabbitmq
TODO: This needs to be better flushed out
- Number of messages ready to be delivered

## chef_authn
chef_keygen_cache has metrics we can make available:
```
chef_keygen_cache:status().
[{keys,10},
 {max,10},
 {max_workers,2},
 {cur_max_workers,2},
 {inflight,[]},
 {avail_workers,2},
 {start_size,0}]
```

More to be added.

**Comment by jaym** [comment]
cc @irvingpop @andy-dufour @jaymzh

**Comment by irvingpop** [comment]
thanks @jaym - I added a comment to PR #1384 about the monitored pools.    Couple of wish-listy-sounding questions:
- Are the gauge values truly point-in-time, or would it be possible to make it a rolling average over some super-short timeframe (1m max)?
- Would it be possible to report on the number of queues items that timed out or were not accepted because the queue was full?   (I could see this being useful from a support analysis standpoint)

**Comment by jaym** [comment]
As I'm implementing the postgresql stats, I'm wondering if these should get broken down by chef table instead of being aggregated for all tables. That way, people can aggregate them if they want, or have them broken down. This wouldn't make sense if the system tables are required as there would be more than 140 tables, but the user tables are more managable at 35.

**Comment by jaym** [comment]
@irvingpop the gauge values are point in time. We might be able to add max in some timeframe, I can take a look at that. We probably have this from folsom, however @andy-dufour's analysis has lead me to believe the metrics it has are not meaningful.

Also, the rejected items is a good idea. Let me see if that's exposed.

**Comment by stevendanna** [comment]
@jaym Great work on this endpoint!  I'm going to close out this ticket as the endpoint has shipped.  We can add more data to it over time.
