### ISSUE TITLE
Problem with ACLs when a user and a client has the same name

### ISSUE THREAD

**Issue by System25** [chef/chef-server#1389]
## Description

If you have in the system a user that has a name (for example: "charles_xavier") and you have a client with the same name ("charles_xavier"), when you try to add that user to the ACL of a node there is an error. I suppose that the cause if that the system doesn't now if the actor that you are trying to add to the ACL is the user or the client.

I think that it would be better if there were a way to specify whether the actor is a client or a user.

## Chef Version

12.0.6

## Platform Version

CentOS 6.

## Replication Case

Create a file called "acltest.txt" with the following content:
```
{
  "create": {
    "actors": [
      "pivotal",
      "charles_xavier"
    ],
    "groups": [
      "clients",
      "users",
      "admins"
    ]
  }
}
```

Then execute the following commands:

```
chef-server-ctl  user-create charles_xavier Charles Xavier charles_xavier@xmen.com mypass
knife client create charles_xavier
knife node create mytestnode
knife raw /organizations/default/nodes/mytestnode/_acl/create -m PUT -i acltest.txt
```

The error message is:
```
ERROR: Server responded with error 400 "Bad Request"
ERROR: Error Body: {"error":["Invalid/missing actor in request body"]}
```

**Comment by coderanger** [comment]
It seems very unlikely we'll change anything at this point given how long this design has been in place, but patches welcome :)

**Comment by stevendanna** [comment]
I believe you can post the clients and users separately:

```
{
  "create": {
    "actors": [],
    "users" : [
      "pivotal",
      "charles_xavier"
    ],
    "clients" : [],
    "groups": [
      "clients",
      "users",
      "admins"
    ]
  }
}
```

**Comment by System25** [comment]
Hi stevendanna, I tested the JSON that you suggest and the Chef server ignores the "users" and "clients" parts of the JSON.

Best regards!

**Comment by stevendanna** [comment]
@System25 Is 12.0.6 the version of the chef-server you are on?  If so, I think you'll need to upgrade to at least 12.9.0 which includes this change: https://github.com/chef/chef-server/commit/45a02c350e3594f475471172122dec1583591960

**Comment by System25** [comment]
After upgrading to last Chef version the problem is solved.

Thank you very much @stevendanna!
