### ISSUE TITLE
chef-server-ctl backup brings down chef server

### ISSUE THREAD

**Issue by rudymccomb** [chef/chef-server#1391]
## Expected Behavior
 `chef-server-ctl backup` should not bring down my Chef Server.
[https://imgur.com/a/5ivBC](url)

## Current Behavior
`chef-server-ctl backup` seems to bring down the Chef Server, nowhere in the docs does it say that backing the above command will bring down the Chef Server for a time.

chef-server-ctl backup
Locating rsync..
/usr/bin/rsync
Starting Chef Server backup
WARNING:  Offline backup mode must stop your Chef server before continuing.  You can skip this message by passing a "--yes" argument. Do you wish to proc
eed? (y/N):
Y
Bringing down the Chef Server
ok: down: bookshelf: 0s, normally up
ok: down: nginx: 1s, normally up
ok: down: oc_bifrost: 0s, normally up
ok: down: oc_id: 0s, normally up
ok: down: opscode-chef-mover: 89125s, normally up
ok: down: opscode-erchef: 0s, normally up
ok: down: opscode-expander: 0s, normally up
ok: down: opscode-solr4: 0s, normally up
ok: down: rabbitmq: 0s, normally up
ok: down: redis_lb: 1s, normally up
Dumping Postgresql database to /tmp/chef_backup20170913-2551-1f2tmsl/chef_backup-2017-09-13-15-17-50.sql
could not change directory to "/tmp/d20170913-2551-vzsijg"
ok: down: postgresql: 0s, normally up
Writing backup manifest
Creating backup tarball
/opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout/unix.rb:183: warning: conflicting chdir during another chdir blo
ck
tar: Removing leading `/' from member names
Bringing up the Chef Server
ok: run: bookshelf: (pid 2846) 1s
ok: run: nginx: (pid 2926) 1s
ok: run: oc_bifrost: (pid 2942) 0s
ok: run: oc_id: (pid 3024) 0s
ok: run: opscode-chef-mover: (pid 3040) 0s
ok: run: opscode-erchef: (pid 3102) 1s
ok: run: opscode-expander: (pid 3413) 0s
ok: run: opscode-solr4: (pid 3547) 1s
ok: run: postgresql: (pid 3611) 0s
ok: run: rabbitmq: (pid 3104) 11s
ok: run: redis_lb: (pid 3849) 0s
Exporting tarball to /var/opt/chef-backup
Cleaning up /tmp/chef_backup20170913-2551-1f2tmsl
Backup Complete!

## Steps to Reproduce (for bugs)

1. Backup your Chef Server 
$`chef-server-ctl backup`
Notice the output shows the services are going down, this seems to be a bug or missing info in the docs. Also There is a warning that says `Offline backup mode must stop your Chef server before continuing`, so is there an Online backup mode?

## Your Environment
* Chef Server Version: 12.15.6
* Total/free RAM and disk space: 4GB/ Using 2GB AWS t2.medium
* Operating System and Version: Ubuntu 16.04LTS
* If upgrading, previous Chef Server version: N/A
* Running in a container? No

**Comment by cheeseplus** [comment]
Followed up in Slack and this is actually expected behaviour - the `--yes` flag just lets you auto-accept this as the program actually prompts you (you must enter Y). I'm pushing an PR to chef-docs that will make this even clearer but this is a non-issue.
