### ISSUE TITLE
Forcing SSL on external Postgres instance breaks chef-server install

### ISSUE THREAD

**Issue by poblahblahblah** [chef/chef-server#1403]
Forcing SSL connections for Postgres causes the install to fail.

## Expected Behavior
I would expect this to work without issue.

## Current Behavior
Chef is not configured properly and you have to start over.

## Steps to Reproduce (for bugs)

1. Force SSL on the postgres instance
2. Run through the chef installation process (install chef-server-core and run chef-server-ctl reconfigure).
3. This will error out because it appears erchef cannot talk to postgres securely.

## Your Environment

* Chef Server Version:  chef-server-core 12.16.14-1
* Total/free RAM and disk space: disk: 4.3G free of 7.7G; ram: 26GB free of 32GB
* Operating System and Version: Ubuntu 16.04 amd64
* If upgrading, previous Chef Server version: N/A
* Running in a container? No

**Comment by PrajaktaPurohit** [comment]
@poblahblahblah This issues should be addressed with the fix in #1711. The fix is in the latest current(https://downloads.chef.io/chef-server/current/13.0.58) and will be available in stable with the next release of Chef-Infra-Server. Please feel free to reopen the issue if you continue to see it.
