### ISSUE TITLE
Ability to Enable/Disable Packagecloud.io OS Repo

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#141]
ZenDesk  3731

As a customer doing monthly semi-automatic updates of our OS packages, I would like the option to disable the configuration of the packagecloud.io repos so that an upgrade of the reset of the packages on the OS does not include the chef server software.

**Comment by stevendanna** [comment]
@sean-horn Is this taken care of with your most recent PR related to the repo being enabled? https://github.com/chef/chef-server/pull/374

**Comment by sean-horn** [comment]
@stevendanna Yes, I'll close it out.

Fixed in #374
