### ISSUE TITLE
Chef server 12.17.5 includes non-current openresty 1.11.2.1 - 1.11.2.4 has security patch

### ISSUE THREAD

**Issue by sailorfred** [chef/chef-server#1417]
## Expected Behavior
Use openresty 1.11.2.4, which has been available since July

## Current Behavior
Openresty 1.11.2.1 from Aug 2016 is included.

## Steps to Reproduce (for bugs)

1. telnet _server_ 443
2. GET /
3. See openresty/1.11.2.1 version reported.

## Your Environment

* Chef Server Version: 12.17.5
* Total/free RAM and disk space:
* Operating System and Version: Ubuntu 16.04
* If upgrading, previous Chef Server version: N/A
* Running in a container? No

**Comment by stevendanna** [comment]
@sailorfred Thank you for the report.  I believe we delayed upgrading to 1.11.2.4 because it didn't build on all supported platforms. @srenatus Opened a PR to backport the relevant security fixes here: https://github.com/chef/omnibus-software/pull/863

**Comment by srenatus** [comment]
Just a small status update -- I've dropped the ball here, sorry about that. I've tried picking it up again [in this branch](https://github.com/chef/chef-server/tree/sr/openresty/1.13.6.1), trying to go forward with openresty 1.13.6.1. However, it's changed its requirements around luajit; and it seems it no longer accepts lua (non-jit, vanilla) instead. Going with the forks for ppc64 and s390x at least compiles fine for `ppc64le` and `s390x` respectively, but leaves us in a bad place for `ppc64`.

So, while this needs further investigations, rest assured that this hasn't completely slipped our minds yet.

**Comment by rhass** [comment]
I haven't tried 1.11.2.5 on PPC64, but can we give it a shot?

**Comment by srenatus** [comment]
@rhass The addition to omnibus-software _alone_ doesn't really resolve this issue in chef-server :) But it has broken its builds on all non-x64 archs, consistent with what we've found before -- newer openresty versions dropping support for non-luajit lua, and luajit of master not working on anything non-x86. (See my comment above.)

**Comment by sailorfred** [comment]
Hmm, it appears this ticket is being closed without addressing the
underlying vulnerabilities in the versions of openresty and nginx.

Please indicate whether the vulnerabilities are being addressed in another
ticket.

Thanks,

Fred

**Comment by markan** [comment]
Sorry, I should have noted that this was closed by #1623.
