### ISSUE TITLE
Bad Upgrade

### ISSUE THREAD

**Issue by krazykid** [chef/chef-server#143]
I did a yum upgrade on my Chef server and noticed that both chef-server-core and chef-server packages were upgraded. As a result now when I do some chef-server-ctl commands like "chef-server-ctl org-list", I get this:

ERROR: Failed to authenticate to https://127.0.0.1:443 as pivotal with key /etc/opscode/pivotal.pem
Response:  An error occurred while trying to find  'pivotal'. Please contact support.

I've tried to do a chef-server-ctl reconfigure, but I get the same error.

**Comment by stevendanna** [comment]
@krazykid Can you attempt to run: chef-server-ctl upgrade and see if the error persists.  If you were updated to a package that has the new multi-key features, you'll need to run the data migrations associated with that new feature, which the `chef-server-ctl upgrade` command should do.

**Comment by krazykid** [comment]
The chef-server-ctl upgrade command had failed too:

```
[root@ip-10-202-0-155 ~]# chef-server-ctl upgrade
Upgrading with options #<OpenStruct skip_confirmation=false, chef11_server_url="https://localhost", chef12_server_url="https://localhost", upload_threads=10, chef11_admin_client_name="admin", chef11_admin_client_key="/etc/chef-server/admin.pem">
Open source Chef 11 server detected.
Would you like to upgrade? [yN]
y
Upgrading the open source Chef 11 server.
Chef 12 short organization name? xxxx-xxx-xxx
Chef 12 full organization name? AAA BB CC
Creating /tmp/chef11-server-data20150410-1035-mdchpm as the location to save the open source Chef 11 server data
Ensuring Chef 12 server is stopped
ok: down: bookshelf: 0s, normally up
ok: down: nginx: 1s, normally up
ok: down: oc_bifrost: 0s, normally up
ok: down: oc_id: 0s, normally up
ok: down: opscode-chef-mover: 58081s, normally up
ok: down: opscode-erchef: 0s, normally up
ok: down: opscode-expander: 0s, normally up
ok: down: opscode-expander-reindexer: 0s, normally up
ok: down: opscode-solr4: 1s, normally up
ok: down: postgresql: 0s, normally up
ok: down: rabbitmq: 0s, normally up
ok: down: redis_lb: 0s, normally up
sed: can't read /opt/chef-server/bin/wait-for-rabbit: No such file or directory
Failed to write fix to wait-for-rabbit script
```

**Comment by mmzyk** [comment]
Ah, we're in a fun place. @krazykid You previously upgrade from Chef server 11 to Chef server 12 correct?

**Comment by mmzyk** [comment]
I believe we can get you out of this, but here is what I think it happening. I think @stevendanna is correct that the yum upgrade got you into a state where you have a Chef server 12 version that expects multikeys, but you haven't run the upgrade.

Running upgrade fails b/c it detects that Chef server 11 is still on your system (based on the packages you described, it is) and thinks that it needs to do the Chef server 11 upgrade to 12. So we need to resolve this first. I don't think we'll lose data, but I hope you have backups. If not, assuming it hasn't been cleaned by the OS, if you check in your /tmp dir you should see some folders that say chef11-* and chef12-*. Save those off some place if they are there, so we have them save and then we can at least recover from the point you did the upgrade to Chef server 12. That is your data from when that migration was done.

Now, the Chef server 11 package is the chef-server package. The Chef server 12 package is the chef-server-core package. You need to uninstall the Chef server 11 package so it is no longer on your system. Just use your package uninstaller for this. Make sure you uninstall chef-server and not chef-server-core. If you uninstall the wrong package you'll remove Chef server 12, which is not what we want.

Once Chef server 11 is uninstalled, trying running upgrade again. I believe this will fix your issues.

**Comment by krazykid** [comment]
I did previously upgrade from 11 to 12. The /tmp/chef11-* directories exist, but they're all empty. :(

I had done a yum erase chef-server before, and it's no longer on the system and ran the upgrade. The upgrade is still unhappy though. The above error message still comes up when I run the upgrade.

**Comment by stevendanna** [comment]
@krazykid does an /opt/chef-server still exist on your system?  If so, try mving it off into /tmp and re-running the upgrade.

**Comment by mmzyk** [comment]
@krazykid is there a /tmp/chef12-* dir? That would also potentially have the data for the Chef 12 server in it to save as a backup. And then do what @stevendanna suggests, as that is how the upgrade is detecting Chef 11, by looking for that dir.

**Comment by krazykid** [comment]
There was a /opt/chef-server directory. There were no /tmp/chef12-* directories. I moved the /opt/chef-server to /tmp. chef-server-ctl upgrade ran to completion! And chef-server-ctl org-list shows my orgs. Thanks @stevendanna and @mmzyk for your great help!

**Comment by krazykid** [comment]
Oh. I don't know if it's possible, but when someone installs the Chef server 12 RPM, you may want to check to see if the 11 version is installed and delete it after 12 is installed.

**Comment by mmzyk** [comment]
@krazykid We actually don't remove it on purpose, as we assume you're upgrading and if something goes wrong it is possible to restart the chef 11 server so nothing is lost.

The final step of the upgrade process is directions to remove the chef 11 package, but I can see how that is easy to miss.

Glad you're good to go now.

**Comment by levmichael3** [comment]
Thanks @stevendanna This worked for me as well.
