### ISSUE TITLE
A role is associated with a cookbook version

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef-server#1435]
We use the pattern of environment pinning, as in https://github.com/jeremymv2/env_pinning since roles are not versioned.

A role file refers to a "role cookbook" like this:

`run_list 'recipe[my_role_cookbook::default]'`

But when I look at roles in the Chef Manage UI, the cookbook is shown with a version number.

This gave me a problem in using our "development" environment, where we do not have any cookbook version pinning:

- The Chef server had many versions of the cookbook, latest was 1.3.0, back to 0.x versions.
- When I ran `chef-client` on a node in the `development` environment, the latest cookbook was not chosen. Instead, it repeatedly chose v0.4.1
- v0.4.1 was also the version shown in the Chef Manage UI, when I looked at the role
(so, compared to the screenshot attached, it said 0.4.1 in the UI before I manually deleted that version from the Chef server)

## Expected Behavior

- A role is not associated with cookbook versions
- I can have a `development` environment (when `cookbook_versions` is empty) and it will pick the latest version of a cookbook on the Chef server

## Current Behavior

- A role seems to be associated with a cookbook version. I can see this in the behavior of running chef-client and when looking at a role in the Chef Manage UI, but I cannot see it using tools like `knife role show` or from my role file
- My workaround was to manually delete all 0.x versions from the Chef server (`knife cookbook delete`), until the Chef Manage UI showed the right version.

## Steps to Reproduce (for bugs)

Please see Chef ticket 17195 for details.

## Your Environment

* Chef Server Version:
* Total/free RAM and disk space:
* Operating System and Version:
* If upgrading, previous Chef Server version:
* Running in a container?
![chef-server-role-links-to-cookbook-version](https://user-images.githubusercontent.com/5772042/33830993-a332f30c-de76-11e7-8558-9a54527494a0.PNG)

**Comment by cheeseplus** [comment]
Roles are not in any way associate with cookbook versions, roles are effectively just expandable items on the run_list that can also apply attributes. If the 'latest' version of a cookbook is not being chosen, that's got to do specifically with what the satisfies the dependency constraints that are applied via metadata.rb and `cookbook_versions` on an Environment.

If you are getting a version, either it satisfies the dependency or something is constraining it. Dependency resolution is about solving for constraints which means that satisfying them doesn't imply using latest - if you want a specific version (or greater/less than) then do so via `metadata.rb`.

I'm not entirely clear on where Manage UI is getting those versions but it's merely a client so using tools like chef-client and knife will be the most accurate representation of reality.

**Comment by martinmosegaard** [comment]
OK, in that case it must have been a constraint in our environment files that I did not notice at the time.

The thing I don't understand though is that I made it work by manually deleting the `0.x` versions. If those were referenced in an environment, I am sure it would have given an error once they were deleted?

Feel free to close this issue unless there is anymore information you need from me.

**Comment by cheeseplus** [comment]
As alluded earlier this could just be dependency solving being itself.

Dependency solving is one of those _hard_ CS problems because SAT solvers _solve for constraints_ not _for latest_. This is a common misconception because in a vacuum that appears to be the behaviour of solvers so if you get an "unexpected" cookbook value in a solution it's not really wrong, in order to ensure you get versions you "want" you can use metadata.rb constraints to force that into the solved set.  That is what it sounds like if you haven't changed constraints elsewhere.

Tools like https://github.com/coderanger/knife-solve or https://github.com/jeremiahsnapp/knife-depsolver can help give you some insight.

**Comment by martinmosegaard** [comment]
Yes, I remember SAT solvers from CS being hard :) Regarding the Chef implementation, it would be awesome if debug logging could reveal the constraints evaluated by the solver.

I know I as a user need to be in control of my setup, but when I forget or miss something, I love when tools can point it out to me.

Thanks for the support.
