### ISSUE TITLE
zypper_package doesn't seem to be passing the package name

### ISSUE THREAD

**Issue by randyrue** [chef/chef-server#1446]
**Trying to install a package in openSUSE using both a "package" or "zypper_package" call with the same result, the embedded "zypper install" call fails.**
## Expected Behavior

**package should call zypper_package and install the package from a local .rpm file**
## Current Behavior

**package calls zypper_package which calls:
["zypper", "--non-interactive", "install", "--auto-agree-with-licenses"]
which returns:
STDERR: Too few arguments.
       At least one package name is required.**

## Steps to Reproduce (for bugs)
**have tried both "package" and "zypper_package"
source is a local rpm file
have also tried naming the package specifically

e.g:
package 'rundeck' do
        package_name 'rundeck'
        source '/root/rundeck_latest.rpm'
end

and:
zypper_package 'rundeck' do
        package_name 'rundeck'
        source '/root/rundeck_latest.rpm'
end**

## Your Environment

*** Chef Server Version:
Chef Development Kit Version: 2.0.28
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1
Client: 
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13

* Total/free RAM and disk space:RAM 8GB/6GB used disk 24GB/17GB used
* Operating System and Version: openSUSE Leap 42.2
* If upgrading, previous Chef Server version:
* Running in a container? Xen VM**

**Comment by stevendanna** [comment]
Hi @randyrue! Apologies for the delay.  It looks like this is a chef client bug.  This repository is for bugs related to the chef server.  Would you mind re-opening this bug against the chef client github repository:

https://github.com/chef/chef

I'll be closing this one out, but feel free to let me know if you need any assistance moving the bug over.
