### ISSUE TITLE
Postgres upgrade from 9.2 to 9.6 fails on a DRBD HA system due to data path differences

### ISSUE THREAD

**Issue by glasschef** [chef/chef-server#1447]
On non-DRBD HA systems, the postgres data directory is `/var/opt/opscode/postgresql/9.x/data`, so the upgrade code looks in `/var/opt/opscode/postgresql/*/data` to find existing versions of postgres to see if it needs to upgrade:

https://github.com/chef/chef-server/blob/12.17.20/omnibus/files/private-chef-cookbooks/private-chef/providers/pg_upgrade.rb#L74-L80

However, in a DRBD HA system, the postgres data directory is actually `/var/opt/opscode/drbd/data/postgresql_9.x/`, and the code tries to look in `/var/opt/opscode/drbd/*/data/` instead of `/var/opt/opscode/drbd/data/*/`, resulting in `old_data_dir.nil?` to be true when checking `if upgrade_required?` and causing the migration of 9.2 data to 9.6 to be skipped.

## Expected Behavior

Upgrading an older postgres-9.2-based Chef Server to a newer postgres-9.6-based Chef Server should succeed when the system is configured for DRBD HA

## Current Behavior

Upgrading an older postgres-9.2-based Chef Server to a newer postgres-9.6-based Chef Server does not migrate 9.2 data to 9.6, and will install an empty database on 9.6 when the system is configured for DRBD HA

## Steps to Reproduce (for bugs)

1.  Set up DRBD installation with Chef Server 12.15.7, and populate the database with some test data
2.  Upgrade one of the backends by installing 12.17.15 package and running `chef-server-ctl upgrade`
3.  Check the database to see that the data has not been successfully migrated

## Your Environment

* Chef Server Version: 12.17.15
* Total/free RAM and disk space:  enough
* Operating System and Version:  Centos 6.5
* If upgrading, previous Chef Server version:  12.15.7
* Running in a container?  nope

**Comment by chilicheech** [comment]
This happened to one of my clusters today. I was able to get around by changing that recipe code from `*data` to `data/*` as you suggested. That was a life saver!

Cheers!

**Comment by btm** [comment]
DRBD HA support was end-of-life on 3/31/2019. Any remaining DRBD HA users should discuss migrating to Chef Backend with their Chef representative.

https://blog.chef.io/2018/10/02/end-of-life-announcement-for-drbd-based-ha-support-in-chef-server/
