### ISSUE TITLE
Hosted Chef Should Allow Log Export or Streaming Through an API

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#145]
As a customer, I would like to be able to dig through logfiles on my orgs at my own pace and also index them in Splunk or another log indexing system.

**Comment by stevendanna** [comment]
@sean-horn Can you add more detail on what kind of logs you are referring to?  I assume this is referring to API access logs?

**Comment by stevendanna** [comment]
Closing this ticket for now.  Users of chef-server can export their logs as they are stored on disk using one of the many available tools for this.  I agree that this would be a good feature for Hosted and that /if/ we implemented it for hosted there are features we could provide in chef-server to make it easier.  However, for this to realistically move forward, it would likely need to be taken up by Ops (cc @paulmooring) or Product (cc @charlesjohnson).

@sean-horn Please let me know if you have concerns.
