### ISSUE TITLE
gather-logs fails when bzip2 is not installed

### ISSUE THREAD

**Issue by smacfarlane** [chef/chef-server#1463]
## Expected Behavior

`chef-server-ctl gather-logs` should produce a .tar.bz2 of the log files

## Current Behavior

On systems without bzip2 installed,  `chef-server-ctl gather-logs` fails. 

```
chef-server-ctl gather-logs
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
```

## Steps to Reproduce (for bugs)

(RHEL) 
1. rpm -e bzip2
2. chef-server-ctl gather-logs 

## Your Environment
* Chef Server Version: chef-server-core-12.17.15-1.el7.x86_64
* Operating System and Version: RHEL 7

**Comment by tas50** [comment]
This was fixed in 2019
