### ISSUE TITLE
cannot use chef-server-ctl for any activities using pivotal account

### ISSUE THREAD

**Issue by forkthis404** [chef/chef-server#148]
brand new install on 12.0.7 on ubuntu 12.0.4, all the services are running but when i try to create, edit, or show a user i get....

ERROR: Failed to authenticate to https://127.0.0.1:443 as pivotal with key /etc/opscode/pivotal.pem
Response:  Invalid signature for user or client 'pivotal'

**Comment by forkthis404** [comment]
crude way to get around it is to use the webui keys as the pivotal keys.  Used private-server-ctl to set the public key of the pivotal user, then replaced the private key of pivotal with the private key of webui in the /etc/opscode directory

**Comment by sakkemsu1** [comment]
Hi @forkthis404,

can you please share us the steps what you followed to fix this issue?

**Comment by PrajaktaPurohit** [comment]
Sorry for the delay in responding to this issue. At this time there is  not enough information for us to be able to duplicate this issue. Please feel free to reopen if the issue persists.
