### ISSUE TITLE
Internal Server Error when trying to upload cookbook

### ISSUE THREAD

**Issue by frlod** [chef/chef-server#1484]
Chef server 12.15.8 on Ubuntu 16.04.
Using HA chef cluster.
Server tail shows this error:

==> /var/log/opscode/opscode-erchef/crash.log <==
2018-04-10 13:29:27 =ERROR REPORT====
Checking presence of checksum: <<"179e85803bd14077c288d304ba5ee89a">> for org <<"022e7ccc496151fa5db965f538402e0b">> from bucket "bookshelf" has taken longer than 5000 ms
2018-04-10 13:29:27 =ERROR REPORT====
Checking presence of checksum: <<"09bdb7a96a25255dc3b45cba44ba7788">> for org <<"022e7ccc496151fa5db965f538402e0b">> from bucket "bookshelf" has taken longer than 5000 ms
2018-04-10 13:29:27 =ERROR REPORT====
Checking presence of checksum: <<"086750b78cfa7f59ef38aa434be4f500">> for org <<"022e7ccc496151fa5db965f538402e0b">> from bucket "bookshelf" has taken longer than 5000 ms
2018-04-10 13:29:27 =ERROR REPORT====
Checking presence of checksum: <<"020c1ece9ad52aed1e0e9af714cb4b04">> for org <<"022e7ccc496151fa5db965f538402e0b">> from bucket "bookshelf" has taken longer than 5000 ms
2018-04-10 13:29:27 =ERROR REPORT====
{<<"method=PUT; path=/organizations/****some_organization****/sandboxes/65f538402e0b7cfde930aa8541f04738; status=500; ">>,{error,{throw,{checksum_check_error,30},[{chef_wm_named_sandbox,validate_checksums_uploaded,2,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/oc_chef_wm/src/chef_wm_named_sandbox.erl"},{line,144}]},{chef_wm_named_sandbox,from_json,2,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/oc_chef_wm/src/chef_wm_named_sandbox.erl"},{line,97}]},{webmachine_resource,resource_call,3,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/webmachine/src/webmachine_resource.erl"},{line,203}]},{webmachine_resource,do,3,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/webmachine/src/webmachine_resource.erl"},{line,148}]},{webmachine_decision_core,resource_call,1,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/webmachine/src/webmachine_decision_core.erl"},{line,47}]},{webmachine_decision_core,accept_helper,1,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/webmachine/src/webmachine_decision_core.erl"},{line,613}]},{webmachine_decision_core,decision,1,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/webmachine/src/webmachine_decision_core.erl"},{line,518}]},{webmachine_decision_core,handle_request,2,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/webmachine/src/webmachine_decision_core.erl"},{line,32}]}]}}}

All backends, backend cluster and frontend status are healthy.
The organization exists (and is visible via knife).

**Client Error**
ERROR: Server returned error 500 for https:/**/server_name**/organizations/**org_name**/sandboxes/ac0eea0acecff2b86cf2df2074c194ea, retrying 1/5 in 3s
(Repeated 5 times)

ERROR: internal server error
Response: internal service error

Note that this happens after trying to restart the cluster after all instances were turned off and turned on. The cluster consists of 3 backends and 2 frontends.

**Comment by yangpeng-chn** [comment]
I encountered the same issue with the same architecture. Hope to find a reason/solution to this.

**Comment by PrajaktaPurohit** [comment]
@frlod @yangpeng-chn We are sorry this took long to respond to. Looks like this is an issue with the bookshelf service and we would need some bookshelf logs to be able to dig into it further. Please feel free to reopen the issue with the bookshelf logs. Thank you!
