### ISSUE TITLE
How to get chef automate metrics like changes submitted, changes delivered ?

### ISSUE THREAD

**Issue by devopsvj** [chef/chef-server#1486]
How to get chef automate metrics like changes submitted, changes delivered

**Comment by devopsvj** [comment]
I have tried to use chef automate API  but not sure what api calls to be used to get those data

**Comment by PrajaktaPurohit** [comment]
@devopsvj Could you please ask for help in the community slack or place a ticket with support. Thank you!
Closing this since it is not a Chef Infra Server issue.
