### ISSUE TITLE
/organizations/<orgname>/<anything>/_acl enpoint differs between EC11 & CS12

### ISSUE THREAD

**Issue by curiositycasualty** [chef/chef-server#15]
In Enterprise Chef 11, `/organizations/ORGNAME/ANYTHING_AT_ALL/_acl` endpoint queries would return the ACLs for ORGNAME.

Where as in Chef Server 12, only the `/organizations/ORGNAME/organization/_acl` endpoint returns such info.

This breaks "knife download ..." and "knife ec backup ..." when used against chef server 12 (as well as any other ChefFS-based tools).

/cc @stevendanna @jkeiser 

Workaround (https://github.com/opscode/chef/blob/master/lib/chef/chef_fs/file_system/acls_dir.rb#L57):
`organization.json` -> `organizations.json`

**Comment by marcparadise** [comment]
Triage notes: 
* [ ]  confirm breakage of knife ec backup and knife download

Assuming so, the path forward here is to support /organizations/ORGNAME/_acl and update chef_fs accordingly

**Comment by sdelano** [comment]
This has been fixed!

```
chef (12.4.0.rc.0)> api.get("/organizations/orgname/anything/_acl")
 => {"create"=>{"actors"=>["pivotal"], "groups"=>["admins"]}, "read"=>{"actors"=>["pivotal"], "groups"=>["admins", "users"]}, "update"=>{"actors"=>["pivotal"], "groups"=>["admins"]}, "delete"=>{"actors"=>["pivotal"], "groups"=>["admins"]}, "grant"=>{"actors"=>["pivotal"], "groups"=>["admins"]}} 
```
