### ISSUE TITLE
chef-reporting does not work correctly when using default_orgname setting

### ISSUE THREAD

**Issue by jonlives** [chef/chef-server#150]
When using Chef Server with the `default_orgname` config setting, chef-reporting fails to run as URLs of the format `https://mychefserver/reports/nodes/<node>/runs` result in a 404 - manually editing the URL to `https://mychefserver/organizations/myorg/reports/nodes/<node>/runs` works correctly.

The nginx config in addons.d _looks_ like it should work in this case, but it currently doesn't.

I'm running chef-server-core-12.0.7

**Comment by markan** [comment]
As reporting is currently deprecated I'm closing this. Feel free to reopen this if I've mis-categorized.
