### ISSUE TITLE
LDAP: Synthesize a displayname from surname, givenname

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#151]
As a customer, I would like the chef server LDAP module to create a `displayname` field by copying the `name` attribute, or concatenating the `givenname` and `surname` attributes together with a space.

For example, my LDAP record might have this, but no `displayname`. Name is a good substitute in this case.

```
name: Sean Horn
```

Alternatively, my LDAP record might have this and no `displayname`

```
sname: Horn
givenname: Sean
```

The Chef server's ldap module should just concatenate those values with a space into `displayname`and create the chef server user record using that.

If neither of these avenues are taken by the chef server against an LDAP server lacking `displayname` attributes for users, their name shows up as `"unknown"` in the Manage interface.

**Comment by docwhat** [comment]
I just filed #800 which is related and/or a duplicate.  Does your schema have `cn`?
