### ISSUE TITLE
WARN: Deprecated Positional Arguments for Sign()

### ISSUE THREAD

**Issue by happicamper** [chef/chef-server#1511]
Chef server is working fine but the log shows a lot of WARN flag whenever a node is using knife bootstrap.

## Expected Behavior
Knife bootstrap will install and do the recipe instructed without WARN deprecations.

## Current Behavior
Knife bootstrap deprecation warning always shows up whenever used.

## Steps to Reproduce (for bugs)

1.

## Environment
* Chef Server Version: Latest(12.17.33)
* Chef client Version: Latest(14.2.0)
* Total/free RAM and disk space: 4 GB / 50 GB Free Storage
* Operating System and Version: Centos 7
* If upgrading, previous Chef Server version:
* Running in a container? No

**Comment by thommay** [comment]
Thanks for the bug report, but this isn't a chef server bug. It's a harmless warning introduced in the Chef Client 14.2 release, and is fixed already in preparation for the release at the start of July.

**Comment by happicamper** [comment]
@thommay Hello, sorry for this report, I've just jumped into the conclusion that this caused by wrong installation or configuration. Thank you very much.
