### ISSUE TITLE
Please provide the contents of the stacktrace.out file if you file a bug report

### ISSUE THREAD

**Issue by raghudevopsaws** [chef/chef-server#1517]
## Steps to Reproduce (for bugs)

1.

## Your Environment

* Chef Server Version:
* Total/free RAM and disk space:
* Operating System and Version:
* If upgrading, previous Chef Server version:
* Running in a container?

**Comment by PrajaktaPurohit** [comment]
@raghudevopsaws Please let us know if there is any bug that needs our attention.
Closing this out for now.
