### ISSUE TITLE
analytics should be removed as an option in chef-server-ctl install command

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#152]
From @vinyar in chef/chef#3273:

>chef-server-ctl install
You must supply an addon name. Valid names include: chef-ha, chef-sync, opscode-analytics, opscode-manage, opscode-push-jobs-server, opscode-reporting.

>Details: 
It will not work out of the box, as both analytics and chef server use postgresql on port 5432. Also, according to @jamesc there are performance penalties to having both on one the same box.

**Comment by sean-horn** [comment]
Yes, please get rid of this. We have purposefully left "combined mode" out of the docs to deter usage.
Much better to start with a decent architecture to begin with.

**Comment by mfdii** [comment]
Now that combined mode is supported, should we add this back in?

**Comment by vinyar** [comment]
I say yes, but only when we add it to the docs with a proper write up, and after testing that it works with other products that might run on chef server - such as push jobs or supermarket.

**Comment by sdelano** [comment]
I agree with @vinyar - when we do the work to ensure it works and document it, we'll re-enable this
