### ISSUE TITLE
Remove cookbook dependency on openssl post Chef 14.4

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#1548]
The cookbook we use to configure the Chef server currently relies on the openssl cookbook to generate certs if they're not provided. With Chef 14.4 this resource will be built into Chef and we can remove this dependency (~1 meg) from the chef-server.

https://github.com/chef/chef-server/blob/5c7c988cba529c4794b21faa9c6bd135f37f47c8/omnibus/files/private-chef-cookbooks/private-chef/metadata.rb#L15

**Comment by PrajaktaPurohit** [comment]
@tas50 Thank you for fixing this! Closing in favor of : https://github.com/chef/chef-server/pull/1567
