### ISSUE TITLE
Do not allow "system" groups to be deleted

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#155]
The "admins", "billing-admins", "clients" and "users" groups should be treated as "system" groups and should not be able to be deleted.

**Comment by jeremiahsnapp** [comment]
https://github.com/chef/chef-manage-issues/issues/62

**Comment by stevendanna** [comment]
@jeremiahsnapp Thanks for filing this.  It looks like it has also been filed here: https://github.com/chef/chef-server/issues/123 along with some implementation advice.  I'm going to close this version out so we only have to track it in one place.

Thanks again!
