### ISSUE TITLE
chef-server-ctl psql reporting cannot find db_password

### ISSUE THREAD

**Issue by tscheffe** [chef/chef-server#1556]
When I install Chef Server `12.17.33` and Opscode Reporting `1.8.0` then try to
run `chef-server-ctl psql reporting` I get an exception and am unable to connect
to the database. Neither `read-only` or `write` work.

The Chef Server and Reporting functionality continue to work as normal, the only
issue seems to be the `psql` command not working with `reporting`.

## Expected Behavior
I expect `$ sudo chef-server-ctl psql reporting` to connect me to the `opscode_reporting` database as the read-only user and `sudo chef-server-ctl psql reporting --write` to connect me to that database as the read-write user.

## Current Behavior
Failure to find `db_password`:
```bash
$ sudo chef-server-ctl psql reporting

/opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/veil-0.3.0/lib/veil/credential_collection/base.rb:81:in `get': Credential 'sql_ro_password' not found in group 'postgresql'. (Veil::CredentialNotFound)
        from /opt/opscode/embedded/service/omnibus-ctl/psql.rb:79:in `block in load_file'
        from /opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:204:in `block in add_command_under_category'
        from /opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:747:in `run'
        from /opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl:242:in `<main>'
```

Fails for write too:
```bash
$ sudo chef-server-ctl psql reporting --write

/opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/veil-0.3.0/lib/veil/credential_collection/base.rb:81:in `get': Credential 'sql_password' not found in group 'postgresql'. (Veil::CredentialNotFound)
        from /opt/opscode/embedded/service/omnibus-ctl/psql.rb:79:in `block in load_file'
        from /opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:204:in `block in add_command_under_category'
        from /opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:747:in `run'
        from /opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl:242:in `<main>'
```

## Steps to Reproduce (for bugs)
On a CentOS6 VM, install Chef Server:

```bash
$ wget https://packages.chef.io/files/stable/chef-server/12.17.33/el/6/chef-server-core-12.17.33-1.el6.x86_64.rpm
$ sudo yum localinstall chef-server-core-12.17.33-1.el6.x86_64.rpm
$ sudo chef-server-ctl reconfigure
```

Then install Opscode Reporting:
```bash
$ wget https://packages.chef.io/files/stable/opscode-reporting/1.8.0/el/6/opscode-reporting-1.8.0-1.el6.x86_64.rpm
$ sudo yum localinstall opscode-reporting-1.8.0-1.el6.x86_64.rpm
$ sudo opscode-reporting-ctl reconfigure
$ chef-server-ctl reconfigure
```

Verify issue:
```bash
$ sudo chef-server-ctl psql reporting --write

/opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/veil-0.3.0/lib/veil/credential_collection/base.rb:81:in `get': Credential 'sql_password' not found in group 'postgresql'. (Veil::CredentialNotFound)
        from /opt/opscode/embedded/service/omnibus-ctl/psql.rb:79:in `block in load_file'
        from /opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:204:in `block in add_command_under_category'
        from /opt/opscode/embedded/lib/ruby/gems/2.4.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:747:in `run'
        from /opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl:242:in `<main>'
```

## Your Environment

* Chef Server Version: Chef Server `12.17.33` and Opscode Reporting `1.8.0`
* Total/free RAM and disk space: Azure VirtualMachine (classic) - Basic A4 (8 Cores, 14 GiB memory), 30G disk with 14G free.
* Operating System and Version: `lsb_releasde -d # CentOS release 6.9 (Final)`
* If upgrading, previous Chef Server version: Chef Server `12.6.0` and Reporting 1.4.0`
* Running in a container? No

## Troubleshooting/Solution:
I was able to get the command working after some troubleshooting, I'll provide
some background and then present the workaround I came up with.

[Here is the relevant code](https://github.com/chef/chef-server/blob/94a476e24249f87c0f47b56f9cdf2af4b312f343/src/chef-server-ctl/plugins/psql.rb). Problem seems to still be present as of posting.

The problem seems to have originated with the [Chef Server 12.14 "Reduce password proliferation"](https://docs.chef.io/release_notes_server.html#reduce-password-proliferation)
effort.

[This commit](https://github.com/chef/chef-server/commit/2d18427f654f92036d5b4121e5381d9dcf375ed0#diff-d1c7618b03e9e7898c02717e0b20e3e3) from @marcparadise seems to be where the command actually broke, or wasn't fixed.

I used some `puts` statements in the code to see some config values and determined
that the `config_key` for the `reporting` database should be `opscode-reporting`,
as that's where the passwords now live. That works for password retrieval, but
breaks on username retrieval. For that to work the `config_key` should stay the
same, as `postgresql`.

This hack fixed it for me:
```
  77     # Sorry.
  78     db_hash_key = "opscode_erchef" if db_hash_key == "opscode-erchef"
+ 79     db_hash_key = "opscode-reporting" if db_name == "opscode_reporting"
  80     db_password=credentials.get(db_hash_key, "sql_#{ro}password")
```

Given that the service continues to work normally, fixing this the "right way"
by moving the config values around seems challenging. Maybe this hack is alright?

**Comment by PrajaktaPurohit** [comment]
@tscheffe Thank you for your time and the insight into the issue. At this time, we have officially EOL'ed opscode_reporting. Please find the details at: https://blog.chef.io/end-of-life-announcement-for-chef-reporting-enterprise-chef-server-11-and-chef-analytics/ 

Closing this issue in favor of the announcement above.
