### ISSUE TITLE
Chef-server installation on ubuntu16 with docker file "Error executing action `run` on resource 'execute[oc_id_schema]'"

### ISSUE THREAD

**Issue by Johnjosh11** [chef/chef-server#1562]
## Your Environment

* Chef Server Version: 12.17.33
* Total/free RAM and disk space: 8 core cpu, 16GB Ram, 10 gb hard disk 
* Operating System and Version: ubuntu16.04
* If upgrading, previous Chef Server version: no
* Running in a container yes

Docker command used - docker run --privileged -ti --name test -d -p 443:443 jboothapati/docker-for-chef-server
Docker image located at - https://github.com/Johnjosh11/Docker-for-chef-Server/blob/branch1-12.17.15/Dockerfile

**Error Message:** 
 * execute[chown -R opscode:opscode /var/log/opscode/oc_id] action run
    - execute chown -R opscode:opscode /var/log/opscode/oc_id
  * execute[oc_id_schema] action run

    ================================================================================
    Error executing action `run` on resource 'execute[oc_id_schema]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Command execution failed. STDOUT/STDERR suppressed for sensitive resource

    Resource Declaration:
    ---------------------
    suppressed sensitive resource output

    Compiled Resource:
    ------------------
    suppressed sensitive resource output

    System Info:
    ------------
    chef_version=12.21.31
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    program_name=/opt/opscode/embedded/bin/chef-client
    executable=/opt/opscode/embedded/bin/chef-client

Recipe: private-chef::postgresql
  * runit_service[postgresql] action restart (up to date)
  * execute[restart_postgresql_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/postgresql/log
Recipe: private-chef::oc_bifrost
  * runit_service[oc_bifrost] action restart (up to date)
  * execute[restart_oc_bifrost_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/oc_bifrost/log
Recipe: private-chef::oc_id
  * runit_service[oc_id] action restart

    ================================================================================
    Error executing action `restart` on resource 'runit_service[oc_id]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
    STDOUT: fail: /opt/opscode/service/oc_id: unable to change to service directory: file does not exist
    STDERR:
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id returned 1

    Cookbook Trace:
    ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
    /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:330:in `block in <class:RunitService>'

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/enterprise/definitions/component_runit_service.rb

     37:   runit_service component do
     38:     action :enable
     39:     retries 20
     40:     control params[:control] if params[:control]
     41:     options(
     42:       log_directory: log_directory
     43:     )
     44:     params[:runit_attributes].each do |attr_name, attr_value|
     45:       send(attr_name.to_sym, attr_value)
     46:     end
     47:   end
     48:

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'

    runit_service("oc_id") do
      params {:package=>"private_chef", :log_directory=>nil, :svlogd_size=>nil, :svlogd_num=>nil, :ha=>nil, :control=>nil, :runit_attributes=>{}, :action=>:enable, :name=>"oc_id"}
      provider Chef::Provider::RunitService
      action [:enable]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 20
      retry_delay 2
      default_guard_interpreter :default
      service_name "oc_id"
      enabled false
      running false
      masked nil
      pattern "oc_id"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service"
      sv_bin "/opt/opscode/embedded/bin/sv"
      sv_dir "/opt/opscode/sv"
      service_dir "/opt/opscode/service"
      lsb_init_dir "/opt/opscode/init"
      options {:log_directory=>"/var/log/opscode/oc_id"}
      log true
      restart_on_update true
      run_template_name "oc_id"
      log_template_name "oc_id"
      check_script_template_name "oc_id"
      finish_script_template_name "oc_id"
      sv_templates true
      log_dir "/var/log/oc_id"
      service_mirror # Declared in

    service("oc_id") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "oc_id"
      enabled nil
      running nil
      masked nil
      pattern "oc_id"
      start_command "/opt/opscode/embedded/bin/sv start /opt/opscode/service/oc_id"
      stop_command "/opt/opscode/embedded/bin/sv stop /opt/opscode/service/oc_id"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service/oc_id"
      restart_command "/opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id"
    end

      declared_type :runit_service
      cookbook_name "private-chef"
      recipe_name "oc_id"
    end

    System Info:
    ------------
    chef_version=12.21.31
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    program_name=/opt/opscode/embedded/bin/chef-client
    executable=/opt/opscode/embedded/bin/chef-client

Running handlers:
Running handlers complete
Chef Client failed. 71 resources updated in 01 minutes 15 seconds
[2018-08-28T06:25:38+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2018-08-28T06:25:38+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-08-28T06:25:38+00:00] FATAL: Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* Mixlib::ShellOut::ShellCommandFailed occurred in chef run: execute[oc_id_schema] (private-chef::oc_id line 152) had an error: Mixlib::ShellOut::ShellCommandFailed: Command execution failed. STDOUT/STDERR suppressed for sensitive resource
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: runit_service[oc_id] (private-chef::oc_id line 37) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
STDOUT: fail: /opt/opscode/service/oc_id: unable to change to service directory: file does not exist
STDERR:
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id returned 1

**Comment by Johnjosh11** [comment]
**Docker file:**
FROM ubuntu:16.04
MAINTAINER OitOps 

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -yq --no-install-recommends wget curl vim rsync && \
    wget --no-check-certificate --content-disposition "http://www.opscode.com/chef/download-server?p=ubuntu&pv=16.04&m=x86_64&v=latest&prerelease=false&nightlies=false" && \
    dpkg -i chef-server*.deb && \
    rm chef-server*.deb && \
    apt-get remove -y wget && \
    rm -rf /var/lib/apt/lists/*
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl
COPY main.sh chef.sh /usr/local/bin/
VOLUME /var/log
CMD ["main.sh"]

**main.sh**
#!/bin/bash -e
sysctl -wq kernel.shmmax=17179869184
sysctl -wq net.ipv6.conf.lo.disable_ipv6=0
/opt/opscode/embedded/bin/runsvdir-start &
if [ -f "/root/chef_configured" ]
  then
    echo -e "\nChef Server already configured!\n"
    chef-server-ctl status
  else
    echo -e "\nNew install of Chef-Server!"
    /usr/local/bin/chef.sh
fi
tail -F /opt/opscode/embedded/service/*/log/current

**chef.sh**
#!/bin/bash

# Create chef-server.rb with variables
echo "nginx['enable_non_ssl']=false" > /etc/opscode/chef-server.rb

if [[ -z $SSL_PORT ]]; then
  echo "nginx['ssl_port']=443" >> /etc/opscode/chef-server.rb
else
  echo "nginx['ssl_port']=$SSL_PORT" >> /etc/opscode/chef-server.rb
fi

if [[ -z $CONTAINER_NAME ]]; then
  echo "nginx['server_name']=\"chef-server\"" >> /etc/opscode/chef-server.rb
else
  echo "nginx['server_name']=\"$CONTAINER_NAME\"" >> /etc/opscode/chef-server.rb
fi

echo -e "\nRunning: 'chef-server-ctl reconfigure'. This step will take a few minutes..."
export PATH=/opt/opscode/bin:/opt/opscode/bin/embedded:$PATH
/opt/opscode/embedded/bin/runsvdir-start &
chef-server-ctl reconfigure

URL="http://127.0.0.1:8000/_status"
CODE=1
SECONDS=0
TIMEOUT=60

return=$(curl -sf ${URL})

if [[ -z "$return" ]]; then
  echo -e "\nINFO: Chef-Server isn't ready yet!"
  echo -e "Blocking until <${URL}> responds...\n"

  while [ $CODE -ne 0 ]; do

    curl -sf \
         --connect-timeout 3 \
         --max-time 5 \
         --fail \
         --silent \
         ${URL}

    CODE=$?

    sleep 2
    echo -n "."

    if [ $SECONDS -ge $TIMEOUT ]; then
      echo "$URL is not available after $SECONDS seconds...stopping the script!"
      exit 1
    fi
  done;
fi

echo -e "\n\n$URL is available!\n"
echo -e "\nSetting up admin user and default organization"
chef-server-ctl user-create admin inadev support support@inadev.com 'support@123' --filename /etc/chef/inadev.pem
chef-server-ctl org-create inadev 'Inadev Corporation' --association_user admin --filename /etc/chef/inadev-validator.pem
echo -e "\nRunning: 'chef-server-ctl install chef-manage'"...
chef-server-ctl install chef-manage
echo -e "\nRunning: 'chef-server-ctl reconfigure'"...
chef-server-ctl reconfigure
echo "{ \"error\": \"Please use https:// instead of http:// !\" }" > /var/opt/opscode/nginx/html/500.json
sed -i "s,/503.json;,/503.json;\n    error_page 497 =503 /500.json;,g" /var/opt/opscode/nginx/etc/chef_https_lb.conf
sed -i '$i\    location /knife_admin_key.tar.gz {\n      default_type application/zip;\n      alias /etc/chef/knife_admin_key.tar.gz;\n    }' /var/opt/opscode/nginx/etc/chef_https_lb.conf
echo -e "\nCreating tar file with the Knife keys"
cd /etc/chef/ && tar -cvzf knife_admin_key.tar.gz admin.pem my_org-validator.pem
echo -e "\nRestart Nginx..."
chef-server-ctl restart nginx
chef-server-ctl status
touch /root/chef_configured
echo -e "\n\nDone!\n"

**Comment by Johnjosh11** [comment]
Can someone please help me with this issue.

**Comment by PrajaktaPurohit** [comment]
@Johnjosh11 I apologize for the delay in getting back to you on this. As of today we do not support omnibus chef-infra-server in docker. If this is something you would like I would request you to please put an idea on our Aha! board. (https://chef-software.ideas.aha.io/).
Omnibus was not structured in a way that made for a good experience for docker users. Closing this request in favor of this known issue.
