### ISSUE TITLE
Chef restore failed when restoring data on new server

### ISSUE THREAD

**Issue by eosho** [chef/chef-server#1563]
I am migrating my chef instance from CentOS to RHEL7. I am able to successfully backup my old instance using `sudo chef-server-ctl backup --yes`. However, when I start the restore on my new server using `chef-server-ctl restore /path/to/tar/archive.tar.gz` postgresql fails with a timeout error.

## Current Behavior
Postgresql fails at "Restoring the postgresql data"
`[ERROR] Command timed out after 600s: Command exceeded allowed execution time, process terminated`

## Steps to Reproduce (for bugs)

1. Just a simple backup from one server and restore on another server.

## Your Environment

* Chef Server Version: 12.9.0
* Total/free RAM and disk space: (2 vcpus, 7 GB memory)
* Operating System and Version: RedHat 7.5
* If upgrading, previous Chef Server version:
* Running in a container? No

**Comment by rhass** [comment]
You may want to try setting `--timeout 3600` or something to that effect.

**Comment by PrajaktaPurohit** [comment]
@eosho Hopefully the suggestion worked for you. Closing this issue due inactivity. Please feel free to reopen if it persists. Thank you!
