### ISSUE TITLE
Can't delete a user, no chef-server-ctl or knife commands for group operations?

### ISSUE THREAD

**Issue by jblaine** [chef/chef-server#157]
Chef server 12.0.8

I see no 'group' subcommands to chef-server-ctl. How do I remove john from the org's 'admins' group with no builtin web UI nowadays, aside from paying for Manage?

```
sudo /opt/opscode/bin/chef-server-ctl user-delete johnmc
Do you want to delete the user john? (Y/N) Y
ERROR: You authenticated successfully to https://127.0.0.1:443 as pivotal but you are not authorized for this action
Response:  Please remove john from this organization's admins group before removing him or her from the organization.
```

**Comment by stevendanna** [comment]
@jblaine A temp. workaround: If you are an admin in the org, you can use the `knife acl` gem to remove the user from the admin group.

**Comment by jblaine** [comment]
Thanks for the workaround,  Steve.

**Comment by williamsjj** [comment]
Just created a new Chef 12 server and the private key for the initial user got corrupted. So I need to be able to delete the user but can't because of this issue. If y'all are going to make the WebUI a premium feature, the CLI needs to be bullet-proof for Open Source.

**Comment by MattHodge** [comment]
@williamsjj Agreed, this is painful..

**Comment by MattHodge** [comment]
For those that stumble upon this post:

```{bash}
# Install knife acl from https://github.com/chef/knife-acl

# Remove user from admins group
knife group remove user <TheUser> admins
 
# Delete a user
chef-server-ctl user-delete <TheUser>
```

**Comment by predatorian3** [comment]
Does the knife-acl gem need to be installed on the chef server itself? I am also running into these issues when using ChefDK and trying to delete a user.

**Comment by jblaine** [comment]
@predatorian3 No.

**Comment by mmzyk** [comment]
@jblaine Thanks for pointing this out and for helping out others.

@williamsjj  &@MattHodge Agreed. We're working on making all of this better.

**Comment by fulloflilies** [comment]
+1

**Comment by tylercloke** [comment]
Fixed here https://github.com/chef/knife-opc/pull/35 and will be out in next release of the Chef Server.

Simply pass `chef-server-ctl org-user-remove <org> <user> --force` (note the force flag) to remove said user from the `admins` and `billing-admins` groups for the offending org(s) and retry `chef-server-ctl user-delete <user>` after.

Updating the `user-delete` command to advise this here https://github.com/chef/knife-opc/pull/36.

For context, the motivation behind all this is, if you remove the last admin from an org's admins group, the org will be in a bad state that is hard to fix, so we are trying to prevent this state. Now (on next Chef Server release) we will actually have all the tools in place in `chef-server-ctl` to get around all these issues.

Will also update the documentation.
