### ISSUE TITLE
Cookbook upload failing with 404

### ISSUE THREAD

**Issue by winterrmute** [chef/chef-server#1570]
Hi, i try to upload a cookbook to our chef server, but with no success.
I've installed the chef server, reconfigured it, created the organization and user. As next I installed chefdk on my workstation and created a cookbook. I created the knife.rb, downloaded the pem files, but while upload of cookbooks I get following message:

```
ERROR: The object you are looking for could not be found
Response: <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
  <title>Chef - 404 Not Found</title>
  <link media="all" rel="stylesheet" type="text/css" href="/css/all.css" />
  <!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/css/lt7.css" /><![endif]-->
</head>
<body>
  <div class="header-block">
    <div id="header">
      <strong class="logo"><a href="https://www.chef.io">Chef</a></strong>
    </div>
  </div>
  <div id="wrapper">
    <div id="main">
      <div class="mybox">
        <div id="content">
          <h1>404 - Not Found</h1>
          <p>Sorry, I can't find what you are looking for.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-block">
    <div id="footer">
      <div class="mybox">
      </div>
      <div class="footer-bottom">
        <span>&copy; 2010&thinsp;&ndash;&thinsp;2017 Chef Software, Inc. All Rights Reserved</span>
      </div>
    </div>
  </div>
</body>
</html>
```

chef-server-ctl responses with:
`10.21.248.66 - - [06/Sep/2018:17:12:03 +0200]  "GET /cookbooks?num_versions=all HTTP/1.1" 404 "0.001" 558 "-" "Chef Knife/14.2.0 (ruby-2.5.1-p57; ohai-14.2.0; x86_64-linux; +https://chef.io)" "-" "-" "-" "14.2.0" "algorithm=sha1;version=1.1;" "some_user" "2018-09-06T15:12:03Z" "some_string" 1033`

We are running our Chef Server on Ubuntu 16.04. My Chef-workstation is running on Ubuntu 18.04

Anyone idea what is going wrong?

**Comment by markan** [comment]
So looking at the URI /cookbooks?num_versions=all I think you don't have an organization in your uri. 
The request should look like /organizations/ORGNAME/cookbooks?num_versions=all. That's why you are getting HTML; nginx isn't actually routing you to the rest API.

**Comment by PrajaktaPurohit** [comment]
@winterrmute Just wanted to check if @markan's suggestion help fix the issue. Please feel free to reopen if not. Thank you!
