### ISSUE TITLE
Getting Error bundler: failed to load command: ./bin/oc-chef-pedant (./bin/oc-chef-pedant) after chef-server-ctl test

### ISSUE THREAD

**Issue by ShardaComputeSolutions** [chef/chef-server#1575]
## Steps to Reproduce (for bugs)

1.

## Your Environment

* Chef Server Version:chef-server-core_12.17.33-1
* Total/free RAM and disk space:   

           
total        used        free      shared  buff/cache   available
Mem:           990M        732M         61M         31M        196M         64M
Swap:            0B          0B          0B

* Operating System and Version: 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
* If upgrading, previous Chef Server version: No
* Running in a container? AWS EC2 t2.micro

**Comment by ShardaComputeSolutions** [comment]
bundler: failed to load command: ./bin/oc-chef-pedant (./bin/oc-chef-pedant)
RuntimeError: Configuration file '/var/opt/opscode/oc-chef-pedant/etc/pedant_config.rb' not found!
  /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/config.rb:34:in `from_argv'
  /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:55:in `setup'
  /opt/opscode/embedded/service/oc-chef-pedant/bin/oc-chef-pedant:10:in `<top (required)>'

**Comment by ShardaComputeSolutions** [comment]
I ran chef-server-ctl cleanse followed by chef-server-ctl reconfigure. 

ran the chef-server-ctl start followed by a test and got the same error. I am new to chef. kindly help. 

root@chef:/# chef-server-ctl start 
ok: run: bookshelf: (pid 30784) 3471s
ok: run: nginx: (pid 30592) 3475s
ok: run: oc_bifrost: (pid 30405) 3477s
ok: run: oc_id: (pid 30562) 3476s
ok: run: opscode-chef-mover: (pid 26414) 4095s
ok: run: opscode-erchef: (pid 23240) 11s
ok: run: opscode-expander: (pid 30689) 3473s
ok: run: opscode-solr4: (pid 30635) 3474s
ok: run: postgresql: (pid 30610) 3475s
ok: run: rabbitmq: (pid 27494) 3900s
ok: run: redis_lb: (pid 26483) 4100s
root@chef:/# chef-server-ctl test
bundler: failed to load command: ./bin/oc-chef-pedant (./bin/oc-chef-pedant)
RuntimeError: Configuration file '/var/opt/opscode/oc-chef-pedant/etc/pedant_config.rb' not found!
  /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/config.rb:34:in `from_argv'
  /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:55:in `setup'
  /opt/opscode/embedded/service/oc-chef-pedant/bin/oc-chef-pedant:10:in `<top (required)>'

**Comment by ShardaComputeSolutions** [comment]
ran cp /opt/opscode/embedded/service/oc-chef-pedant/pedant_config.rb /var/opt/opscode/oc-chef-pedant/etc/ to copy the pedant_config.rb file, followed by reconfigure and test to receive the below error:

Configuring logging...
bundler: failed to load command: ./bin/oc-chef-pedant (./bin/oc-chef-pedant)
Errno::ENOENT: No such file or directory @ rb_sysopen - /var/log/opscode/oc-chef-pedant/http-traffic.log
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:752:in `initialize'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:752:in `open'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:752:in `create_logfile'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:746:in `rescue in open_logfile'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:742:in `open_logfile'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:736:in `set_dev'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:671:in `initialize'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:387:in `new'
  /opt/opscode/embedded/lib/ruby/2.4.0/logger.rb:387:in `initialize'
  /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:75:in `new'
  /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:75:in `configure_logging'
  /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant.rb:57:in `setup'
  /opt/opscode/embedded/service/oc-chef-pedant/bin/oc-chef-pedant:10:in `<top (required)>'

**Comment by daytonpa** [comment]
Off topic, but a t2.micro may also not be enough hardware.  All system requirements [can be found here](https://docs.chef.io/chef_system_requirements.html).

**Comment by markan** [comment]
t2.micro is definitely too small. 2GB is a bare minimum, with 4GB recommended. Basically SOLR/java will eat somewhere around .7-1 GB starting cold, and grow under load. 

I'm going to close this issue,  please reopen if you see these problems with higher memory installs.

**Comment by markan** [comment]
I'm marking this as wontfix because while you could possibly tune solr to use less RAM, you'd have to tune a lot of other things as well to fit it into a low memory instance, and it probably wouldn't end up being very useful without a lot of work, if you could do it at all. It's a technically interesting project though.
