### ISSUE TITLE
Chef Server returns 500 on PUT to NODE resource, failure in gen_server call to chef_index_queue

### ISSUE THREAD

**Issue by markan** [chef/chef-server#1586]
In a tiered system the frontends fail with 500's and report a stack trace like this in the erchef logs:
```
<<"method=PUT; path=/organizations/XXX/nodes/NODENAME; status=500; ">>,{error,{exit,{timeout,{gen_server,call,['chef_index_queue/chef',{publish,<<"vnode-815">>,<<"{\"action\":\"add\",\"payload\":
...
```

## Expected Behavior
We expects nodes to be passed to the indexing layer and properly indexed. 

## Current Behavior

The internal erlang message queue gets deeply backed up. 
In an erlang shell, the command:
```erlang:process_info(whereis('chef_index_queue/chef'),message_queue_len).```
will report hundreds, if not thousands of queued messages. Sometimes this will even push the host into swap.  (77k nodes in one case, each 100k+ in size)

This backup causes the request to publish to fail, as it takes more than the 5 s timeout.

## Debug notes
(Stolen from zendesk 15041)
* RabbitMQ was not down. It "appeared" to be functioning normally and was accepting messages and serving them up.
* opscode-expander logs showed yuuuuge "wait times" (hundreds to thousands of seconds), the time from which an item is published on the queue to when it is expanded and sent to solr
* opscode-expanderctl queue-depth, however, showed empty queues
```
cd /opt/opscode/embedded/service/opscode-expander
sudo veil-env-helper --pack -s rabbitmq.password bin/opscode-expanderctl queue-depth
```

* the opscode-expander log also showed millisecond times for both tokenizing the document and posting it to solr
* the backlog of queues was actually inside an erlang process message queue on the frontends, waiting to be sent to RabbitMQ
* the 5s gen_server timeout was because we couldn't process these messages in 5s. according to the logs, the backlogs was up to 1000s of seconds

## Steps to Reproduce (for bugs)

We don't currently have a good repro. One possibility is slow network connections between FE & BE.
Sometimes increasing cores and RAM on FEs corrects the problem.

## Your Environment

* Chef Server Version: 12.15. Tiered configuration.
* Total/free RAM and disk space: FE 8GB/4 CPU, BE 32GB/ 24 CPU
* Operating System and Version: RHEL 7

**Comment by markan** [comment]
Actions to help resolve:
* While we have a chef_index:status to report message queue depth, we don't expose that externally.  We should make it easier to probe the system to help understand what is failing. In particular the bunnyc queue depth should probably be reported in the statistics endpoint, and we may want to track some sort of connection stats.

* We are using our own fork of bunnyc and the underlying amqp code. Is there something better to be using? Are we using it correctly?  Right now we are using a fork from 6 years back.

* We should investigate batching to solr instead of rabbitmq. We currently do that with our Elasticsearch configurations.

**Comment by sean-horn** [comment]
Got this again on Zendesk 22180

**Comment by PrajaktaPurohit** [comment]
Steps to repro: 
In conversation with @markan learned from a customer.
Adding 1s sleep to the response from elasticsearch will overwhelm the system.

**Comment by marcparadise** [comment]
Resolved with https://github.com/chef/chef-server/pull/1945.  

Separately, rabbitmq does not ship in current versions of Chef Server.
