### ISSUE TITLE
12.18.14 API version bump introduced an incompatibility with an older version of Berkshelf

### ISSUE THREAD

**Issue by moutons** [chef/chef-server#1598]
### Chef Server Version
12.18.14

### Platform Details
not relevant to the issue

### Configuration
not relevant

### Scenario:
cookbook uploads with chefDK 3.1.0 and chef-server 12.18.14 will fail 

### Steps to Reproduce:
Use Chef Server 12.18.4 and Berkshelf 7.0.4 (or chefdk 3.1.0) to upload a cookbook
https://github.com/chef/chef-dk/blob/d154b308119a182ffd69e1d644b7c2691c699341/Gemfile.lock#L48

### Expected Result:
Successful cookbook upload, appropriate handling of `req_api_version=1` appears to be the issue as it pertains to Chef Server.

### Actual Result:
Here's error output from berks:
```
I, [2018-12-03T17:14:32.822218 #24377] INFO -- : Starting upload 
D, [2018-12-03T17:14:33.138192 #24377] DEBUG -- : Uploading apt 
E, [2018-12-03T17:14:34.215923 #24377] ERROR -- : Net::HTTPServerException: 400 "Bad Request" 
E, [2018-12-03T17:14:34.216052 #24377] ERROR -- : /opt/chefdk/embedded/lib/ruby/2.5.0/net/http/response.rb:122:in `error!' 
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/http.rb:152:in `request' 
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/http.rb:123:in `put'
```
This can be associated with the following output in erchef logs:
```
2018-12-03T17:06:03Z erchef@127.0.0.1 method=PUT; path=/organizations/support/cookbooks/apt/6.1.3; status=400; req_id=g3IAA2QAEGVyY2hlZkAxMjcuMC4wLjEBAAJsMQC4AAMAAAAA; org_name=support; msg={invalid_key,<<"all_files">>}; couchdb_groups=false; couchdb_organizations=false; couchdb_containers=false; couchdb_acls=false; 503_mode=false; couchdb_associations=false; couchdb_association_requests=false; req_time=2; rdbms_time=1; rdbms_count=1; user=support-user; req_api_version=1;
```

This was the change to Berkshelf to accommodate the API version bump:
https://github.com/berkshelf/berkshelf/pull/1789

Modifying berkshelf in-place to have the new lines in lib/berkshelf/ridley_compat.rb let upload complete successfully.

**Comment by PrajaktaPurohit** [comment]
@moutons Looks like this could be fixed by the customer by upgrading to the newer version of berkshelf post v7.0.6. Please repoen the issue if there need to be some work done related to this on the chef-server side.
