### ISSUE TITLE
chef-server does not respect api_fqdn set in chef-server.rb

### ISSUE THREAD

**Issue by voroniys** [chef/chef-server#1606]
NOTE:
We use GitHub issues to track bugs and feature requests. If you need help please post to our Mailing List or join the Chef Community Slack.

 * Chef Community Slack at http://community-slack.chef.io/.
 * Chef Mailing List https://discourse.chef.io/

### Chef Server Version
12.18.14-1
### Platform Details
Ubuntu 18.04 on AWS EC2

### Configuration
```
# cat /etc/opscode/chef-server.rb
api_fqdn = 'chef.shared.internal'

```

### Scenario:
I want chef being configured for the name provided in api_fqdn and not to EC2 fqdn.

### Steps to Reproduce:
Deploy ec2 instance
use /etc/opscode/chef-server.rb as specified above
run chef-server-ctl reconfigure

### Expected Result:
Chef server is configured to the name specified in api_fqdn, fo instance certificates in /var/opt/opscode/nginx/ca has CN equal to provided api_fqdn, and not the ohai provided fqdn

### Actual Result:
server is always configured to node['fqdn'] and ignore api_fqdn setting in chef-server.rb completely

**Comment by kevinreedy** [comment]
Confirmed this today on another Ubuntu 18.04 box with Chef Server 13.0.17. Fixed my issue with the answer at https://stackoverflow.com/questions/54185355/chef-server-api-fqdn-is-ignored

**Comment by jashaik** [comment]
We tried reproducing the issue by setting the api_fqdn to non-default.chef-server.dev and running reconfigure but everything is working as expected.The issue mentioned in this ticket is not reproduceble with Chef Server 13.0.17 or Chef Server 14.

The certs also getting generated in the path /var/opt/opscode/nginx/ca .
![Screenshot 2021-01-28 at 1.18.34 PM.png](https://images.zenhubusercontent.com/5fe2f3f58d2c76b05d0adc02/e4d13cce-3ed7-40cb-834d-916ddf64d8f3)
![Screenshot 2021-01-28 at 1.22.29 PM.png](https://images.zenhubusercontent.com/5fe2f3f58d2c76b05d0adc02/042b9ffd-32e5-460d-ba7a-c994449ee41b)
The pedant tests are also passing without any issues related to api_fqdn
![Screenshot 2021-01-27 at 11.46.50 AM.png](https://images.zenhubusercontent.com/5fe2f3f58d2c76b05d0adc02/6d1cc5a4-f94b-4d45-a9d3-cafce2333fa8)
The chef-manage is also working as expected.
![Screenshot 2021-01-28 at 11.41.15 AM.png](https://images.zenhubusercontent.com/5fe2f3f58d2c76b05d0adc02/bc18f6f9-e4ea-4bdf-9da0-3781b6477ce3)

You can reopen the the ticket if the issue persists but we are closing it for now

**Comment by lbakerchef** [comment]
Tried to reproduce.  I changed my `api_fqdn` to `blah` and reconfigured.  `chef-server-ctl test` then bugged out, as I expected.
```
# cat /etc/opscode/chef-server.rb
api_fqdn "blah"
# chef-server-ctl test
Configuring logging...
Creating platform...
Configured server URL: https://blah
Configured base resource URL: https://blah
Creating org pedant_testorg_api_80109
bundler: failed to load command: ./bin/oc-chef-pedant (./bin/oc-chef-pedant)
SocketError: Failed to open TCP connection to blah:443 (getaddrinfo: Temporary failure in name resolution)
```
