### ISSUE TITLE
chef/openresty-noroot needs to be rebuilt

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#1697]
chef/openresty-noroot has not been rebuilt recently and is currently depending on an older version of openssl.  This makes it difficult to depend on alongside other Habitat packages that also depend on openssl.

**Comment by PrajaktaPurohit** [comment]
The latest release in habitat is on July 11th 2019. This is currently marked as unstable. The stable version is from April 2019.
There might be 2 conversations to have here:
1. Make sure automate uses manifest OR
2. Promote everything in the automate manifest file to stable

**Comment by tas50** [comment]
Closing this out as we've updated the hab plan for openresty
