### ISSUE TITLE
When you create a user via chef-server-ctl add-user with --filename pointed at invalid path, the user is created, but the key is not put on the filesystem.

### ISSUE THREAD

**Issue by tylercloke** [chef/chef-server#17]
```
root@vagrant:~# chef-server-ctl user-create test test test test@test.com testtest --filename /<invalid_folder>/file.key
ERROR: Errno::ENOENT: No such file or directory - /path/to/file.key
root@vagrant:~# chef-server-ctl user-create test test test test@test.com testtest --filename /<valid_folder>/file.key
ERROR: Conflict
Response: User 'wtf' already exists
```

So it creates the user just fine, and you get a conflict when you try to re-create it (valid), but you won't have the key on your filesystem. There are other ways to get the key, but that's annoying.

**Comment by marcparadise** [comment]
This is fixed in current knife-opc, so bumping the rev in omnibus should resolve it

**Comment by github0100** [comment]
you may created the org or user my mistake, but every problem  has some solution.its simple

sudo -s
chef-server-ctl org-delete learndevops        # learndevops is my org-name you may have different 

this will delete the old one so you can create new user or org name.
