### ISSUE TITLE
Allow _status endpoint to report healthy if data_collector is down

### ISSUE THREAD

**Issue by trickyearlobe** [chef/chef-server#1703]
### Describe the Enhancement:

Add a configuration option to allow the `data_collector` health check to be excluded from the overall health reported by the `_status` endpoint.

### Describe the Need:
When using the `_status` endpoint to control which frontends are included in the load balancer pool, perfectly good frontends are removed from the pool if the `data_collector` endpoint (Automate 1 or 2) is down.

This causes an unnecessary Chef Server outage as all the frontends are perfectly able to service requests.

Reported by 2 customers.

### Current Alternatives
* Disable health checks on the load balancer (poor experience under failure conditions)
* Switch to checking if the http/https ports are responding (unreliable check)
* Site-local modifications to chef server cookbooks that generate config files which exclude the data_collector check (breaks on upgrades)

### Can We Help You Implement This?:

I already have working code tested by a customer that I can drop into a PR.

**Comment by markan** [comment]
This has been implemented and merged, but we are leaving this open until we do a release and can merge the docs https://github.com/chef/chef-web-docs/pull/2019
