### ISSUE TITLE
Chef Infra Server search(solr) uses supported/secure software(es), resolving open CVEs

### ISSUE THREAD

**Issue by btm** [chef/chef-server#1732]
Replaces solr with Elasticsearch to remove unsupported solr package that contains security vulnerabilities.

Operationally brings Chef Infra Server users toward migrating to the Automate Infra API (automate uses elasticsearch)

Aha! Link: https://chef.aha.io/epics/CHEF-E-2

**Comment by stevendanna** [comment]
Done!
