### ISSUE TITLE
Chef Infra Server test matrix

### ISSUE THREAD

**Issue by btm** [chef/chef-server#1734]
Confidence that Chef Infra Server and Automate Infra API distributions do not contain regressions
Automated testing for the different topologies of Chef Infra Server.
The supported topologies for chef-server are:

- Standalone
- Tiered
- External Postgres
- External elasticsearch

The supported configurations are:

- FIPS
- With SSL for external postgres or elasticsearch
- With Addons (manage + push-jobs)
- Ipv6
- Ldap

Please find more details in: https://docs.google.com/document/d/1l4fOu_zohLvWjKTFYs3-lgyqWzDwJ7WK35Eehj-DFs4/edit

A cross matrix of with scenarios from above topologies and configurations: (Sheet: test release plan) https://docs.google.com/spreadsheets/d/1_gwxdrMnUiV8t2noi8zs1HyGivtIGMEx9KbYriIw7BY/edit#gid=1411321437

Acceptance Criteria:
1. Developer / Release engineer is able to run a test suite testing different topologies in various configurations easily before release.
2. The tests give a clear indication incase of a failure with a certain topology or configuration.
3. The infrastructure is modular, it is easy to add/ change scenarios for testing. (A scenario is a combination of topologies and configurations)
4. If possible there is an ease of updating the package to stable after the test suite is run.
5. The pipeline can be run once a week perhaps or when desired?

Aha! Link: https://chef.aha.io/epics/CHEF-E-64

**Comment by christopher-snapp** [comment]
The integration tests have been in place for some time with the exception of habitat artifacts.

Testing of habitat artifacts will be tracked in #1744
