### ISSUE TITLE
Extend Chef Infra Server's build pipeline to include integration tests of multiple installation topologies.

### ISSUE THREAD

**Issue by christopher-snapp** [chef/chef-server#1742]
## Current State

The Chef Infra Server product currently relies on manual testing of different installation topologies which may result in unstable release artifacts reaching customers. 

## Desired State

Buildkite steps should be added to the Chef Infra Server release pipeline following the standalone testers of the build artifact.  These Buildkite steps would leverage multiple Terraform scenarios each responsible for setting up a different topology for integration testing.

**Comment by christopher-snapp** [comment]
We will need to add a S3 backend store for tracking the state of different pipeline executions to ensure we clean up all resources in AWS after each test run.

**Comment by christopher-snapp** [comment]
Expeditor documentation for configuring additional pipelines can be found here:

https://expeditor.chef.io/docs/reference/buildkite-dsl/

**Comment by btm** [comment]
Working with Releng to do the buildkite work is covered by this issue: https://github.com/chef/release-engineering/issues/877
