### ISSUE TITLE
Update to Erlang 19

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1745]
## Current Status
We currently use Erlang 18.3.3.9. 

## Upgrade Plan
1. Update the deps
Approach 1:
Update the rebar.config.lock to the yearold versions of deps. There is some work done in this regard: https://github.com/chef/chef-server/pull/1577

Approach 2:
Upgrade all the deps to their latest versions in the rebar.config.lock

2. Upgrade Erlang to 19.
3. Make necessary code changes to maintain compatibility

Update deps to latest versions (if not already updated)

Also, erlware_commons will need to be patched.  see: https://app.zenhub.com/workspaces/chef-infra-5d1b845f1659a92b9fa6194c/issues/chef/chef-server/1766

There might be some dep failures related to 
[ ] epgsql
[ ] ibrowse 
[ ] mover(possibly) (has older versions of erchef?)
Some code failures related to
[ ] type signatures
[ ] dialyzer

4. Check if upstream patches are merged for forked deps,
    - merge and update dep OR
    - rebase the fork and update dep
[ ] erlware_commons

##Acceptance Criteria:
[ ] Adhoc build is successful and tests pass with Erlang 19.

**Comment by lbakerchef** [comment]
### Work Progress
Preliminary Investigation
- [ ] Build: FAILED - (dependency issues - observer_cli, etc)
Deleted `rebar.lock` files for: oc_erchef, chef-mover, oc_bifrost, bookshelf, data_collector
- [ ] Build: PASSED
- [ ] Install: FAILED (services down, won't start)
Rebased with latest master, rebuild
- [ ] Install: PASSED
- [ ] Upgrade to Erlang 19
Edit omnibus_overrides.rb
- [ ] Build: FAILED (lager parse transform error)
Updated rebar.config files to get latest master of lager
- [ ] Build: FAILED (`crypto:rand_bytes` deprecation?)
Patched all occurrences of `crypto:rand_bytes` => `crypto:strong_rand_bytes` 
`find . -type f -name *.erl -exec sed -i '' s/crypto:rand_bytes/crypto:strong_rand_bytes/g {} +`
- [ ] Build: FAILED (`chef-sugar` gem)
Deleted `rebar.lock`, `Berksfile.lock`
- [ ] Build: FAILED
===> Compiling _build/default/lib/erlware_commons/src/ec_file.erl failed
_build/default/lib/erlware_commons/src/ec_file.erl:177: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
_build/default/lib/erlware_commons/src/ec_file.erl:178: random:uniform/0: the 'random' module is deprecated; use the 'rand' module instead
