### ISSUE TITLE
8. Update to Erlang 22

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1752]
Once the Chef Infra Server is upgraded to Erlang 20, and the LDAP bug in #1642 is tested, Proceed with updating the dependencies to the latest versions and update erlang to version 22.

[ ] Update the dependencies with rebar3 to the latest.

[ ] Change software definition at https://github.com/chef/omnibus-software/blob/master/config/software/erlang.rb with version 22 of erlang.

[ ] Update https://github.com/chef/chef-server/blob/master/omnibus_overrides.rb#L5 to the above updated version.

[ ] Make the necessary code changes to oc_erchef, oc_bifrost, bookshelf.

[ ] Update the buildkite pipeline to test with Erlang 22.

Acceptance Criteria:
[ ] Verify pipeline passes with erlang 22.
[ ] Adhoc version of Chef-server builds with Erlang 22.

**Comment by lbakerchef** [comment]
https://github.com/chef/chef-server/pull/1856

**Comment by stevendanna** [comment]
Done!
