### ISSUE TITLE
Update config_rb_server.rst

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#1757]
@lbakerchef commented on [Wed Aug 21 2019](https://github.com/chef/chef-web-docs/pull/2085)

``postgresql['sslmode']``
	SSL encryption mode between Chef Server and PostgreSQL.  Valid settings are 'disable' (off) and 'require' (on).  Default value: 'disable'.  

---

@IanMadd commented on [Wed Aug 21 2019](https://github.com/chef/chef-web-docs/pull/2085#issuecomment-523628777)

Hi @lbakerchef, can you add your [DCO sign-off ](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) to this PR. Thanks!

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-web-docs/pull/2085
