### ISSUE TITLE
Update config_rb_server_optional_settings.rst

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#1758]
@lbakerchef commented on [Mon Sep 16 2019](https://github.com/chef/chef-web-docs/pull/2121)

### Description

Documentation changes for:
https://github.com/chef/chef-server/pull/1728
https://github.com/chef/chef-server/pull/1711

```
postgresql['sslmode']
bookshelf['sql_connection_user']
oc_bifrost['sql_connection_user']
oc_id['sql_connection_user']
opscode_erchef['sql_connection_user']
postgresql['db_connection_superuser']
```

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-web-docs/pull/2121
