### ISSUE TITLE
Update server_security.rst

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#1760]
@lbakerchef commented on [Tue Aug 20 2019](https://github.com/chef/chef-web-docs/pull/2083)

### NOTES

My default presumption in creating these docs was that an external PostgreSQL instance is mainly the responsibility of the user and is not mainly the responsibility of Chef.  Therefore I didn't want to get into heavy or detailed instructions on how to setup an external PostgreSQL instance.  I have a note that these docs assume familiarity with PostgreSQL administration, configuration, and troubleshooting, and to consult the appropriate PostgreSQL documentation as necessary.  My presumption was that we didn't want to, in essence, recreate PostgreSQL docs within our docs.  Having said that, I thought we should at the very least have brief numbered steps ('boxes to check off') in setting up external PostgreSQL so that the user would know what they needed to do on the PostgreSQL side to have it communicate with Chef Server.  Basically, the user needs to know what Chef Server needs and expects of the PostgreSQL setup.

Beyond that, naturally I thought that instructions on configuring the Chef Server side of things *IS* our responsibility.

I'm new here, so if anything I said is incorrect, by all means let me know what the proper orientation or assumptions should be in creating these docs :)

SSL Encryption Between Chef Infra Server and External PostgreSQL
================================================================

**New in Chef Server X.Y:**  Chef Server X.Y introduces the capability to encrypt traffic between Chef Infra Server and an external PostgreSQL configuration over SSL.  These instructions are not all-encompassing and assume familiarity with PostgreSQL administration, configuration, and troubleshooting.  Consult the appropriate PostgreSQL documentation as necessary, e.g. https://www.postgresql.org/docs/9.6/ssl-tcp.html.

To enable this encryption (typical scenario):

1. Ensure that OpenSSL is installed on the PostgreSQL machine.

2. Ensure that PostgreSQL has been built with SSL support compiled-in.

3. Place SSL certificates in the proper directories on the PostgreSQL machine, and ensure correct filenames, ownerships and permissions.

4. Enable SSL support on PostgreSQL, and specify paths to the SSL certificates, if necessary.

   Edit the postgresql.conf file on the PostgreSQL machine and ensure the relevant entries are present and not commented out (substitute the appropriate paths):

```
   # mandatory
   ssl=on

   # optional - uncomment accordingly
   #ssl_cert_file='<PATH/TO/CERT/FILE>'
   #ssl_key_file='<PATH/TO/KEY/FILE>'
```

5. Consider forcing the use of SSL connections from the PostgreSQL side, otherwise non-SSL connections could be used.  This can be achieved by editing pg_hba.conf on the PostgreSQL machine, and changing the relevant Chef Server connections to hostssl.

   This is a sample pg_hba.conf file with hostssl connections for Chef Server (the contents of your pg_hba.conf will be different):

```
   # "local" is for Unix domain socket connections only
   local      all             all                                     peer

   # IPv4 local connections:
   hostssl    all             all             127.0.0.1/32            md5

   # IPv6 local connections:
   hostssl    all             all             ::1/128                 md5

   # nonlocal connections
   hostssl    all             all            192.168.33.100/32        md5
```

6. Restart PostgreSQL.  This can typically be done with the following command on the PostgreSQL machine (substitute the appropriate path):

```
   $ /<PATH/TO/POSTGRESQL>/postgresql restart
```

7. Edit /etc/opscode/chef-server.rb on the Chef Server machine and add the following line:

```
   postgresql['sslmode']='require'
```

8. Run the following command on the Chef Server machine:

```
   $ chef-server-ctl reconfigure
```

9. Verify that SSL is enabled and that SSL connections are up between Chef Server and your running PostgreSQL instance.  One way to do this is by using psql on the PostgreSQL machine:

```
   $ su - postgres
   $ psql

   postgres=# show ssl;
    ssl
   -----
    on
   (1 row)

   postgres=# select * from pg_stat_ssl;

     pid  | ssl | version |           cipher            | bits | compression | clientdn
   -------+-----+---------+-----------------------------+------+-------------+----------
    16083 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16084 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16085 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16086 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16087 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16088 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16089 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16090 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16091 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16092 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16093 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16094 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16095 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16096 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16097 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16098 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16099 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16100 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16101 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16102 | t   | TLSv1.2 | ECDHE-RSA-AES256-GCM-SHA384 |  256 | f           |
    16119 | f   |         |                             |      |             |
   (21 rows)
```

---

@PrajaktaPurohit commented on [Tue Aug 20 2019](https://github.com/chef/chef-web-docs/pull/2083#issuecomment-523214001)

probably also need to expose the option in: https://docs.chef.io/server_components.html#postgresql-settings

---

@IanMadd commented on [Wed Aug 21 2019](https://github.com/chef/chef-web-docs/pull/2083#issuecomment-523629003)

Hi @lbakerchef, can you add a [DCO sign-off ](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco) to this PR. Thanks!

---

@lbakerchef commented on [Mon Aug 26 2019](https://github.com/chef/chef-web-docs/pull/2083#issuecomment-524932019)

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-web-docs/pull/2083
