### ISSUE TITLE
Use Postgres for search in Chef-Infra-Server instead of Elasticsearch.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1777]
Background:
 - With getting elasticsearch out of the stack, advantages of code reusability.
 - Easier to keep the data in sync
 - Postgres full text search might do well in the more direct search situations.

Path Proposed:
 - The common search cases can be transformed into specific sql queries.
 - Special handling for role, recipe, tag and environment can help convert a lot of searches into direct select statements.
 - Adding a new 'restricted search' api can implement the straightforward sql changes (mentioned above)
 - Gradually phase out the old es.

Concerns:
 - Performance for common search cases
 - Worst case performance.
 - Complete replication of search capabilities could be difficult to do.

Acceptance Criteria:
 - The chef-infra-server stack does not depend on Elasticsearch.

**Comment by marcparadise** [comment]
We did spike on this briefly earlier this year; currently this will require more digging, as so far we have not been able to find a way to search for deeply nested attributes using jsonb.
