### ISSUE TITLE
allow full package path when installing add-ons 

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#178]
From @alexpop in chef/opscode-omnibus#746:

> I was following the Chef server [upgrade documentation](https://docs.chef.io/upgrade_server.html). Once upgraded, I moved on and followed the steps to install the latest add-ons(manage, reporting, etc):

> ```
Then run the install command using the --path option to specify the location for the package:
$ chef-server-ctl install NAME_OF_PACKAGE --path /path/to/package
```

> After downloading the required rpm's and reading the above note, I was confident this would:

> ```
chef-server-ctl install opscode-manage --path /media/chef/opscode-manage-1.11.0-1.el5.x86_64.rpm
```

> The command failed with:
```
[2015-04-08T13:01:31+01:00] FATAL: Chef::Exceptions::Package: yum_package[opscode-manage] (private-chef::add_ons_local line 35) had an error: Chef::Exceptions::Package: Package opscode-manage not found:
```

> It looks like the current implementation in the 'private-chef::add_ons_local' recipe is to expect the parent folder for the --path option.

> I opened this issue to allow both the parent folder and the full package path to be specified for the --path option. This would be a more standard install method. I asked a few folks in order to validate this and they all felt for the full package path as I did.

**Comment by stevendanna** [comment]
@laexpop is already working on this in https://github.com/chef/chef-server/pull/173

**Comment by alexpop** [comment]
I better fix can be implemented here once issue https://github.com/chef/omnibus-ctl/issues/29 is fixed.
