### ISSUE TITLE
4. Phase3: Update the tags in the erlang deps to the latest.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1781]
The tags in the erlang deps are pointing to the older versions that were released previously.

1) Update the tags to the latest for the deps following erlang apps:
 - oc_erchef
 - oc_bifrost
 - bookshelf
 - chef-mover
 Document the deps that cannot be updated to the latest.
2) Can we switch to the upstream version of anything that is a chef fork without losing out current changes
  - epgsql
  - erlware_commons
  - ibrowse
  - jiffy
  - meck
  - hoax - the latest fails with HOAX_FIXTURE deprecation error.
3) Update the apps to be used with later versions of chef-server
 <s> - rabbitmq (considering we want to update to erlang 20: https://www.rabbitmq.com/which-erlang.html) - update to 3.7.6 </s>
  - lager
 
Acceptance criteria:
- Tags are updated consistently across all the rebars.config.
- Updated version of rabbitmq is still compatible with later versions of erlang.
- Verify pipeline is green
- Adhoc build is green.

**Comment by marcparadise** [comment]
Tracking internally as INFS-149
