### ISSUE TITLE
Add support for running all integration test scenarios via a single command

### ISSUE THREAD

**Issue by christopher-snapp** [chef/chef-server#1786]
The `Makefile` should include a convenient way to run all scenarios via something similar to a `make all`

One question that will need to be answered is how many / which permutations of the scenarios should be included.

**Comment by PrajaktaPurohit** [comment]
Scenarios are broken down into workspaces (topology + configuration) We have a make apply-all to run multiple workspaces. #1791

**Comment by PrajaktaPurohit** [comment]
This is meant to identify all of the scenarios that should go in the make-all

**Comment by christopher-snapp** [comment]
After discussion with @PrajaktaPurohit it was decided that this feature is not required with the full test matrix being provided within BuildKite.
