### ISSUE TITLE
Chef-server to be tested with external postgres in different cloud providers.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1798]
The external postgres setup is supported on different cloud providers(Azure). This usecase should help testing with Azure.

This is the Azure service: https://azure.microsoft.com/en-us/services/postgresql/

**Comment by christopher-snapp** [comment]
I'm wondering if this issue can be broken up into:

1. Add external postgres scenario.
2. Add support for running scenarios in Azure.

**Comment by christopher-snapp** [comment]
Ok, so I better understand now that this is related to #1559 and how the Azure Postgres DBaaS requires the username to be `<username@hostname>`.

I will look into how I might use terraform to spin up a database in Azure's DBaaS, but that is uncharted territory for me that may take some time.

I'm curious whether it is a smaller lift to get an AWS instance setup that we install postgres on with a username that follows their `<username@hostname>` convention.  If that is easier, it may be worth doing so testing can proceed while I figure out the Azure stuff.
