### ISSUE TITLE
Upgrade jetty in solr

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#180]
From @jessehu in chef/opscode-omnibus#725:

> As https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html said "This year will mark the end of our open source support for Jetty 7 and Jetty 8." So Jetty 6/7/8 is end of life by 2014.
> 
> Can we update solr to newer version which uses higher version of jetty ? Chef Server 11 nows uses jetty 6.1.3.
> 
> ll /opt/chef-server/embedded/service/chef-solr/jetty/lib/total 740
> -rw-r--r-- 1 root root 472383 Oct 17 01:50 jetty-6.1.3.jar
> -rw-r--r-- 1 root root 128058 Oct 17 01:50 jetty-util-6.1.3.jar
> drwxr-xr-x 2 root root 4096 Mar 12 03:09 jsp-2.1
> -rw-r--r-- 1 root root 131998 Oct 17 01:50 servlet-api-2.5-6.1.3.jar
> 
> related code: https://github.com/chef/opscode-omnibus/blob/master/config/software/opscode-solr4.rb
> 
> Our product uses Chef 11 and jetty 9.2.9 is required by the security strategry.

**Comment by stevendanna** [comment]
As mentioned in the previous discussion, it looks like it would be rather easy to move us to Jetty 8 as there are prebuilt Solr packages that include Jetty 8.  

Assigning to myself.

**Comment by stevendanna** [comment]
@jessehu Just want to let you know that we've opened a PR https://github.com/chef/chef-server/pull/221 for upgrading solr and jetty.  That still doesn't put us on jetty 9, but I wanted to give you a status update.

**Comment by jessehu** [comment]
Thanks @stevendanna. I will try Chef Server 12 to check it.

**Comment by PrajaktaPurohit** [comment]
I am sorry we could not get to this sooner. Closing since we are replacing Solr with Elasticsearch from the next stable release onwards (14.x)
