### ISSUE TITLE
Chef-server upgrade testing

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1800]
This test case will enable us to easily test version compatibility between predetermined supported versions.
1. 12.x -> 13.1(assuming 13.1 is the new release number)
2. 13.0 -> 13.1
3. 11 -> 12.3 -> 12.17 -> 13.1
4. 11 -> 13.1 (known failure)
5. 12.3 -> 13.1 (known failure)

Any others TBD?

**Comment by OBrienCommaJosh** [comment]
Closing this because 13.1.13 is released. If we need to address this for 13.2, let's create a new issue.
