### ISSUE TITLE
Enable external azure postgresql to work with chef-server.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#1805]
https://github.com/chef/chef-server/pull/1728

Acceptance criteria:
[ ] Tested changes with external azure
[ ] Tested changes with chef-backend
[ ] Tested changes with tiered setup
[ ] chef-server-ctl psql works
[ ] chef-server-ctl psql --write works
[ ] chef-server-ctl psql --as-admin works

Azure Postgresql Service: https://azure.microsoft.com/en-us/services/postgresql/

**Comment by danielcbright** [comment]
thanks @PrajaktaPurohit for getting the PR merged for this!
