### ISSUE TITLE
Update postgresql from 9.2.9 to latest

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#181]
From @jessehu in chef/opscode-omnibus#721:

> Hi Chef team,
> 
> Is it possible to update postgresql in Chef Server 11 from 9.2.9 to latest 9.3.x or 9.4.x ? Our product uses Chef 11 and doesn't want to upgrade from Chef 11 to 12 yet, and the security strategry is using postgresql 9.3.5 or 9.4.x (rather than 9.2.9 which is packaged in latest chef server)
> 
> Thanks.

In the original ticket, we discussed the fact that moving to 9.3 or 9.4 actually represents a major version bump.  However, there are ongoing, stable releases for the 9.2 series.  The near term action for this ticket is to move to the latest in the 9.2 series.

**Comment by stevendanna** [comment]
Current version is: 9.2.19

**Comment by btm** [comment]
We moved from 9.2 to 9.6 in #1310
