### ISSUE TITLE
Release Chef Infra Server 13.1

### ISSUE THREAD

**Issue by OBrienCommaJosh** [chef/chef-server#1819]
Infra Server release required before 2019.11.30 in order to meet commitments.

**Comment by OBrienCommaJosh** [comment]
@PrajaktaPurohit can you help me get all of the dependencies for a 13.1 release linked to this?

**Comment by btm** [comment]
Chef Infra Server 13.1.13 was released on 11/25/2019:

https://discourse.chef.io/t/chef-infra-server-13-1-13-released/16282
