### ISSUE TITLE
Support upgrades to 12 from older Chef 11 versions

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#182]
Currently, our documentation states that we only support upgrades from 11.1.0 or greater.  Some users overlook this or otherwise don't want to go through a multi-step upgrade.  However, upgrades from older versions can be wrought with difficulties.  For example, the user's in this tickets battled a number of bugs:

https://github.com/chef/opscode-omnibus/issues/463

**Comment by georgecook-cbt** [comment]
The main page that documents upgrading has no reference of a chef-server ~> 11.1 requirement for success. It would be helpful to throw that info on that page to start.

https://docs.chef.io/upgrade_server.html
