### ISSUE TITLE
Investigate upgrading rabbitmq to more recent versions

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#1825]
We recently upgraded Chef Server dependencies in order to upgrade to Erlang 19 and 20+.  Although Rabbitmq was upgraded some during this process, we had issues (testing and/or compilation) upgrading Rabbitmq to the latest version(s) .  @PrajaktaPurohit suggested that an issue be filed to track the possibility of doing more upgrade work on Rabbitmq in the future.

**Comment by PrajaktaPurohit** [comment]
Rabbitmq is no longer supported in the Chef Infra Server stack. Closing this for that purpose.
