### ISSUE TITLE
Create a terraform scenario for testing external postgres

### ISSUE THREAD

**Issue by christopher-snapp** [chef/chef-server#1839]
As a part of the release process we are able to test an external PostgreSQL database with a single Chef Infra Server

**Comment by christopher-snapp** [comment]
This scenario exists already thanks to @PrajaktaPurohit.  There is a known issue (#1866) where the chef-server reconfigure fails if the connection to the postgresql server is over ipv6.

**Comment by PrajaktaPurohit** [comment]
Closing since we have a scenario!
