### ISSUE TITLE
FQDN longer than 64 characters results in invalid self-signed cert

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#184]
From @sean-horn in chef/opscode-omnibus#715:

> From http://tickets.chef.co/browse/OC-7334
> 
> Openssl will fail to create a certificate if the CN is longer than 64 characters. By default the CN of the certificate created by the private-chef-ctl reconfigure cookbooks is set to the api_fqdn.
> 
> The reconfigure will not fail but will instead create an empty certificate file. Nginx fails to start as it is unable to parse the empty certificate file correctly.

**Comment by PrajaktaPurohit** [comment]
Closing due to age. Please reopen if the problem still causes pain.
