### ISSUE TITLE
NGINX cert file not updated/does not match after Server 11->12 upgrad

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#186]
From @tbunnyman in chef/opscode-omnibus#465: 

> Upgrading Chef Server 11 to Chef Server 12RC2 changed the NGINX ssl certificate.
> 
> I had to delete the old one and pull a new one from the server. However pulling the file listed in knife's documents /var/opt/chef-server/nginx/ca/HOSTNAME.crt produced the old certificate that was no longer valid. I had to pull the certificate over https and using my web browser.

From @doubt72:

> The issue you're seeing is most likely because the default cert location in the old Open Source Chef Server is different than the location in Chef 12 (which uses the location that Enterprise Chef Server used). So when Chef 12 didn't see one, it just generated a new one.
> 
> By default, the old location (which you do seem to have been using) is:
>    /var/opt/chef-server/nginx/ca
> 
> By default, the new location is:
>     /var/opt/opscode/nginx/ca
> 
> The easiest solution here is simply to copy the old certs (key, crt) into the new location, then restart nginx ("chef-server-ctl restart nginx") to re-read them.

**Comment by PrajaktaPurohit** [comment]
Closing it due to the age. Please feel free to reopen if the problem causes pain.
