### ISSUE TITLE
Cloan Hoax Repo

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#1867]
Chef-server is currently pointed to: https://github.com/lbakerchef/hoax, branch `lbaker/fixes-for-erlang20.`  This is because Hoax needed fixes when I was upgrading Erlang to version 19 and 20, and I did not have 'make chef repo' powers.

We probably want chef to point to its own clone of that repo.  Not the original upstream version, but the lbakerchef version above.

**Comment by PrajaktaPurohit** [comment]
@lbakerchef Could you check if have access to https://github.com/chef/hoax it looks that access is granted to that repo. Closing this bug for now. Please reopen if needed.

**Comment by lbakerchef** [comment]
Access confirmed.  Copied lbaker/fixes-for-erlang20 branch over to this repo.
