### ISSUE TITLE
Control RabbitMQ Memory Allocation

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#187]
From @sean-horn in chef/opscode-omnibus#701:

> As a customer, I would like opscode-omnibus to offer control of the rabbitmq memory allocation in the config area with contents in /var/opt/opscode/drbd/data/rabbit/db/rabbit@localhost/etc/rabbitmq.config, like
> 
> `[ {rabbit, [{vm_memory_high_watermark, <%= node['private_chef']['rabbitmq']['mem'] %>}] } ].`

**Comment by PrajaktaPurohit** [comment]
We will be removing Rabbitmq after moving from Solr to Elasticsearch. That is scheduled to happen soon. Closing this as a wont fix for that reason.
