### ISSUE TITLE
chef external service - opscode solr4 for elastic search

### ISSUE THREAD

**Issue by AnamikaN** [chef/chef-server#1878]
I am trying to configure push jobs on chef server. I install push jobs on chef server using below command.
chef-server-ctl install opscode-push-jobs-server
when i ran 'chef-server-ctl reconfigure' command, i am getting below error-

Recipe: private-chef::opscode-solr4-external
  * elasticsearch_index[chef] action create

    ================================================================================
    Error executing action `create` on resource 'elasticsearch_index[chef]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Connection refused - Connection refused connecting to http://localhost:9200/chef, giving up

    Cookbook Trace:
    ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/elasticsearch_index_provider.rb:25:in `index_exists?'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/elasticsearch_index_provider.rb:9:in `block in <class:ElasticSearchIndex>'

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/opscode-solr4-external.rb

     23:   elasticsearch_index "chef" do
     24:     server_url node['private_chef']['opscode-solr4']['external_url']
     25:     index_definition({"settings" => {
     26:                         "analysis" => {
     27:                           "analyzer" => {
     28:                             "default" => {
     29:                               "type" => "whitespace"
     30:                             }
     31:                           }
     32:                         },
     33:                         "number_of_shards" => node['private_chef']['opscode-solr4']['elasticsearch_shard_count'],
     34:                         "number_of_replicas" => node['private_chef']['opscode-solr4']['elasticsearch_replica_count']
     35:                       },
     36:                       "mappings" => {
     37:                         "object" => {
     38:                           "_source" => { "enabled" => false },
     39:                           "_all" => { "enabled" => false },
     40:                           "properties" => {
     41:                             "X_CHEF_database_CHEF_X" => { "type" => "string",
     42:                                                           "index" => "not_analyzed",
     43:                                                           "norms" => {
     44:                                                             "enabled" => false
     45:                                                           }
     46:                                                         },
     47:                             "X_CHEF_type_CHEF_X" => { "type" => "string",
     48:                                                       "index" => "not_analyzed",
     49:                                                       "norms" => {
     50:                                                         "enabled" => false
     51:                                                       }
     52:                                                     },
     53:                             "X_CHEF_id_CHEF_X" => { "type" => "string",
     54:                                                     "index" => "not_analyzed",
     55:                                                     "norms" => {
     56:                                                       "enabled" => false
     57:                                                     }
     58:                                                   },
     59:                             "data_bag" => { "type" => "string",
     60:                                             "index" => "not_analyzed",
     61:                                             "norms" => {
     62:                                               "enabled" => false
     63:                                             }
     64:                                           },
     65:                             "content" => { "type" => "string", "index" => "analyzed"}
     66:                           }
     67:                         }
     68:                       }
     69:                      })
     70:   end
     71: end

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/opscode-solr4-external.rb:23:in `from_file'

    elasticsearch_index("chef") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :elasticsearch_index
      cookbook_name "private-chef"
      recipe_name "opscode-solr4-external"
      server_url "http://localhost:9200"
      index_definition {"settings"=>{"analysis"=>{"analyzer"=>{"default"=>{"type"=>"whitespace"}}}, "number_of_shards"=>3, "number_of_replicas"=>2}, "mappings"=>{"object"=>{"_source"=>{"enabled"=>false}, "_all"=>{"enabled"=>false}, "properties"=>{"X_CHEF_database_CHEF_X"=>{"type"=>"string", "index"=>"not_analyzed", "norms"=>{"enabled"=>false}}, "X_CHEF_type_CHEF_X"=>{"type"=>"string", "index"=>"not_analyzed", "norms"=>{"enabled"=>false}}, "X_CHEF_id_CHEF_X"=>{"type"=>"string", "index"=>"not_analyzed", "norms"=>{"enabled"=>false}}, "data_bag"=>{"type"=>"string", "index"=>"not_analyzed", "norms"=>{"enabled"=>false}}, "content"=>{"type"=>"string", "index"=>"analyzed"}}}}}
      index_name "chef"
    end

    System Info:
    ------------
    chef_version=12.21.31
    platform=amazon
    platform_version=2017.09
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    program_name=/opt/opscode/embedded/bin/chef-client
    executable=/opt/opscode/embedded/bin/chef-client

Recipe: private-chef::oc_id
  * execute[restart_oc_id_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/oc_id/log

Running handlers:
Running handlers complete
Chef Client failed. 30 resources updated in 40 seconds
[2020-01-16T17:55:08+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2020-01-16T17:55:08+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-01-16T17:55:08+00:00] FATAL: Errno::ECONNREFUSED: elasticsearch_index[chef] (private-chef::opscode-solr4-external line 23) had an error: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://localhost:9200/chef, giving up

any ideas on how to fix this?

**Comment by PrajaktaPurohit** [comment]
Hey @AnamikaN. Sorry you are running into this. We have a couple of questions for you:

**Comment by AnamikaN** [comment]
@PrajaktaPurohit thank you for your quick response. This issue is fixed. You were right, it was not related to push-jobs. The aws-signing-proxy was not running. I am not sure, why it was not running but i ran below command and it fixed the issue.

initctl start aws-signing-proxy

**Comment by AnamikaN** [comment]
@PrajaktaPurohit I had another question related to push-jobs. In our aws infrastructure, we have chef HA server with one bootstrap frontend and frontend server. It has two load balancers in front of these two instances. one is application and one is classic load balancer. Push-jobs TCP requests goes to classic load balancer. When i am trying to associated bootstrap frontend instance to PJ classic load balancer, it says outOfService.

Our infrasturcutre is based on https://github.com/chef-customers/aws_native_chef_server. I am not sure what is wrong, why push-jobs is not working.

**Comment by AnamikaN** [comment]
This issue is closed.
