### ISSUE TITLE
Does chef12 support PostgresSQL 9.5 and later? Also where i can find which all PostgresSQL versions are compatible with chef12?

### ISSUE THREAD

**Issue by rahul3887** [chef/chef-server#1888]
We use GitHub issues to track bugs and feature requests. If you need help please post to our Mailing List or join the Chef Community Slack.

 * Chef Community Slack at http://community-slack.chef.io/.
 * Chef Mailing List https://discourse.chef.io/

 Support issues opened here will be closed and redirected to Slack or Discourse.

**Comment by PrajaktaPurohit** [comment]
@rahul3887 The earlier versions of Chef Infra Server shipped with postgres 9.2. 
Chef Infra Server 12.17.33 onwards shipped with postgresq 9.6. (That should work for both internal and external configurations of postgres setup)

Chef Infra Server does not use many version specific features of postgres so we are relatively independent of postgres version. That being said, we have done limited testing of Chef Infra Server(with Chef Backend) with postgres 10 and 11 and Chef Infra Server should work as far as we know.

That being said, to answer your question, any version of Chef Infra Server supporting postgres 9.6 should be able to work with postgres 9.5 or later.

**Comment by PrajaktaPurohit** [comment]
NOTE: It would be good to create a versions supported matrix for chef-server and postgresql (or elasticsearch) especially for the BYOD and cloud.

**Comment by tas50** [comment]
Closing this out since going forward the only release of PG that can be used will bein Server 14.7
