### ISSUE TITLE
chef-server-ctl user-edit throwing hydrate errors

### ISSUE THREAD

**Issue by mikelindsey-okta** [chef/chef-server#1890]
## Description
As titled.  chef-14.11.21.  

## Chef Version
14.11.21

## Platform Version
AWS linux

## Replication Case
chef-server-ctl user-edit username

## Client Output
```
ERROR: ArgumentError: Please pass in the object class to hydrate or use #edit_hash
```

## Stacktrace
https://github.com/chef/chef/blob/master/lib/chef/knife/core/ui.rb#L219 change to the following resolves the issue.
```
          if object_class.nil?
            begin
              Chef::JSONCompat.parse(output)
            rescue
              raise ArgumentError, "Please pass in the object class to hydrate or use #edit_hash"
            end
```

**Comment by PrajaktaPurohit** [comment]
@mikelindsey-okta Thank you for reporting the issue. We would love to help figuring our/fixing the issue you are seeing. On that end we have a couple of questions for you:
1. Could you list the Chef-Infra-Server version you are seeing this with.
2. Does the user you are trying to edit already exist on the Chef Infra Server?

**Comment by joshbrand** [comment]
I'm seeing the same error on chef-infra-server `13.1.36`

**Comment by jtimberman** [comment]
The underlying problem seems to stem from the `knife-opc` gem. First, we were trying to modify a user with `chef-server-ctl user-edit`

```
$ sudo -E chef-server-ctl user-edit SOME_USER -VV
INFO: Using configuration from /etc/opscode/pivotal.rb
Traceback (most recent call last):
	10: from /opt/opscode/embedded/bin/knife:23:in `<main>'
	 9: from /opt/opscode/embedded/bin/knife:23:in `load'
	 8: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/bin/knife:24:in `<top (required)>'
	 7: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application/knife.rb:163:in `run'
	 6: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife.rb:229:in `run'
	 5: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife.rb:485:in `run_with_pretty_exceptions'
	 4: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	 3: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife.rb:486:in `block in run_with_pretty_exceptions'
	 2: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/knife-opc-0.4.4/lib/chef/knife/opc_user_edit.rb:50:in `run'
	 1: from /opt/opscode/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `edit_data'
/opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife/core/ui.rb:219:in `edit_data': Please pass in the object class to hydrate or use #edit_hash (ArgumentError)
```

For those following along at home, the `chef-server-ctl` subcommand here is a wrapper to use `knife opc user edit` with the correct configuration for the local Chef Server, using the `src/chef-server-ctl/plugins/wrap-knife-opc.rb` plugin (in the `chef-server` repo). In our case, this is the `pivotal.rb` configuration, so if we use that configuration with `knife opc user edit` instead, we see the error bubble up from `knife/core/ui.rb` exactly as above:

```
$ sudo -E /opt/opscode/embedded/bin/ruby /opt/opscode/embedded/bin/knife opc user edit SOME_USER -c /etc/opscode/pivotal.rb -VV
INFO: Using configuration from /etc/opscode/pivotal.rb
Traceback (most recent call last):
	10: from /opt/opscode/embedded/bin/knife:23:in `<main>'
	 9: from /opt/opscode/embedded/bin/knife:23:in `load'
	 8: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/bin/knife:24:in `<top (required)>'
	 7: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application/knife.rb:163:in `run'
	 6: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife.rb:229:in `run'
	 5: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife.rb:485:in `run_with_pretty_exceptions'
	 4: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	 3: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife.rb:486:in `block in run_with_pretty_exceptions'
	 2: from /opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/knife-opc-0.4.4/lib/chef/knife/opc_user_edit.rb:50:in `run'
	 1: from /opt/opscode/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `edit_data'
/opt/opscode/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/knife/core/ui.rb:219:in `edit_data': Please pass in the object class to hydrate or use #edit_hash (ArgumentError)
```

For reference, the `knife-opc` gem line 50 is: https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_edit.rb#L50

To work around this issue on our Chef Server, we output the user to a JSON file, and then use `knife opc user edit` with that file as an input to edit the user.

```
$ sudo -E chef-server-ctl user-show SOME_USER -F json
{
  "username": "SOME_USER",
  "email": "SOME_USER@example.com",
  "display_name": "SOME USER",
  "first_name": "SOME",
  "last_name": "USER",
  "public_key": "-----BEGIN PUBLIC KEY-----\nSNIPPED\n-----END PUBLIC KEY-----\n\n"
}
$ vi user.json
<make some changes>
$ sudo -E /opt/opscode/embedded/bin/ruby /opt/opscode/embedded/bin/knife opc user edit SOME_USER -c /etc/opscode/pivotal.rb -i user.json
```

**Comment by lamont-granquist** [comment]
To be clear:  the API of knife deliberately broke to block a huge security hole.  It used to inflate objects based on the object type being passed in the JSON payload which would allow an attacker (although it would need to be an attacker that could impersonate the chef-server) to inflate any class of object.  To remedy that knife has required for some time now that the class must be passed into edit_hash, so this breakage is very deliberate to force consumers to fix their broken insecure code.

I didn't know chef-server-ctl called knife-opc, but it looks like that is what needs to get fixed.

**Comment by PrajaktaPurohit** [comment]
Closing in favor of: https://github.com/chef/knife-opc/issues/53
