### ISSUE TITLE
Custom postgresql port is ignored

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#190]
From @ares in chef/opscode-omnibus#555: 

>  https://github.com/opscode/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/providers/pg_database.rb#L21 does not honour custom port configured in chef-server.rb

> Similar applies to database_exist? method below

**Comment by marcparadise** [comment]
Note that the WIP for external postgres will incidentally resolve this issue.

**Comment by marcparadise** [comment]
This is not a bug.  The connections we currently make to postgres to set the database up are over unix socket and not tcp - neither port nor host name are used in those connections. 

The port is correctly configured in all dependant  applications, which connect over tcp.
