### ISSUE TITLE
Improve monitoring of external data services.

### ISSUE THREAD

**Issue by markan** [chef/chef-server#1904]
https://chef-software.ideas.aha.io/ideas/CHEF-I-25 

As we move towards more usage of external PostgreSQL and Elasticsearch, the opportunities for network latency between those services and chef-sever increase. We should make it easier to diagnose when those services are misbehaving, and harden our services to be more robust in the face of those.

This probably should involve
1) better logging and monitoring around the external accesses. This includes statsd, prometheus, and maybe logging.
Statistics include pool size, utilization. HTTP latency, request counts, request latency and error counts.  (maybe broken out by POST/GET) 

This should as much as possible cover postgres elasticsearch and maybe external S3

2) We have various internal timeouts around those services; and we know at least approximately their values. We should be explicitly flagging when the above latencies are at risk of triggering those timeouts. Maybe that's in the form of log messages, or maybe we expose that in the status endpoint or other monitoring tools.

**Comment by PrajaktaPurohit** [comment]
#2000 #1997 #1982
