### ISSUE TITLE
node['chef-server']['accept_license'] license acceptance not working with Chef Server 13 

### ISSUE THREAD

**Issue by mattray** [chef/chef-server#1910]
Setting the attribute `node['chef-server']['accept_license'] = true` as documented in the chef-ingredient cookbook doesn't work.

chef-server Cookbook 5.5.2
chef-ingredient 3.1.2
Chef Infra Server 13.1.13

My current work-around is to create the file `/etc/chef/accepted_licenses/chef_infra_server` in a wrapper cookbook before calling this.

**Comment by mattray** [comment]
Ahh, the README for chef-ingredients states
`accept_license - A boolean value that specifies if license should be accepted if it is asked for during reconfigureaction. This option is applicable to only these products: manage, analytics, reporting and compliance.`

**Comment by PrajaktaPurohit** [comment]
@mattray This looks like an issue with the chef-ingredient cookbook. We will open / try to transfer it to the chef-cookbooks repo.

**Comment by btm** [comment]
This would be fixed by https://github.com/chef-cookbooks/chef-ingredient/pull/245. Since this is from another repository, I'm closing this issue.
