### ISSUE TITLE
chef-server-ctl install locally with --path only works on fully qualified path

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#192]
In chef/opscode-omnibus#631 the esteemed @tylercloke proclaimed:

> Works:
> 
> `chef-server-ctl install opscode-manage --path /home/vagrant`
> 
> Doesn't work:
> 
> `cd /home`
> `chef-server-ctl install opscode-manage --path ./vagrant`

**Comment by tylercloke** [comment]
I've never been so esteemed before! And for such an easy issue report!

**Comment by eeyun** [comment]
I'm totally seeing this on 12.7.0-1 but it appears that even supplying an explicit path seems to fail.

We are attempting this with the push-jobs-server package.

**Comment by PrajaktaPurohit** [comment]
Closing this issue because of its age, please reopen if the problem causes pain.
