### ISSUE TITLE
[hosted] Allow Self Service Org Full Name Changes

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#193]
@sean-horn has proclaimed in chef/opscode-chef#547:

> As a customer, I would like to be able to change the Full Name of an org without involving CHEF Support. This activity is already possible in Chef 12 RC4.
> 
> A user's ability to do this action even after successful authentication might stem from them being a member of the Admins group.
> 
> An example usage might look something like this, although it would be better if we could avoid having to specify the org's shortname in the orgdatafile.json . A much more ergonomic usage would be the ability to specify all args from the commandline.
> 
> orgdatafile.json
> {
> "name":"ORGNAME",
> "full_name":"NEW_FULL_NAME"
> }
> 
> `knife raw 'ORGNAME' -i orgdatafile.json -s https://centos-6.3/organizations/`

**Comment by PrajaktaPurohit** [comment]
Closing as a won't fix. While Erchef supports this feature, a lot of tooling around it uses orgname as a unique identifier. There is not a solid use-case for the enhancement at this time. Please feel free to reopen in the future, if needed.
