### ISSUE TITLE
Chef server uses 100% of CPU Usage

### ISSUE THREAD

**Issue by chakravarthykkalyan0804** [chef/chef-server#1936]
We have chef-server 12.9.1 installed on physical machines and we are seeing a constant CPU usage of around 95%.
Even after adding CPU cores, usage stays at around 95%. CPU seems to be taken up by processes kicked off by the opscode user. Opscode is constantly spinning up new processes with new PIDs. Is there any way we can decrease CPU usage?

$ top

top - 16:26:41 up 13 days, 14:21,  2 users,  load average: 1143.86, 1007.47, 958.23                                                 
Tasks: 1596 total, 1163 running, 428 sleeping,   0 stopped,   5 zombie                                                              
%Cpu(s):  1.8 us, 98.2 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st                                                     
KiB Mem :  8155036 total,   202528 free,  5563312 used,  2389196 buff/cache                                                         
KiB Swap:  4063228 total,  1852084 free,  2211144 used.  2051988 avail Mem                                                          
                                                                                                                                    
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                        
 14886 opscode   20   0    4224    348    276 R  14.5  0.0   0:00.51 child_setup                                                    
 14682 root      20   0  171792   4264   1936 R   6.8  0.1   0:02.45 top                                                            
 14888 opscode   20   0    4224    352    276 R   4.3  0.0   0:00.14 child_setup                                                    
 13776 opscode   20   0    4224    352    276 R   3.7  0.0   0:02.37 child_setup                                                    
 13862 opscode   20   0    4224    348    276 R   3.7  0.0   0:01.83 child_setup                                                    
 13905 opscode   20   0    4224    348    276 R   3.7  0.0   0:02.14 child_setup                                                    
 14113 opscode   20   0    4224    352    276 R   3.7  0.0   0:01.36 child_setup                                                    
 13159 opscode   20   0    4224    348    276 R   3.4  0.0   0:03.06 child_setup  

Logs below:

/var/log/opscode/opscode-erchef/crash.log
chef_keygen_cache,keygen_timeout}
2020-03-05 20:20:02 =ERROR REPORT====
{chef_keygen_cache,keygen_timeout}
2020-03-05 20:20:02 =ERROR REPORT====
{chef_keygen_cache,keygen_timeout}
2020-03-05 20:20:02 =ERROR REPORT====

/var/log/opscode/opscode-erchef/erchef.log
2020-03-05 20:19:27.327 [info] {chef_keygen_cache,incr_worker_count,1.5}
2020-03-05 20:19:27.327 [error] {chef_keygen_cache,keygen_timeout}
2020-03-05 20:19:27.327 [info] {chef_keygen_cache,decr_worker_count,1}
2020-03-05 20:19:27.327 [info] {chef_keygen_cache,incr_worker_count,1.5}
2020-03-05 20:19:27.328 [error] {chef_keygen_cache,keygen_timeout}
2020-03-05 20:19:27.328 [info] {chef_keygen_cache,decr_worker_count,1}
2020-03-05 20:19:27.328 [info] {chef_keygen_cache,incr_worker_count,1.5}

**Comment by tas50** [comment]
I've moved this issue to the chef-server repository so it can be addressed there.

**Comment by markan** [comment]
This might be a manifestation of an issue with the keygen worker we fixed here: https://github.com/chef/chef_authn/pull/35. Basically we were getting into a pathological state where we weren't finishing within the timeout, and it was timing out and starting new workers while not cleaning up the old one. So we could end up running large numbers of ssh-keygen processes, and that in turn would starve the workers for resources, guaranteeing they wouldn't finish in time, and perpetuating the situation.

Later versions of chef-server (after 12.17.33) have this fix. In the short term, you might increase the chef_authn  keygen_timeout value to be substantially higher. The default is 1000ms, I might choose something like 30000ms.

**Comment by markan** [comment]
One last thought: do you happen to have FIPS turned on? The FIPS approved implementation of ssh-keygen doesn't use the crypto acceleration x86 instructions and is substantially slower. If so, definitely bump the timeout, on some machines keygen can take over 1s in that mode.

**Comment by markan** [comment]
Note for future attempts to repro, this can often be triggered by starting in FIPS mode on a t2.medium or other CPU throttled host.

**Comment by chakravarthykkalyan0804** [comment]
Thank you Marken for your response. I will verify settings and verify if we can bring down CPU Usage.

**Comment by chakravarthykkalyan0804** [comment]
Hi Marken, I am trying to find how we can find chef_authn keygen_timeout value. We do not have Chef U configured.

**Comment by chakravarthykkalyan0804** [comment]
updated /etc/opscode/chef-server.rb 
we added these two lines to chef-server.rb
opscode_erchef['keygen_cache_workers'] = 1
opscode_erchef['keygen_timeout'] = 30000 
and re-configure. This helped to bring spike down.

**Comment by chakravarthykkalyan0804** [comment]
updated /etc/opscode/chef-server.rb 
we added these two lines to chef-server.rb
opscode_erchef['keygen_cache_workers'] = 1
opscode_erchef['keygen_timeout'] = 30000 
and re-configure. This helped to bring spike down.

**Comment by markan** [comment]
Glad to hear that helped!
