### ISSUE TITLE
Chef Server still asks for accepting license when built from source

### ISSUE THREAD

**Issue by karthanistyr** [chef/chef-server#1974]
### Chef Server Version
13.2.3

### Platform Details
Built on Ubuntu 18.04

### Configuration
N/A -- building the deb package

### Scenario:
After reading [Introducing the New Chef: 100% Open, Always](https://blog.chef.io/chef-software-announces-the-enterprise-automation-stack/), it seems clear that the Chef EULA should only apply to the precompiled binaries as provided by Chef Software, e.g. via downloads.chef.io, and that the source code and all derivatives from it should be covered by the Apache 2.0 License.

However, after compiling the chef-server deb package on my machine, I am still compelled to accept the Chef EULA for the Chef Infra Server component (along with that of the client and inspec).

While I understand the technical reasons for this prompt (the license check is baked into the code), it appears that Chef Software hasn't fully complied with their own policy of licensing the source code as Apache 2.0 if the direct result of a compilation leads to accepting terms that shouldn't apply.

### Steps to Reproduce:
```bash
$ apt-get install ruby rebar git zlib1g-dev libsqlite3-dev libpq-dev build-essential bundler autoconf
$ git clone https://github.com/chef/chef-server
$ cd chef-server/omnibus && bundle install --binstubs && ./bin/omnibus build chef-server
$ dpkg -i pkg/pkg/chef-server-core_13.2.3+20200428135755-1_amd64.deb
$ chef-server-ctl reconfigure
+---------------------------------------------+
            Chef License Acceptance

Before you can continue, 3 product licenses
must be accepted. View the license at
https://www.chef.io/end-user-license-agreement/

Licenses that need accepting:
  * Chef Infra Server
  * Chef Infra Client
  * Chef InSpec

Do you accept the 3 product licenses (yes/no)?

>
```
### Expected Result:
The process should not ask for accepting the Chef EULA, **at least** in the case of Chef Infra Server as this version of the product was not distributed by Chef Software.

Perhaps the license check should be added separately by Chef Software' own compilation and distribution pipeline at a later stage, and the source code should be exempt of such logic.

### Actual Result:
There was a prompt for accepting the Chef EULA even for the Chef Infra Server component.

**Comment by bobchaos** [comment]
Doing your own build isn't sufficient to be compliant with the Chef EULA, you need a build that has been stripped of all Chef's branding. Come see us in the Chef Community Slack's #community-distros channel, we can help you build your own, or you can just use the stuff already built by cinc.sh . Do note cinc doesn't publish a server yet, but then server 12 isn't EOL yet. Hope this helps.

**Comment by karthanistyr** [comment]
@bobchaos it does, actually, thanks!
