### ISSUE TITLE
Allow sign up to be disabled

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#199]
From @smith in chef/oc-id#41:

> As a Chef server administrator, I would like to disable the sign up functionality and links to it in the oc-id web interface.
> 
> A `default['private_chef']['oc_id']['enable_sign_up']` should be present and default to `true`. If set to false, it should:
> - Remove all sign up links from oc-id
> - If sign up functionality is implemented in oc-id, it should go to a page explaining that sign up is disabled
> - If LDAP is enabled on the server, this attribute should be set to `false` automatically.
> - In the configuration for Manage, it should take the setting from oc-id unless explicitly otherwise set in the Manage configuration (the Manage attribute is called disable_sign_up. This one is different because it's better to use positive terminology consistently in configuration options (everything on https://docs.chef.io/config_rb_server_optional_settings.html uses "enable" instead of "disable".) The one in Manage should be changed to match this one but eventually go away.)

**Comment by tas50** [comment]
Closing this out since we're not actively expanding the functionality of oc-id.
