### ISSUE TITLE
Enterprise Chef / Chef Server 12: View Public Keys of all Users

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#20]
As a customer of Enterprise Chef/Chef Server 12

"I want to be able to set permissions or have the default permissions for users(In the Users group, not members of Admins) to be able to see the public key, full name, and email address of other users in the same org.

"As a user you are only allowed to see basic information of other users. We use Chef-Vault and as a user they are not allowed to add admins of the vault unless they can see their public key. Since it is just the public key I would think that information could be shared more freely than it is today."

I should be able to do ```knife user show USERNAME``` as a user that is a member of only the standard Users group, but currently, the requirement is that the user be a member of the Admins group to view this unprivileged information.

Additionally, the same access should be allowed for https://github.com/opscode-cookbooks/chef-vault#chef_vault_secret running on managed client nodes to users/nodes public keys through the RBAC system by default in Chef Server 12. 

Found in ZenDesk 474 and HelpSpot 18264

**Comment by sean-horn** [comment]
This is possible according to the following, but we should have a more clean cut, official way to do the same.

http://lists.opscode.com/sympa/arc/chef/2015-01/msg00308.html
https://gist.github.com/stevendanna/1eb99f01a2f0f22ba619

**Comment by pburkholder** [comment]
Also ZenDesk 3505

**Comment by pburkholder** [comment]
See also https://github.com/Nordstrom/chef-vault/issues/126 for discussion related to this.

**Comment by pburkholder** [comment]
https://github.com/chef/chef-server/pull/244 should address this issue. Thanks @stevendanna !

**Comment by tiago-cruz-movile** [comment]
Worked using chef-server-core-12.2.0.

Thanks a lot!

**Comment by stevendanna** [comment]
Nice!

**Comment by petracvv** [comment]
Would it be possible to reopen this? It now works for a user in the users group to read info on other users, but clients still can't read this information. As @sean-horn said:

> Additionally, the same access should be allowed for https://github.com/opscode-cookbooks/chef-vault#chef_vault_secret running on managed client nodes to users/nodes public keys through the RBAC system by default in Chef Server 12.

This is a bit annoying if we want to save secrets using chef-vault in a recipe and give certain users access to those secrets as well.

**Comment by http-418** [comment]
I am also having trouble with chef-vault secrets.   Since clients can't read users' public keys, it is not possible to encrypt chef-vault secrets for users via calls inside recipes.

I would love to see this ticket re-opened.

**Comment by stevendanna** [comment]
@petracvv @http-418 Mind opening a new ticket for clients reading user objects?  On the technical side, I think the same basic fix could work, but I'd like to think through the policy implications of that.

**Comment by pburkholder** [comment]
@stevendanna I think we should consider a "wont fix" for this. While there's nothing inherently wrong with reading public keys, it means we're putting engineering time into use cases for programmatically having clients access secrets and encrypt them. I think if you're doing that you probably shouldn't be using Chef-Vault but should be using a dedicated secret service such as Conjur, Summon, Hashicorp vault or one of those ilk.

I may be missing other use cases, but I don't think its a big win for effort that would go into it.

**Comment by http-418** [comment]
@pburkholder You have already put engineering time into these use cases.  This ticket is one such example.  Chef-vault is quite widely used. 

@stevendanna I'm going to open a new issue referencing this one.

**Comment by pburkholder** [comment]
I retract my objection. Thanks for the clarifying use-case:

> We have been using chef-vault to deploy secrets to our Chef clients. Specifically, we often generate secrets in recipes, then encrypt them for other nodes and users by reading their public keys via the Chef API.
> This is not currently working in Chef 12, because clients cannot read public keys for users.
