### ISSUE TITLE
Support SSO login

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#200]
In a ticket with a long lineage, @smith said in chef/oc-id#37 that @ryancragun said in chef/chef-manage-issues#10 that:

> As a Chef Manage user I would like to use SSO login (SAML, OpenID, etc) to authenticate and login to the Management console.

Note from the editor: Let's try to get a definitive answer for this one before it gets to a 4th repository.

**Comment by edyesed** [comment]
FWIW, I'd like to see this feature as well.

**Comment by smith** [comment]
@edyesed the best way to get some movement on this probably is to move the discussion to https://feedback.chef.io/. Closing this now.

**Comment by tmaier** [comment]
Related idea on the feedback page: https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/8375115-improvements-to-external-user-authentication-and-a
