### ISSUE TITLE
Clarify Push Jobs IPv6 support

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#2019]
Currently, the push-jobs add-on does not appear to work out of the box with IPv6 because we generate nginx upstream configuration that doesn't correctly put the IP address in `[]`s, resulting in the following error:

```
2020-05-21_08:17:23.97520 nginx: [emerg] invalid port in upstream "2a05:d01c:13:cb01:2e94:2b02:9f4f:8732:10003" in /var/opt/opscode/nginx/etc/addon.d/10-push_jobs_upstreams.conf:5
```

While we could likely work-around this in our tests via more explicitly setting some configuration value, I think we should probably clarify whether we expect pushy to work in IPv6 mode and if so make sure that whatever workaround we put in our tests is also put into the documentation.

Note, that I may have missed something here as we have a lot of issues we are working through at the moment.

@markan Do you have any further context here?

**Comment by markan** [comment]
At this point I would say we shouldn't expect it to work with IPv6 out of the box. Probably wouldn't be too hard to fix; but would require code changes. We would have to check that the client manages ports correctly in ruby as well. When we wrote the client Ruby had some similar bugs with port specifications in URLs, and I don't know if we worked around them, or if the workarounds stayed correct after multiple Ruby upgrades.

**Comment by stevendanna** [comment]
@markan Awesome, thanks for the confirmation.  Our IPv6 tests will likely require some follow up work for a number of reasons, so we can look at this again in the future, but I think given our current set of priorities, deferring that work for a bit makes sense.

**Comment by tas50** [comment]
Closing this out since we're no longer supporting push jobs
