### ISSUE TITLE
Improve Zendesk Integration

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#203]
@smith reported in chef/oc-id#22:

> There are a couple of things we should change on the Zendesk SSO:
> - [ ] When there's a failure, it sends the user back to a URL like  https://id.opscode.com/id/zendesk/signout?kind=error&message=Please+use+one+of+the+options+below+to+log+in+to+Zendesk. Fix this so the message parameter is parsed and displayed as a flash message.
> - [ ] When hitting /id/zendesk/signout, it signs them out of oc-id and drops them on the sign in page. Instead, we should _not_ sign them out of oc-id, and give them a message saying that they were signed out of Zendesk, but not their Chef account, and a link to sign back in.
> - [ ] When logging in via /id/zendesk, there should be a flash message telling you you'll be signed in to Zendesk
> - [ ] When signing in by the normal route, there should be a link to support somewhere on the page

@smith do you see this more as a Hosted-centric feature?  Or something generally appropriate for Chef Server.

**Comment by smith** [comment]
@stevendanna It's hosted-centric but included with oc-id. We're moving toward having as few differences as possible between hosted and on-prem. The endpoints just get a 404 if no Zendesk configuration is present: https://github.com/chef/chef-server/blob/master/src/oc-id/app/controllers/zendesks_controller.rb#L31

**Comment by tas50** [comment]
Closing this out since we're not actively working on improving oc-id at this point in time.
