### ISSUE TITLE
[integration_pipeline] Ldap-ipv4 fails to install chef-workstation in the pipeline

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2036]
The ldap scenario but fails on trying to run in the integration_test pipeline
https://buildkite.com/chef/chef-chef-server-master-integration-test/builds/141#_

It works when testing manually INSTALL_VERSION=13.2.0 UPGRADE_VERSION=13.2.49 WORKSPACE=omnibus-external-openldap-ipv4-rhel-8 make apply

This error has been seen in the past. All errors for Ldap were fixed in 13.2.36, But this has started to show up again.

Adding /var/chef-workstation/cache/chef-stacktrace.out to capture paths might offer some insight into the reason for failiure.

Going back : https://buildkite.com/chef/chef-chef-server-master-integration-test/builds/91#00d63e9b-1d3d-490d-9ade-d837021af2e2 built with
UPGRADE_VERSION="13.2.12+20200513204302"
fails to run the scenario past workstaion install.

but https://buildkite.com/chef/chef-chef-server-master-integration-test/builds/78#3fef4bf8-a18f-4428-98d4-fb640cce89c2 built with
UPGRADE_VERSION="13.2.7+20200429213046"
actually ran the scenario but failed in tests.

**Comment by christopher-snapp** [comment]
Ok, I'm pretty sure I (finally) narrowed this down to to a flaky connection that can be addressed by giving the newly instantiated instance a few more seconds (30) before we attempt to do a `chef-run` against it.

**Comment by christopher-snapp** [comment]
PR #2037 seems to show the fix working, and I've run the change through several pipeline builds and all have passed.
