### ISSUE TITLE
Allow users to create applications

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#205]
@smith says in chef/oc-id#18:

> Right now the only thing you can see is "Authorized Applications", unless you're an admin.
> 
> People should be able to create and manage their own applications, similar to the "Developer applications" section on https://github.com/settings/applications.

The original ticket has further discussion not included here.

**Comment by tas50** [comment]
Closing this out as oc-id is what it is at this point and isn't being moved to automate.
