### ISSUE TITLE
Prepare for release of 13.3

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2066]
#1947 and #1973 affect some users of 13.2.0. Prepare a release 13.3.x with the fix in #2064.

**Comment by PrajaktaPurohit** [comment]
If this work ever needs to be picked up:
Build at: https://buildkite.com/chef/chef-chef-server-chef-server-13-omnibus-adhoc/builds/172
Integration test(failed) : https://buildkite.com/chef/chef-umbrella-master-chef-server/builds/95#_ (Some of the failures might be related to the setup but will need to dig into that if this needs to be picked up again.

**Comment by tas50** [comment]
Closing this out since we're moving forward with the 14.x release cycle and security updates there.
