### ISSUE TITLE
Add ability to retrieve more than just username

### ISSUE THREAD

**Issue by haidangwa** [chef/chef-server#2080]
# Version:

```
$ chef --version
Chef Development Kit Version: 3.2.30
chef-client version: 14.4.56
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.70
```

# Environment:
We run these on chef sysadmin workstations (Mac and Windows) and from an AWS ECS Fargate container for nightly tasks.

# Scenario:

As a system administrator and also with a group of system administrators, it would be very helpful to be able to query the chef server for all users on the system along with certain details about their accounts, such as email address. This plugin allows us to query for this today, but the process is cumbersome and involves making multiple trips back to the chef server API.

# Steps to Reproduce:

- Run `knife opc user list` to get the entire list of chef users
- In a loop, get the user data for each user:
```
for user in `knife opc user list`; do 
  knife opc user show $user -Fj
done
```
The rest of this would be some parsing of the return values to get the username and email addresses.

# Expected Result:

I'd like to make just one API call that returns to me all of the data that I need -- complete user info for every user. Something like `knife opc user show -a -Fj`.

# Actual Result:

Today, I have to make multiple trips back to the API in order to get the data that I need. For our company, this takes a very long time. To get around this, I've concocted a direct sql query to bypass the API, but this is not future proof if the db schema changes. This also puts other undue requirements accessing the data, because our database has certain rules around inbound access (RDS postgres and AWS security group rules). It's not easily done from a sysadmin's workstation without modifying the security group rules.

**Comment by btm** [comment]
Do we want a single API endpoint on the infra server that returns all users, or would it be enough for `knife opc user show -a -Fj` to make a call for the list of users, then individual calls for all the users, and present that as combined output?

**Comment by haidangwa** [comment]
@btm What I imagined was one endpoint that returned all the detailed data about a user, not just their username.
