### ISSUE TITLE
Reconfigure doesn't handle not having a hostname set well

### ISSUE THREAD

**Issue by jmink** [chef/chef-server#21]
Behavior:
A chef-server-ctl reconfigure dies with the error: FATAL: RuntimeError: Please add a server section for  to /etc/opscode/private-chef.rb!

This appears to be due to the server not having a valid hostname set, therefore cookbooks/private-chef/recipes/default.rb:87 indexes into the config with nil or "" and doesn't find the local host and complain.  It would be cleaner to just error if the host name is 0 characters.

**Comment by irvingpop** [comment]
This is one of the most common first issues encountered by new Chef server users.    We do state in [the documentation](http://docs.chef.io/server/install_server.html) that `A resolvable hostname that is specified using a FQDN or an IP address` but we could make it more intuitive

**Comment by sdelano** [comment]
A good user experience here would be something along the lines of:

```
Chef Server could not resolve your hostname: (p.s. it's blank)

Please set it with ...
```

in HA mode, we could even go one step further to note that you should also have an entry in `chef-server.rb` for each server that corresponds to that hostname.

**Comment by irvingpop** [comment]
:+1:

**Comment by PrajaktaPurohit** [comment]
Closing in favor of #1641
