### ISSUE TITLE
Use a custom error report handler in oc_erchef

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#214]
Using a custom error handler in oc_erchef via error_logger:add_report_handler will allow us to provide a uniform method of capturing and reporting errors in erchef.  This would also provide a starting place for filtering if sensitive data out of error reports without losing other valuable data. 

See also #156.  

Note that we'd also have to disable lager interception of error_logger reports via specifying lager configuration entry `{error_logger_redirect, false}`.

**Comment by PrajaktaPurohit** [comment]
Closing as a wont fix for now. The is indeed a good suggestion, will reopen if we have a good use-case for this in the future.
