### ISSUE TITLE
Incorrect license in elasticsearch omnibus software definition

### ISSUE THREAD

**Issue by smith** [chef/chef-server#2140]
The [Omnibus software definition for Elasticsearch](https://github.com/chef/chef-server/blob/master/omnibus/config/software/elasticsearch.rb) states that it's Apache 2.0 licensed but the source URL is linking to the default distribution which contains code under the Elastic License.

The OSS-only version can be downloaded from https://www.elastic.co/downloads/past-releases/elasticsearch-oss-6-8-1. 

Also note that this is release is missing quite a few security patches since the latest in the 6.8 branch is 6.8.12.

**Comment by stevendanna** [comment]
Thanks @smith! I've opened a pull request to fix this which is running through our test pipeline now.
