### ISSUE TITLE
SSL Callback fails with 403 Error tomcat-Set content type on response- set content type on POST

### ISSUE THREAD

**Issue by chakravarthykkalyan0804** [chef/chef-server#2141]
Current version of Tomcat is 9.0.37
We have a microservice developed with HSTS setting incorporated which does not allow SSL traffic.
SSL Callback fails with 403 Error tomcat-Set content type on response- content type on POST
hostname:apache-tomcat-9.0.37
'''curl -k -v -POST --cert Z://Atlantis/certs/SIT/cstmsitlvngs51.crt --key Z: hostname. Key -d @DerogUpdateAllElements.xml --header "content-type:'''

'''application/soap+xml" https:// hostname:9999//'''

'''Warning: Couldn't read data from file "DerogUpdateAllElements.xml", this makes Warning: an empty POST.'''

'''About to connect() to hostname.dev.local port 9999 (#0)'''

'''Trying xxx.xx.xx.xx..'''

'''Connected to hostname (xx.xx.xx.xx) port 9999 (#0)'''

'''Initializing NSS with certpath: sql:/etc/pki/nssdb'''

'''skipping SSL peer certificate verification'''

'''SS: client certificate not found: Z

'''SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'''

'''Server certificate:'''

'''common name: hostname.dev.local'''

'''POST /identdunlistener/IdentDUN/ HTTP/1.1'''

'''User-Agent: curl/7.29.0'''

'''Host: hostname.dev.local:9915'''

'''Accept: /'''

'''content-type: application/soap+xml'''

'''Content-Length: 0'''

'''HTTP/1.1 403 '''

'''X-Frame-Options: DENY'''

'''Content-Type: application/json'''

'''Transfer-Encoding: chunked'''

'''Date: Tue, 06 Oct 2020 01:56:59 GMT'''

'''HTTP error before end of send, stop sending'''
# Describe the problem

## Stacktrace

<details><summary>  </summary>
```
```
</details>

## Possible Solution

Aha! Link: https://chef.aha.io/features/SH-335

**Comment by chakravarthykkalyan0804** [comment]
https://stackoverflow.com/questions/42261607/tomcat-8-0-mime-mapping-content-type

**Comment by PrajaktaPurohit** [comment]
@chakravarthykkalyan0804 Sorry to see you are having trouble. We are focussed on fixing any issue pertaining the Chef Infra Server. Could you please let us know the version of Chef Server you are seeing this issue with and some more details about your environment and steps for replication if possible. Thank you!

**Comment by PrajaktaPurohit** [comment]
Closing since this does not seem related to chef-server. Please feel free to reopen if needed.
