### ISSUE TITLE
Rails 6 fails on EL6 due to old GCC version

### ISSUE THREAD

**Issue by christopher-snapp** [chef/chef-server#2149]
`sass-rails` 6.0.0 introduced a runtime dependency on `sassc-rails` which needs to be compiled as a native extension.

The version of GCC on EL6 is ancient and has caused issues with chef-server builds in the past. As a result the `omnibus-gcc` package was created a year ago to upgrade the version of GCC on EL6 but the approach used to upgrade GCC was beginning to cause other compilation issues similar to the ones being discussed here:

https://github.com/chef/chef/issues/9831#issuecomment-626817131

Compiling `sassc-rails` using `omnibus-gcc` results in a chef-server artifact that fails on a stock EL6 machine with:

```
LoadError: Could not open library '/opt/opscode/embedded/service/gem/ruby/2.6.0/gems/sassc-2.3.0/lib/sassc/libsass.so': /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /opt/opscode/embedded/service/gem/ruby/2.6.0/gems/sassc-2.3.0/lib/sassc/libsass.so)
```

More information can be found in the following build failure:

https://buildkite.com/chef/chef-chef-server-master-omnibus-adhoc/builds/1700#18e62f8f-bbda-4851-9987-2acfabf6f8ce/100-1971

**Comment by tehlers320** [comment]
RHEL6 is end of life on Nov 30th from Red Hat. It wouldn't be entirely un-reasonable to announce EOL for RHEL6 chef-server IMO. I'm sure you have many other customers though.

**Comment by christopher-snapp** [comment]
I've upgraded the version of GCC in our build pipeline's EL6 AMI to use `devtoolset-7`.  This provides a RHEL supported approach to using a newer version of GCC to support Rails 6
