### ISSUE TITLE
Organize Chef Infra Server dependency update schedule.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2151]
Create a list of all the dependencies of Chef Infra Server
 - Omnibus level
 - Code level

Add information related to the following for each of the dependency:
- Name of the dep
- Current version
- supported until / EOL by
- any known CVE's
- patches applied or dates the patches for CVE's would be applied.
- included in release version
- priority

Acceptance Criteria:
- Define a list of dependencies
- Define their scheduled date of regular update

Aha! Link: https://chef.aha.io/features/SH-429

**Comment by PrajaktaPurohit** [comment]
https://docs.google.com/spreadsheets/d/1ErqmTkPP1oFmsFRdnPgGECkaQARZoxuh2isGAfosgwo/edit?usp=sharing

This has a list of all the deps for Chef Infra Server. WIP to identify the current and out of date versions.
After current round of updates, this should be reviewed on 31st Jan 2021 for the next round of updates.

**Comment by tas50** [comment]
We have the remaining components identified and epics created for bumping them all.
