### ISSUE TITLE
chef-server-ctl reconfigure fails on large memory machines

### ISSUE THREAD

**Issue by nvwls** [chef/chef-server#2154]
### Chef Server Version
14.0.65

### Platform Details

CentOS 7.8
512GB RAM
8TB Free disk space

### Configuration
Standalone

```
node.default['chef-server']['configuration'] = <<CONFIGURATION
nginx['non_ssl_port'] = false
nginx['ssl_port'] = 4000
nginx['show_welcome_page'] = false
CONFIGURATION
```

### Scenario:
Set up a chef-server

### Steps to Reproduce:
Running `chef-server-ctl reconfigure` on a large memory machine.

### Expected Result:
`chef-server-ctl reconfigure` succeeds

### Actual Result:
```
-----------------------------------------------------------------------
INDEX004: Invalid elasticsearch heap size

              elasticsearch['heap_size'] is 128979MB

          The recommended heap_size is between 1GB and 26GB. Refer to
          https://www.elastic.co/guide/en/elasticsearch/reference/6.8/heap-size.html
          for more information.
-----------------------------------------------------------------------
```

Aha! Link: https://chef.aha.io/features/SH-433

**Comment by tehlers320** [comment]
@nvwls i made https://github.com/chef/chef-server/pull/2155 which may resolve the part of the cookbook had no spec to start with, it could really use one.

**Comment by PrajaktaPurohit** [comment]
Sorry for the inconvenience. #2155 should fix it. Please feel free to reopen if not.
