### ISSUE TITLE
[dep update] Update postgresql to 12

### ISSUE THREAD

**Issue by btm** [chef/chef-server#2157]
Upgrade internal Postgres in Chef Infra Server to 12 (or 13, Amazon RDS might not yet support Postgres 13).  This will help us get newer security features and better performance.

We need to be able to work with Older versions of Postgres for external postgres scenarios and to maintain compatibility with other products.

1. Add omnibus support for PG12
2. Add tests for external Postgres scenario with PG12 to integration_test pipeline. At this point for a branch pointing to PG 12 by default should work by default.
3. To upgrade from older versions can use:  pg_upgrade followed by vacuum analyze
4. Finally change the default in Chef Server to use PG12

#### Acceptance Criteria:
1. Chef Infra server can migrate from PG9.6 to 12
2. Backward compatibility for older versions PG is tested and succeeds.
3. chef-server-ctl commads that need to connect to the db like chef-server-ctl user-create / chef-server-ctl org-create are tested and they work

Aha! Link: https://chef.aha.io/features/SH-3047

**Comment by tehlers320** [comment]
I would like this for one big reason. Amazon RDS can go "serverless" with postgres 11 which for low volume loads could save me a bunch of $$$.

Postgres 9 does not support "serverless"

**Comment by tehlers320** [comment]
If this gets pulled in it may be worth also merging https://github.com/chef/chef-server/pull/2110 which removes postgres 92.

**Comment by PrajaktaPurohit** [comment]
https://buildkite.com/chef/chef-umbrella-master-chef-server/builds/132#3a5b4d96-c419-4cd1-a0b6-705469bd0f4b -> the builds currently pass while updating to postgres 12. Next things which this gets pickedup:
1. Check if pg_upgrade is actually running the upgrade and data from 9.6 is transferred into 12.0
2. Add tests to the umbrella pipeline to test for the actual data, perhaps can start with checking that the counts match in the integration test pipeline.

**Comment by jtimberman** [comment]
As of today, PostgreSQL 12.5-R1 is the latest version available in AWS RDS.

**Comment by tas50** [comment]
Good to know. Thanks @jtimberman

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/2238

**Comment by lbakerchef** [comment]
https://github.com/chef/chef-server/pull/2241

**Comment by scottalexanderchefio** [comment]
Amazon Aurora PostgreSQL 9.6.XX will reach end of life on January 31, 2022.  Databases not upgraded before the end of life deadline will be upgraded to the appropriate major version during the next scheduled maintenance window.  This means that any chef server user using (external) Amazon Aurora PostgreSQL 9.6.XX will have to upgrade. This includes our Hosted Chef service offering.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/2577 is the upgrade to 13.2. Closing this in favor of the PR mentioned.
