### ISSUE TITLE
searches failing with 500s on hosted chef

### ISSUE THREAD

**Issue by nrgetik** [chef/chef-server#2163]
### Chef Server Version
14.0.24

### Platform Details
Hosted Chef

### Configuration
Hosted Chef :)

### Scenario:
Searches are failing for certain orgs, e.g.

```
knife search node "*:*"
```

Results in 500s on a Hosted Chef organization that has 18,000 nodes

### Expected Result:
Successful results returned

### Actual Result:
```
ERROR: Server returned error 500 for https://api.chef.io/organizations/ORGNAME/search/node?q=*:*&start=10000&rows=1000, retrying 1/5 in 4s
```

@joshbrand to add further detail

**Comment by joshbrand** [comment]
Some added context: the 500s appear to be coming from elasticsearch itself, the first few pages of results appear to succeed, it's only at this 10k+ mark that things begin to fail.

**Comment by stevendanna** [comment]
@joshbrand I believe 10,000 mark is the point at which ES stops allowing pagination

**Comment by stevendanna** [comment]
Is it possible we need to set https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-result-window on ES in Hosted?

**Comment by nrgetik** [comment]
@stevendanna i *think* @joshbrand tried that in preprod already. we've seen that before in onprem deployments and usually it just limits the result set to 10k instead of erroring with 500, but maybe something's changed
