### ISSUE TITLE
[dep update] Update version of Perl to 5.32.0

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2166]
Chef Infra Server currently uses 5.18.1. Only versions above 5.20.0 are currently supported. Upgrade perl to 5.32.0 or 5.33.0

This might have to be done in parallel with upgrading the version of sqitch)

Acceptance criteria:
Sqitch continues to work (Test that reconfigures are still successful)

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/issues/1863

**Comment by tehlers320** [comment]
Not sure if its the right place, but i had to add this for mine. https://github.com/tehlers320/omnibus-software/blob/PERL/config/software/cpanminus.rb#L44

**Comment by tas50** [comment]
This is blocking our ability to build chef-server directly on RHEL 8: https://buildkite.com/chef/chef-chef-server-master-omnibus-release/builds/426#08bb5da4-7392-48df-80f6-3150b184edd7/6-8417

**Comment by tas50** [comment]
Closing this out in favor of the 5.34 issue now
