### ISSUE TITLE
[dep update] Update sqitch to 1.1.0

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2167]
Chef Infra Server is currently on version 0.973. It should be upgraded to 0.999 or 1.1.0.

No version prior to 0.999 is currently tested.

Acceptance criteria:
- Reconfigures are successful
- Upgrading chef-server is successful

**Comment by tehlers320** [comment]
you're going to hit a bunch of licensing issues with this. 

Here is my version of the config that i can only get to build with omnibus.rb set to ignore licenses. 
https://github.com/tehlers320/omnibus-software/blob/sqitch/config/software/sqitch.rb

**Comment by tas50** [comment]
This is part of the Perl upgrade story now
