### ISSUE TITLE
Add "SSL options" configuration to mini_s3 and/or ercloud

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#2171]
Old mini_s3 (pre-sigv4 upgrade) had an SslOpts parameter in the new/5 function.  The 'new' mini_s3 (post-sigv4 upgrade) unceremoniously dropped the SslOpts parameter, because erlcloud neither has a new/5, nor an SslOpts parameter in any new function.  It was a case of "kicking the can down the road until we figure out what to do."

Per @stevendanna on Sep 15 2020:
"Dropping SSL Options is going to be a problem for A2-based Chef Server's as we need to be able to pass the SSL Options to talk to bookshelf with the right TLS configuration."

The first thing I'd investigate, as a hunch or intuition, is whether or not the #aws_config record created using mini_s3:new (which calls a similar function in erlcloud) has some kind of ssl options field.  If it lacks one, an unused field could possibly be commandeered.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/automate/compare/praj/test_sig_v4 setting {fail_if_no_peer_cert, false} is the current workaround for this issue.
