### ISSUE TITLE
The status endpoint in chef-server should return the version of the server installed.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2172]
Currently the chef-server status endpoint (https://192.168.33.100/_status on the dev-env) returns the following json:
```{"status":"pong","upstreams":{"chef_elasticsearch":"pong","chef_sql":"pong","oc_chef_authz":"pong"},"keygen":{"keys":10,"max":10,"max_workers":2,"cur_max_workers":2,"inflight":0,"avail_workers":2,"start_size":0},"indexing":{"mode":"batch"}}```

It would be helpful to Include the version of chef-server installed as a part of this json.

Currently version can be extracted from:

```
root@api:~# cat /opt/opscode/version-manifest.txt
chef-server 14.0.67+20201111171939
```

or "build_version" from its json counterpart:  /opt/opscode/version-manifest.json

Acceptance criteria:
The status endpoint returns the version of chef-server installed.

**Comment by btm** [comment]
Out of curiosity, does _status have support for any kind of security, like an access control list? From time to time we get security reports concerned with nginx/openresty returning it's version in some end point as leaking too much information.

**Comment by PrajaktaPurohit** [comment]
That is a great point. I think there is still value in shipping this since it has been asked for by some customers in the past. As per a suggestion from @tas50 we can make it configurable to avoid making it a security issue for those who would not like to display this information. Issue tracked at #2214
