### ISSUE TITLE
Support mutual TLS authentication

### ISSUE THREAD

**Issue by btm** [chef/chef-server#2179]
### Support enabling and configuration mutual TLS (mTLS), aka client certificate verification 

For additional security, particularly in cases where the Infra Server API might be publicly accessible, customers would like to enable mutual TLS on the Infra Server. 

Traditionally with SSL/TLS, the client verifies that the certificate used by the server is signed by a trusted Certificate Authority. For web sites the trusted CA is usually a public CA such as DigiCert. For internal servers it is usually a private CA set up by the enterprise. With mutual TLS, the server also verifies that the client's certificate is signed by a trusted CA. If it is not, the client cannot connect to the server at all.

Today the Infra Client supports mutual TLS using the `ssl_client_cert` and `ssl_client_key` [config.rb settings](https://docs.chef.io/config_rb_client/). The Infra Server does not have support for enabling this feature, it must be done by [terminating the SSL connection](https://www.f5.com/services/resources/glossary/ssl-termination) on another system before it reaches the Infra Server.

The feature proposed is to enable the configuration of mTLS on the Infra Server.

### Acceptance Criteria
* mTLS can be configured as required on the Infra Server through the configuration file
* a CA for mTLS can be specified  on the Infra Server through the configuration file

### Implementation
The relevant nginx/openresty configuration settings should be:
```
   ssl_client_certificate /home/ubuntu/connect_root.pem;
   ssl_verify_client on;
   ssl_verify_depth 10;
```

These likely get set in this file on a chef server:
```
/var/opt/opscode/nginx/etc/chef_https_lb.conf
```

by conditionals configured in this file in the chef-server repository:
```
omnibus/files/private-chef-cookbooks/private-chef/templates/default/nginx/nginx_chef_api_lb.conf.erb
```

**Comment by tas50** [comment]
DONE!
