### ISSUE TITLE
Upgrade the built in Chef from 15.12.22 to 15.14.0

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2192]
We need to get on the latest version of 15:

Update omnibus:
https://github.com/chef/chef-server/blob/master/omnibus_overrides.rb#L9

Update the gemfile.lock in https://github.com/chef/chef-server/tree/master/src/chef-server-ctl by running `bundle update chef`

Update the gemfile.lock in https://github.com/chef/chef-server/tree/master/oc-chef-pedant by running `bundle update chef`

**Comment by PrajaktaPurohit** [comment]
This has been updated to 15.15 (latest from the chef-15 branch) https://github.com/chef/chef-server/pull/2228

**Comment by PrajaktaPurohit** [comment]
Closing out as a duplicate https://github.com/chef/chef-server/issues/2229
