### ISSUE TITLE
Manual partybus init

### ISSUE THREAD

**Issue by jmink** [chef/chef-server#22]
When doing a fresh CS12 install (in this case on REHL 5, on the backend of a tiered setup) the following error pops up:

    [2014-11-11T17:20:15-05:00] FATAL: RuntimeError: ruby_block[migration-level file sanity check]     (private-chef::partybus line 53) had an error: RuntimeError: ERROR:
    The /var/opt/opscode/upgrades/migration-level file is missing or corrupt!  Please read     http://docs.opscode.com/upgrade_server_ha_notes.html#pre-flight-check and correct this file before     proceeding
    
    * If this is a new installation:
      run: "cd /opt/opscode/embedded/service/partybus ; /opt/opscode/embedded/bin/bundle exec     bin/partybus init"
    * If you have upgraded a previous installation:
      copy the /var/opt/opscode/upgrades/migration-level file from a not-yet-upgraded FrontEnd node
    
    Error message No such file or directory - /var/opt/opscode/upgrades/migration-level
    
    [root@ec2-54-148-65-220 ~]# cd /opt/opscode/embedded/service/partybus ;         /opt/opscode/embedded/bin/bundle exec bin/partybus init
    
We should look into this error and determine how to avoid it/make it clearer.

**Comment by sdelano** [comment]
Closing this after discussions with @irvingpop and @sean-horn. This should have been fixed [here](https://github.com/chef/chef-server/commit/46c45a726124245c2fe1af70c7dcb66e2ef29ffe). If this comes up again, we can reopen the issue.
