### ISSUE TITLE
oc-id verification failing in master

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#2215]
I was able to [confirm](https://buildkite.com/chef/chef-chef-server-master-verify/builds/2926#43075a24-eff6-43a1-bf68-57441b7aec07/78-1507) oc-id tests are failing on master. 

The latest info on the underlying Rails conflict  that is known to cause this can be found [here](https://github.com/rails/rails/issues/34790#issuecomment-681034561), though given our use of 2.6.6 our [current patch](https://github.com/chef/chef-server/blob/master/src/oc-id/spec/support/monkeypatch.rb) should be fine.

We semi-recently (Dec?) switched from ruby 2.6.5 -> 2.6.6, but a [diff of 2.6.5 and 2.6.6](https://github.com/ruby/ruby/compare/v2_6_5...v2_6_6) shows no changes to the monitor variables that could re-introduce this. We have not changed Rails versions in a while either.

Our last merge to master was Monday, and it [did not have this issue](https://buildkite.com/chef/chef-chef-server-master-verify/builds/2904).

This is also affecting builds of work in progress (#2207).

**Comment by johnmccrae** [comment]
Here's an example of this in case anyone is curious - https://buildkite.com/chef/chef-chef-server-master-verify/builds/2929#60fe14f1-007d-4da0-8f42-c4af08d98446

**Comment by PrajaktaPurohit** [comment]
Thank you for looking into this @marcparadise. Looks like ruby on the builders was updated from 2.6.0 to 2.7.0 and that was  causing these failures. https://github.com/chef/chef-server/pull/2216 should fix it.
