### ISSUE TITLE
Chef Server should generate a full .p12/pfx file and not just a private key for the client.pem file

### ISSUE THREAD

**Issue by johnmccrae** [chef/chef-server#2239]
## Motivation

As a Chef Admin / IT Admin,
I want to store my certificates for everything in the proper format in Macos Keychain or Windows Certstore 
and NOT on disk,
So that my environment will be more secure.

Currently, there are customer requirements to make the Chef environment more secure. We implemented mTLS on Server as a first step to get there (chef client already supported that feature). A second, related, request is to not store any certs on disk as that creates opportunities for mayhem.  

To support this we would need to be able to store the client.pem file in either Keychain on MacOS or a Windows certificate store (either the CurrentUser or LocalMachine store depending on the current security domain requirement). Note that the client.pem is a private key and not a full certificate. 
	
Both OS stores require that you store a complete certificate and not just a private key - a private key does not contain sufficient detail for the certificate stores to validate it properly. 

Therefore, in order to store the client.pem from Chef Server off-disk on the client, we will need to rethink / redesign both the format of the client.pem and how it is generated. 

## Specification

I have no design proposal right now, I am using this DCR to start the conversation. The one thing that must happen here, however, is that Chef Server must generate a proper .p12 file for the node and not just pass it the private key. 

As we look toward moving Chef Server into a cloud environment for integration with SimpleMDM and Auth0 the conversation includes creation of a pfx file to properly identify the node to all parties concerned - Chef, SimpleMDM and Auth0. Having Chef Server create a proper p12/pfx for each node could potentially remove some of the design issues currently faced. 

## Downstream Impact

This is potentially going to break things but this needs to be investigated further to scope out just how minor or major the impact will be. One way to reduce the mayhem could be to allow a coexistence of both the old style (just give me the private key client.pem) and the new style (client.p12). A switch in the server.rb file could be used as the mechanism to turn that on/off.

**Comment by tas50** [comment]
Closing this out based on our conversation during standup. This is handled on the client side.
