### ISSUE TITLE
[docs update] workaround for operating on global endpoints with knife exec

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2240]
Knife exec uses the chef_server_url from knife.rb.

If changes need to be made to any global end points like user or user keys,
chef_server_url needs to be updated to https://hostname instead of http://hostname/organizations/orgname/

or a flag for --chef_server_url http://<hostname> should be included in the command line.
eg: knife exec -E 'api.delete("/users/myuser/keys/user33")' --server-url https://<hostname>

Also make note: in case of user keys default key cannot be deleted by anyone other than the admin user.

**Comment by jashaik** [comment]
chef-workstation PR - https://github.com/chef/chef-workstation/pull/1781
