### ISSUE TITLE
Update JDK to 11.0.10

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2253]
It's time to bump the JDK again. There's a large number of bug fixes along with CVEs:

https://www.oracle.com/java/technologies/javase/11-0-10-relnotes.html

**Comment by PrajaktaPurohit** [comment]
Updated in 14.1.0: https://github.com/chef/chef-server/blob/master/omnibus/Gemfile.lock#L20 -> https://github.com/chef/omnibus-software/commit/fb0fa049edd5d1c5109ef22b8c974bf3d12c81a8
