### ISSUE TITLE
Remove Ubuntu 16.04 builds ~ April 30th 2021

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2259]
Ubuntu 16.04 goes EOL April 30th 2021. We should remove this from our builds around that date so we can start building on Ubuntu 18.04 and reduce our overall pipeline costs.

https://github.com/chef/chef-server/blob/master/.expeditor/release.omnibus.yml#L15

## Definition of done

- [ ] Confirmed that no test scenarios rely on 16.04
- [ ] Remove from pipeline config
- [ ] Adhoc build passes
- [ ] PR to update Docs with new requirements

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/commit/919818b22d251a94366acfa55f45a8324c9d50eb - 14.3.0 onwards.
