### ISSUE TITLE
Amazon Linux 2 support

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2280]
We have Amazon Linux 2 builders/testers in Buildkite now and we should produce packages for Amazon Linux 2. Without a doubt folks are using the current EL7 packages on Amazon right now. We should just make it more official so it's clear that works.

The change would be the same as this line in chef/chef: https://github.com/chef/chef/blob/master/.expeditor/release.omnibus.yml#L34

**Comment by PrajaktaPurohit** [comment]
Agreed, that we should test the EL7 package on Amazon Linux 2.

**Comment by tas50** [comment]
Merged
