### ISSUE TITLE
Installing local packages is indeterminate if you have multiple packages of the same version in the install dir

### ISSUE THREAD

**Issue by tylercloke** [chef/chef-server#23]
Say you have `opscode-reporting_1.0.0.deb` and `opscode-reporting_1.0.1.deb`in a directory `/tmp`.

When running the local install command:

```
chef-server-ctl install opscode-reporting --path /tmp
```

it is indeterminate which will be installed. I think it just picks the first one it finds that matches the package regex.

We should probably have `--path` point to the actual package file, such as `--path /tmp/opscode-reporting_1.0.1.deb` instead of `--path /tmp` so we know which package is being used.

**Comment by stevendanna** [comment]
This is being worked on here: https://github.com/chef/chef-server/pull/173

**Comment by alexpop** [comment]
Opened pull request #340 with the code for this

**Comment by stevendanna** [comment]
Fixed by @alexpop in #340
