### ISSUE TITLE
chef-server-ctl restore is not working as expected.

### ISSUE THREAD

**Issue by Rajankumarprgrs** [chef/chef-server#2316]
### Chef Server Version
14.1.0
Standalone
### Platform Details
ubuntu-18.04

### Configuration

opscode_erchef['keygen_start_size'] = 30
opscode_erchef['keygen_cache_size']=60
nginx['ssl_dhparam']='/etc/opscode/dhparam.pem'
insecure_addon_compat false
data_collector['token'] = 'foobar' unless data_collector.nil?
profiles['root_url'] = 'https://localhost:9998' unless profiles.nil?
### Scenario

Trying to test backup and restore, but after applying backup few services are not getting started(runsv) 
### Steps to Reproduce
1.Spinning up an ec2 instance and installing chef-server
2.Creating user and org.
3.Taking backup(**sudo chef-server-ctl backup /var/opt/backup**)
4.Creating another instance and installing chef-server without user and orgs.
5.Applying the backup like **sudo chef-server-ctl restore  /tmp/chef-backup-2021-03-10-15-02-29.tgz**

### Expected Result
Restore should happen without any error.

### Actual Result
Users and org is getting restored in database but Getting below error during restoration :
null_resource.chef_server_config (remote-exec): ERROR:  role "oc_id_ro" already exists
null_resource.chef_server_config (remote-exec): ALTER ROLE
null_resource.chef_server_config (remote-exec): ERROR:  role "opscode-pgsql" already exists
null_resource.chef_server_config (remote-exec): ALTER ROLE
null_resource.chef_server_config (remote-exec): ERROR:  role "opscode_chef" already exists
null_resource.chef_server_config (remote-exec): ALTER ROLE
null_resource.chef_server_config (remote-exec): ERROR:  role "opscode_chef_ro" already exists
null_resource.chef_server_config (remote-exec): ALTER ROLE
null_resource.chef_server_config (remote-exec): ERROR:  database "bifrost" already exists
null_resource.chef_server_config (remote-exec): GRANT
null_resource.chef_server_config (remote-exec): ERROR:  database "oc_id" already exists
null_resource.chef_server_config (remote-exec): GRANT
null_resource.chef_server_config (remote-exec): ERROR:  database "opscode-pgsql" already exists
null_resource.chef_server_config (remote-exec): ERROR:  database "opscode_chef" already exists
null_resource.chef_server_config (remote-exec): GRANT
null_resource.chef_server_config (remote-exec): REVOKE
null_resource.chef_server_config (remote-exec): GRANT
null_resource.chef_server_config (remote-exec): You are now connected to database "bifrost" as user "opscode-pgsql".
null_resource.chef_server_config (remote-exec): SET

**On further debugging ....getting below error in the target instance:**

Running handlers:
Running handlers complete
Chef Infra Client failed. 150 resources updated in 20 seconds
[2021-03-10T16:19:05+00:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2021-03-10T16:19:05+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-03-10T16:19:05+00:00] FATAL: Chef::Exceptions::MultipleFailures: Multiple failures occurred:
* Mixlib::ShellOut::ShellCommandFailed occurred in Chef Infra Client run: runit_service[redis_lb] (private-chef::redis_lb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
STDOUT: fail: /opt/opscode/service/redis_lb: runsv not running
STDERR:
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/redis_lb returned 1
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: component_runit_service[bookshelf] (private-chef::bookshelf line 93) had an error: Mixlib::ShellOut::ShellCommandFailed: runit_service[bookshelf] (/var/opt/opscode/local-mode-cache/cookbooks/enterprise/resources/component_runit_service.rb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/bookshelf ----
STDOUT: fail: /opt/opscode/service/bookshelf: runsv not running
STDERR:
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/bookshelf ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/bookshelf returned 1
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: component_runit_service[opscode-erchef] (private-chef::opscode-erchef line 98) had an error: Mixlib::ShellOut::ShellCommandFailed: runit_service[opscode-erchef] (/var/opt/opscode/local-mode-cache/cookbooks/enterprise/resources/component_runit_service.rb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/opscode-erchef ----
STDOUT: fail: /opt/opscode/service/opscode-erchef: runsv not running
STDERR:
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/opscode-erchef ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/opscode-erchef returned 1
* Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: component_runit_service[nginx] (private-chef::nginx line 246) had an error: Mixlib::ShellOut::ShellCommandFailed: runit_service[nginx] (/var/opt/opscode/local-mode-cache/cookbooks/enterprise/resources/component_runit_service.rb line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
STDOUT: fail: /opt/opscode/service/nginx: runsv not running
STDERR:
---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx ----
Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/nginx returned 1

Aha! Link: https://chef.aha.io/features/SH-3039

**Comment by jashaik** [comment]
I have tried in the local dev VM, found that nginx,opscode-erchef,bookshelf and redis_lb services are not running after restoring the backup.Need to do more investigation for finding the rootcause. @PrajaktaPurohit @tas50

**Comment by sean-horn** [comment]
Reproduced at Progress as well.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/2476

**Comment by PrajaktaPurohit** [comment]
Related: https://github.com/chef/chef-server/issues/2496

**Comment by jashaik** [comment]
PR - #2504

**Comment by PrajaktaPurohit** [comment]
This fix should be available in 14.5 release of Chef Infra Server.
