### ISSUE TITLE
Getting 400 error while accessing the chef-server(chef-manage) after enabling mTLS

### ISSUE THREAD

**Issue by Rajankumarprgrs** [chef/chef-server#2318]
### Chef Server Version

chef-server 14.0.98
chef-client 16.10.17
OpenSSL 1.0.2y 

### Platform Details
Ubuntu 16.04.7 LTS
Ubuntu 18.04.5 LTS
Ubuntu 20.04

### Configuration
https://github.com/chef/umbrella/blob/master/chef-server/scenarios/aws/mtls/files/openssl_root_ca.cnf
https://github.com/chef/umbrella/blob/master/chef-server/scenarios/aws/mtls/templates/openssl_intermediate_ca.cnf.tpl
https://github.com/chef/umbrella/blob/master/chef-server/scenarios/aws/mtls/templates/chef-server.rb.tpl
https://github.com/chef/umbrella/blob/master/chef-server/scenarios/aws/mtls/templates/client-creds.tpl
https://github.com/chef/umbrella/blob/master/chef-server/scenarios/aws/mtls/templates/mutual_tls_config.sh.tpl

### Scenario
Testing of Infra Client communicating to Infra Server with mTLS enabled

### Steps to Reproduce

1.Enable mTLS using the above configs and try running knife commands on chef-server
2.Access chef-server web page after enabling mTLS

### Expected Result

1.Knife command should run on chef-server as well.
2.Chef-server's web page should be accessible.

### Actual Result
1.Getting “ERROR: The SSL certificate of ec2-34-219-229-167.us-west-2.compute.amazonaws.com could not be verified” on using knife commands in chef server after enabling mTLS

2.Getting 400 error while accessing the chef-server(chef-manage) after enabling mTLS

For more details refer https://github.com/chef/umbrella/issues/77

**Comment by PrajaktaPurohit** [comment]
This has been fixed with the 14.3 release of chef infra server. And added to the nightly and chef-server-full pipeline. Related umbrella PR:https://github.com/chef/umbrella/pull/110 and https://github.com/chef/umbrella/pull/111
