### ISSUE TITLE
Use version tags for chef in omnibus_override.rb

### ISSUE THREAD

**Issue by ramereth** [chef/chef-server#2359]
I recently noticed that this:

https://github.com/chef/chef-server/blob/96a9a9bcf344a8f30abf713007cfc8788a556d07/omnibus_overrides.rb#L9

Was changed to pointing to a branch instead of a specific tagged version. This change was made in #2228 and seems to be related to working around a build issue. This causes a few issues for community distributions since this doesn't lock the version to a specific commit or tag for chef. In addition, for users, this pulls in an unreleased version of Chef 15 which may have bugs or issues.

I have a few questions or suggestion:

1. Can we change this so that it points to a tagged released version of Chef?
2. When you update this to work on Chef 16 (and beyond), will you stick to pointing to the branch or will you go back to using tagged versions?

Thanks!

**Comment by PrajaktaPurohit** [comment]
You are correct, in that this was indeed some to mitigate a build issue. 
But it would indeed be good to point to a release version. 
We would like to get to a point where we need to deal with minimum pinning, but in the future as much as possible or as soon as possible we will try to move off the branch to a stable build.

I will pull this into our backlog to be looked at soon.

**Comment by PrajaktaPurohit** [comment]
Done! https://github.com/chef/chef-server/pull/2370 and https://github.com/chef/chef-server/pull/2378.  Should be fixed from version 14.2.13 of Chef Infra Server.
