### ISSUE TITLE
Node environment change not sticking

### ISSUE THREAD

**Issue by richardlock** [chef/chef-server#237]
chef-server 12.0.1-1
chef-client 12.2.1 through 12.3.0

Chef-client runs for some nodes seem to revert previous environment changes carried out using knife node edit or knife node environment set.  After the chef-client run completes, knife node show reports a different environment for the node.

**Comment by sdelano** [comment]
Hi @richardlock -

This behavior (last writer wins) has existed since the inception of the Chef Server. The problem exists because a `chef-client` run checks out the state of a node at the beginning of the run, and saves any modifications to that state at the end of a run. If you've modified the node state out-of-band during this time (e.g. via `knife node edit` or the Manage console), any changes you've made will be overridden.

This [accepted proposal](https://github.com/chef/chef-rfc/blob/master/rfc045-node_state_separation.md) in the `chef-rfc` repo will address the issue.

This is also tracked in our JIRA tracker [here](https://tickets.opscode.com/browse/CHEF-4978).

**Comment by richardlock** [comment]
Thanks Stephen.  This seems to be happening even when the knife node edit is completed before the chef-client run starts.  I will test again and see if our issue is different to the behaviour described above.

**Comment by joshoohaah** [comment]
Just ran into this  issue of my `knife environment set` commands being overwritten by the settings in the nodes `client.rb` file.    Is this because this issue is still open?

**Comment by gseac** [comment]
I just ran into this issue yesterday.  Does anyone know whether this has been resolved?

**Comment by richardlock** [comment]
As a workaround, I've been doing the following on affected nodes.  Basically, removing the environment line from client.rb while no chef-client processes were running.  One some nodes, the cause seemed to be a stale chef-client process.

```
sudo service chef-client stop
ps aux | grep -ie chef-client | awk '{print $2}' | sudo xargs kill -9
sudo /bin/sed -i -e '/^environment ".*"/d' /etc/chef/client.rb
sudo service chef-client start
sudo chef-client -E new_environment
```

**Comment by gseac** [comment]
Thanks Richard.  This seems to do the trick!

**Comment by joshoohaah** [comment]
another option that I used instead @richardlock and @gseac is to use the chef-client cookbook to manage the client.rb file  https://github.com/chef-cookbooks/chef-client.  I configured the settings when I deploy to 'omit' the environment setting in the `client.rb` file then.  This way you don't have to run any scripts outside of the chef run.  PLUS, that chef-client cookbook deploys a bunch of goodness as well.

**Comment by richardlock** [comment]
Thanks Joshua.  We use the chef-client cookbook to manage some other settings, but I didn't realise you could omit the environment setting in the client.rb file.  Not all of our client.rb files have the environment line, so I'm not sure if it was dropped in a later chef-client version.  I will try configuring that setting as it will save us some pain with environment moves.

**Comment by joshoohaah** [comment]
great @richardlock. yes I had the exact same use case as 'some had it ' and 'some did not'.  having chef-client cookbook manage it and handle that use case.  You can either have your own custom client.rb.erb 
template that you use and have your recipe point to...
```
include_recipe 'chef-client::config'
resources("template[#{node['chef_client']['conf_dir']}/client.rb]").cookbook '<your cookbook name>'
```
Or you can specify in your attributes of your cookbook to clear out the environment value like so:
` default['chef_client']['config']['environment'] = nil`

**Comment by richardlock** [comment]
Great - thanks for your help @joshoohaah.

**Comment by richardlock** [comment]
No longer needed.
