### ISSUE TITLE
spike: chef-server use omnibus software definitions where possible.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2384]
As a chef-developer I would like to be able to use the standard software definitions where available instead of using the local ones.

This will reduce the maintenance overhead and new user confusion. It will also help the internal tooling (unless it needs to be modified) to keep track of various versions of software being used.

Chef server currently uses the following from local omnibus/config/software: (There might be more)
- postgresql
- elasticsearch (Elasticsearch for chef-server does not build some of the modules like geoip, x-pack)

Spike on
1. if that is for a reason - that needs to be documented.
2. use the omnibus-software/config/software definitions where possible.

Aha! Link: https://chef.aha.io/features/SH-3056

**Comment by tas50** [comment]
For both of these we're doing slightly different things at this point so it probably makes the most sense for us to maintain our own code.
