### ISSUE TITLE
Bootstrapped node data does not get added to elasticsearch

### ISSUE THREAD

**Issue by gscho** [chef/chef-server#2387]
### Chef Server Version

14.0.58

### Platform Details

centos 7

### Configuration

Standalone

### Scenario

Newly bootstrapped node data is not ingested into elasticsearch causing `knife search` and `knife status` commands to not return any results. The nodes are however added successfully to postgresql and `knife node show` works as expected.

### Steps to Reproduce

Not sure how to reproduce this problem.

### Expected Result

The expectation that knife commands that rely on elasticsearch data work properly, namely `knife status`, `knife search`, and `knife ssh`

### Actual Result

The node data is present in postgresql but not in elasticsearch.

### Troubleshooting Steps Taken

To try and resolve this issue, we have performed a `chef-server-ctl reindex <org> -d -t -w` which ran successfully but did not solve the issue.

We also tried setting  `opscode_erchef['search_queue_mode'] = 'inline'` but this also had no effect.

**Comment by gscho** [comment]
Just in case others run into this issue, it was due lack of disk space. There was ~25% of the disk remaining but during a backup the size grew too large and the elasticsearch high disk watermark was reached.

**Comment by tas50** [comment]
This will be partially addressed in the 14.3 release which includes checks for free disk space before the reindex runs.
