### ISSUE TITLE
Provide rabbitmq management commands for debugging and repair

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#239]
Currently, our support team is manually enabling rabbitmq management plugins and walking the user through management tasks.  An example of the type of procedures they use can be found here:

https://github.com/chef/support-docs/blob/master/server/data/rabbitmq.md#rabbitmqadmin

(sorry for the private link for non-Chef Software employees).  The analytics team is working on commands:

https://github.com/chef/omnibus-analytics/pull/208

for the most common operations.  However, those won't help if the Analytics machine has crashed or if they need to manage queues that analytics does know about.

The Chef Server should provide the tools people need to recover when things have gone wrong (even though we try to make sure they don't go wrong).

Possible solutions include:
- Enabling the rabbitmq management plugins to make support procedures easier/faster,
- Porting over the commands  from analytics to chef-server-ctl 

See also the related issue https://github.com/chef/chef-server/issues/103

**Comment by stevendanna** [comment]
Closing as I believe this was solved in 60fc1595. @sean-horn @jeremiahsnapp Do you agree that the core issues here are covered by Dave's work? If not, what do we still ned to handle.

**Comment by jeremiahsnapp** [comment]
👍
