### ISSUE TITLE
Unable to remove users from Admin Group

### ISSUE THREAD

**Issue by afiune** [chef/chef-server#24]
Unable to remove a user from the admin's group, (at least from the WebUI) it does not say something but the following data base conflict:

![screen shot 2014-11-14 at 2 15 30 pm](https://cloud.githubusercontent.com/assets/5712253/5052731/d3b31cde-6c08-11e4-96c6-59d9d68a9967.png)

** Sorry for the log as an attachment. There is no way I can get the logs from the client. Super secure data center.

Running on:
 * Chef-Server 12 rc.5
 * RHEL 6.5

**Comment by stevendanna** [comment]
@afiune Is this something you still need help with?

**Comment by afiune** [comment]
Yes and no. Yes I need help but I guess the answer is to upgrade the chef-server. Am I wrong?

**Comment by sdelano** [comment]
@afiune Is this still an issue?

**Comment by afiune** [comment]
@stevendanna nope.. all good! Thanks
