### ISSUE TITLE
Test FIPS mode on ubuntu in the umbrella pipeline.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2415]
Currently Chef Infra Server supports FIPS only on Centos. From release 14.3 onwards we will also support FIPS on Ubuntu.

Umbrella pipeline has a scenario for testing FIPS. This can be used to test FIPS only with RHEL at this time.
REF: https://github.com/chef/umbrella/tree/master/chef-server/scenarios/aws/fips

The adhoc build does not test FIPS : https://github.com/chef/chef-server/blob/master/omnibus/omnibus-test.sh#L64 that is always set to false.

Chef if we can identify the distribution and enable FIPS accordingly or add different scenario to test for FIPS on Ubuntu.

Acceptance Criteria:
1. Umbrella pipeline has support for FIPS on ubuntu.
2. The nightly pipeline run enables FIPS on ubuntu test.
3. The server-full pipeline enables FIPS on ubuntu test.

Aha! Link: https://chef.aha.io/features/SH-3016

**Comment by PrajaktaPurohit** [comment]
Verified the openssl included FIPS (by @tas50 )
```
# An openssl config that enables FIPS by default
openssl_conf = openssl_conf_section
[openssl_conf_section]
alg_section             = evp_sect
[evp_sect]
fips_mode = yes
```
And were are able to reconfigure chef-server on that box.

**Comment by tas50** [comment]
Since we'd need to pay for FIPS support in Ubuntu I think we can probably close this one out as a won't fix for now
