### ISSUE TITLE
chef-server-ctl reconfigure should fetch trusted certs if mtls is enabled.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2426]
If a user has enabled mtls on Chef Infra Server. They will need to fetch the certs using 
```
# export PATH=/opt/opscode/embedded/bin:$PATH
# /opt/opscode/embedded/bin/knife ssl fetch -c /etc/opscode/pivotal.rb
```
Reconfigure should auto fetch these for the user if mtls is enabled.

Notes:
https://github.com/chef/umbrella/blob/main/chef-server/scenarios/aws/mtls/main.tf#L175-L176 
in the umbrella scenario perform these manual steps. 

The way to find if mtls is enabled:
is if https://github.com/chef/chef-server/blob/main/omnibus/files/server-ctl-cookbooks/infra-server/attributes/default.rb#L526-L528 have a value other than false

It might be worth adding the check to see of the above attributes are false at https://github.com/chef/chef-server/blob/main/omnibus/files/server-ctl-cookbooks/infra-server/recipes/default.rb#L177
If they are false => mtls not enable and do nothing
if they are not false => mtls enabled and we should fetch the certs (https://github.com/chef/umbrella/blob/main/chef-server/scenarios/aws/mtls/main.tf#L176)

Acceptance criteria:
- [x] chef-server-ctl user-list command should work out of the box when mtls is enabled on Chef Infra Server.
- [x] chef-server-ctl commands should all work after the reconfigure.
- [x] we should not require https://github.com/chef/umbrella/blob/main/chef-server/scenarios/aws/mtls/main.tf#L175-L176 after the fix is in place.

Aha! Link: https://chef.aha.io/features/SH-3025

**Comment by lbakerchef** [comment]
```
[0m[1mnull_resource.mutual_tls_config (remote-exec):[0m [0mBEGIN USER LIST TEST
[0m[1mnull_resource.mutual_tls_config (remote-exec):[0m [0msudo chef-server-ctl user-list
[0m[1mnull_resource.mutual_tls_config (remote-exec):[0m [0m+ sudo chef-server-ctl user-list
[0m[1mnull_resource.mutual_tls_config (remote-exec):[0m [0mpivotal
[0m[1mnull_resource.mutual_tls_config (remote-exec):[0m [0mecho -e '
[0m[1mnull_resource.mutual_tls_config (remote-exec):[0m [0mEND USER LIST TEST
```
