### ISSUE TITLE
More configurable log levels

### ISSUE THREAD

**Issue by smith** [chef/chef-server#245]
# Why

The Rails defaults for logging to standard output are not very flexible and difficult to configure at runtime. For example, in #235, we have to do a hack to get some output from a command, where we should just be able to turn off logging while running that command with an environment variable.
# Acceptance Criteria

https://github.com/heroku/rails_stdout_logging is installed and configured; the user can set the log level in the configuration file (for the output when the service is running) and using an environment variable (for when running commands from the console.)

**Comment by PrajaktaPurohit** [comment]
Closing this as a won't fix for now.
