### ISSUE TITLE
chef-server-reconfigure does not bounce rabbitmq after making changes to chef-server.rb

### ISSUE THREAD

**Issue by vinyar** [chef/chef-server#247]
**Scenario:**

Install chef-server deb (12.0.8) on backend
run chef-server-ctl reconfigure
setup chef-server.rb for tiered or ha config
run chef-server-ctl reconfigure
Setup front end
front end will fail to connect to backend until rabbitmq is bounced separately, following the post chef-server reconfigure.

**Troubleshooting:**
test if rabbitmq is listening (post second reconfigure)
telnet 172.21.20.181 5672 (false)
telnet localhost 5672 (true)

test if rabbitmq is listening (post second reconfigure and manual rabbitmq bounce)
telnet 172.21.20.181 5672 (true)
telnet localhost 5672 (true)

**Expected behavior:**
making changes to cher-server.rb should bounce necessary services to make services work.
In this scenario, rabbitmq should be bounced when chef-server config is changes from standalone to tiered or ha.

**Example of a workaround:**
https://github.com/opscode-cookbooks/chef-server-cluster/blob/master/recipes/bootstrap.rb#L76-L87

(originally opened in https://github.com/chef/chef/issues/3361)

**Comment by stevendanna** [comment]
We likely need notifications on these two resources:

https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/recipes/rabbitmq.rb#L61-L75

This would be a good issue for someone looking for a first contributions to the chef-server/omnibus

**Comment by vinyar** [comment]
Still hitting this with customers, especially in the HA config.
Get ready for a PR :+1:

**Comment by PrajaktaPurohit** [comment]
This might have been fixed with the upgrade for the runit cookbook in release 13.0.17 of Chef Infra Server. Closing this for now, since we will be removing install of rabbitmq in the near future. (Once we move from Solr to Elasticsearch)
