### ISSUE TITLE
Additional Policyfile APIs for Automate

### ISSUE THREAD

**Issue by kalroy** [chef/chef-server#2480]
Work that's been identified for future additional features in Automate around Infra Policyfiles, which is tracked in chef/automate#5826.

This is out of scope and not planned at this time.

**Comment by tas50** [comment]
@kalroy Can we get a timeline for when this work needs to be done and what the priority of this work is for Automate?

**Comment by PrajaktaPurohit** [comment]
The information that is required for each revision is available in the db and can be extracted with `select policy_group_name from policy_revisions_policy_groups_association where policy_revision_revision_id='REVISION_ID';`

While building the response for GET in to_json https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/oc_chef_wm/src/oc_chef_wm_named_policy.erl#L111 for each revision update the group information extracted by the above query.

@kalroy : is there an option to hit the /organizations/NAME/policies/POLICY_NAME/revisions/REVISION_ID endpoint to get the groups associated with a respective REVISION_ID?

**Comment by tas50** [comment]
Replaced with https://chefio.atlassian.net/browse/INFS-75
