### ISSUE TITLE
Builds failing with 500s from Artifactory

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2486]
https://buildkite.com/chef/chef-chef-server-master-omnibus-release/builds/414#30602597-bde0-404f-a691-1a877429580e

**Comment by tas50** [comment]
1 hr on the server side

**Comment by anandhapadmanabhan** [comment]
We had an issue with artifactory disk usage, the old artifacts were not removed during the earlier artifactory issue around May 10th. The old artifacts are now cleared and we should be good to do go. 
20Mins spent on relops side
