### ISSUE TITLE
Automate 2 Embedded Chef Infra Server Failed Org Reindexing

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#2518]
**Describe the bug**

----------------------------------------------

When I try to reindex an Automate 2 embedded Chef Server's org, the attempted reindex fails

**To Reproduce**

* Install https://docs.chef.io/automate/infra_server/#command-line-install-of-chef-automate-and-infra-server
* Create a user and org following steps 5. and 6. here https://docs.chef.io/server/install_server/#standalone

         chef-server-ctl user-create janedoe Jane Doe janed@example.com 'abc123' --filename janedoe.pem
         chef-server-ctl org-create testit 'Testingit' --association_user janedoe --filename testit-validator.pem

* Notice on the Automate system's command line that I can view the user and org, like this

         # chef-server-ctl org-list
         testit

        # chef-server-ctl user-list
        janedoe
        pivotal
         
* Try a reindex

         # chef-server-ctl reindex testit
         /hab/pkgs/chef/chef-server-ctl/14.1.0/20210225010004/vendor/bundle/gems/bundler- 
         1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
         Reindexing orgs: ["testit"]
         - Reindexing.
         escript: exception error: no match of right hand side value
                 {ok,"400",
                     [{"Server","openresty"},
                      {"Date","Thu, 29 Apr 2021 19:41:14 GMT"},
                      {"Content-Type","text/html"},
                      {"Content-Length","250"},
                      {"Connection","close"}],
                     "<html>\r\n<head><title>400 No required SSL certificate was sent</title></head>\r\n<body 
         bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>No required SSL certificate was 
         sent</center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n"}
         Failed to reindex data for testit!         

**Expected behavior**

The testit org's search index is dropped and reindexed from the postgresql content and is searchable afterwards

**Actual behavior**

```
         # chef-server-ctl reindex testit
         /hab/pkgs/chef/chef-server-ctl/14.1.0/20210225010004/vendor/bundle/gems/bundler- 
         1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
         Reindexing orgs: ["testit"]
         - Reindexing.
         escript: exception error: no match of right hand side value
                 {ok,"400",
                     [{"Server","openresty"},
                      {"Date","Thu, 29 Apr 2021 19:41:14 GMT"},
                      {"Content-Type","text/html"},
                      {"Content-Length","250"},
                      {"Connection","close"}],
                     "<html>\r\n<head><title>400 No required SSL certificate was sent</title></head>\r\n<body 
         bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>No required SSL certificate was 
         sent</center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n"}
         Failed to reindex data for testit!]
```

In the `chef-automate system-logs` output during this attempted operation, we see this

```
Apr 29 19:58:42 automate-deployment.test hab[1336]: automate-cs-nginx.default(O): 127.0.0.1 - - [29/Apr/2021:19:58:42 +0000]  "GET /_route/organizations/testit HTTP/1.1" 400 "0.000" 250 "-" "-" "-" "-" "-" "-" "-" "-" "-" "-" 87
```

This appears to correlate to line 149 on the system

```
# grep -n Headers /hab/pkgs/chef/oc_erchef/14.1.0/20210225010013/bin/reindex-opc-organization
149:    {ok, "200", _Headers, Body} = rpc:call(?ERCHEF, ibrowse,send_req, [IntLB ++ "/_route/organizations/" ++ OrgName, [], get]),
153:    Headers = string:join(lists:map(fun({Key, Val}) -> binary_to_list(Key) ++ "=" ++ integer_to_list(Val) end, KVList), ";"),
154:    rpc:call(?ERCHEF, xdarklaunch_req,parse_header, [ fun(_) -> Headers end]).
```

and in https://github.com/chef/chef-server/blob/39fb0a3358cbd9e05d76f36dccc55e7024a67808/src/oc_erchef/priv/reindex-opc-organization#L149

## Versions (please complete the following information):
- OS: RHEL 7
- Automate Build Number 20210420090302

**Additional context**

`chef-automate version` output from the Automate 2 system

```
# chef-automate version
Version: 2
  CLI Build: 20210416180743
  Server Build: 20210420090302
```

`chef-automate service-versions` from the Automate 2 system

```
# chef-automate service-versions
chef/backup-gateway 0.1.0 20210225022012
chef/automate-postgresql 9.6.11 20200929122522
chef/automate-pg-gateway 0.0.1 20201223040715
chef/automate-elasticsearch 6.8.14 20210309060053
chef/automate-es-gateway 0.1.0 20210305110358
chef/automate-ui 2.0.0 20210420085155
chef/pg-sidecar-service 0.0.1 20210225021936
chef/cereal-service 0.1.0 20210225021803
chef/event-service 0.1.0 20210225021907
chef/authz-service 0.1.0 20210309055746
chef/es-sidecar-service 1.0.0 20210225021453
chef/event-feed-service 1.0.0 20210309055746
chef/automate-dex 0.1.0 20210225021933
chef/teams-service 0.1.0 20210225021851
chef/authn-service 0.1.0 20210225021956
chef/secrets-service 1.0.0 20210225021851
chef/applications-service 1.0.0 20210225021849
chef/notifications-service 1.0.0 20210225021720
chef/nodemanager-service 1.0.0 20210415102807
chef/compliance-service 1.11.1 20210415102807
chef/license-control-service 1.0.0 20210225021855
chef/local-user-service 0.1.0 20210225021453
chef/session-service 0.1.0 20210225021851
chef/config-mgmt-service 0.1.0 20210309055742
chef/ingest-service 0.1.0 20210309055742
chef/infra-proxy-service 0.1.0 20210419015943
chef/data-feed-service 1.0.0 20210309055742
chef/event-gateway 0.1.0 20210225021924
chef/automate-gateway 0.1.0 20210419015946
chef/automate-cs-bookshelf 14.1.0 20210305102850
chef/automate-cs-oc-bifrost 14.1.0 20210305102849
chef/automate-cs-oc-erchef 14.1.0 20210305102850
chef/automate-cs-nginx 14.1.0 20210305102850
chef/automate-load-balancer 0.1.0 20201125093110
chef/deployment-service 0.1.0 20210416180743
```

Aha! Link: https://chef.aha.io/epics/SH-E-312

**Comment by PrajaktaPurohit** [comment]
Fixed with https://github.com/chef/chef-server/pull/3390 and available from 15.6.1 of Infra Server release.
