### ISSUE TITLE
Load Testing of PostgreSQL Upgrade 9.6 -> 13.3

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#2520]
Testing is needed to quantify how long migration actually takes during an upgrade from PostgreSQL 9.6 to 12.x, presumably under some kind of load and/or with a lot of data.

Some basic metrics to give to customers for postgres upgrade from 9.6 -> 12.5, e.g. if 200gb data, this is how long it will take, if 100gb, this is how long, etc.

Questions:

1) Dumb question: Are we testing an upgrade from chef-server version whatever, to lbaker/postgres12.5 (which includes a postgresql upgrade in most scenarios)?  Or are we just taking postgresql 9.6 and upgrading to 12.5 (no chef-server)?

2) Is this for a particular scenario, e.g. external postgres, or for all?

3) Are we just measuring time, or is there anything else?

A few things Prajakta mentioned, from my notes:
some basic metrics to give customers

can you keep hitting endpoint while migration takes place?

chef-load in Umbrella has a way to generate data.

For context, see:
https://github.com/chef/chef-server/pull/2380
https://github.com/chef/umbrella/pull/123

May be useful:
https://github.com/chef/chef-load
I can try to set up a meeting with someone who can walk us through this.

**Comment by PrajaktaPurohit** [comment]
Closing in favor of #2521, #2522, #2536 and #2537
