### ISSUE TITLE
[pg_upgrade] Impact Study of PostgreSQL Upgrade 9.6 -> 12.5 on Disk space / Memory and Time taken

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#2522]
Some basic metrics to give to customers for postgres upgrade from 9.6 -> 12.5

What are the disk space constraints?
- Min and Max disk space required to complete a successful upgrade to Pg 13. 
- Include the space requirements for backup? (maybe)
- for the upgrade
- for the vacuum full
- for reindex? (if needed)

- Should the disk space check be modified: https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/providers/pg_upgrade.rb#L148 based on the new data? Or to be atleast 1.1 times more than the existing db?

Document the reason we chose to not use the --link option

How much memory will it take without hanging?
for 5k clients doing simple checkins - m5.xlarge would be the recommendation.

NOTES: (As discussed with @vinay-satish and @PrajaktaPurohit )
- Use umbrella pipeline for setup of chef-load and add additional nodes to generate more data as required.
(https://github.com/chef/chef-load)

For context, see:
https://github.com/chef/chef-server/pull/2380
https://github.com/chef/umbrella/pull/123

Acceptance Criteria:
1. We can recommend min and max disk space required for the upgrade to Postgres 13.
2. We have documentation clearly defining the recommendation.

**Comment by PrajaktaPurohit** [comment]
REF: https://docs.google.com/document/d/1x9KhJg-4PrpUOgBPiDckosYHtO3v1T6ntao928KTgPM/edit

**Comment by vinay-satish** [comment]
Testing steps
1 get a system with chef-server upgraded to 14.5.29 version
2 load some data
   du -hs /var/opt/opscode/postgresql/9.6/data
      1.1G  /var/opt/opscode/postgresql/9.6/data
   select count(*) from nodes;
      56745
   SELECT pg_size_pretty( pg_database_size('bifrost') );
      706 MB
   SELECT pg_size_pretty( pg_database_size('opscode_chef') );
      105 MB
   SELECT pg_size_pretty( pg_database_size('oc_id') );
      7367 kB
3 Take backup
   time chef-server-ctl backup --yes
      real  1m33.441s
      user  1m18.109s
      sys   0m6.419s
   du -hs /var/opt/chef-backup/chef-backup...
      278M  /var/opt/chef-backup/chef-backup-2021-07-05-12-00-59.tgz
4 Pg backup
   mkdir /tmp/opt-opscode-embedded-postgresql
   time mv --verbose /opt/opscode/embedded/postgresql/* /tmp/opt-opscode-embedded-postgresql
   du -hs /tmp/opt-opscode-embedded-postgresql
      45M   /tmp/opt-opscode-embedded-postgresql
5 Upgrade
   time curl -vo /tmp/chef-server.deb https://packages.chef.io/files/unstable/chef-server/14.5.31+20210629073633/ubuntu/18.04/chef-server-core_14.5.31+20210629073633-1_amd64.deb
      real  0m8.751s
      user  0m0.223s
      sys   0m0.517s
   du -hs /tmp/chef-server.deb
      218M  /tmp/chef-server.deb
   time dpkg -iEG /tmp/chef-server.deb
      real  0m30.824s
      user  0m23.859s
      sys   0m8.740s
   time cp --force --recursive --verbose /tmp/opt-opscode-embedded-postgresql/* /opt/opscode/embedded/postgresql
      real  0m1.376s
      user  0m0.023s
      sys   0m0.214s
   time CHEF_LICENSE='accept' chef-server-ctl upgrade
      real  1m22.932s
      user  0m20.805s
      sys   0m5.682s
   time chef-server-ctl start
      real  0m3.796s
      user  0m0.713s
      sys   0m0.137s
   time chef-server-ctl cleanup
      real  0m6.937s
      user  0m4.840s
      sys   0m0.842s
6 Restore
   time chef-server-ctl restore /var/opt/chef-backup/chef-backup... --cleanse
      real  0m12.668s
      user  0m10.480s
      sys   0m3.189s
   du -hs /var/opt/opscode/postgresql/12.5/data
      871M  /var/opt/opscode/postgresql/12.5/data/
   select count(*) from nodes;
      56745
   SELECT pg_size_pretty( pg_database_size('bifrost') );
      707 MB
   SELECT pg_size_pretty( pg_database_size('opscode_chef') );
      105 MB
   SELECT pg_size_pretty( pg_database_size('oc_id') );
      7913 kB

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/wiki/Postgres-Upgrade-13.3
