### ISSUE TITLE
[pg_upgrade] VACUUM FULL and Analyze

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2536]
Vacuum Analyze (Document only no changes in omnibus upgrade code)

How much additional (memory) and disk space is required for Vacuum Full?

What recommendations can we give for the Analyze commands:

Quick but blocking: $BINDIR/vacuumdb --all --analyze-only
Slow but non-blocking: $BINDIR/vacuumdb --all --analyze-in-stages

Acceptance Criteria:
1. We can recommend the minimum and max disk space and time required for Vacuum Full
2. We can recommend / give pros and cons with time taken for the analyze command to be run after migration.
3. Updated documentation for Vacuum and Analyze command recommendations.

**Comment by jashaik** [comment]
**Investigation Report**
Data directory size – 1.3GB

**Vacuum Full:**
command: ./vacuumdb --all –full

Disk Analysis:
1. the system will first create an AccessExclusiveLock on the target, which does not allow outside access (preparation for later copy), and then create a new table with the same table structure as the target table.
2. Scan the target table and copy the live tuples from the table to the new table.
3. Delete the target table, recreate the index on the new table, update the VM, FSM and statistical information, related system tables, etc.

Minimum Disk space:  Size of data directory * 2
Maximum Disk space: No Limitations
Time:  26 Seconds

**Analyze:**
Commands: 
Blocking: ./vacuumdb --all --analyze-only
Non Blocking: ./vacuumdb --all --analyze-in-stages
Time: 15 seconds

Analyze gathers statistics for the query planner to create the most efficient query execution paths. Accurate statistics will help the planner to choose the most appropriate query plan, and thereby improve the speed of query processing.

If the customer system should be handled the requests while doing the analyze then they can go with ‘analyze-in-stages’ option else ‘analyze-only’ can be a good choice.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/wiki/Postgres-Upgrade-13.3
