### ISSUE TITLE
[pg_upgrade] Document the upgrade process for / after migrating to Postgres 13.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2541]
Document the steps for the upgrade to Chef Infra Server to the version with Postgres 13.2:
1. Internal postgres:
- Test Backup and restore?
- What are the steps that the installer will take care of?
- What steps do the users need to run manually?
- What is the order in which to run them, what can run concurrently
- When can the API come back up?

2. External Postgres:
The chef omnibus installer does not upgrade the external postgres. It will be useful to write the guidelines of what an omnibus installed external upgrade will look like.
- Test backup and restore?
- What are the steps the installer will take care of?
- What does the server expect the state of the db to be before enabling the services. (steps to be run on the postgres database after the upgrade, vacuum full, analyze and reindex)
- When can the API come back up? Can we do it as soon as the migration/vacuum is complete?

See: https://github.com/chef/chef-server/pull/2706

# Standalone Scenario

1. It is strongly recommended to run vacuum full before starting the upgrade.
   ```
   $ sudo su postgres
   $ cd /opt/opscode/embedded/postgres/<version>/bin/
   $ /usr/bin/vacuumdb --all --full
   $ exit
   ```

1. Consult the documentation on `chef-server-ctl backup`.
https://docs.chef.io/server/server_backup_restore/

   Backup the database.  **MAKE A NOTE OF WHERE THE BACKUP WAS PLACED** (normally under /var/opt/chef-backup).  Please note that chef-server will go offline t
o perform the backup.
   Example:

   `$ sudo chef-server-ctl backup`

1. If you are running chef-server version 12.17.15 or greater, **SKIP THIS STEP** and proceed to step X below.  Otherwise, consult the documentation on upgrad
ing Chef Infra Server.
   https://docs.chef.io/server/upgrades/

   If you are running a chef-server release prior to 12.17.15, you cannot upgrade directly to 14.8.X.  You must perform a stepped upgrade first.

   - If you are running chef-server 12.3.0, you must first upgrade 12.17.15.
   - If you are running chef-server 11, you must first upgrade to 12.3.0, and then to 12.17.15.

   After performing the stepped upgrade, return here and continue with step X below.

1. Download the chef-server version 14.8.X upgrade package.
https://downloads.chef.io/tools/infra-server

1. Stop services.

   `$ sudo chef-server-ctl stop || sudo chef-server-ctl kill rabbitmq`

1. Install the chef-server 14.8.X package.

   dpkg:
   `$ sudo dpkg -iEG /path/to/chef-server-core-<version>.deb`

   rpm:
   `$ sudo rpm -U /path/to/chef-server-core-<version>.rpm`

1. Upgrade chef-server.

   `$ sudo CHEF_LICENSE='accept' chef-server-ctl upgrade`

1. If the upgrade failed, SKIP THIS STEP and continue at step X below.
If the upgrade was successful, start services, cleanup, and reindex the database.
   ```
   $ sudo chef-server-ctl start
   $ sudo chef-server-ctl cleanup
   $ sudo /usr/bin/reindexdb --all
   ```
   You are now finished with the chef-server upgrade.  **DO NOT PROCEED FURTHER.**

1. If the upgrade failed, and you are left with a corrupted chef-server and/or corrupted database, it is strongly recommended that you **DO NOT UNDER ANY CIRC
UMSTANCES RISK YOUR BACKUP OF THE DATABASE.**  You should take any and all steps in order to preserve the backup, including copying it to another disk.  Consu
lt with a professional sysadmin for instructions, best practices, etc.

1. Contact customer support.
1. Reinstall the original version of chef-server you were using before attempting the upgrade process (if you had to perform a stepped upgrade, install your o
riginal version of chef-server before the stepped upgrade, not any versions you upgraded to in the stepped upgrade process).  Again, it is recommended that yo
u **DO NOT RISK YOUR BACKUP OF THE DATABASE.**  For instance, consider using a separate disk from your backup for the new installation.

   Download link for chef-server:
   https://docs.chef.io/server/install_server/

   Installation instructions for chef-server:
   https://docs.chef.io/server/install_server/

1. Consult the documentation on restore, and restore the database from the path where it was previously saved.
https://docs.chef.io/server/server_backup_restore/

   Example:
   `chef-server-ctl restore /var/opt/chef-backup/chef-backup-2021-06-11-18-59-19.tgz`

# External PostgreSQL Scenario

**Vacuum the PostgreSQL database**

1. Log into the external PostgreSQL machine.

1. Run vacuum full.  Example:
   ```
   $ sudo su postgres
   $ /usr/bin/vacuumdb --all --full
   vacuumdb: vacuuming database "bifrost"
   vacuumdb: vacuuming database "oc_id"
   vacuumdb: vacuuming database "opscode_chef"
   vacuumdb: vacuuming database "postgres"
   vacuumdb: vacuuming database "template1"
   $ exit
   ```
**Backup the PostgreSQL database**

1. Log into the chef-server machine.

1. Consult the documentation on `knife-ec-backup`.
   https://blog.chef.io/migrating-chef-server-knife-ec-backup-knife-tidy

   If it is not already installed, install `knife-ec-backup`.  A sample session follows
   (note that your steps could differ, depending on the versions of your software,
   the topology of your setup, your OS and distrubition, and a range of other factors).
   Example:
   ```
   $ apt-get update
   $ apt install ruby
   $ apt install make
   $ curl -L https://chef.io/chef/install.sh | sudo bash -s -- -P chefdk
   $ export PATH=$PATH:/root/.chefdk/gem/ruby/2.6.0/bin
   $ apt-get -y install gcc postgresql libpq-dev
   $ /opt/chefdk/embedded/bin/gem install knife-ec-backup -- --with-pg-config=/opt/opscode/embedded/postgresql/9.6/bin/pg_config
   ```
1. If it is not already configured, configure knife.  A sample session follows (again, note that your steps could differ, depending on a range of factors).
   Example:
   ```
   $ chef-server-ctl org-create 4thcafe 'Fourth Cafe, Inc.' --association_user janedoe --filename /tmp/4thcafe-validator.pem
   $ chef generate repo chef-repo
   $ cd chef-repo/
   $ mkdir -p .chef
   $ echo '.chef' >> .gitignore
   $ cp /tmp/4thcafe-validator.pem .chef
   $ cp /home/ubuntu/janedoe.pem .chef
   $ cd .chef
   $ knife configure
   WARNING: No knife configuration file found. See https://docs.chef.io/config_rb/ for details.
   Please enter the chef server URL: [https://1.2.3.4/organizations/myorg] https://1.2.3.4/organizations/4thcafe
   Please enter an existing username or clientname for the API: [ubuntu] janedoe
   $ knife ssl fetch
   ```
1. Backup the database.
   Example:
   ```
   $ mkdir /backup
   $ /opt/chefdk/embedded/bin/knife ec backup /backup
   ```
**Upgrade Chef Infra Server**

1. If you are running chef-server version 12.17.15 or greater, **SKIP THIS STEP** and proceed to step X below.  Otherwise, consult the documentation on upgrad
ing Chef Infra Server.
   https://docs.chef.io/server/upgrades/

   If you are running a chef-server release prior to 12.17.15, you cannot upgrade directly to 14.8.X.  You must perform a stepped upgrade first.

   - If you are running chef-server 12.3.0, you must first upgrade 12.17.15.
   - If you are running chef-server 11, you must first upgrade to 12.3.0, and then to 12.17.15.

   After performing the stepped upgrade, return here and continue with step X below.

1. Download the chef-server version 14.8.X upgrade package.
https://downloads.chef.io/tools/infra-server

1. Stop services.
   `$ sudo chef-server-ctl stop || sudo chef-server-ctl kill rabbitmq`

1. Install the chef-server 14.8.X package.

   dpkg:
   `$ sudo dpkg -iEG /path/to/chef-server-core-<version>.deb`

   rpm:
   `$ sudo rpm -U /path/to/chef-server-core-<version>.rpm`

1. Upgrade chef-server.

   `$ sudo CHEF_LICENSE='accept' chef-server-ctl upgrade`

1. IF THE UPGRADE WAS SUCCESSFUL, start services and cleanup.
   ```
   $ sudo chef-server-ctl start
   $ sudo chef-server-ctl cleanup
   ```
   You are now finished with the chef-server upgrade.  Proceed directly to the Upgrade PostgreSQL section.

1. **IF THE UPGRADE FAILED**, and you are left with a corrupted chef-server and/or corrupted database,
    it is strongly recommended that you DO NOT UNDER ANY CIRCUMSTANCES RISK YOUR BACKUP OF THE DATABASE.
    You should take any and all steps in order to preserve the backup, including copying it to another disk.

1. If the upgrade failed, and you are left with a corrupted chef-server and/or corrupted database, it is strongly recommended that you DO NOT UNDER ANY CIRCUM
STANCES RISK YOUR BACKUP OF THE DATABASE.  You should take any and all steps in order to preserve the backup, including copying it to another disk.  Consult w
ith a professional sysadmin for instructions, best practices, etc.

1. Contact customer support.
1. Reinstall the original version of chef-server you were using before attempting the upgrade process (if you had to perform a stepped upgrade, install your o
riginal version of chef-server before the stepped upgrade, not any versions you upgraded to in the stepped upgrade process).  Again, it is recommended that yo
u DO NOT RISK YOUR BACKUP OF THE DATABASE.  For instance, consider using a separate disk from your backup for the new installation.

   Download link for chef-server:
   https://docs.chef.io/server/install_server/

   Installation instructions for chef-server:
   https://docs.chef.io/server/install_server/

1. Consult the documentation on knife-ec-restore, and restore the database from the path where it was saved previously.
   https://blog.chef.io/migrating-chef-server-knife-ec-backup-knife-tidy

   Example:
`$ /opt/chefdk/embedded/bin/knife ec restore /backup/`

1. Do not proceed further until you have an uncorrupted Chef Server upgraded to version X.Y.Z,
   and an uncorrupted PostgreSQL database.

**Upgrade PostgreSQL**

1. Log into the external PostgreSQL machine.

1. Update packages and install PostgreSQL 13.3.
   Example (Ubuntu):
   ```
   $ sudo apt-get update
   $ sudo apt-get install postgresql-13
   ```

1. Check if there are any differences in the config files.  Make sure to update the new config files if required.
   ```
   $ diff /etc/postgresql/<old-pg-version>/main/postgresql.conf /etc/postgresql/13/main/postgresql.conf
   $ diff /etc/postgresql/<old-pg-version>/main/pg_hba.conf     /etc/postgresql/13/main/pg_hba.conf
   ```
1. Stop the PostgreSQL service.
   `$ sudo systemctl stop postgresql.service`
1. Log in as the postgres user.
   `$ su postgres`
1. Check clusters (notice the --check argument, this will not change any data).
   ```
   $ /usr/lib/postgresql/13/bin/pg_upgrade \
     --old-datadir=/var/lib/postgresql/9.6/main \
     --new-datadir=/var/lib/postgresql/13/main \
     --old-bindir=/usr/lib/postgresql/9.6/bin \
     --new-bindir=/usr/lib/postgresql/13/bin \
     --old-options '-c config_file=/etc/postgresql/9.6/main/postgresql.conf' \
     --new-options '-c config_file=/etc/postgresql/13/main/postgresql.conf' \
     --check
   ```
1. Migrate the data (without the --check argument).
   ```
   $ /usr/lib/postgresql/13/bin/pg_upgrade \
     --old-datadir=/var/lib/postgresql/9.6/main \
     --new-datadir=/var/lib/postgresql/13/main \
     --old-bindir=/usr/lib/postgresql/9.6/bin \
     --new-bindir=/usr/lib/postgresql/13/bin \
     --old-options '-c config_file=/etc/postgresql/9.6/main/postgresql.conf' \
     --new-options '-c config_file=/etc/postgresql/13/main/postgresql.conf'
   ```
1. Log out of the postgres user.
`$ exit`
1. Swap the ports for the old and new PostgreSQL versions.
   ```
   $ sudo vim /etc/postgresql/13/main/postgresql.conf
   # change "port = 5433" to "port = 5432"

   $ sudo vim /etc/postgresql/9.6/main/postgresql.conf
   # change "port = 5432" to "port = 5433"
   ```
1. Start the PostgreSQL service.
   `$ sudo systemctl start postgresql.service`

1. Log in as the postgres user and confirm that the new PostgreSQL version is 13.3.
   ```
   $ sudo su postgres
   $ psql -c "SELECT version();"
                                                                      version
   ---------------------------------------------------------------------------------------------------------------------------------------------
    PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit
   (1 row)
   ```
1. Run reindexdb.  Example:
   ```
   $ /usr/bin/reindexdb --all
   reindexdb: reindexing database "bifrost"
   reindexdb: reindexing database "oc_id"
   reindexdb: reindexing database "opscode_chef"
   reindexdb: reindexing database "postgres"
   reindexdb: reindexing database "template1"
   ```

1. Log into the chef-server machine.

1. Check the status of chef-server.  PostgreSQL should be connected.
   ```
   $ sudo chef-server-ctl status
   -------------------
    Internal Services
   -------------------
   run: bookshelf: (pid 15763) 219163s; run: log: (pid 16559) 228464s
   run: elasticsearch: (pid 15797) 219162s; run: log: (pid 16345) 228507s
   run: nginx: (pid 15901) 219162s; run: log: (pid 16745) 228452s
   run: oc_bifrost: (pid 15909) 219161s; run: log: (pid 16237) 228519s
   run: oc_id: (pid 15915) 219161s; run: log: (pid 16255) 228513s
   run: opscode-erchef: (pid 15948) 219160s; run: log: (pid 16673) 228458s
   run: redis_lb: (pid 15952) 219160s; run: log: (pid 16779) 228445s
   -------------------
    External Services
   -------------------
   run: postgresql: connected OK to 10.0.11.0:5432
   ```

**Comment by lbakerchef** [comment]
# Customer Instructions, Standalone Scenario

1. It is strongly recommended to run vacuum full before starting the upgrade.
```
$ sudo su postgres
$ cd /opt/opscode/embedded/postgres/<version>/bin/
$ /usr/bin/vacuumdb --all --full
$ exit
```

1. Consult the documentation on `chef-server-ctl backup`.
   https://docs.chef.io/server/server_backup_restore/

   Backup the database.
   MAKE A NOTE OF WHERE THE BACKUP WAS PLACED (normally under /var/opt/chef-backup).
   Please note that chef-server will go offline to perform the backup.
   Example:

`$ sudo chef-server-ctl backup`


1. If you are running chef-server version 12.17.15 or greater, skip this step and proceed with step 4 below.
   If you are running a chef-server release prior to 12.17.15, you cannot upgrade directly to 14.8.X.
   You must perform a stepped upgrade first.

   If you are running chef-server 12.3.0, you must first upgrade 12.17.15.
   If you are running chef-server 11, you must first upgrade to 12.3.0, and then to 12.17.15.
   Please consult the docs linked below for information on these upgrades.

   https://docs.chef.io/server/upgrades/

   After performing the stepped upgrade, return here and continue with step 4 below.

1. Download the chef-server version 14.8.X upgrade package.

    https://downloads.chef.io/tools/infra-server

1. Stop services.

```
$ # NOTE: umbrella scenarios stop rabbitmq, so I'm including that below.  Correct?  Incorrect?
$ sudo chef-server-ctl stop || sudo chef-server-ctl kill rabbitmq
```

--------------------------------------------------------------
1. WE MAY NOT USE THIS - THIS STEP MAY BE DELETED

   Move the postgresql directory to a safe location or it could be deleted and cause errors.
   Example:

```
$ sudo mkdir /my-postgresql-dir/opt-opscode-embedded-postgresql
$ sudo mv --verbose /opt/opscode/embedded/postgresql/* /my-postgresql-dir/opt-opscode-embedded-postgresql
```
--------------------------------------------------------------

1. Install the chef-server 14.8.X package.

dpkg:
`$ sudo dpkg -iEG /path/to/chef-server-core-<version>.deb`

rpm:
`$ sudo rpm -U /path/to/chef-server-core-<version>.rpm`

--------------------------------------------------------------
1. WE MAY NOT USE THIS - THIS STEP MAY BE DELETED

   Restore the previously-moved postgresql directory.
   Example:

`$ sudo cp --force --recursive --verbose /my-postgresql-dir/opt-opscode-embedded-postgresql/* /opt/opscode/embedded/postgresql`
--------------------------------------------------------------

1. Upgrade chef-server.

`$ sudo CHEF_LICENSE='accept' chef-server-ctl upgrade`

1. If the upgrade failed, SKIP THIS STEP and continue at step X below.
   If the upgrade was successful, start services, cleanup, and reindex the database.
```
$ sudo chef-server-ctl start
$ sudo chef-server-ctl cleanup
$ sudo /usr/bin/reindexdb --all
```
   You are now finished with the chef-server upgrade.  DO NOT PROCEED FURTHER.

1. If the upgrade failed, and you are left with a corrupted chef-server and/or corrupted database,
    it is strongly recommended that you DO NOT UNDER ANY CIRCUMSTANCES RISK YOUR BACKUP OF THE DATABASE.
    You should take any and all steps in order to preserve the backup, including copying it to another disk.

   Reinstall the original version of chef-server you were using before attempting the upgrade process
   (if you had to perform a stepped upgrade, install your original version of chef-server before the
   stepped upgrade, not any of the versions in the stepped upgrade process).  Again, it is recommended
   that you DO NOT RISK YOUR BACKUP OF THE DATABASE.  Use a separate disk from your backup for the
   installation.

   Download chef-server:
   https://docs.chef.io/server/install_server/

   Install instructions for chef-server:
   https://docs.chef.io/server/install_server/

1. Consult the documentation on restore, and restore the database from the path where it was saved previously.
   https://docs.chef.io/server/server_backup_restore/

   Example:
`chef-server-ctl restore /var/opt/chef-backup/chef-backup-2021-06-11-18-59-19.tgz`



# Customer Instructions, External PostgreSQL Scenario

Vacuum the PostgreSQL database.

1. Log into the external PostgreSQL machine.

1. Run vacuum full.  Example:
```
$ sudo su postgres
$ /usr/bin/vacuumdb --all --full
vacuumdb: vacuuming database "bifrost"
vacuumdb: vacuuming database "oc_id"
vacuumdb: vacuuming database "opscode_chef"
vacuumdb: vacuuming database "postgres"
vacuumdb: vacuuming database "template1"
$ exit
```
1. Log out of the external PostgreSQL machine.

Backup the PostgreSQL database.

1. Log into the chef-server machine.

1. Consult the documentation on `knife-ec-backup`.
   https://blog.chef.io/migrating-chef-server-knife-ec-backup-knife-tidy

   If it is not already installed, install knife-ec-backup.  A sample session follows
   (note that your steps could differ, depending on the versions of your software,
   the topology of your setup, your OS and distrubition, and a range of other factors).
   Example:
```
$ apt-get update
$ apt install ruby
$ apt install make
$ curl -L https://chef.io/chef/install.sh | sudo bash -s -- -P chefdk
$ export PATH=$PATH:/root/.chefdk/gem/ruby/2.6.0/bin
$ apt-get -y install gcc postgresql libpq-dev
$ /opt/chefdk/embedded/bin/gem install knife-ec-backup -- --with-pg-config=/opt/opscode/embedded/postgresql/9.6/bin/pg_config
```
1. If it is not already configured, configure knife.  A sample session follows
   (again, note that your steps could differ, depending on a range of factors).
   Example:
```
$ chef-server-ctl org-create 4thcafe 'Fourth Cafe, Inc.' --association_user janedoe --filename /tmp/4thcafe-validator.pem
$ chef generate repo chef-repo
$ cd chef-repo/
$ mkdir -p .chef
$ echo '.chef' >> .gitignore
$ cp /tmp/4thcafe-validator.pem .chef
$ cp /home/ubuntu/janedoe.pem .chef
$ cd .chef
$ knife configure
WARNING: No knife configuration file found. See https://docs.chef.io/config_rb/ for details.
Please enter the chef server URL: [https://1.2.3.4/organizations/myorg] https://1.2.3.4/organizations/4thcafe
Please enter an existing username or clientname for the API: [ubuntu] janedoe
$ knife ssl fetch
```
1. Backup the database.
   Example:
```
$ mkdir /backup
$ /opt/chefdk/embedded/bin/knife ec backup /backup
```
Upgrade Chef Server.

1. If you are running chef-server version 12.17.15 or greater, skip this step and proceed with step X below.
   If you are running a chef-server release prior to 12.17.15, you cannot upgrade directly to 14.8.X.
   You must perform a stepped upgrade first.

   If you are running chef-server 12.3.0, you must first upgrade 12.17.15.
   If you are running chef-server 11, you must first upgrade to 12.3.0, and then to 12.17.15.
   Please consult the docs linked below for information on these upgrades.

   https://docs.chef.io/server/upgrades/

   After performing the stepped upgrade, return here and continue these instructions at step X below.

1. Download the chef-server version 14.8.X upgrade package.

https://downloads.chef.io/tools/infra-server

1. Stop services.

```
$ # NOTE: umbrella scenarios stop rabbitmq, so I'm including that below.  Correct?  Incorrect?
$ sudo chef-server-ctl stop || sudo chef-server-ctl kill rabbitmq
```

--------------------------------------------------------------
1. WE MAY NOT USE THIS - THIS STEP MAY BE DELETED

   Move the PostgreSQL directory to a safe location or it could be deleted and cause errors.
   Example:

```
$ sudo mkdir /my-postgresql-dir/opt-opscode-embedded-postgresql
$ sudo mv --verbose /opt/opscode/embedded/postgresql/* /my-postgresql-dir/opt-opscode-embedded-postgresql
```
--------------------------------------------------------------

1. Install the chef-server 14.8.X package.

dpkg:
`$ sudo dpkg -iEG /path/to/chef-server-core-<version>.deb`

rpm:
`$ sudo rpm -U /path/to/chef-server-core-<version>.rpm`

1. WE MAY NOT USE THIS - THIS STEP MAY BE DELETED

   Restore the previously-moved postgresql directory.
   Example:

`$ sudo cp --force --recursive --verbose /my-postgresql-dir/opt-opscode-embedded-postgresql/* /opt/opscode/embedded/postgresql`

1. Upgrade chef-server.

`$ sudo CHEF_LICENSE='accept' chef-server-ctl upgrade`

1. IF THE UPGRADE WAS SUCCESSFUL, start services and cleanup.
```
$ sudo chef-server-ctl start
$ sudo chef-server-ctl cleanup
```
You are now finished with the chef-server upgrade.  Proceed directly to the Upgrade PostgreSQL section.

1. IF THE UPGRADE FAILED, and you are left with a corrupted chef-server and/or corrupted database,
    it is strongly recommended that you DO NOT UNDER ANY CIRCUMSTANCES RISK YOUR BACKUP OF THE DATABASE.
    You should take any and all steps in order to preserve the backup, including copying it to another disk.

1. Reinstall the original version of chef-server you were using before attempting the upgrade process
   (if you had to perform a stepped upgrade, install your original version of chef-server before the
   stepped upgrade, not any of the versions in the stepped upgrade process).  Again, it is recommended
   that you DO NOT RISK YOUR BACKUP OF THE DATABASE.  Use a separate disk from your backup for the
   installation.

   Download chef-server here:
   https://docs.chef.io/server/install_server/

   Install instructions for chef-server:
   https://docs.chef.io/server/install_server/

1. Consult the documentation on knife-ec-restore, and restore the database from the path where it was saved previously.
   https://blog.chef.io/migrating-chef-server-knife-ec-backup-knife-tidy

   Example:
`$ /opt/chefdk/embedded/bin/knife ec restore /backup/`

1. Do not proceed further until you have an uncorrupted Chef Server upgraded to version X.Y.Z,
   and an uncorrupted PostgreSQL database.

Upgrade PostgreSQL

1. Log out of the chef-server machine.

1. Log into the external PostgreSQL machine.

1. Update packages and install the new PostgreSQL 13.3.
   Example (Ubuntu):
```
$ sudo apt-get update
$ sudo apt-get install postgresql-13
```

1. Check if there are any differences in the config files.  Make sure to update them if required.
```
$ diff /etc/postgresql/12/main/postgresql.conf /etc/postgresql/13/main/postgresql.conf
$ diff /etc/postgresql/12/main/pg_hba.conf /etc/postgresql/13/main/pg_hba.conf
```
1. Stop the PostgreSQL service.
`$ sudo systemctl stop postgresql.service`
1. Log in as the postgres user.
`$ su postgres`
1. Check clusters (notice the --check argument, this will not change any data).
```
$ /usr/lib/postgresql/13/bin/pg_upgrade \
  --old-datadir=/var/lib/postgresql/9.6/main \
  --new-datadir=/var/lib/postgresql/13/main \
  --old-bindir=/usr/lib/postgresql/9.6/bin \
  --new-bindir=/usr/lib/postgresql/13/bin \
  --old-options '-c config_file=/etc/postgresql/9.6/main/postgresql.conf' \
  --new-options '-c config_file=/etc/postgresql/13/main/postgresql.conf' \
  --check
```
1. Migrate the data (without the --check argument).
```
$ /usr/lib/postgresql/13/bin/pg_upgrade \
  --old-datadir=/var/lib/postgresql/9.6/main \
  --new-datadir=/var/lib/postgresql/13/main \
  --old-bindir=/usr/lib/postgresql/9.6/bin \
  --new-bindir=/usr/lib/postgresql/13/bin \
  --old-options '-c config_file=/etc/postgresql/9.6/main/postgresql.conf' \
  --new-options '-c config_file=/etc/postgresql/13/main/postgresql.conf'
```
1. Log out of the postgres user.
`$ exit`
1. Swap the ports for the old and new PostgreSQL versions.
```
$ sudo vim /etc/postgresql/13/main/postgresql.conf
# change "port = 5433" to "port = 5432"

$ sudo vim /etc/postgresql/9.6/main/postgresql.conf
# change "port = 5432" to "port = 5433"
```
1. Start the PostgreSQL service.
`$ sudo systemctl start postgresql.service`

1. Log in as the postgres user again and confirm that the new PostgreSQL version is 13.3.
```
$ sudo su postgres
$ psql -c "SELECT version();"
                                                                   version
---------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 13.3 (Ubuntu 13.3-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit
(1 row)
```
1. Run reindexdb.  Example:
```
$ /usr/bin/reindexdb --all
reindexdb: reindexing database "bifrost"
reindexdb: reindexing database "oc_id"
reindexdb: reindexing database "opscode_chef"
reindexdb: reindexing database "postgres"
reindexdb: reindexing database "template1"
```

1. Log out of the external PostgreSQL machine.

1. Log into the chef-server machine.

1. Check the status of chef-server.  PostgreSQL should be connected.
```
$ sudo chef-server-ctl status
-------------------
 Internal Services
-------------------
run: bookshelf: (pid 15763) 219163s; run: log: (pid 16559) 228464s
run: elasticsearch: (pid 15797) 219162s; run: log: (pid 16345) 228507s
run: nginx: (pid 15901) 219162s; run: log: (pid 16745) 228452s
run: oc_bifrost: (pid 15909) 219161s; run: log: (pid 16237) 228519s
run: oc_id: (pid 15915) 219161s; run: log: (pid 16255) 228513s
run: opscode-erchef: (pid 15948) 219160s; run: log: (pid 16673) 228458s
run: redis_lb: (pid 15952) 219160s; run: log: (pid 16779) 228445s
-------------------
 External Services
-------------------
run: postgresql: connected OK to 10.0.11.0:5432
```
