### ISSUE TITLE
[pg_upgrade] Update postgres to 13.2 instead of 12.5

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2543]
At the time of starting this work, 12.5 was the latest version available in RDS.
At this moment RDS also supports 13.2

Acceptance Criteria:
1. Omnibus Chef Infra Server packages support postgres 13.2
2. chef-server-ctl commads that need to connect to the db like chef-server-ctl user-create / chef-server-ctl org-create work.

**Comment by lbakerchef** [comment]
See: https://github.com/chef/chef-server/pull/2577

**Comment by PrajaktaPurohit** [comment]
#2523
