### ISSUE TITLE
Cleanup /analytics/erchef Queue During Upgrade

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#257]
Zendesk 2166 and all other customers who have upgraded in-place through Analytics versions and Chef Servers

Upgrading from EC 11.2.x -> 11.3.x or EC 11.x -> CS 12.x should result in the /analytics/erchef RabbitMQ queue being deleted as part of the upgrade. A side effect is that this will lock EC 11.3.x with Analytics 1.1.x, which is not too bad.

EC 11.3.x and CS 12.x are designed to operate with Analytics 1.1.x, which references the /analytics/alaska queue only.

When both queues are present, the opscode-erchef code appears to get confused and place messages in both. This is a problem, because eventually, the erchef queue will fill up the system's disk.

**Comment by PrajaktaPurohit** [comment]
We will be removing Rabbitmq in the near future. (After replacing solr with elasticsearch). Closing this for that reason.
