### ISSUE TITLE
Version detection on upgrades could check for multiple installations

### ISSUE THREAD

**Issue by glasschef** [chef/chef-server#260]
When upgrading a previous version of Chef server, instead of just checking for the open-source chef directory could we also check for other Chef server installs (like Enterprise Chef) and prompt the user somehow to clean up the one they aren't using?  

https://github.com/chef/chef-server/blob/355f18741742baaf5fd48edecb6192b07ac9de00/omnibus/files/private-chef-ctl-commands/upgrade.rb#L84

There have been several cases where users have had old open-source chef installation directories lying around on their Enterprise Chef server, and while it's great that the upgrade will prompt them about an open source upgrade, it doesn't tell them why it thinks open source is installed or how to clean it up.  If we detected multiple installations on an upgrade then we could explicitly inform the user that they probably want to get rid of one.

**Comment by PrajaktaPurohit** [comment]
Closing this, since it seems to be an issue especially upgrading from Chef Infra Server 11 to Chef Infra Server 12. Please feel free to reopen if this is seen on upgrades to Chef Infra Server 13.
