### ISSUE TITLE
'knife node create' and node that already exist

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef/chef-server#263]
Hello,

On Chef 11 the knife node create used to return 'already exists' when you try to create one node that already exists.

Now, using Chef and Knife 12, the node create always create (and erase) all the metadata from the node:

```
tiagocruz@stark:~$ knife node show cheftest-centos-6-64
Node Name:   cheftest-centos-6-64
Environment: production
FQDN:        cheftest-centos-6-64
IP:          10.0.2.15

tiagocruz@stark:~$ knife node create cheftest-centos-6-64
Created node[cheftest-centos-6-64]

tiagocruz@stark:~$ knife node show cheftest-centos-6-64
Node Name:   cheftest-centos-6-64
Environment: _default
FQDN:        
IP:          
Run List:    
Roles:       
Recipes:     
Platform:
```

The main problem is: My autoscaling is not working any more, 'cause I used to trust in knife to know if the node name already exists or not :)

```
echo "Reserving hostname $SRV_HOSTNAME try ($RETRY/$MAXRETRY)..."
  knife node create $KNIFE_OPT $SRV_HOSTNAME --disable-editing
  if [ $? -eq 0 ]; then
    echo "OK: Hostname $SRV_HOSTNAME reserved"
  else
    let RETRY=RETRY+1
    SLEEP=$[($RANDOM % 5) + 1]
    echo "Warning: Fail on $SRV_HOSTNAME, waiting $SLEEP seconds" 
    sleep $SLEEP
    reserveName
  fi
```

Thanks

**Comment by tiago-cruz-movile** [comment]
Related: https://github.com/chef/chef/issues/3385

**Comment by sdelano** [comment]
Hi @tiago-cruz-movile, thanks for taking the time to report this.

I've tracked this down and this is an issue with knife and the `chef` gem, so I'm going to close this ticket here and follow up with some more information in the client issue.

**Comment by tiago-cruz-movile** [comment]
Thanks @sdelano!

Could you please provide the number or id? I would like to watch this one :)

Thanks a lot!
