### ISSUE TITLE
knife org user add ORG_NAME USER_NAME works without pivotal.pem

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2638]
There is a lack of documentation on docs.chef.io for the updated knife command knife org

This was previously contained with knife opc used as knife opc org but has since been moved, this new documentation has not been created.

https://docs.chef.io/workstation/plugin_knife_opc/#opc-org-user-add

The above docs says;

To manage organizations, or change a user’s assignment to an organization, the pivotal key is required.

In reality as shown below, a user can be added to an org without pivotal.pem.

root@chef-automate:/home/ubuntu# chef-server-ctl list-server-admins
/hab/pkgs/chef/chef-server-ctl/14.4.4/20210520120637/vendor/bundle/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
pivotal
r-goto
r-goto@Mac:~/.chef/repos/first-org-repo %knife user create test5 --email test@test.com --password 123123 --user r-goto --key .chef/r-goto.pem
Created test5
root@chef-automate:/home/ubuntu# chef-server-ctl user-show test5 -l
display_name: test5
email: test@test.com
first_name:
last_name:
organizations:
public_key: -----BEGIN PUBLIC KEY-----
~
-----END PUBLIC KEY-----

username: test5
root@chef-automate:/home/ubuntu#
r-goto@Mac:~/.chef/repos/first-org-repo %knife org user add first-org test5 --user r-goto --key .chef/r-goto.pem
root@chef-automate:/home/ubuntu# chef-server-ctl user-show test5 -l
display_name: test5
email: test@test.com
first_name:
last_name:
organizations: first-org
public_key: -----BEGIN PUBLIC KEY-----
~
-----END PUBLIC KEY-----

username: test5

Please advise us whether pivotal is indeed required to add a user to an org or it's just a doc defect.

root@chef-automate:/home/ubuntu# chef-automate version
Version: 2
CLI Build: 20210609164108
Server Build: 20210616033549
root@chef-automate:/home/ubuntu# chef-server-ctl version
Chef Automate Chef server 14.4.4/20210614091959

**To Reproduce**

you'll need chef workstation 21.5.420 or greater that includes Chef Infra Client 17.x

the issue is that the documentation is not available at docs.chef.io

**Expected behavior**

https://docs.chef.io/workstation/knife_org/ should lead to valid documentation the same way that https://docs.chef.io/workstation/knife_user/ does

**Actual behavior**

there is no available documentation for `knife org` and the docs for `knife opc org` are possibly incorrect and need review.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/customer-bugs/issues/423

**Comment by snehaldwivedi** [comment]
Hi, I have tried to replicate the issue on my side on latest chef version but its working fine please go through the steps I followed 

```
I have created a new user and added to an existing org with `chefadmin` and I am not able to do that
$ knife user create "xyz" --email "xyz@test.com" --password "xyz@123" -f xyz.pem
Created xyz
```

```
$ knife org user add zzz-org1 xyz
ERROR: You authenticated successfully to https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee as xyz but you are not authorized for this action.
Response:  'chefadmin' not associated with organization 'zzz-org1'
```

But same if I tried with pivotal user I am able to add it 

```
$ knife org user add zzz-org1 xyz

$ knife user show xyz -l
display_name:  xyz
email:         xyz@test.com
first_name:    
last_name:     
organizations: zzz-org1
username:      xyz
```

I have added a separate ticket for documentation https://github.com/chef/chef-workstation/issues/2259. Please let us know if you still face this issue with some more details

**Comment by snehaldwivedi** [comment]
closing in the behalf of comment https://github.com/chef/customer-bugs/issues/423#issuecomment-918068051
