### ISSUE TITLE
Error executing action `create` on resource 'private-chef_pg_database[opscode-pgsql]'

### ISSUE THREAD

**Issue by markan** [chef/chef-server#275]
Copied from https://github.com/chef/chef/issues/2715

Filing this under chef-server, since this appears to be an install failure. 

More detail would be welcome, including:
- What command was being run. Was this an install?
- What version of chef-server
- What OS

**Comment by danielsdeleo** [comment]
@sridhar-ars veera1989 Your bug has been moved here.

**Comment by danielsdeleo** [comment]
@veera1989 your bug was moved here

**Comment by danielsdeleo** [comment]
Error reported in other ticket:

```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
STDOUT:
STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1
```

**Comment by danielsdeleo** [comment]
Also, in chef#2714:

> I get the below errors when i try to install chef server on RHEL ec2 instance

**Comment by ryancragun** [comment]
@sridhar-ars @veera1989
I ran into an issue very similar to this and found two things wrong:

* `/var/log` was missing the group x bit which prevented searches further down the directory tree. Adding the bit allowed svlogd to open /var/log/opscode/postgresql/9.2/current
 
 `$: chmod 755 /var/log`

* The mode on `/tmp` missing the w bit which is required for postgresql to open a socket.

  `$: chmod 777 /tmp`

Hope that helps

**Comment by alnet** [comment]
I had the same issue installing on a testing box that also happen to have an omnibus installed gitlab already on the box. In my case the clash was the copy of postgresql that Gitlab installed already having the socket in place in /tmp. When Chef tried to reconfigure, it saw the socket, but wasn't able to use it because it was trying to delete the socket file owned by the other copy of postgresql.

I worked around it by editing each project's copy of postgresql's config to put their socket file in /tmp/gitlab and /tmp/chef respectively, and then re-running "chef-server-ctl reconfigure"  I'm sure the better option is to setup a single copy of postgres and make both projects use it, but I was more interested in getting both applications running since it's all for testing anyway.

**Comment by kamidzi** [comment]
Similar to https://tickets.opscode.com/browse/CHEF-4134, I solved this by changing shm settings. From @kelvk:

```
kernel.shmmax = 137438953472
kernel.shmall = 134217728
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
$ dpkg-deb  -I chef-server-core_12.0.8-1_amd64.deb
 new debian package, version 2.0.
 size 459863754 bytes: control archive=1486199 bytes.
     325 bytes,    13 lines      control
 6497824 bytes, 56476 lines      md5sums
    1536 bytes,    47 lines   *  postinst             #!/bin/bash
     190 bytes,     8 lines   *  postrm               #!/bin/bash
 Package: chef-server-core
 Version: 12.0.8-1
 License: unknown
 Vendor: Omnibus <omnibus@getchef.com>
 Architecture: amd64
 Maintainer: Chef Software, Inc.
 Installed-Size: 1182820
 Conflicts: private-chef
 Replaces: private-chef
 Section: misc
 Priority: extra
 Homepage: https://www.chef.io
 Description: The full stack of chef-server
```

**Comment by PrajaktaPurohit** [comment]
It might be useful to 
1. have a preflight check to check for
a. Postgres port available
b. shmmax settings
c. permissions
2. when we can check if Postgresql can be connected to and give an appropriate message if not.
(leaning towards 2)

**Comment by tas50** [comment]
Closing out in favor of https://github.com/chef/chef-server/issues/4
