### ISSUE TITLE
Chef Server needs to have an API to indicate if an user is part of server-admin group

### ISSUE THREAD

**Issue by kalroy** [chef/chef-server#2756]
A Chef server user can be added to `server-admin` group 
`chef-server-ctl grant-server-admin-permissions alice` 

Reference:
https://docs.chef.io/server/ctl_chef_server/#server-admins

The Chef Server API for user `/organizations/NAME/users/NAME` does not provide any indication about whether the user 
is granted server-admin or not.

Addition of a field is required:

```
{
  "username": "paperlatte"
  "email": "latte",
  "display_name": "Ms. Latte",
  "first_name": "Paper",
  "last_name": "Latte",
  "public_key": "-----BEGIN PUBLIC KEY----- ... "
 "is_server-admin": true
}
```

**Comment by tas50** [comment]
I'd rather we implement a user_type field here so we don't end up wth a handful of these boolean values.

**Comment by tas50** [comment]
Closing this out since we're moving away from users in the server and there's no real value in building this now for that migration.
