### ISSUE TITLE
Consistency in user list API response for server users and organisation users

### ISSUE THREAD

**Issue by vinay033** [chef/chef-server#2786]
# Describe the problem
Using the chef-automate with chef-server API, we have a server users list and org users list but the response is not consistent.

## Replication Case
checks the server users API and Org users API to check the response.
for server users, we are getting like
```
{
    "users": [
       {
            "username": "sonali",
            "first_name": "Sonali",
            "last_name": "Wale",
            "email": "swale@progress.com"
        },
        {
            "username": "vinay",
            "first_name": "Vinay",
            "last_name": "Sharma",
            "email": "vsharma@chef.io"
        }
    ]
}
```
and for org we are getting like 
```
{ 
    "users": [ 
          { "username": "himanshi" }, 
          { "username": "sonali" } 
     ] 
}
``` 

## Possible Solution
We need the same kind of response from both API's.

**Comment by tas50** [comment]
This will require a new version of the API that can normalize the values. Otherwise this would be a breaking change.

**Comment by marcparadise** [comment]
This was intentional, in that the user reference in an organization isn't actually a 'user' object - it's just intended as an org membership list. 

We can look at changing this - since it would be adding fields it probably wouldn't need a server API version bump - but I'd like to better understand the need before continuing.

**Comment by PrajaktaPurohit** [comment]
Closing since there has been no movement on this. Please feel free to reopen with more information.
