### ISSUE TITLE
Chef CPU high usage and web server failing

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2787]
We are trying to upgrade Chef server from version 12.x to 13.x to have still supported major version installed. In the current setup we have every Chef server servers around 5000-7000 clients. Server is installed with all embedded software, no any external DBs or tools are used except of Software for updating cookbooks from version control.

When Chef server is upgraded we observe next things:

CPU usage goes high as sky, taking 26 CPU cores out of 32 available on the server, the rest is taken by other tasks
Clients are served and served correctly, but not all of them, a lot of clients (around two thirds) get 5xx errors. If I request server status with curl locally, I also get sometimes correct answer, sometimes I get server error.
In this unstable mode server stays for days (two days tested, then downgraded)
We tried also 14.x version, and here situation gets even worse as the server gets all available CPU and then stops to serve clients at all.

**Comment by jashaik** [comment]
I haven't seen any high CPU usage after upgrading from 12.17.15 to 13.x with some data.I will verify try to verify it with 5000 clients
![Screenshot 2021-09-09 at 3 23 17 PM](https://user-images.githubusercontent.com/76031665/132665008-c2c10c3a-aa85-4d2f-aeed-4432c2d6e9e8.png)

**Comment by jashaik** [comment]
Given 1.5 days timebox for reproducing this issue.

**Comment by jashaik** [comment]
We are working on the below things to include in the next chef-server release as part of improvments.

- Updating the Webmachine to latest version to avoiding 'sel_conn_closed'/connection related issues
- Exporting the max_connection_requests to omnibus ( passing to opscode-httpc) for giving the option to handle the load
- improving the debug logs for better support.
