### ISSUE TITLE
Migrate from ElasticSearch 6.x to OpenSearch 1.2.x

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2813]
## User Story
As a Chef Infra Server admin, I require the latest version of dependencies
So that I can keep my Chef infrastructure and business secure

## Acceptance Criteria
- New installs run with external Opensearch work
- Upgrading external elasticsearch to Opensearch is tested and documented
- New internal opensearch installs work <- basic omnibus work
- Upgrade internal opensearch installs work <- some more omnibus work around automating the manual steps in moving from es to opensearch
- Test with standalone-fresh-install | standalone-upgrade | tiered fresh install and upgrade | external opensearch
- New installs run on Opensearch 1.x
- Existing Elasticsearch 6 installs are seamlessly migrated to Opensearch

## Implementation Details
- This work needs to be done in Q4 as the release of Elasticsearch 8 means 6.x stops receiving security updates.

## Definition of Done
- End to end testing is in place to validate the upgrade
- Coordination has taken place with the Automate team to ensure integrated Chef Infra Server works with Opensearch in Automate
- Release notes explain changes  that may impact Automate admins such as URL/Path changes that may impact monitoring

Related automate issue: https://github.com/chef/automate/issues/5744

**Comment by vinay-satish** [comment]
Reference PR - https://github.com/chef/chef-server/pull/2933

**Comment by btm** [comment]
https://opensearch.org/docs/latest/upgrade-to/upgrade-to/
![image](https://user-images.githubusercontent.com/4381/146465221-54b6e9c7-cc9e-40a2-8502-7cc4ae010837.png)
