### ISSUE TITLE
Check CVE's related to chef

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2814]
Cannot see the 9 CVE's which we have listed on the release notes for Chef Infra Server 14.9.23. Can you please have them included in the release notes.

https://docs.chef.io/release_notes_server/?v=14.9.23

Expected behavior
All the listed CVE's should have added in the release notes of the latest Chef Infra version 14.9.23.

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/customer-bugs/issues/478

**Comment by tas50** [comment]
This escalation was closed out and handled off to support
