### ISSUE TITLE
Dev VM not syncing up the local changes

### ISSUE THREAD

**Issue by vinay-satish** [chef/chef-server#2831]
We are not able to hot load the changes into dev vm. The `./sync` scrip is not syncing up the changes to the dev vm. Testing the changes becomes difficult without this as we have to build the package and test.

Acceptance criteria
- [ ] The `./sync` script should be fixed or create an issue to fix the sync utility in the future.
- [ ]  If an issue is create to fix the sync utility in the future there must be a work around to load the local changes without having to package.
- [ ] run the erchef console and make some updates locally, confirm that those are reflected in the console.

**Comment by vinay-satish** [comment]
Blocked - need more analysis on dvm and sync code

**Comment by PrajaktaPurohit** [comment]
Basic loading for erchef works - might need to change branches from master to main.
