### ISSUE TITLE
Vagrant: use-external PostgreSQL broken

### ISSUE THREAD

**Issue by apavely** [chef/chef-server#2843]
### Expected Result
`use-external` builds a valid external PostgreSQL vagrant box.

### Actual Result
I was trying to provision an external PostgreSQL server with `use-external`.

Two issues:
1. The defined repository is pointing to the PGDG repository's `xenial-pgdg` suite. The defined Vagrant box is using `bento/ubuntu-18.04` (a.k.a. `bionic`). Defined here: https://github.com/chef/chef-server/blob/13e5c1f17c7b08abdbc710142616643c43192fe2/dev/scripts/provision-postgres.sh#L1
1. Packages won't install since the defined package names do not exist:
    ```
    E: Unable to locate package postgresql-13.3
    E: Couldn't find any package by glob 'postgresql-13.3'
    E: Couldn't find any package by regex 'postgresql-13.3'
    ```
    From: https://github.com/chef/chef-server/blob/13e5c1f17c7b08abdbc710142616643c43192fe2/dev/scripts/provision-postgres.sh#L5

**Comment by marcparadise** [comment]
This looks to have been closed with #2844 and #2932
