### ISSUE TITLE
Improve logging and tooling for troubleshooting

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2858]
```
As a Chef Infra Server developer
I want proper debug logging and tooling in place
So that I can rapidly reserve customer escalations
```

```
As a Chef Infra Server admin
I want proper debug logging and tooling in place
So that debug sessions with developers are quick and fruitful
```

Let's make sure we add all the things we need to be able to troubleshoot failures more easily in the field. Customer escalations require hopping on live systems to debug issues. We want to make sure as we do that, we have everything we need in place to quickly get to the bottom of the issue and resolve the problems.

**Comment by jashaik** [comment]
As per our discussion with Marc, Created issue for monitoring tools - https://github.com/chef/chef-server/issues/3069

**Comment by tas50** [comment]
Closing this out since the initial goal was met
