### ISSUE TITLE
Investigate credential creation in opensearch.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2866]
This is a spike to investigate the creation of credentials for opensearch.

Omnibus:
- [ ] Identify the best way to link credentials generated for opensearch with es-gateway and the chef_secrets system.

Habitat:
- [ ] Placeholder.

**Comment by jashaik** [comment]
@PrajaktaPurohit Looking like this the best way to create the credentials in opensearch . Please review
https://opensearch.org/docs/latest/security-plugin/access-control/api#create-user

**Comment by jashaik** [comment]
commit:
https://github.com/chef/chef-server/pull/2933/commits/30e30b8fb1122c6d3ad51596480d4ea45eb03230
