### ISSUE TITLE
MTLS and upgrade scenarios is red is Umbrella

### ISSUE THREAD

**Issue by vinay-satish** [chef/chef-server#2872]
`mtls-ipv4-ubuntu-18.04` and `standalone-upgrade-ipv4-ubuntu-20.04-from-12.17.15` scenarios is failing in the umbrella from 08/10.
Latest build fail - https://buildkite.com/chef/chef-umbrella-main-chef-server/builds/765
For the same build and same umbrella branch the build was green - https://buildkite.com/chef/chef-umbrella-main-chef-server/builds/751

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/2877
