### ISSUE TITLE
cwe-200 information exposure due to ssl and multiple names/addresses to hit the server

### ISSUE THREAD

**Issue by igarrison** [chef/chef-server#288]
We had a report come into security@chef.io.

Do the simplest install of enterprise chef:
1. download the deb file from chef.io
2. dpkg -i chef-server*
3. chef-server-ctl reconfigure
4. chef-server-ctl upgrade

Then try and reach the server via its ip address or dns name that is not the same as its hostname:

$ wget -S "http://52.74.205.192" --no-check-certificate 2>&1 | egrep -i "ip-172-31-0|52.74.205.192"
--2015-05-21 18:08:36--  http://52.74.205.192/
Connecting to 52.74.205.192:80... connected.
  Location: https://52.74.205.192:443/
Location: https://52.74.205.192:443/ [following]
--2015-05-21 18:08:36--  https://52.74.205.192/
Connecting to 52.74.205.192:443... connected.
WARNING: cannot verify 52.74.205.192's certificate, issued by
‘/C=US/ST=WA/L=Seattle/O=YouCorp/OU=Operations/CN=ip-172-31-0-118.ap-southea
st-1.compute.internal/emailAddress=you@example.com’:
    WARNING: certificate common name
‘ip-172-31-0-118.ap-southeast-1.compute.internal’ doesn't match requested
host name ‘52.74.205.192’.
  Location: https://52.74.205.192/users/login
Location: https://52.74.205.192/users/login [following]
--2015-05-21 18:08:37--  https://52.74.205.192/users/login
Reusing existing connection to 52.74.205.192:443.

From this you can see that I go to http://52.74.205.192 but there are ssl warnings that expose the internal hostname ip-172-31-0-118.ap-southeast-1.compute.internal.

https://cwe.mitre.org/data/definitions/200.html

I was able to reproduce this on my home chef server running 12.0.8.  I couldn't find any records showing whether this issue had already been reported or not.  We may be crediting the reporter with a blog post for this find if he wants to be recognized.

It does seem easy to address this problem by setting api_fqdn "chef.example.com" and then always consistently using chef.example.com to reach your chef server (does not expose the internal hostname if its different).

Dev Team, I defer to you guys on the priority for fixing this or not.

-ian

**Comment by stevendanna** [comment]
I'm going to close this.  This is a result of using the default ssl cert with no configured api_fqdn.  There are certainly many minor information exposures in the chef-server, but this one is avoidable by using the provided config.  For others, we can open specific bugs for those as we find them.
