### ISSUE TITLE
Migrate from Elasticsearch 6 -> Opensearch 1.1

### ISSUE THREAD

**Issue by tas50** [chef/chef-server#2890]
```
As an CISO I require non EOL software
to ensure the safety of my infrastructure
```

```
As a cloud-vendor partner of Chef I require compatible software licenses
to avoid putting my business at risk
```

Currently Chef Infra Server ships with Elasticsearch 6. Elastic has a policy of supporting the N-1 release. Currently, that means ES 7 and ES 6. ES 8 is in beta and will ship soon, at which time we will cease to receive security updates and Chef Infra Server and Automate will begin getting flagged by security scanning software and security teams. We need to migrate to a new version to continue to receive security updates. Elasticsearch 7 introduced a new license, which is incompatible with SaaS usage, particularly that by our cloud partners. This prevents us from moving to ES 7 or above. Due to this license restriction, we will need to move to the Opensearch project, which is Amazon-backed and includes a compatible license in addition to new functionality we need.

## Acceptance Criteria

- New installations use OS 1.1
- Existing self-contained Infra Server installs are migrated to OS 1.1
- External installs of ES 6+ continue to function as usual until we deprecate that as a supported path
- Upgrade time understood and documented
- Umbrella scenarios test new install / upgrade / external paths

**Comment by PrajaktaPurohit** [comment]
https://chefio.atlassian.net/browse/INFS-29
