### ISSUE TITLE
Chef-Server reindex failure.

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2894]
Initially we upgraded the DB to new postgressql version, but later after discussion with Jeff we roll back to old version for postgressql and execute below upgrade command.

Command:

chef-server-ctl upgrade

Error:

Running handlers:
Running handlers complete
Chef Infra Client finished, 361/790 resources updated in 01 minutes 53 seconds
Chef Server Reconfigured!
ok: down: bookshelf: 1s, normally up
ok: down: elasticsearch: 0s, normally up
ok: down: nginx: 1s, normally up
ok: down: oc_bifrost: 0s, normally up
ok: down: oc_id: 1s, normally up
ok: down: opscode-erchef: 0s, normally up
ok: down: redis_lb: 0s, normally up
The service postgresql is running externally and cannot be managed
vi chef-server-ctl. Please login to your instance to manage it directly.

Infra Server Upgrade] - ERROR: migration-level not initialized.
[Infra Server Upgrade] - ERROR: If this is an existing Chef Infra Server install try running chef-server-ctl rebuild-migration-state and then retry the upgrade

Later we created below file

Add below lines on below lines

             /var/opt/opscode/upgrades/migration-level

             {"major":1,"minor":34}
Then we below command executed.

chef-server-ctl rebuild-migration-state
chef-server-ctl upgrade

Failed again:

Recipe: private-chef::bootstrap

execute[/opt/opscode/bin/chef-server-ctl start postgresql] action run
================================================================================
Error executing action run on resource 'execute[/opt/opscode/bin/chef-server-ctl start postgresql]'
Mixlib::ShellOut::ShellCommandFailed
Expected process to exit with [0], but received '8'
---- Begin output of /opt/opscode/bin/chef-server-ctl start postgresql ----
STDOUT: -------------------------------------------------------------------
The service postgresql is running externally and cannot be managed
vi chef-server-ctl. Please login to your instance to manage it directly.

STDERR:
---- End output of /opt/opscode/bin/chef-server-ctl start postgresql ----
Ran /opt/opscode/bin/chef-server-ctl start postgresql returned 8

ERROR :

Reindexing all organizations

[2021-10-07T19:51:29+00:00] ERROR: Server returned error 500 for https://127.0.0.1/organizations, retrying 1/5 in 3s

[2021-10-07T19:51:32+00:00] ERROR: Server returned error 500 for https://127.0.0.1/organizations, retrying 2/5 in 8s

[2021-10-07T19:51:40+00:00] ERROR: Server returned error 500 for https://127.0.0.1/organizations, retrying 3/5 in 14s

To Reproduce

Server has been migrated from 12x to 14.x

External PgDB upgraded from 9.6 to 13.3

**Comment by lbakerchef** [comment]
Add note - issue was with schema permissions on rds.  That was causing the setup failures.
Add comment in the code - ...
