### ISSUE TITLE
Strict-Transport-Security header isn't present on all responses

### ISSUE THREAD

**Issue by hreeder** [chef/chef-server#2897]
### Chef Server Version

Infra Server 14.5.29

### Platform Details

[Operating system distribution and release version. Cloud provider and instance type if running in the cloud. Total/Free RAM and disk space. Is this running in a container?]
N/A

### Configuration

[Standalone, Tiered, HA, Chef Backend? New install or upgrade? Ideally include your /etc/opscode/chef-server.rb or otherwise provide details of changes from the default]

### Scenario

[What you are trying to achieve and you can't?]
We should have the `Strict-Transport-Security` header present in all responses

### Steps to Reproduce

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
`curl -i -k --silent https://server-url/` - Observe the headers, Strict-Transport-Security is missing.

### Expected Result

[What are you expecting to happen as the consequence of above reproduction steps?]
The Strict-Transport-Security header to be present on all responses from the server.

### Actual Result

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
The STS header only gets applied to certain paths - when tested it was present in `/_status` but not on `/` or `/version`

#### Workaround
In our scenario, as we're operating in AWS, we bake AMIs using chef-solo & packer, so this is how I've worked around it for now (after installing the deb omnibus installer):

```ruby
ruby_block 'Set STS Header' do
  block do
    sts_value = 'Strict-Transport-Security "max-age=<%= @helper.get_max_age_for_hsts %>; includeSubDomains";'
    sts_header = "      <% if @server_proto == 'https' %>add_header #{sts_value}<% end %>"
    fe = Chef::Util::FileEdit.new("/opt/opscode/embedded/cookbooks/private-chef/templates/default/nginx/nginx_chef_api_lb.conf.erb")
    fe.insert_line_after_match(/location ~ "^\/[0-9]{3,3}\.(json|html)|favicon.ico|index.html$" {/, sts_header)
    fe.insert_line_after_match(/location "\/css\/" {/, sts_header)
    fe.insert_line_after_match(/location "\/images\/" {/, sts_header)
    fe.insert_line_after_match(/location \/version {/, sts_header)
    fe.write_file
  end
  action :run
end

```

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef-server/pull/3031 and released in 14.11.36
