### ISSUE TITLE
Failed to upgrade Chef Server in hardened node

### ISSUE THREAD

**Issue by zx-progress** [chef/chef-server#2913]
### Chef Server Version
Current running version: Chef Server V12.19.26 
I'm trying to upgrade to: V14.8.7

### Platform Details
RHEL7

### Configuration
Hardened node.

### Scenario
I was trying to upgrade Chef Server from V12.19.26 to V14.8.7, following the steps in https://docs.chef.io/server/upgrades/

On one of the node, I cannot change user in Step 1.
_sudo su - opscode-pgsql_

### Steps to Reproduce
Follow the upgrade steps in https://docs.chef.io/server/upgrades/
Run _sudo su - opscode-pgsql_

### Expected Result
Chef Server upgrade successful.
If Chef Server upgrade may fail on some hardened nodes, can we have some pre-upgrade check script to check for the necessary dependencies? 

### Actual Result
It says:
_exec: /var/opt/opscode/postgresql/.profile [Permmission denied]_

**Comment by tas50** [comment]
@zx-progress We'll need more information on what a hardened node means before we can dig in here.

**Comment by PrajaktaPurohit** [comment]
Please feel free to reopen with the additional information.
