### ISSUE TITLE
Use oc-id with multiple Chef servers

### ISSUE THREAD

**Issue by smith** [chef/chef-server#292]
# Why?

If I'm running a private supermarket or other service that needs to authenticate with a Chef server via oc-id, and I have multiple Chef servers and multiple LDAP servers, I want to authenticate with the Chef user account of the server that I need.
# Acceptance Criteria
- One can configure oc-id authenticate against multiple Chef servers
- When this is configured, the user is presented with a way to select which Chef server to authenticate against
- When logged in, there is a way for the user to see which Chef server they used
- When doing key-based authentication (like when uploading a cookbook to supermarket), we can try to authenticate against multiple Chef servers using the given key pair
- oc-id has some mechanism to determine which Chef server was last used for authentication

**Comment by PrajaktaPurohit** [comment]
This might be a feature we would like to support with Automate, not as a part of Chef Infra Server omnibus build.
