### ISSUE TITLE
Adding customer external postgres upgrade with a new server fe box scenario in umbrella

### ISSUE THREAD

**Issue by vinay-satish** [chef/chef-server#2920]
### Description
Currently in the external postgres upgrade scenario we do the upgrade in the chef-server box only.

But customers usually spin up a new box, copy essential files from the old machine and install the upgrade version of chef-server and then change the external pg box to the new upgraded box. This scenario is different from the current one as there are few things which start like bootstrap.

### Related issue
https://github.com/chef/chef-server/issues/2894

### Acceptance criteria
- [ ] A working scenario in umbrella with the above details.

**Comment by PrajaktaPurohit** [comment]
Done!
