### ISSUE TITLE
backup issue while doing upgrade preparations

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2922]
We are currently in the process of preparing to upgrade our Chef Infra from 12.17.33 to Chef Infra 14.2.2 as that is the last stable release available on Xenial. Once we have performed this initial upgrade we will then migrate to latest stable Chef Infra +14.9.3 on Focal.

Currently, we are using the knife-tidy and knife-ec-backup toolset in preparation for the upgrade per the following Chef Progress blog entry https://www.chef.io/blog/migrating-chef-server-knife-ec-backup-knife-tidy. The tools are installed and operational on both a clone of our production server and our production server. Currently all knife-ec-back operations are being performed on the clone of production. So whatever remedy is applied will first need to be applied to our clone, tested, then applied to production.

We have hit a snag when running the ec backup. It appears that we have an issue accessing the "billing-admin" group's permissions which result in knife's ec back failure.

Command with concurrency 1:
/opt/chefdk/embedded/bin/knife ec backup ~/.chef/backups/ -V --only-org some_org --with-user-sql --with-key-sql --concurrency 1 -c /etc/opscode/pivotal.rb | tee knife_ec_backup_cc1_.output

Command with concurrency 20:
/opt/chefdk/embedded/bin/knife ec backup ~/.chef/backups/ -V --only-org some_org --with-user-sql --with-key-sql --concurrency 20 -c /etc/opscode/pivotal.rb | tee knife_ec_backup_cc20_.output

**Comment by lbakerchef** [comment]
See connected PR.
