### ISSUE TITLE
Chef Infra Server Backup story

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#2927]
[Placeholder]

**Comment by btm** [comment]
- Getting [knife-tidy](https://github.com/chef/knife-tidy) and [knife-ec-backup](https://github.com/chef/knife-ec-backup) cleaned up, documented, etc.
- Ask field folks of there are use cases that require those to be run on a system other than one of the Infra Servers; e.g. can we merge that functionality into `chef-server-ctl` instead?

**Comment by tas50** [comment]
Closing this out since it never became more than a placeholder
