### ISSUE TITLE
Check external pg 9.6 with 14.10

### ISSUE THREAD

**Issue by vinay-satish** [chef/chef-server#2953]
Need to check if we are backward compatible with the external pg 9.6 after changes are done to chef-server with pg 13.

**Comment by vinay-satish** [comment]
The tests are passing with the following umbrella scenario. - SCENARIO=external-postgresql PLATFORM=ubuntu-18.04 INSTALL_VERSION=14.9.23 UPGRADE_VERSION=14.10.23 ENABLE_ADDON_PUSH_JOBS=false MANAGE_VERSION=3.0.16 ENABLE_IPV6=false make apply

**Comment by PrajaktaPurohit** [comment]
Thank you!
