### ISSUE TITLE
Use bundler-audit on oc-id

### ISSUE THREAD

**Issue by smith** [chef/chef-server#298]
# Why?

To be notified of security vulnerabilities in Gem dependencies and fix them.
# Acceptance Criteria
- A rake task that gets the most recent data using https://github.com/rubysec/bundler-audit and exits non-zero if any vulnerabilities
  are found
- Travis or Delivery fails the build if any new vulnerabilities are present
- Existing vulnerabilities are patched or ignored with documentation about why they are being ignored

**Comment by PrajaktaPurohit** [comment]
Closing. Github provides us with a lot of help in this regard.
