### ISSUE TITLE
Automate mundane configuration/setup in dev vm and/or vagrant

### ISSUE THREAD

**Issue by lbakerchef** [chef/chef-server#2986]
Developers normally need to do many mundane tasks in configuration/setup by hand in order to troubleshoot or debug an issue or start an investigation using a dev vm or vagrant box, and these tasks are time-consuming and repetitive.  Examples of this are adding users, adding nodes, setting up knife or other clients, setting up and moving around security certificates, setting up `chef-server.rb`, etc.  We should automate as much of this as possible or practicable.

This 'mundane tasks' issue is not only present on the dev vm, but also on terraform boxes used for umbrella testing.  An excerpt from a `standalone-fresh-install` terraform box is depicted below, illustrating typical pain encountered:
```
root@ip-10-0-7-19:~# sudo chef-server-ctl user-create janedoe Jane Doe janed@example.com 'abc123' --filename ~/.chef/janedoe.pem
ERROR: Conflict
Response: Username or email address already in use.
root@ip-10-0-7-19:~# /opt/opscode/bin/knife node list
WARNING: No knife configuration file found. See https://docs.chef.io/config_rb/ for details.
WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/chef/client.pem>
ERROR: Your private key could not be loaded from /etc/chef/client.pem
Check your configuration file and ensure that your private key is readable
root@ip-10-0-7-19:~# mkdir -p .chef
root@ip-10-0-7-19:~# cp /home/ubuntu/janedoe.pem .chef
root@ip-10-0-7-19:~# /opt/opscode/bin/knife ssl fetch
WARNING: Certificates from api.chef-server.dev will be fetched and placed in your trusted_cert
       directory (/root/.chef/trusted_certs).

       Knife has no means to verify these are the correct certificates. You should
       verify the authenticity of these certificates after downloading.
ERROR: Network Error: getaddrinfo: Name or service not known
Check your knife configuration and network settings
```
It may be possible to do this as an epic, and have the tasks in phases or iterations.  E.g. to start, we could simply write up common tasks in a document and include the document it the appropriate place (`dev-docs` or `chef-server/dev`).  The next iteration could be to write a bash or other script for each common task.  The third iteration could be....

First iteration acceptance criteria:
A few copy/paste scripts or snippets to help automate a variety of mundane development chores.
- [x] Copy/paste script to automate knife configuration on dev vm.
- [x] Copy/paste script to automate knife configuration on terraform umbrella scenario.
- [ ] More to come...

**Comment by lbakerchef** [comment]
```
#########
# dev vm
#########

sudo -i
cd
mkdir -p .chef

# create janedoe user and 4thcafe org
sudo chef-server-ctl user-create janedoe Jane Doe janed@example.com 'abc123' --filename ~/.chef/janedoe.pem
sudo chef-server-ctl org-create 4thcafe 'Fourth Cafe, Inc.' --association_user janedoe --filename ~/.chef/4thcafe-validator.pem

# configure knife
echo "[default]
client_name     = 'janedoe'
client_key      = '~/.chef/janedoe.pem'
chef_server_url = 'https://api.chef-server.dev/organizations/4thcafe'">~/.chef/credentials
knife ssl fetch
knife ssl check
```

**Comment by lbakerchef** [comment]
Whoops, this^^ looks a lot like what's in the README.md in the chef-server repo.  Reinventing the wheel.

**Comment by lbakerchef** [comment]
I crafted this to set up knife on a terraform umbrella scenario.  Note that it is slightly different than the instructions above.
```
####################
# umbrella scenario
####################
mkdir -p .chef
root@ip-10-0-6-201:~# cp /home/ubuntu/4thcoffee-validator.pem .chef
root@ip-10-0-6-201:~# cp /home/ubuntu/janedoe.pem .chef
root@ip-10-0-6-201:~# echo "[default]
client_name     = 'janedoe'
client_key      = '~/.chef/janedoe.pem'
chef_server_url = 'https://SCENARIO-IP-ADDRESS/organizations/4thcoffee'">~/.chef/credentials
/opt/opscode/bin/knife ssl fetch
/opt/opscode/bin/knife ssl check
# the knife ssl check above will cause an error.
# to fix it, get the ip address from the line "The server's certificate belongs to..." and paste as SCENARIO-IP-ADDRESS in credentials above.
# then rerun the fetch and check above
```

**Comment by lbakerchef** [comment]
```
####################
# umbrella scenario
# configure knife (rhel)
####################

sudo -i

alias knife='/opt/opscode/bin/knife'
export EDITOR=vim

cd
mkdir -p .chef

# copy over user and org files
# this is for rhel. for ubuntu, the path is /home/ubuntu...
cp /home/ec2-user/4thcoffee-validator.pem .chef
cp /home/ec2-user/janedoe.pem .chef

# ADDRESS is the address you logged in with
echo "[default]
client_name     = 'janedoe'
client_key      = '~/.chef/janedoe.pem'
chef_server_url = 'https://ADDRESS/organizations/4thcoffee'">~/.chef/credentials
knife ssl fetch
knife ssl check

# the knife ssl check above will cause an error.
# to fix it, get the ip address from the line "The server's certificate belongs to..." and paste it over ADDRESS in credentials above.
# then rerun the fetch and check above.
```

**Comment by marcparadise** [comment]
General dev vm issues: 
- can we find a more automated way to file sync from host? 
- hot code loading works, but it's very slow for the `sync` app to scan all of the files.  Once it is done, hot compile/reload works consistently and quickly but the initial scan can take ten or more minutes before it gets to this point.

**Comment by lbakerchef** [comment]
A few requests for dev vm:

- Could we have knife already set up and configured with a default admin user - could be janedoe or whoever you find appropriate?
- Could we have things set up (alias or whatever) so that typing `knife` automatically uses the correct full path to knife (`/opt/opscode/bin/knife` or whatever)?
- Could we have `knife ec backup` already installed, configured, ready-to-use, paths set up, etc?

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/3149 - done!
