### ISSUE TITLE
Add documentation to fetch WebUI key from Server in public docs

### ISSUE THREAD

**Issue by kalroy** [chef/chef-server#2988]
Chef Server needs to have instructions in Docs page which mentions:
- What is WebUI key?
- How to fetch WebUI key from Server?

The Chef Server Web UI key is required for Automate Infra Proxy Server

**Comment by tas50** [comment]
This documentation belongs in the Automate docs from the Infra Views feature. Otherwise users are going to have to jump one from doc site to the other. We should just guide them through the whole process end to end.
