### ISSUE TITLE
 Bifrost database is growing with every sync

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef-server#3010]
We have written an internal tool to automatically sync cookbooks from a git repository to Chef Infra Server.

It performs delta syncs every minute (based on what changes in the git repo) and then perform a full sync nightly (as a backstop in case the delta syncs missed something).

What we're seeing is that the bifrost database grows by about 60MB every full sync.

Normally I wouldn't trip about this, but we just recently migrated to a new Chef Infra Server using knife-ec-backup and the bifrost database went from 140GB to 600MB. Now after just a few weeks the bifrost database is 1.39GB.

We originally did the migration because calls to bifrost was the bottleneck in Chef Infra Server being able to serve requests because the authz calls were taking up-to 6 seconds at times.

We're running chef-server-core v14.5.29 on RHEL 7.

Support Notes

This issue is down to multiple cookbook updates, however, this causes a lot of Bifrost data.

We initially had chef-server-ctl cleanup-bifrost created for ticket https://getchef.zendesk.com/agent/tickets/6991

This however does extend to all of the tables in the bifrost DB,

This bug is to resolve that.

To Reproduce

with a large bifrost DB, mainly with lots of data in the auth_object, object_acl_actor and object_acl_group tables, run chef-server-ctl cleanup-bifrost

Expected behavior

This should help in the cleardown of these older and orphaned items

Actual behavior

It does not extend to tidy up these tables in the DB

Additional context

https://github.com/chef/chef-server/blob/main/src/chef-server-ctl/plugins/cleanup_bifrost.rb

**Comment by jasonwbarnett** [comment]
I think this may have been resolved by https://github.com/chef/chef-server/pull/3275, but I would ask @vinay-satish to be sure.

**Comment by PrajaktaPurohit** [comment]
Closing, release https://docs.chef.io/release_notes_server/#14.16.19 includes the fix for the issue.
