### ISSUE TITLE
“add-user-key argument error: wrong number of arguments”

### ISSUE THREAD

**Issue by mkmcdonald** [chef/chef-server#302]
This is a cross-post from chef/chef (https://github.com/chef/chef/issues/3274).

Quoting @jdallen,

> running chef-server-ctl add-user-key leads to argument error:
>
> /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/http.rb:125:in `post': wrong
> number of arguments (0 for 2..3) (ArgumentError)
>
> The problem seems to be in the post_rest method on line 43 in: 
> /opt/opscode/embedded/service/omnibus-ctl/helpers/key_ctl_helper.rb
>
> it needs to change from:
> @chef_rest.post_rest
> to:
> @chef_rest.post_rest(url,body)

Quoting myself,

> This is a one-line fix. Please take a look at this issue, Chef Software.

**Comment by sdelano** [comment]
This has been fixed and is in Chef Server 12.1.0 RC1

**Comment by mkmcdonald** [comment]
Thank you, @sdelano.
