### ISSUE TITLE
nodes and clients not showing up in search, even after reindex

### ISSUE THREAD

**Issue by jstange** [chef/chef-server#3041]
### Chef Server Version

chef-server-core-14.11.31-1.el7.x86_64 (also 14.0.65)

Single node, no plugins or HA anything special.

### Platform Details

CentOS Linux release 7.9.2009 (Core)
t3.medium on AWS 
2.4G free on the relevant disk
Not containerized
```
MemTotal:        3818780 kB
MemFree:          782888 kB
MemAvailable:    1113020 kB
```

### Configuration

Standalone. I upgraded from 14.0.65 to 14.11.31 while trying things to fix things, to no avail.

Our configuration is nonstandard in terms of port layout and SSL restrictions, though it doesn't feel relevant.

```
server_name='<machine IP>'
api_fqdn server_name
nginx['server_name'] = server_name
nginx['enable_non_ssl'] = false
nginx['non_ssl_port'] = 81
nginx['ssl_port'] = 7443
nginx['ssl_ciphers'] = 'HIGH:!MEDIUM:!3DES:!LOW:!kEDH:!aNULL:!ADH:!eNULL:!EXP:!SSLv2:!SEED:!CAMELLIA:!PSK'
nginx['ssl_protocols'] = 'TLSv1.2'
bookshelf['external_url'] = 'https://'+server_name+':7443'
bookshelf['vip_port'] = 7443
nginx['ssl_certificate'] = '<our SSL cert>'
nginx['ssl_certificate_key'] = '<our SSL key>'
nginx['ssl_ca_path'] = '/our/ssl/ca/dir'
nginx['ssl_ca_file'] = '<our SSL CA>'
```

### Scenario

While `knife search role '*'`, `knife search client '*'`, and `knife search environment '*'` all behave correctly, node searches always returns empty results, whether invoked from recipes with `search(:node, "stuffhere")` or with `knife search`. Persists even after `chef-server-ctl reindex`, re-bootstrapping nodes, and various other kickings and proddings.

```
# knife search node '*:*' -i
0 items found
```

But there are definitely some nodes:

```
# knife node list
a_development_node
another_development_node
a_staging_node
chef_server_node
```

The log entry from the search doesn't look interesting:

```
<machine IP> - - [2021-12-23T21:06:12+00:00]  "GET /organizations/mu/search/node?q=*:*&start=0&rows=1000 HTTP/1.1" 200 "0.016" 62 "-" "Chef Infra Client Knife/16.14.1 (ruby-2.7.2-p137; ohai-16.17.0; x86_64-linux; +https://chef.io)" "127.0.0.1:8000" "200" "0.015" "16.14.1" "algorithm=sha1;version=1.1;" "my_org" "2021-12-23T21:06:12Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1061 "a096862e-e92d-4acc-b7bf-97b7716844c2"
```

If I reindex the node in question and watch the logs, I see it submit some reasonable-looking content:

2021-12-23 20:53:06.665 [info] reindexing[my_org]: reindex requested for my_org
2021-12-23 20:53:06.667 [info] reindexing[my_org]: 4 items of type node to reindex
2021-12-23 20:53:07.169 [info] reindexing[my_org]: 8 items of type role to reindex
2021-12-23 20:53:07.180 [info] reindexing[my_org]: 7 items of type environment to reindex
2021-12-23 20:53:07.191 [info] reindexing[my_org]: 5 items of type client to reindex
2021-12-23 20:53:07.211 [info] reindexing[my_org]: 8 items of type <<"some_data_bag">> to reindex
<...several dozen other data bags...>
2021-12-23 20:53:07.808 [info] reindexing[my_org]: reindex complete!
```

...but the behavior remains the same.

Also of interest is that a search on clients is also missing everything except the validator for my org user (that is, none of the node clients show up):

```
# knife search client '*'
1 items found

admin:      false
chef_type:  client
json_class: Chef::ApiClient
name:       my_org-validator
public_key:
validator:  true
```

```
# knife client list
a_development_node
another_development_node
a_staging_node
chef_server_node
my_org-validator
```

### Steps to Reproduce

See above.

### Expected Result

Wildcard search should return nodes/clients; filters should return subsets of nodes/clients.

### Actual Result

Empty results when search for nodes or clients.

**Comment by jstange** [comment]
...I got irritated over the weekend, nuked the metadata and the Chef Server installation, and rebuilt it from scratch. Search works again, which fixes my immediate problem.

I think it's the second time this particular installation has exhibited this behavior. If memory serves, it was originally created from a backup (in the `chef-server-ctl backup/restore` sense), which is all that distinguishes it from our other, relatively well-behaved installations.

I preserved a copy of the dysfunction first, in case anyone wants to dissect it later.

**Comment by jpc-Arkea** [comment]
We believe that this incident is close or [similar to yours](https://github.com/chef/chef-server/issues/3109)

Did you find a fix ?

**Comment by jashaik** [comment]
@jstange Could you please try the below solution which solved for @jpc-Arkea .

Reference - https://github.com/chef/chef-server/issues/3109#issuecomment-1022084825
-----------------------------------------------------------------------------------------
Our problem is solved : Elastic indexes were read_only
You can see index read-only by a tcpdump on 9200 port : tcpdump -i any -A port 9200
something like this :
{"took":0,"errors":true,"items":[{"index":{"_index":"chef","_type":"object","_id":"582ff685300a61234af803a95db0968c","status":403,"error":{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}}}]}

You can disable read_only mode by followed command :
curl -XPUT -H "Content-Type: application/json" http://127.0.0.1:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'
----------------------------------------------------------------
Please try the above soltuion and update us.
