### ISSUE TITLE
External Opensearch Support

### ISSUE THREAD

**Issue by jashaik** [chef/chef-server#3068]
1. Chef-server should support external opensearch 
2. All the chef-server tests should be green

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/pull/3047

**Comment by jashaik** [comment]
@PrajaktaPurohit Subtasks to be created
1. Erchef side auth changes & omnibus changes -> @jashaik 
2. Metrics &  tests -> @vinay-satish

**Comment by PrajaktaPurohit** [comment]
Add provision-opensearch scripts to dvm setup.

**Comment by PrajaktaPurohit** [comment]
https://chefio.atlassian.net/browse/INFS-2
