### ISSUE TITLE
Investigate Datadog or some other better monitoring tools for load testing

### ISSUE THREAD

**Issue by jashaik** [chef/chef-server#3069]
# Redirect Alert!

## Submit your feature request via the [Chef Ideas Portal](https://chef-software.ideas.aha.io/)
Investigate and add support of monitoring tools in the chef-server to help load testing.

1. Verify Existing data dog monitoring tools with the help of support team
2. Identify other monitoring tools if the data dog is not in the place.

**Comment by PrajaktaPurohit** [comment]
https://chefio.atlassian.net/browse/INFS-187
