### ISSUE TITLE
Upgrade to rails 7 and ruby 3+ in oc-id

### ISSUE THREAD

**Issue by saghoshprogress** [chef/chef-server#3094]
- [  ] Upgrade to ruby (3+)
- [  ]  Upgrade to rails 7 
- [  ] Test the new Build 
- [  ] Test the build-kite Pipeline

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/chef-server/issues/2936

**Comment by PrajaktaPurohit** [comment]
https://chefio.atlassian.net/browse/INFS-9
