### ISSUE TITLE
Need to be able to set proxy environment variables in keepalived's cluster.sh script

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#327]
After spending a lot of time troubleshooting a customer's new Chef Server HA cluster using chef-ha it turned out the cause of the failure to failover properly was the chef-ha scripts were unable to use the proxy server.

The keepalived scripts that handle detaching/attaching the AWS storage and secondary IP couldn't connect to the external AWS host `https://ec2.us-west-2.amazonaws.com`. Setting the `http_proxy` and `https_proxy` environment variables enabled the communication but when the scripts queried the internal uri `http://169.254.169.254/latest/dynamic/instance-identity/document` the proxy server's instance-id was always returned instead of the actual instance making the query. The customer fixed this by setting the `no_proxy` environment variable.

Some examples of the need for these proxy settings are explained in the following documentation.

http://docs.aws.amazon.com/cli/latest/userguide/cli-http-proxy.html

The tricky part about these environment variables is that they don't need to be set in the user's session. They need to be set in the `/var/opt/opscode/keepalived/bin/cluster.sh` file so when keepalived runs the `cluster.sh` script to transition the state of each backend the environment variables are accessible for the scripts that handle detaching/attaching the AWS storage and secondary IP. After setting the environment variables in `cluster.sh` we were able to successfully test a failover by stopping keepalived on the master (active) backend.

The trouble with adding the variables directly to `/var/opt/opscode/keepalived/bin/cluster.sh` is that a `chef-server-ctl reconfigure` will erase the changes. This can be avoided by making the changes in the template file `/opt/opscode/embedded/cookbooks/private-chef/templates/default/cluster.sh.erb` and then running `chef-server-ctl reconfigure` to apply the changes to the final destination `/var/opt/opscode/keepalived/bin/cluster.sh`. Even these changes will eventually be lost whenever you install a new chef-server-core package so ultimately the real solution is to add new configuration options to handle these variables.

Can someone please provide the ability to set the following environment variables in the `cluster.sh` file.

```
export HTTP_PROXY=http://username:password@a.b.c.d:n
export HTTPS_PROXY=http://username:password@w.x.y.z:m
export NO_PROXY=169.254.169.254
```

**Comment by irvingpop** [comment]
hey @jeremiahsnapp -  my PR to add proxy support to chef-ha was merged a few weeks ago, but needs to be released: https://github.com/chef/chef-ha/pull/6
cc: @stevendanna

**Comment by jeremiahsnapp** [comment]
That's awesome @irvingpop . Thanks for the heads up.
