### ISSUE TITLE
EC11 to CS12 upgrade uses `make` command which crashes the upgrade when not available

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#33]
The new way of running the sqitch migration uses `make` but if that's not available then the upgrade crashes. It wasn't available in my test environment and I saw it crash another user's environment.

https://github.com/opscode/opscode-omnibus/blob/12.0.0-rc.7/files/private-chef-upgrades/001/014_upgrade_migration_schema.rb#L8

The old way of running the sqitch migration doesn't use `make` so we haven't run into this problem before.

https://github.com/opscode/opscode-omnibus/blob/12.0.0-rc.7/files/private-chef-upgrades/001/013_bcrypt_users.rb#L7-L10

@sdelano suggested to me that "We should just fix it not to run make"

In the meantime, the requirement has been added to the upgrade docs.

**Comment by jacobvosmaer** [comment]
This issue bit me too.

Where are the upgrade docs? Not linked here https://www.chef.io/blog/2014/12/16/release-chef-client-12-0-3/ .

`apt-get install make` fixed the problem for me.

**Comment by jeremiahsnapp** [comment]
Hi @jacobvosmaer, you hit this bug while upgrading the Chef Server right? Not the Chef Client.

The [Chef Server upgrade docs](http://docs.chef.io/server/upgrade_server.html#standalone) do mention that the `make` command must be installed on the Chef Server.

**Comment by jacobvosmaer** [comment]
Yes I was upgrading Chef Server (12.0.0 to 12.0.3), and no I did not look at the upgrade docs before I did that.

I find the upgrade docs rather intimidating, but they do make a point of installing `make`.

**Comment by mmzyk** [comment]
@jacobvosmaer Can you explain what makes the docs intimidating? We've been investing a lot of effort to make them better and more accessible, so feedback on this is good.

**Comment by jacobvosmaer** [comment]
Thanks for asking @mmzyk .

> There are two upgrade scenarios for upgrades from earlier versions of Chef server 12 to newer versions of Chef server 12: high availability and standalone. The steps for each scenario are identical to the steps for upgrades from Enterprise Chef. See the appropriate sections below and follow the same steps.

This is confusing for someone who has not been using Enterprise Chef. It would also help to have links that take you to the 'appropriate sections'.

Once I get to my section, I get the feeling I must be looking at the wrong documentation. Nowhere in the [standalone section](http://docs.chef.io/server/upgrade_server.html#standalone) is the 'upgrade from CS 12' scenario mentioned again. I never installed 'Enterprise Chef' or typed 'private-chef-ctl' before. I feel lost and I stop reading.

Looking back, it seems these steps would have worked for me:
- install `make`
- install the new .deb
- `chef-server-ctl upgrade`
- `chef-server-ctl start`

**Comment by mmzyk** [comment]
@jacobvosmaer Thanks. I'll make sure our doc writer gets this feedback.

**Comment by schisamo** [comment]
Per the issue description, can we also just fix the core issue and not use `make` to execute sqitch? Sqitch has it's own binary.

**Comment by stevendanna** [comment]
This issue was fixed in Chef 12.0.6
