### ISSUE TITLE
Logjam

### ISSUE THREAD

**Issue by damm** [chef/chef-server#333]
Hi,

I recently deployed Chef-server 12.0.8 and after testing w/ https://www.ssllabs.com/ssltest I got a grade B.

> This server supports weak Diffie-Hellman (DH) key exchange parameters. Grade capped to B. [Weakdh](https://weakdh.org/)

**Comment by stevendanna** [comment]
@damm Thanks for taking the time to file this issue.  This will be resolved in 12.1 which uses a 2048 bit prime (and allows you to specify a stronger one if desired): https://github.com/chef/chef-server/pull/301

**Comment by damm** [comment]
@stevendanna Awesome I did not see anything related to Logjam specifically so I made this ticket.
