### ISSUE TITLE
ssl_dhparam should be exposed for nginx in chef-server.rb

### ISSUE THREAD

**Issue by jblaine** [chef/chef-server#349]
Via the ssl_dhparam configuration variable `ssl_dhparam`, nginx has support for pointing to a site-unique and strong Diffie-Hellman group. Reference https://weakdh.org/ and https://weakdh.org/sysadmin.html

I'm proposing that this variable be exposed + used via chef-server.rb, as in:

`nginx['ssl_dhparam'] = '/etc/dhparams.pem'`

**Comment by stevendanna** [comment]
@jblaine That will be exposed in 12.1.0 and by default we will be creating a 2048 bit dhparam:

https://github.com/chef/chef-server/commit/2b50eb4c985ed98c813788acf46a4565b628fd70

Thanks for taking the time to report this.
