### ISSUE TITLE
Add show-versions Subcommand to Omnibus-ctl

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#35]
https://github.com/opscode/omnibus-ctl/pull/19

**Comment by sdelano** [comment]
This still looks good. Let's get chef/omnibus-ctl#19 rebased and merged and then get a PR here to bump the `omnibus-ctl` version.

**Comment by sean-horn** [comment]
I'll close the Manage one https://github.com/chef/omnibus-ctl/pull/21 in favor of this more global work

**Comment by tas50** [comment]
Closing this out at this point since Manage is going to be EOL at the end of the year and we're not further developing functionality for it.
