### ISSUE TITLE
 chef-server-ctl org-create is broken in 12.4.0.rc.2

### ISSUE THREAD

**Issue by DKlotz-APS** [chef/chef-server#356]
No matter what you put in the command:
In example:
chef-server-ctl org-create Test "Test123"

you always get:
ERROR: The data in your request was invalid
Response: Field 'name' invalid

**Comment by DKlotz-APS** [comment]
Version is 12.4.0.rc.2

**Comment by stevendanna** [comment]
Thanks for taking the time to file this ticket.  I believe the problem is your capitalized name.  It appears that only lowercase names are allowed:

https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/oc_chef_authz/src/oc_chef_organization.erl#L192

**Comment by brianhussey** [comment]
I had the same issue, dropping case resolved it.

**Comment by gamedesigngroup** [comment]
Same issue, not resolved by using lowercase
