### ISSUE TITLE
oc-id sign up url not configurable; regression

### ISSUE THREAD

**Issue by mmzyk** [chef/chef-server#363]
With the 12.1 release, the oc-id signup url is now set to point to hosted and isn't respecting the signup url config value.

In this commit https://github.com/chef/chef-server/commit/32f7bdf097e00f897a165f83342b5751ecad5a14 we were too over-eager in converting to chef-web-core and change oc-id to use the value there and removed the option to have it be set by the local value.

/cc @cnunciato. I'd swap it back myself, but I'm a bit uncertain on how things play with chef-web-core. Is this a matter of making it sign_up_url again and adding back the delegate in the asset helper class?

**Comment by mmzyk** [comment]
Here is the original PR that implemented making the links configurable, for reference: https://github.com/chef/oc-id/pull/38

**Comment by mmzyk** [comment]
Also, @jamescott, the sign_up_url parameter is missing from the docs.

If should be here: https://docs.chef.io/config_rb_server_optional_settings.html#oc-id

oc_id['sign_up_url'] = "example.com"

Configures where the sign up link for oc-id goes to. Defaults to https://#{node['private_chef']['api_fqdn']}/signup if not specified.

**Comment by tas50** [comment]
Closing as a won't fix since we're not going to be expanding oc-id going forward.
