### ISSUE TITLE
Unable to add or replace user keys

### ISSUE THREAD

**Issue by rhass-r7** [chef/chef-server#364]
I am unable to replace/add user keys on the Chef server when running `sudo chef-server-ctl add-user-key rhass .chef/keys/rhass.pub --key-name test --expiration-date 2025-07-01T00:00:00Z` as the following error occurs:

```
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/http.rb:125:in `post': wrong number of arguments (0 for 2..3) (ArgumentError)
    from /opt/opscode/embedded/service/omnibus-ctl/helpers/key_ctl_helper.rb:43:in `post_rest'
    from (eval):128:in `block (2 levels) in load_files'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.4/lib/omnibus-ctl.rb:177:in `call'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.4/lib/omnibus-ctl.rb:177:in `block in add_command_under_category'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.4/lib/omnibus-ctl.rb:566:in `run'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.4/bin/omnibus-ctl:31:in `<top (required)>'
    from /opt/opscode/embedded/bin/omnibus-ctl:23:in `load'
    from /opt/opscode/embedded/bin/omnibus-ctl:23:in `<main>'
```

The expected behavior is for the command to pass the correct number of arguments into method which is being called.

**Comment by rhass-r7** [comment]
This issue appears to be resolved in Chef Server 12.1. I am not sure if there is intention to keep supporting 12.0.x, if not -- then I will close this issue.

**Comment by rhass-r7** [comment]
There is a bug in the 12.0 implementation in which keys can be added without a name value, which results in an unamed key which can no longer be removed.

**Comment by PrajaktaPurohit** [comment]
This will be checked as a part of #365. Closing.
