### ISSUE TITLE
Upgrade from OSC 11.1 to Chef server 12.1 fails.

### ISSUE THREAD

**Issue by mmzyk** [chef/chef-server#371]
It appears that for any user upgrading from the open source Chef server 11.1 or greater to Chef server 12.1 the upgrade will fail.

The work around is to upgrade to 12.0.8, uninstall the Chef 11.x server on the system, then upgrade to 12.1 from 12.0.8, as that will succeed.

The issue is that as the upgrade nears completion it tries to upload the data to the now running Chef server 12.1 instance. This runs afoul with an error message about violating the new v1 protocol that was introduced in 12.1: 

```
$ /opt/opscode/embedded/bin/knife ec restore -VV --skip-useracl --with-user-sql --concurrency 10 -c /tmp/knife-ec-backup-config.rb /path/to/chef12/data

ERROR: /clients/claracache002iad.io.orgnamechanged.info.json failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Since Server API v1, all keys must be updated via the keys endpoint. "]}
INFO: HTTP Request Returned 400 Bad Request: error
```

This error message was found by running the knife-ec-restore command that is used by the upgrade process by hand, as the upgrade process obscures it. It might be that this error only results if clients are being migrated, but I have to believe that will be true for most systems attempting this migration.

**Comment by tylercloke** [comment]
Testing fix: http://wilson.ci.chef.co/job/chef-server-12-trigger-ad_hoc/600/downstreambuildview/

**Comment by tylercloke** [comment]
https://github.com/chef/chef-server/pull/392

**Comment by tylercloke** [comment]
Fixed in next release of Chef Server (version 12.1).

**Comment by tylercloke** [comment]
Fixed in next release of Chef Server (version 12.1).

**Comment by sean-horn** [comment]
Please take 12.1.0 off of the download site. It will be hanging around, waiting to catch folks late to upgrade.
