### ISSUE TITLE
CS 12.1.0 nginx can't reach OC-ID if localhost resolves to IPv6 address

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#375]
[Chef Server 12.1.0 OC-ID uses rails 4.2.0](https://github.com/chef/chef-server/blob/12.1.0/src/oc-id/Gemfile.lock#L267) which [now listens on localhost instead of 0.0.0.0 by default](http://guides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server).

If `/etc/hosts` has localhost resolving to both IPv4 and IPv6 IP addresses then rails will bind to the IPv6 address. This breaks access to OC-ID because `oc_id['vip']` [currently defaults](https://github.com/chef/chef-server/blob/12.1.0/omnibus/files/private-chef-cookbooks/private-chef/attributes/default.rb#L518) to `127.0.0.1`. This breaks OAuth login for private Supermarket and Analytics servers.

Proposed fix is to change the default to be `oc_id['vip'] = 'localhost'`. This fix works in my test server.

**Comment by pmoosh** [comment]
Yep - happens to me as well. Currently I just remove the localhost entry for IPV6 address. I would assume it should listen on IPV4 as well as IPV6

**Comment by juliandunn** [comment]
@jeremiahsnapp can you submit a PR with that?

**Comment by mmzyk** [comment]
This change was merged to master with this commit: https://github.com/chef/chef-server/commit/1570533ba0fed8c2784dfb585f8bc26c2b43a611

**Comment by mmzyk** [comment]
And this should ship with the next server release.
