### ISSUE TITLE
Password-based auth will fail for installations upgraded from early 11.x EC and 1.4

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#39]
The final portion of this change which invoked chef-mover to upgrade users to bcrypt-sha1 encryption  was never merged in: 

https://github.com/opscode/opscode-omnibus/pull/212/files#diff-065818c635e5d9c58ec887ed71a64cbdR22

Note that the underlying schema change exists in the current 'migration 13', but the migration does not include the execution of chef-mover to update the data: https://github.com/opscode/opscode-omnibus/blob/master/files/private-chef-upgrades/001/013_bcrypt_users.rb

Because the conversion is never done, data is not migrated from the legacy password (sha1) to the new password form (sha1-bcrypt intermediate stage, or bcrypt). 

Secondarily,   `oc_erchef` no longer looks in `users.serialized_object` field to validate a user's password, instead expecting them to  exist in the password-related columns of the user table.
### Impacts
- If an installation of chef server originated at 11.1.x  or earlier,  password data for users created prior to 11.2.x  is kept in the older sha1 hash format until they log in successfully via web ui. 
- if a certain upgrade path is followed, users will not be able to log into manage under 12.x (or directly authenticate against the `/authenticate_user` endpoint) until a password reset is performed for that user account. 
### Who Impacted
- Installations of chef server that have upgraded from 11.1 or 1.4 -> 11.2 
- Installations of chef server that have upgraded from 11.x -> 12.x 
### Not impacted
- Users created after installation 11.2 or higher
- New installations that started after 11.2 or higher 
- users imported via upgrade from OSC 11. 
### Exceptions
- if a user logged in while 11.2.x was installed, their password would have have been updated to the new format in the process of logging in.

**Comment by PrajaktaPurohit** [comment]
Closing since this is no longer relevant. Sorry for the inconvenience caused.
