### ISSUE TITLE
chef server core 12.0 rc6 rpm thinks its newer than ga

### ISSUE THREAD

**Issue by andrewelizondo** [chef/chef-server#40]
Attempting to upgrade from chef server 12 rc6 to the ga release prompted the following.

$ rpm -Uvh chef-server-core-12.0.0-1.el6.x86_64.rpm
warning: chef-server-core-12.0.0-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
Preparing...                ########################################### [100%]
        package chef-server-core-12.0.0_rc.6-1.el6.x86_64 (which is newer than chef-server-core-12.0.0-1.el6.x86_64) is already installed

**Comment by sdelano** [comment]
@stevendanna @schisamo - I know we've gone a bit of the ways towards addressing this issue, but where do we currently stand?

Will RC releases still show up as being newer than the GA releases?

**Comment by schisamo** [comment]
This was fixed with: https://github.com/chef/omnibus/commit/0d5e3d137719034e4b21d9b75302843702b575a0

From what I can tell CS 12.0.3+ should be G2G.

**Comment by stevendanna** [comment]
I'm going to close this out.  Our packaging infrastructure has changed substantially from the time this was filed and we believe this issue to be resolved.
