### ISSUE TITLE
chef-server-core_12.1.0-1 fails to install on ubuntu

### ISSUE THREAD

**Issue by spuder** [chef/chef-server#422]
Installing chef-server on a brand new VM fails with error: 

```
undefined method `exitstatus' for nil:NilClass (NoMethodError)
```

Steps to reproduce:

``` bash
mkdir foobar; cd foobar
vagrant init (Change the 'base' box to 'ubuntu/trusty64'
vagrant up
vagrant ssh
sudo su -
wget https://web-dl.packagecloud.io/chef/stable/packages/ubuntu/trusty/chef-server-core_12.1.0-1_amd64.deb
dpkg -i chef-server-core_12.1.0-1_amd64.deb
chef-server-ctl reconfigure
```

``` bash
    ================================================================================
    Error executing action `run` on resource 'execute[oc_id_schema]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received ''
    ---- Begin output of bundle exec rake db:migrate ----
    STDOUT:
    STDERR: no ruby in PATH/CONFIG
    ---- End output of bundle exec rake db:migrate ----
    Ran bundle exec rake db:migrate returned

    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/oc_id.rb

    130: execute "oc_id_schema" do
    131:   command "bundle exec rake db:migrate"
    132:   path ["/opt/opscode/embedded/bin"]
    133:   cwd "/opt/opscode/embedded/service/oc_id"
    134:
    135:   # There are other recipes that depend on having a VERSION environment
    136:   # variable. If that environment variable is set when we run `rake db:migrate`,
    137:   # and it is set to something the migrations do not expect, this will
    138:   # break.
    139:   #
    140:   # We want to migrate to the latest version, which we can get by looking at the
    141:   # date prefix of the latest file in the db/migrate directory.
    142:   #
    143:   # Also set the RAILS_ENV as is needed.
    144:   environment("RAILS_ENV" => "production",
    145:               "VERSION" => `ls -1 /opt/opscode/embedded/service/oc_id/db/migrate | tail -n 1 | sed -e "s/_.*//g"`.chomp)
    146:
    147:   only_if { is_data_master? }
    148: end
    149:
    150: component_runit_service "oc_id" do
    151:   package 'private_chef'
    152: end
    153:
    154: if node['private_chef']['bootstrap']['enable']
    155:   execute "/opt/opscode/bin/private-chef-ctl start oc_id" do
    156:     retries 20
    157:   end
    158: end
    159:

    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/oc_id.rb:130:in `from_file'

    execute("oc_id_schema") do
      action :run
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "bundle exec rake db:migrate"
      backup 5
      cwd "/opt/opscode/embedded/service/oc_id"
      environment {"RAILS_ENV"=>"production", "VERSION"=>"20140313153625"}
      path ["/opt/opscode/embedded/bin"]
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "oc_id"
      only_if { #code block }
    end

Recipe: private-chef::rabbitmq
  * execute[restart_rabbitmq_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/rabbitmq/log
Recipe: private-chef::postgresql
  * runit_service[postgresql] action restart
    - restart service runit_service[postgresql]
  * execute[restart_postgresql_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/postgresql/log
Recipe: private-chef::oc_bifrost
  * runit_service[oc_bifrost] action restart
    - restart service runit_service[oc_bifrost]
  * execute[restart_oc_bifrost_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/oc_bifrost/log
Recipe: private-chef::oc_id
  * runit_service[oc_id] action restart

    ================================================================================
    Error executing action `restart` on resource 'runit_service[oc_id]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
    STDOUT: fail: /opt/opscode/service/oc_id: unable to change to service directory: file does not exist
    STDERR:
    ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
    Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id returned 1

    Cookbook Trace:
    ---------------
    /opt/opscode/embedded/cookbooks/cache/cookbooks/runit/libraries/provider_runit_service.rb:184:in `restart_service'

    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb

     37:   runit_service component do
     38:     action :enable
     39:     retries 20
     40:     control params[:control] if params[:control]
     41:     options(
     42:       :log_directory => log_directory
     43:     )
     44:     params[:runit_attributes].each do |attr_name, attr_value|
     45:       send(attr_name.to_sym, attr_value)
     46:     end
     47:   end
     48:

    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/enterprise/definitions/component_runit_service.rb:37:in `block in from_file'

    runit_service("oc_id") do
      params {:package=>"private_chef", :log_directory=>nil, :svlogd_size=>nil, :svlogd_num=>nil, :ha=>nil, :control=>nil, :runit_attributes=>{}, :action=>:enable, :name=>"oc_id"}
      provider Chef::Provider::Service::Runit
      action :enable
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 20
      retry_delay 2
      default_guard_interpreter :default
      service_name "oc_id"
      pattern "oc_id"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service"
      sv_bin "/opt/opscode/embedded/bin/sv"
      sv_dir "/opt/opscode/sv"
      service_dir "/opt/opscode/service"
      lsb_init_dir "/opt/opscode/init"
      options {:log_directory=>"/var/log/opscode/oc_id"}
      log true
      restart_on_update true
      run_template_name "oc_id"
      log_template_name "oc_id"
      check_script_template_name "oc_id"
      finish_script_template_name "oc_id"
      sv_templates true
      service_mirror # Declared in

    service("oc_id") do
      provider Chef::Provider::Service::Simple
      action :nothing
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "oc_id"
      pattern "oc_id"
      start_command "/opt/opscode/embedded/bin/sv start /opt/opscode/service/oc_id"
      stop_command "/opt/opscode/embedded/bin/sv stop /opt/opscode/service/oc_id"
      status_command "/opt/opscode/embedded/bin/sv status /opt/opscode/service/oc_id"
      restart_command "/opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id"
    end

      declared_type :runit_service
      cookbook_name "private-chef"
      recipe_name "oc_id"
    end


Running handlers:
[2015-07-13T15:21:36+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-13T15:21:36+00:00] ERROR: Exception handlers complete
Chef Client failed. 135 resources updated in 287.183962046 seconds
[2015-07-13T15:21:36+00:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
[2015-07-13T15:21:36+00:00] FATAL: Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
```

**Comment by spuder** [comment]
This is an ordering problem. Reproduced again. The work around is to stop chef, and reconfigure again. 

```bash
chef-server-ctl reconfigure
# Wait for error
chef-server-ctl stop
chef-server-ctl reconfigure
```

**Comment by karnold** [comment]
Im experiencing the same issue.  any luck resolving this?

**Comment by spuder** [comment]
Unfortunately I can't remember exactly what I did to work around it. Looking at my bash history, I believe it was as simple as rebooting the machine and manually stopping all dependent services. (rabbitmq, postgres, ect...)


```
  404  15/10/15 11:43:01 chef-server-ctl stop & chef-server-ctl start & chef-server-ctl tail
  405  15/10/15 11:43:01 chef-server-ctl reconfig
  406  15/10/15 11:43:01 chef-server-ctl reconfigure
  407  15/10/15 11:43:01 chef-server-ctl status
  408  15/10/15 11:43:01 chef-server-ctl test
  409  15/10/15 11:43:01 chef-server-ctl status
  410  15/10/15 11:43:01 chef-server-ctl restart
  411  15/10/15 11:43:01 chef-server-ctl test
  412  15/10/15 11:43:01 chef-server-ctl status
  413  15/10/15 11:43:01 chef-server-ctl tail
  414  15/10/15 11:43:01 chef-server-ctl reconfigure
  415  15/10/15 11:43:01 chef-server-ctl restart
  416  15/10/15 11:43:01 chef-server-ctl upgrade
  417  15/10/15 11:43:01 chef-server-ctl status
  418  15/10/15 11:43:01 chef-server-ctl reconfigure
  419  15/10/15 11:43:01 chef-server-ctl restart
  420  15/10/15 11:43:01 reboot
  421  15/10/15 11:43:01 chef-server-ctl tail
  422  15/10/15 11:43:01 chef-server-ctl test
  423  15/10/15 11:43:01 apt-get update
  424  15/10/15 11:43:01 apt-get upgrade
  425  15/10/15 11:43:01 opscode-reporting-ctl reconfigure
```

**Comment by stenio123** [comment]
This happened to me after I had an error during installation. The solution was to reset the machine.

**Comment by lioramilbaum** [comment]
I am facing similar problems during the chef-server cookbook run:
https://github.com/chef-cookbooks/chef-server/issues/125

Any idea how to fix it?

**Comment by desktophero** [comment]
Ran into this before moving away from a `t2.micro` instance. Forgot to triple check the mins on hardware reqs for Chef Server.

**Comment by nealbrown** [comment]
Just another data point: vm with 4 vCPU / 4G was failing, 8 vCPU / 16G succeeded, 

on chef-server-core_12.15.8-1_amd64.deb and https://github.com/chef-cookbooks/chef-server/releases/tag/v5.4.0, gives the following error but proceeds:

`* execute[chef-server-core-reconfigure] action run[2017-07-24T10:36:56-07:00] INFO: Processing execute[chef-server-core-reconfigure] action run (/home/user/.chef/local-mode-cache/cache/cookbooks/chef-ingredient/libraries/chef_ingredient_provider.rb line 105)

      [execute] 
                ================================================================================
                Error executing action `run` on resource 'ruby_block[restart_service]'
                ================================================================================
                
                Mixlib::ShellOut::ShellCommandFailed
                ------------------------------------
                Expected process to exit with [0], but received '1'
                ---- Begin output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
                STDOUT: timeout: run: /opt/opscode/service/oc_id: (pid 8858) 31s, got TERM
                STDERR: 
                ---- End output of /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id ----
                Ran /opt/opscode/embedded/bin/sv restart /opt/opscode/service/oc_id returned 1
                
                Cookbook Trace:
                ---------------
                /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `tap'
                /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:174:in `safe_sv_shellout!'
                /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/helpers.rb:202:in `restart_service'
                /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:56:in `block (3 levels) in <class:RunitService>'
                /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:282:in `block in <class:RunitService>'
                
                Resource Declaration:
                ---------------------
                # In /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb
                
                 53:         ruby_block 'restart_service' do
                 54:           block do
                 55:             action_enable
                 56:             restart_service
                 57:           end
                 58:           action :nothing
                 59:           only_if { new_resource.restart_on_update && !new_resource.start_down }
                 60:         end
                 61: 
                
                Compiled Resource:
                ------------------
                # Declared in /var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:53:in `block in <class:RunitService>'
                
                ruby_block("restart_service") do
                  action [:nothing]
                  retries 0
                  retry_delay 2
                  default_guard_interpreter :default
                  block_name "restart_service"
                  declared_type :ruby_block
                  cookbook_name "private-chef"
                  block #<Proc:0x00000008244c28@/var/opt/opscode/local-mode-cache/cookbooks/runit/libraries/provider_runit_service.rb:54>
                  only_if { #code block }
                end
                
                Platform:
                ---------
                x86_64-linux
                
                Chef Server Reconfigured!
[2017-07-24T10:41:03-07:00] INFO: execute[chef-server-core-reconfigure] ran successfully
      - execute chef-server-ctl reconfigure
  
`

**Comment by emhohensee** [comment]
This was a hardware resources issue with me. I was able to successfully run `chef-server-ctl reconfigure` on a 2 CPU 2GB RAM Digital Ocean droplet.

**Comment by PrajaktaPurohit** [comment]
Sorry it took so long to respond to your issue! Currently we run the Chef Infra Server test pipeline with a t3.medium instance (2 VCPUs and 4 GB memory). And that does not seem to run into issues. We would recommend using instances larger than this. Closing for now, please feel to open if you see this issue on larger instances with newer builds.
