### ISSUE TITLE
ssl err while configuring chef server 12

### ISSUE THREAD

**Issue by harsh3265** [chef/chef-server#428]
Hey Guys,
im a beginner in chef server.Iam facing a probelm while config the chef server.it gives ssl validation failure connecting to my host ip:192.168.33.10.i tried the steps of following two url:
1)http://jtimberman.housepub.org/blog/2014/12/11/chef-12-fix-untrusted-self-sign-certs/ 
2)https://www.chef.io/blog/2014/12/12/chef-12-fix-untrusted-self-signed-certificates/
still the ssl val;idation fails for my hostname:192.168.33.10.
my knife.rb config file is as follows:
 # See https://docs.getchef.com/config_rb_knife.html for more information on knife configuration options

current_dir = File.dirname(**FILE**)
log_level                :info
log_location             STDOUT
node_name                'harsh180'
client_key               '/chef-repo/.chef/harsh180.pem'
validation_client_name   'mycompany-validator'
validation_key           '/chef-repo/.chef/mycompany-validator.pem'
chef_server_url          'https://192.168.33.10'
cookbook_path            [ '/chef-repo/cookbooks' ]
its a very BIG hurdle for me.I trying to configure this since 3days.
Please Help.

**Comment by stevendanna** [comment]
Apologies that no one responded to this issue.  I'm closing it now, but if you still require help with anything related to Chef, please let us know.
