### ISSUE TITLE
chef-server upgrade failure 14.04 12.0.8-1 -> 12.1.1-1

### ISSUE THREAD

**Issue by idistech** [chef/chef-server#431]
Hi All, 

We have just run a normal upgrade on ubuntu 14.04 lts, and hit a bit of brick wall.

Upgrade via apt-get update
# dpkg -l | grep chef

ii  chef                                      12.4.1-1                                            amd64        The full stack of chef
ii  chef-server-core                          12.1.1-1                                            amd64        The full stack of chef-server
ii  chef-sync                                 1.0.0-rc.3-1                                        amd64        The full stack of chef-sync

Any running of chef-server-ctl produces the following error.
# chef-server-ctl status

/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:163:in `eval': uninitialized constant DateTime (NameError)
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:55:in`require'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.2.1/lib/ffi_yajl/ext.rb:42:in `<class:Encoder>'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.2.1/lib/ffi_yajl/ext.rb:41:in`module:FFI_Yajl'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.2.1/lib/ffi_yajl/ext.rb:30:in `<top (required)>'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:55:in`require'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:55:in `require'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.2.1/lib/ffi_yajl.rb:45:in`<top (required)>'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:55:in `require'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:55:in`require'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.0.current.0/lib/chef/json_compat.rb:20:in `<top (required)>'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:55:in`require'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:55:in `require'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.0.current.0/lib/chef/key.rb:19:in`<top (required)>'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:60:in `require'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:60:in`rescue in require'
    from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/custom_require.rb:35:in `require'
    from (eval):20:in`load_file'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:163:in `eval'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:163:in`load_file'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:158:in `block in load_files'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:157:in`each'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:157:in `load_files'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/bin/omnibus-ctl:29:in`<top (required)>'
    from /opt/opscode/embedded/bin/omnibus-ctl:23:in `load'
    from /opt/opscode/embedded/bin/omnibus-ctl:23:in`<main>'

Any answers/thoughts greatly appreciated.

**Comment by idistech** [comment]
Update ..
We had this working fine for many months, system has upgraded many times.

Ive seen the 
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same ruby VM
falling back to ffi which might work (or might not, no promises)


error appear, which I know is mentioned elsewhere, but not service effecting.. Our error above seems to touch on ffi_yaj .. 

Ubuntu 14.04 is stuck on ruby 1.9.3, dont now of this is a pointer

# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/1.9.1
  - RUBY EXECUTABLE: /usr/bin/ruby1.9.1
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/1.9.1
     - /root/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin

**Comment by marcparadise** [comment]
Hi there! Sorry to hear you've run into issues - I was just going to ask what version upgrading from->to, then I saw you changed the title.  Do you have any add-ons installed?

**Comment by idistech** [comment]
HI, thanks for the response ;-)

opscode-manage
opscode-reporting
I think, ( as per originally the instructions on https://docs.chef.io/install_server.html )

Can you confirm where this data might be stored, so I can check ?

PS : Ive downgraded back to 12.0.8 and server has come alive again .. 

Many. many thanks
G

**Comment by marcparadise** [comment]
Glad to hear you were able to downgrade to 12.0.8 in the interim.  I can't easily get that info this second but will post it as soon as I can.  We are tracking a separate issue that may be related.  I will keep you posted.

**Comment by PrajaktaPurohit** [comment]
Apologies we could not get back to you sooner. Closing this issue for now. Please feel free to reopen if it continues to happen with Ubuntu 16.04 or later and with the later versions of Chef Infra Server. (Stable release is 13.2.0)
