### ISSUE TITLE
can't install add-ons in 12.1.1 over command-line

### ISSUE THREAD

**Issue by juliandunn** [chef/chef-server#434]
Someone reported this one in IRC, so I decided to validate it myself, and yeah, it looks like a bug:

http://pastebin.com/raw.php?i=9RgzP7YH

To repro it yourself, use the `chef-server` cookbook and fire up a standalone Ubuntu Chef server.

**Comment by stevendanna** [comment]
The underlying chef-client issue has been fixed on master so this bug will be fixed in our next release.
