### ISSUE TITLE
Getting bad gateway while creating admin user in chef server

### ISSUE THREAD

**Issue by vaibhavjpr** [chef/chef-server#435]
[root@blrtest36 ~]# chef-server-ctl user-create vkadmin Admin Chef root@localhost vkadmin -f admin.pem
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 1/5 in 4s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 2/5 in 5s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 3/5 in 14s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 4/5 in 29s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 5/5 in 58s
ERROR: bad gateway

[root@blrtest36 opscode-erchef]# chef-server-ctl user-create vkadmin Admin Chef root@localhost vkadmin -f admin.pem
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 1/5 in 4s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 2/5 in 5s
^Z
[1]+  Stopped                 chef-server-ctl user-create vkadmin Admin Chef root@localhost vkadmin -f admin.pem
[root@blrtest36 opscode-erchef]# chef-server-ctl status
run: bookshelf: (pid 11666) 42s; run: log: (pid 8558) 64166s
run: nginx: (pid 11715) 41s; run: log: (pid 8818) 64161s
run: oc_bifrost: (pid 11735) 41s; run: log: (pid 8186) 64172s
run: oc_id: (pid 11784) 41s; run: log: (pid 8206) 64171s
run: opscode-erchef: (pid 11832) 40s; run: log: (pid 8627) 64165s
run: opscode-expander: (pid 11838) 39s; run: log: (pid 8476) 64167s
run: opscode-expander-reindexer: (pid 11843) 39s; run: log: (pid 8483) 64167s
run: opscode-solr4: (pid 11850) 38s; run: log: (pid 8312) 64169s
run: postgresql: (pid 10847) 607s; run: log: (pid 8094) 64173s
run: rabbitmq: (pid 11859) 38s; run: log: (pid 8076) 64174s
run: redis_lb: (pid 12015) 38s; run: log: (pid 8789) 64162s

What could be the issue?

**Comment by vaibhavjpr** [comment]
Gettting bad request output in chef-server-ctl output

[root@blrtest36 opscode-erchef]# chef-server-ctl test
Configuring logging...
Creating platform...
Configured URL: https://blrtest36.idc.oracle.com
Creating org pedant_testorg_blrtest36_12541
/opt/opscode/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!': 400 "Bad Request" (Net::HTTPServerException)
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http/response.rb:128:in `value'
        from /opt/opscode/embedded/service/oc-chef-pedant/lib/pedant/core_ext/net_http.rb:57:in `connect'

**Comment by dvsurya** [comment]
Hi, did you get any solution - for "bad gateway" error?

**Comment by vaibhavjpr** [comment]
No not yet 

Sent from my Windows Phone

-----Original Message-----

**Comment by talcloudshare** [comment]
Same happened for me while running through step 6 in https://docs.chef.io/install_server.html on a fresh Ubuntu Server 14.04.3 installation
Running chef-server-ctl reconfigure and then running step 6 again resolved the issue for now

**Comment by vaibhavjpr** [comment]
Infact I also did same and the issue fixed.

Sent from my Windows Phone
________________________________

**Comment by marcosps** [comment]
I'm facing the same problem here, running chef on Fedora 23.

I also tried the solution of @talcloudshare and @vaibhavjpr , but it doesn't helped. Any tips?

I'm using chef-server-core-12.4.1-1.el7.x86_64.rpm on my Fedora.

**Comment by Swetha4b0** [comment]
I also tried the solutions above with no result.
Did anyone find a solution for the issue?

**Comment by jwadolowski** [comment]
Same issue here. Clean installation of chef-server 12.6.0 on RHEL 6.8. Deployment according to: https://docs.chef.io/install_server.html. Can't create 1st user.

```
$ chef-server-ctl user-create admin Chef Admin admin@localhost 'password' --filename /root/.chef/admin.pem
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 1/5 in 3s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 2/5 in 7s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 3/5 in 13s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 4/5 in 28s
ERROR: Server returned error 502 for https://127.0.0.1/users/, retrying 5/5 in 55s
```

Logs: https://gist.github.com/jwadolowski/a8a01e47a83b0cc00237a3b1be7a2e28

It seems to be related to RabbitMQ requests, however all services are up and running:

```
$ chef-server-ctl status
run: bookshelf: (pid 13774) 1664s; run: log: (pid 30677) 3981s
run: nginx: (pid 13817) 1664s; run: log: (pid 30682) 3981s
run: oc_bifrost: (pid 13825) 1664s; run: log: (pid 30665) 3981s
run: oc_id: (pid 13864) 1663s; run: log: (pid 30667) 3981s
run: opscode-erchef: (pid 21172) 20s; run: log: (pid 30669) 3981s
run: opscode-expander: (pid 13996) 1661s; run: log: (pid 30675) 3981s
run: opscode-solr4: (pid 14053) 1660s; run: log: (pid 30686) 3981s
run: postgresql: (pid 14092) 1659s; run: log: (pid 30689) 3981s
run: rabbitmq: (pid 14115) 1659s; run: log: (pid 30668) 3981s
run: redis_lb: (pid 15696) 1493s; run: log: (pid 30670) 3981s
```

RabiitMQ port (5672) is definitely open and I can connect to it:

```
$ nc 127.0.0.1 5672 -v
Connection to 127.0.0.1 5672 port [tcp/amqp] succeeded!
```

**Comment by Swetha4b0** [comment]
Hi Jakub,

As you can see from the status of the processes, the uptime of opscode-erchef is very low (20s) which means there is some issue with the opscode-erchef installation.
Try cleansing the server setup with the command "chef-server-ctl cleanse" and reconfigure the server.

**Comment by jwadolowski** [comment]
Hey,

something is definitely not right with `opscode-erchef`, as it gets restarted by itself ever couple of seconds.

``` 
$ for i in $(seq 1 10); do chef-server-ctl status opscode-erchef; sleep 6; done
run: opscode-erchef: (pid 5154) 14s; run: log: (pid 30661) 799s
run: opscode-erchef: (pid 5154) 21s; run: log: (pid 30661) 806s
run: opscode-erchef: (pid 5154) 29s; run: log: (pid 30661) 814s
run: opscode-erchef: (pid 5312) 1s; run: log: (pid 30661) 821s
run: opscode-erchef: (pid 5312) 9s; run: log: (pid 30661) 829s
run: opscode-erchef: (pid 5312) 16s; run: log: (pid 30661) 836s
run: opscode-erchef: (pid 5312) 24s; run: log: (pid 30661) 844s
run: opscode-erchef: (pid 5312) 32s; run: log: (pid 30661) 852s
run: opscode-erchef: (pid 5463) 3s; run: log: (pid 30661) 859s
run: opscode-erchef: (pid 5463) 11s; run: log: (pid 30661) 867s
```

I'm testing standalone Chef server deployment from scratch and my impression is that despite of exactly the same procedure final effect is completely non-deterministic. Sometimes it does work, but very often it doesn't. 

Last time I got the following error during ` chef-server-ctl user-create`: 

```
WARN: Failed to read the private key /etc/opscode/pivotal.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /etc/opscode/pivotal.pem>
ERROR: Your private key could not be loaded from /etc/opscode/pivotal.pem
Check your configuration file and ensure that your private key is readable
```

Which seems to connected to https://github.com/chef/chef-server/issues/727

I executed `chef-server-ctl cleanse` followed by `chef-server-ctl reconfigure`, but nothing has changed. I even followed advice from #727 and copied `pivotal.pem`, but got this in the end:

```
$ chef-server-ctl user-create admin Chef Admin admin@localhost.com 'password' --filename /root/.chef/admin.pem
ERROR: Failed to authenticate to https://127.0.0.1:443 as pivotal with key /etc/opscode/pivotal.pem
Response:  Invalid signature for user or client 'pivotal'
```

**Comment by cheeseplus** [comment]
Given the age of this report and the fact the issues reported are all slightly different but not quite the same thing, I'm closing this one. Please feel free to open a new issue with current versions but as it stands most of these seem to have been local configuration issues.

**Comment by knitinfk** [comment]
can some one update if their is already a  solution for this problem?
