### ISSUE TITLE
license endpoint should return number of nodes in existing orgs

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#437]
Currently the node count used by the license endpoint simply counts all nodes in the nodes table. This is not an accurate count. If an organization is deleted no cleanup work is done so the nodes in that org remain in the nodes table resulting in inaccurate node counts.

This SQL query should be fixed so it joins with the orgs table.

https://github.com/chef/chef-server/blob/12.1.1/src/oc_erchef/apps/chef_db/priv/pgsql_statements.config#L22-L23

```
SELECT COUNT(*) as count FROM nodes LEFT JOIN orgs ON nodes.org_id = orgs.id WHERE orgs.id IS NOT NULL;
```

**Comment by stevendanna** [comment]
@jeremiahsnapp Thanks for the report, were you planning on filing a PR for this change or should someone else pick it up?
