### ISSUE TITLE
c-s-c chef12-upgrade-download command has two -d options

### ISSUE THREAD

**Issue by mmzyk** [chef/chef-server#45]
The chef12-upgrade-download command has two options that have a short option of -d. I believe in this case the last one will win, but they should have unique short options. The work around for now is to just use the long option names.

See https://github.com/opscode/opscode-omnibus/blob/master/files/private-chef-ctl-commands/chef12_upgrade_download.rb#L27 and https://github.com/opscode/opscode-omnibus/blob/master/files/private-chef-ctl-commands/chef12_upgrade_download.rb#L53

**Comment by stevendanna** [comment]
Fixed in 12.0.3
