### ISSUE TITLE
I can't change postgresql port

### ISSUE THREAD

**Issue by diegows** [chef/chef-server#459]
I need to change the port where Chef's PostgreSQL is listening but it fails. I've added the options "postgresql['port'] = 6432" to the chef-server.rb. chef-server-ctl reconfigure fails, because there are some resources in the recipes that use the psql command without getting the port information from somewhere.

**Comment by marcparadise** [comment]
There were some recent changes merged into the CHef Server nightlies that will correct this. Is it an option for you to grab a nightly and confirm?

**Comment by marcparadise** [comment]
I forgot to include the actual location (assumes ubuntu): https://packagecloud.io/chef/current/packages/ubuntu/trusty/chef-server-core_12.2.0+20150730143118-1_amd64.deb

**Comment by diegows** [comment]
I've tried with this package chef-server-core-12.2.0+20150730184117-1.el6.x86_64.rpm and no luck.

```
[2015-07-30T23:22:30+00:00] FATAL: PG::ConnectionBad: private_chef_pg_database[opscode-pgsql] (private-chef::postgresql line 137) had an error: PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 6432?
```

# cat /etc/opscode/chef-server.rb 
postgresql["port"] = 6432

I've tried to specify the new port before running reconfigure the first time, and then (in a fresh instance) I ran reconfigure, modified the port and ran the reconfigure again with the same results.

**Comment by auroaj** [comment]
This files contain commands without port specify:

    /opt/opscode/embedded/cookbooks/private-chef/providers/pg_database.rb
    /opt/opscode/embedded/cookbooks/private-chef/libraries/ec_postgres.rb
    /opt/opscode/embedded/cookbooks/private-chef/recipes/bifrost_database.rb

I changed it manually and it is work sometimes...
But I want to change it from chef recipe and I can't reach work result.

**Comment by tylercloke** [comment]
Bootstrap is definitely also broken for non-default ports, can make a PR soon:

https://github.com/chef/chef-server/blob/master/src/chef-server-bootstrap/bin/bootstrap-platform#L41

**Comment by auroaj** [comment]
As I understand the code, postgresql['port'] used to specify external postgres instance, not chef embedded.
It means that we can't setup embedded postgres to non-standard port.

**Comment by marcparadise** [comment]
This fix will be in the next package pushed to  chef/current on  packagecloud.
