### ISSUE TITLE
Support Multi Factor Authentication in oc-id

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#46]
As a customer, I would like CHEF to support more secure auth methods in their products.

Manage ticket for the same OC-11782

Most likely implementation point according to OC-11782 https://github.com/chef/chef-server/tree/master/src/oc-id

**Comment by tas50** [comment]
I'm going to close this out at this point in time. We're not actively investing in expanding the functionality of oc-id. We have a new authentication system within Chef Automate, which is the future of auth in the Chef product suite.
