### ISSUE TITLE
Check For Binaries During OSS 11 -> CS 12 Upgrade

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#468]
Zendesk 5574

As a customer, I would like the upgrader to be better at figuring out the state of my system.

If the upgrader finds /opt/chef-server, but no binaries and an /opt/opscode directory with binaries, then it should assume that I have uninstalled the open source chef server package, write a message to STDOUT about what it found, and move along to upgrading whatever system it finds in /opt/opscode

**Comment by sean-horn** [comment]
Zendesk 2573

**Comment by stevendanna** [comment]
@sean-horn To expand on this, is the problem you are seeing that `chef-server-ctl upgrade` is trying to initialize an 11 to 12 upgrade because /opt/chef-server exists even on servers that have already been upgraded to 12?

**Comment by sean-horn** [comment]
@stevendanna The upgrade process chose to attempt an upgrade of an earlier mangled(binaries removed with `dpkg -r PACKAGE`) installation of /opt/chef-server rather than a recent, working installation of Enterprise Chef 11. 

Of course, we could say "Completely remove /opt/chef-server with `chef-server-ctl cleanse`", but that would lead to other issues 

https://github.com/chef/chef-server/issues/115 
https://github.com/chef/chef-server/issues/179

**Comment by PrajaktaPurohit** [comment]
Closing, since this is not supported any more.
