### ISSUE TITLE
LDAP system recovery password set up error

### ISSUE THREAD

**Issue by bbideep** [chef/chef-server#47]
I am trying to setup system recovery password for an LDAP user [Chef 11], but getting 
the
below error when I run the command "private-chef-ctl password Test.User10"

"406 Not Acceptable
Password for Test.User10 successfully enabled for System Recovery."

This message looks kind of confusing with the first line error message and
second line success message!

But, when I try to login to manage UI with system recovery password [LDAP
down], I get the below error -

"Incorrect username or password, or system recovery is not enabled for this
account. If you think system recovery should work for your account, please
contact your system administrator."

When I drilled down further, it is the "http://127.0.0.1:9465/users/Test.User10" request that is failing and returning the error.
Header contains Accept and Content-Type as 'application/json'

I tried doing a curl with accept, X-Ops-Sign, X-Ops-Userid, X-Ops-Timestamp, X-Ops-Content-Hash headers against the URL "http://127.0.0.1:9465/users" and I got a response - 
{"error":"Failed to authenticate as pivotal. Synchronize the clock on your host."}

My system in on EST.

**Comment by stevendanna** [comment]
@bbideep Apologies for the long delay.  Is this still an issue for you?

**Comment by sdelano** [comment]
@stevendanna - Does this look similar to any of recently-fixed LDAP issues?

**Comment by marcparadise** [comment]
Closing this from lack of response. @bbideep if this is still occurring as a problem, please re-open this with the latest details.
