### ISSUE TITLE
Solr returning multiple results for same node (11.1.6)

### ISSUE THREAD

**Issue by theckman** [chef/chef-server#471]
We've noticed a strange behavior with the chef-server (`11.1.6`) and searches. In some situations when executing a search, solr is returning multiple hits for the same node.

The situation today involved the following query: `cloud_provider:linode AND chef_environment:prod_default`. When the search returned, there were 2 nodes found and both were the same node.

Digging in to the `chef-solr` logs on the server, I see that solr is reporting two hits for the search:

```
2015-08-10_20:57:17.31633 Aug 10, 2015 8:57:17 PM org.apache.solr.core.SolrCore execute
2015-08-10_20:57:17.31634 INFO: [] webapp=/solr path=/select params={sort=X_CHEF_id_CHEF_X+asc&indent=off&start=1&q=content:cloud_provider__%3D__linode+AND+cont
ent:chef_environment__%3D__prod_default&wt=json&fq=%2BX_CHEF_database_CHEF_X:chef_00000000000000000000000000000000+%2BX_CHEF_type_CHEF_X:node&rows=1000} hits=2
status=0 QTime=0
```

And it's not always two hits and not always the same instance of `chef-server` hitting this.

If you need any further information I'd be happy to forward along what I can.

**Comment by ranjib** [comment]
@danielsdeleo @seth we are hitting this pretty frequently now, and very concerned about it. Since it  has drastic effect on search driven config files (and the corresponding app). We want to know if this is a known bug , or only we are hitting this, and how we can help in fixing this.

**Comment by PrajaktaPurohit** [comment]
Closing this since it was on 11.1.6. Please feel free to reopen if this still occurs on 13.1.13.
