### ISSUE TITLE
opscode-reporting error 500

### ISSUE THREAD

**Issue by EugenioMarzo** [chef/chef-server#480]
Dear All,

the following error is generated during a convergence of all nodes:

2015-08-18T12:00:45Z oc_reporting@127.0.0.1 method=POST; path=/organizations/myorg/reports/nodes/mynode01/runs; status=500; user=mynode01; org_name=myorg; protocol_version=0.1.0; req_time=5; erchef_time=3; erchef_count=1; msg={fetch_org_guid,{api_fetch_org_id,{conn_failed,{error,econnrefused}}}};

**Comment by mmzyk** [comment]
@EugenioMarzo It's really hard to diagnose what is going wrong from a small error snippet like that, beyond clearly that the connection was refused. These issues are best used for bug reports, but this looks like it's going to be something specific to your setup.

Please either seek help in the #chef room on IRC or contact Chef Support to help you with this issue: https://www.chef.io/support/

Thanks.

**Comment by EugenioMarzo** [comment]
@mmzyk 
Thank you for your answer and sorry I did not insert more information.

I found the cause of this problem. My chef server has been configured with a different listen porta that is 8443.  In chef-server.rb I have nginx['ssl_port'] = 8443.

The problem is inside the erb template of sys.config of opscode-reporting cookbook version 0.2.0.
The file is templates/default/oc_reporting.config.erb the into the following line is missing the parameter of the port:

 {chef_service, [{root_url, "https://<%= node['private_chef']['lb']['vip'] %>"}

Changing the above line with 

 {chef_service, [{root_url, "https://<%= node['private_chef']['lb']['vip'] %>:8443"} 

solved my problem.

Thank you,
Eugenio
