### ISSUE TITLE
Prevent Unintended Updates for RHEL on existing systems

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#491]
The original problem is tracked and fixed for any new installs in this PR.

https://github.com/chef/chef-server/pull/374

The problem is though that this PR doesn't fix existing systems because the fix isn't applied by `chef-server-ctl reconfigure`. It's only applied when `chef-server-ctl install` is run.

So we need a separate fix that disables the chef-stable yum repository on any existing system.

**Comment by adamedx** [comment]
@mmzyk , @stevendanna, can you take a look?

**Comment by jeremiahsnapp** [comment]
I'm closing this as a duplicate of https://github.com/chef/chef-server/issues/154
