### ISSUE TITLE
403 Forbidden on new nodes 

### ISSUE THREAD

**Issue by dgarstang** [chef/chef-server#499]
Use:
knife node create foobar

Run chef-client and chef-client runs ok but throws 403 errors when trying to update the node.

And, that's pretty much it. Problem does not occur when knife bootstrap is used, which isn't an option in my case. This is with chef 12.

**Comment by stevendanna** [comment]
@dgarstang Apologies no one responded to this here, however I believe I did respond to a similar query on discourse here: https://discourse.chef.io/t/forbidden-403-after-adding-nodes-on-chef-12/6838/2

I'm going to close this issue out as it isn't a bug but rather a consequence of Chef 12's permissions system.
