### ISSUE TITLE
Disabling LDAP requires editing the node directly

### ISSUE THREAD

**Issue by dreamnite** [chef/chef-server#510]
chef-server-core 12.0.5-1.el6

Short version: there  should be a way to remove/unconfigure ldap without editing the node data for the chef server directly. 

Long version:
After configuring LDAP per https://docs.chef.io/server_ldap.html, we needed to turn it off. Tried doing so by removing ldap items from /etc/opscode/chef-server.rb and running a chef-server-ctl/opscode-manage-ctl, but the ldap configuration persisted.

Attempted to set to nil, with no joy. Finally was able to remove the ldap configuration by editing the /opt/opscode/embedded/nodes/<servername>.json and removing the ldap sections. 

Let me know if you'd like any additional information.

**Comment by stevendanna** [comment]
I think this bug should have been fixed in the lastest release as we now make sure to delete any existing node data before the reconfiguration.
