### ISSUE TITLE
Lose persmission on  built-in 'users' group

### ISSUE THREAD

**Issue by chrisduong** [chef/chef-server#521]
Hi,

I wanted to remove the ability to update of "users" group, but unfortunately, I instead remove all permissions to access "users" group. Now even "admins" group cannot read "users" group.

Is there anyway that I can regain access "users" group. Thanks a lot.

**Comment by markan** [comment]
Sorry for the late reply to this. For reference the 'fixie' tool is designed to help with this kind of situation.  https://github.com/chef/fixie/blob/master/doc/CommonTasks.md may be useful, covering audit and automated fixup for broken orgs.
