### ISSUE TITLE
First 'chef-server-ctl install' makes yum repo files w/o proxy info and fails

### ISSUE THREAD

**Issue by jblaine** [chef/chef-server#525]
Chef Server 12.3.0

I'm root. I have `https_proxy` and `http_proxy` set.

Running `chef-server-ctl install opscode-manage` creates an `/etc/yum.repos.d/chef-stable.repo` that does not include proxy information. Yum fails.

**Comment by stevendanna** [comment]
Thanks for filing this, `chef-server-ctl install` no longer configures these yum repos and instead uses mixlib-install to download the packages directly.
