### ISSUE TITLE
Multiple SSL for multiple domains

### ISSUE THREAD

**Issue by dgoradia** [chef/chef-server#530]
Is there a way to tell chefserver to use multiple SSL certs for different domains? 

We have 2 domains that the cherserver should be accessible from but as far as I can tell the parameters only accept one cert:

```
nginx['ssl_certificate'] = "..."
nginx['ssl_certificate_key'] = "..."
```

**Comment by danielsdeleo** [comment]
You need to make a certificate with the Subject Alternative Name extension. Unfortunately, we don't have a guide for this, and many of the guides on the internet are subtly incorrect.

**Comment by PrajaktaPurohit** [comment]
Closing for now. Please feel free to reopen if needed.
