### ISSUE TITLE
Always get "unable to solve dependencies in alotted time" error

### ISSUE THREAD

**Issue by jeffbyrnes** [chef/chef-server#531]
Coming here from chef/omnibus-chef#237 (thanks @lamont-granquist!).

We’re using Hosted Chef, and recently started experiencing this error with our base cookbook in our stage environment, which has no cookbook version pinning (it’s more QA than stage, frankly).

I pinned this cookbook to `~> x.y`, and that solved the issue for a number of nodes, but a handful have continued to throw this error.

Turned out that these nodes had another cookbook that had little or no version pinning in it for very common cookbooks (`apt`, `maven`, `java`, etc.)

Adding pins for those cookbooks, again, solved the issue. However, it would be nice to leave our stage environment unconstrained, for testing/workflow reasons.

**Comment by PrajaktaPurohit** [comment]
Closing since we recommend users to use policyfiles which would make depsolving local.
