### ISSUE TITLE
Chef Server serves old cookbook versions

### ISSUE THREAD

**Issue by BackSlasher** [chef/chef-server#535]
I have the following structure:

```bash
# knife cookbook show a
a  0.2.16  0.2.15  0.2.14  0.2.13  0.2.12  0.2.11  0.2.10  0.2.9  0.2.8  0.2.7  0.2.6  0.2.5  0.2.4  0.2.3  0.2.2  0.2.1  0.2.0  0.1.111  0.1.110  0.1.109  0.1.108  0.1.107  0.1.106  0.1.105  0.1.104  0.1.103  0.1.102  0.1.101  0.1.100  0.1.99  0.1.98  0.1.97  0.1.96  0.1.95  0.1.94  0.1.93  0.1.92  0.1.91  0.1.90  0.1.89  0.1.88  0.1.87  0.1.86  0.1.85  0.1.84  0.1.83  0.1.82  0.1.81  0.1.80  0.1.79  0.1.78  0.1.77  0.1.76  0.1.75  0.1.74  0.1.73  0.1.72  0.1.71  0.1.70  0.1.69  0.1.68  0.1.67  0.1.66  0.1.65  0.1.64  0.1.63  0.1.62  0.1.61  0.1.60  0.1.59  0.1.58  0.1.57  0.1.56  0.1.55  0.1.54  0.1.53  0.1.52  0.1.51  0.1.50  0.1.49  0.1.48  0.1.47  0.1.46  0.1.45  0.1.44  0.1.43  0.1.42  0.1.41  0.1.40  0.1.39  0.1.38  0.1.37  0.1.36  0.1.35  0.1.34  0.1.33  0.1.32  0.1.31  0.1.30  0.1.29  0.1.28  0.1.27  0.1.26  0.1.25  0.1.24  0.1.23  0.1.22  0.1.21  0.1.20  0.1.19  0.1.18  0.1.17  0.1.16  0.1.15  0.1.14  0.1.13  0.1.12  0.1.11  0.1.10  0.1.9  0.1.8  0.1.7  0.1.6  0.1.5  0.1.4  0.1.3  0.1.1  0.1.0
# knife cookbook show b
b   0.1.54  0.1.53  0.1.52  0.1.51  0.1.50  0.1.49  0.1.48  0.1.47  0.1.46  0.1.45  0.1.44  0.1.43  0.1.42  0.1.41  0.1.40  0.1.39  0.1.38  0.1.37  0.1.36  0.1.35  0.1.34  0.1.33  0.1.32  0.1.31  0.1.30  0.1.29  0.1.28  0.1.27  0.1.26  0.1.25  0.1.24  0.1.23  0.1.22  0.1.21  0.1.20  0.1.19  0.1.18  0.1.17  0.1.16  0.1.15  0.1.14  0.1.13  0.1.12  0.1.11  0.1.10  0.1.9  0.1.8  0.1.7  0.1.6  0.1.5  0.1.4  0.1.3  0.1.2  0.1.1  0.1.0
```
Cookbook `a` depends on cookbook `b` like so:
```ruby
# cookbooks/a/metadata.rb
#...
depends 'b', '>= 0.1.1'
#...
```
I recently noticed that clients, (including Vagrant machines that use `berkshelf` for acquiring cookbooks) are fetching a specific old verion of `b` (0.1.34) instead of the latest (0.1.54).
When requested directly in the runlist, the latest version of `b` is fetched.
I hacked this snippet, executable using `chef-shell -z -c ~/.chef/knife.rb` to show the issue:
```ruby
api_service = Chef::REST.new(Chef::Config[:chef_server_url])
Chef::Cookbook::FileVendor.fetch_from_remote(api_service)
env = '_default' # No version constraints
puts "Indirect: " + api_service.post("environments/#{env}/cookbook_versions",{run_list: ['a']})['b'].version
# Indirect: 0.1.34
puts "Direct: " + api_service.post("environments/#{env}/cookbook_versions",{run_list: ['b']})['b'].version
# Direct: 0.1.54
```
I'm wondering:
1. Why Chef isn't choosing the latest version when no constraints are in place (I checked), especially considering that this is not a real node (so it shouldn't have any "cached" cookbooks)?
2. What's so special about version 0.1.34? Where is a possible pin except roles (I have none) and environments (I made sure it's not there)?
3. Where can I dig around to find this cookbook logic? I'm currently probing the `oc_erchef` but I'm afraid I'm wasting my time.

Could be related to to [CHEF-5243](https://tickets.opscode.com/browse/CHEF-5243), and berkshelf/berkshelf#1140

**Comment by stevendanna** [comment]
Is cookbook a's only dependency cookbook 'b'?  Does cookbook 'b' have any dependencies?  Often the cause of such a solution is some common dependency of cookbook A and cookbook B further down the dependency graph.

**Comment by BackSlasher** [comment]
No, I double checked using:
```ruby
api_service = Chef::REST.new(Chef::Config[:chef_server_url])
Chef::Cookbook::FileVendor.fetch_from_remote(api_service)
env = '_default' # No version constraints
api_service.post("environments/#{env}/cookbook_versions",{run_list: ['a']}).values.map{|v|v.metadata.dependencies.select{|dk,dv|dk == 'b'}}
#  => [{"b"=>">= 0.1.1"}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}] 
```
So the only dependency is from `a`. I also used `berks viz` to verify.

**Comment by BackSlasher** [comment]
@stevendanna quick question - does the dependency resolver try to get the solution with the highest version numbers, or just the first solution it finds?
Seems to me that it takes the first solution and I was assuming it picks the highest versions possible

**Comment by marcparadise** [comment]
It will pick the highest version number that it can to meet all dependencies.  

Unless I'm misreading your check above, it looks like you filtered only on 'b' in the results for given runlist 'a'?

**Comment by danielsdeleo** [comment]
@BackSlasher it has kind of a weird algorithm for determining the best. The very newest cookbooks are considered much better than any older cookbooks, and it frequently will pick an older "top level" item in order to get a newer version of a dependency. While this is frustrating, it's likely not a thing that can be fixed without a major breakage, since many people are probably implicitly relying on this behavior without knowing about it.

This is one of the big reasons why we created the policyfiles feature:

1. We can improve the resolver logic without breaking the whole universe (policyfiles are actually using a better solver right now).
2. You get to see what the resolver did before running anything in production

The code for the solver Chef Server is using is here: https://github.com/chef/dep-selector but it's a huge amount of effort to make any functional changes to it, as you'll have to support the old and new behavior together, and have a way for chef-client to pick the one it wants.

**Comment by BackSlasher** [comment]
I **want** it to pick the newer versions of my cookbooks. It seems like it doesn't.
@marcparadise yeah, I'm getting a lower version of `b` when the runlist only contains `a`. I wanted to rule out any chance that another cookbook requires a lower version of `b`, so I made this filter.
@danielsdeleo, I saw a dependency resolver in Erlang in the Chef Server repo. Is it not the one being used by the server? Is the ruby one you linked behaviorally identical?

**Comment by danielsdeleo** [comment]
@BackSlasher the Ruby one is the original implementation from back when Chef Server was written in Ruby. We wrote a pure Erlang implementation, but it had different behavior in many edge cases, so we had to switch back to the Ruby one (it maintains a pool of ruby solver processes and talks to them via erlectricity). So the behavior you're interested in looking into is in the dep-selector gem. But, as I said before, it cannot be changed without having a means for both chef-client and server to pick between the old and new behaviors. You'll get what you want a lot quicker if you either use policyfiles or generate environment files to lock the cookbooks.

**Comment by BackSlasher** [comment]
@danielsdeleo I re-read your statement
> The very newest cookbooks are considered much better than any older cookbooks, and it frequently will pick an older "top level" item in order to get a newer version of a dependency.

And I get it now!
On `b` I depend on `elasticsearch`, which I only pinned down later (because they did a major overhaul), and 0.1.34 was the last version who's metadata wasn't spermy-pinned.
Playing with the runlist and comparing the output of 
```ruby
res = api_service.post("environments/#{env}/cookbook_versions",{run_list: my_runlist})
res.keys.map{|k|[k,res[k].version]}.sort_by{|k,v|k}.each{|i|puts i.inspect}
```
helped me be sure.
So Chef server preferred that version in order to preserve the latest `elasticsearch` cookbook.
I'll take that as a lesson to
[spermy
pin
everything](http://static.fjcdn.com/pictures/Shut_b76733_1693530.jpg)

Thanks everyone for the quick reply!

**Comment by kbuchsicf** [comment]
suggest closing this issue - as user error. I trying to debug a similar problem, but much simpler.
