### ISSUE TITLE
Chef-Server 12.1.2 unable to remove user from org, thinks root is logged in as user being remvoed.

### ISSUE THREAD

**Issue by predatorian3** [chef/chef-server#538]
I am running into an issue where when I try to remove a user from the Chef-Server using the `chef-server-ctl` command, I get the following errors. 

```
[root@chefserver00 ~]# chef-server-ctl org-user-remove orgname user01
ERROR: You authenticated successfully to https://127.0.0.1:443 as user01 but you are not authorized for this action
Response:  Please remove user01 from this organization's admins group before removing him or her from the organization.
```

I also get the same errors when attempting to delete a user, I'm also unable to edit the user. I was able to delete their private key, and recreate it though.

**Comment by tylercloke** [comment]
Did you edit `/etc/opscode/pivotal.rb` from its original value? All the org and user management commands do in `chef-server-ctl` is wrap `knife-opc` with it hard-coded to using pivotal's (the system superuser's) knife config.

https://github.com/chef/chef-server/blob/fce335d0f84cf042ba291e2cfe7aa9204e1188d6/omnibus/files/private-chef-ctl-commands/wrap-knife-opc.rb#L18

**Comment by marcparadise** [comment]
Based on the error message, could you also confirm that user01 has not been added to the org's admin group?  There is a policy in place that prevents users who are admins from being removed, unless they are first removed from the admins group.

**Comment by PrajaktaPurohit** [comment]
Closing this for now. Please feel free to reopen if the issue persists.
