### ISSUE TITLE
Missing opscode-push-jobs-server build for RHEL 7

### ISSUE THREAD

**Issue by royaldark** [chef/chef-server#546]
It appears that there is not yet a build for the `opscode-push-jobs-server` package for RHEL 7. This is especially frustrating since `opscode-push-jobs-server` is mentioned extensively in the general Chef server setup documentation (https://docs.chef.io/install_server.html).

I discussed this issue with `coderanger` on IRC who suggested it was caused by an overlooked build failure and that I file an issue here. Is it possible to get a RHEL 7 build on packagecloud?

**Comment by tylercloke** [comment]
Oops wrong button.

**Comment by royaldark** [comment]
Any updates on this? I'm willing to compile and contribute a RHEL 7 build if that would help. We could really use `opscode-push-jobs-server`!

**Comment by mickfeech** [comment]
any updates?

**Comment by stephenlauck** [comment]
:+1: to this getting built.

**Comment by jmink** [comment]
The latest release in current has a RHEL 7 build: http://artifactory.chef.co/webapp/builds/opscode-push-jobs-server/2.0.0-alpha.4+20160225080813/2016-02-25T09:14:14.353+0000/com.getchef:opscode-push-jobs-server:2.0.0-alpha.4+20160225080813/?6

**Comment by stevendanna** [comment]
This is now available from our main downloads site: https://packages.chef.io/stable/el/7/opscode-push-jobs-server-2.1.0-1.el7.x86_64.rpm
