### ISSUE TITLE
Unable to install chef-server on docker container

### ISSUE THREAD

**Issue by spurti** [chef/chef-server#548]
I am unable to install chef-server (chef-server-core_12.0.8-1_amd64.deb) over a docker container (ubuntu 14.04 x86_64).
When running chef-server-ctl reconfigure it fails with following error:

Error executing action run on resource 'execute[/opt/opscode/bin/private-chef-ctl start rabbitmq]'
Mixlib::ShellOut::ShellCommandFailed

Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
STDOUT: warning: rabbitmq: unable to open supervise/ok: file does not exist
STDERR:
---- End output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
Ran /opt/opscode/bin/private-chef-ctl start rabbitmq returned 1

NOTE: Before starting installation , I have done following steps:
dpkg-divert --local --rename --add /sbin/initctl
ln -sf /bin/true /sbin/initctl
sysctl -w kernel.shmmax=17179869184

Is there any other work-around to get chef-server up on docker container

**Comment by moribellamy** [comment]
I'm having the same problem.

This is probably a bug with docker, since AFAIK installation works on a normal ubuntu VM. Maybe move the issue there?

Chef gurus, please chime in though :)

**Comment by goacid** [comment]
+1

**Comment by spurti** [comment]
Closing the ticket. Since it is issue with docker and not chef-server

**Comment by moribellamy** [comment]
FWIW, I've had success enough with this image: https://hub.docker.com/r/base/chef-server/.

Some combination of Chef 11 plus the specialized tuning in that image makes it work. Also consider using chef-solo, which I've had no problems with and suited my needs.
