### ISSUE TITLE
Permissions errors when upgrading from chef-server 11 -> 12

### ISSUE THREAD

**Issue by seryl** [chef/chef-server#57]
chef-server-11.1.1-1.el6.x86_64.rpm -> chef-server-core-12.0.1-1.x86_64.rpm

All of the nodes I currently have do not have save permissions after the upgrade.

Also; had to use knife backup to restore all of my data, seemed to be lost during the upgrade.

**Comment by mmzyk** [comment]
@seryl Your data should still be present. Chef Server 12 does not install to the same directory as the open source Chef Server 11. Chef Server 11 is in /opt/chef-server, where as Chef Server 12 installs to /opt/opscode (legacy naming from when it wasn't fully open source and from before the company changed it's name - eventually everything should converge back to /opt/chef-server, but there's no timetable for this.

Unless you've uninstalled the chef-server package, you should be able to fire it back up, although the Chef Server 12 package does overwrite the default location for the chef-server-ctl commands. However, the chef-server-ctl commands for Chef Server 11 are still found at /opt/opscode/bin (I believe I have the path correct, I'm trying to recall off the top of my head here).

All of that being said, what error are you seeing? Can you provide the exact error if possible? What you've described isn't expected.

**Comment by sdelano** [comment]
Closing this issue as there has been no response on what the permissions mis-matches were. @seryl - feel free to re-open with more details.

Thanks!
