### ISSUE TITLE
Confusing error message with duplicate email address

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#59]
When creating a user with an email address already taken by an existing user, you will receive the following confusing error message:

```
vagrant@private-chef:~$ sudo chef-server-ctl user-create foobar John Q Public "john.public@example.com" some_password
ERROR: Conflict
Response: User 'foobar' already exists
```

Note that there is no user `foobar` but we still receive this generic conflict message because the email address is already taken.

In the near term, we should present a better error message to the user.  In the long term, we should consider whether the uniqueness constraint on email addresses is necessary outside of Hosted Chef.

**Comment by structurefall** [comment]
+1 . A better error message would help, but what I REALLY want is to be able to have two users with the same email. In my case I have a couple of non-human users that I'd like to point at the same mailbox.

**Comment by marcparadise** [comment]
'                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: structurefallSent: Thursday, May 28, 2015 8:28 PMTo: chef/chef-serverReply To: chef/chef-serverSubject: Re: [chef-server] Confusing error message with duplicate email address (#59)+1 . A better error message would help, but what I REALLY want is to be able to have two users with the same email. In my case I have a couple of non-human users that I'd like to point at the same mailbox.

—Reply to this email directly or view it on GitHub.
