### ISSUE TITLE
backend postgresql preflight validation runs on front-end nodes. 

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#599]
Some of these  (specifically if DB and roles already exist)  should onyl be running on backend nodes, and possibly only for the  backend bootstrap node so that we don't see the same issue when bringing up a replacement back end. 

Because bringing front-ends online typically involves copying files from a backend, the existing check for `chef-server-running.json` being present prevents this from coming up in most cases. 

However, if chef-server-running is omitted from the files being copied (and there's no reason for it to be copied, so this should be supported), the front-end will fail when external postgresql is configured

**Comment by stevendanna** [comment]
@marcparadise Are any of these commands destructive?  Is there a problem with running them from the frontends? What is the user likely to see in this case?

**Comment by marcparadise** [comment]
They're not destructive, but if you're adding a new  FE node and don't have
a chef-server-running.json , it will fail because it sees that the db
already exists.

**Comment by stevendanna** [comment]
Ahh, I see.  Perhaps we should change that particular test to not matter on a frontend.  But I would still like to know things like "can this frontend connect to the postgresql server" sooner rather than later.  Although, that also enforces an ordering of when you bring machines up that maybe isn't necessary.

**Comment by marcparadise** [comment]
Definitely, I'd want to leave the connectivity checks in place, and 
specifically exclude the checks around database roles/schemas having 
been defined.

Actually - if anything, it might even make sense to reverse those tests 
for FEs - you shouldn't be deploying a FE if the back end has not 
already done that set up.

**Comment by sdelano** [comment]
@paulmooring - I think this is what you ran into yesterday
