### ISSUE TITLE
Gather-logs script throws errors on IPv6 enabled hosts

### ISSUE THREAD

**Issue by andy-dufour** [chef/chef-server#601]
On an IPv6 only host if you run gather logs you'll receive output similar to the below:

chef-server-ctl gather-logs 
ping: unknown host <hostname>
ping: unknown host <hostname>
Logs gathered in <hostname>-<date-timestamp>.tbz2

/cc @jaymzh

**Comment by PrajaktaPurohit** [comment]
@andy-dufour Looks like this git fixed with the more recent versions of Chef Infra Server. Closing.
