### ISSUE TITLE
Gather-logs script does not collect PostgreSQL logs

### ISSUE THREAD

**Issue by andy-dufour** [chef/chef-server#602]
When running chef-server-ctl gather-logs on a back-end chef server the PostgreSQL logs are not collected for troubleshooting purposes.

Not everything is logged to the various erlang logs, for example a unique constraint exception will appear in the chef-server erlang logs but will not provide enough detail on the table, constraint violated to effectively troubleshoot.

/cc @jaymzh

**Comment by stevendanna** [comment]
Hrm, are we sure?  I definitely have gather-log tarballs in my Downloads directory with the postgresql logs on disk.  If there is a problem, it likely lives here:

https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-scripts/gather-logs#L96-L101

**Comment by andy-dufour** [comment]
Since I filed this I noticed subsequent gather logs have collected postgres logs - may have been an edge case, I'll try and reproduce

**Comment by PrajaktaPurohit** [comment]
@andy-dufour Looks like the gather-logs script does collect postgresql logs. Closing this for now. Please free to reopen if found otherwise.
