### ISSUE TITLE
RabbitMQ writes logs to /var/opt - not logrotated

### ISSUE THREAD

**Issue by irvingpop** [chef/chef-server#603]
Found in CS12 (not sure if EC11 is affected).   RabbitMQ writes out additional logfiles to:
- /var/opt/opscode/rabbitmq/log/rabbit@localhost.log
- /var/opt/opscode/rabbitmq/log/rabbit@localhost-sasl.log

These can grow very large over time and are not rotated.   The rabbitmq.conf specifies the log directory as:

```
RABBITMQ_LOG_BASE="/var/opt/opscode/rabbitmq/log"
```

here: https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/templates/default/rabbitmq.conf.erb#L3

**Comment by stevendanna** [comment]
Would moving the logs to /var/log/opscode break people?

**Comment by sean-horn** [comment]
@stevendanna If you can encourage rabbitmq to do it for you that would be great. No I don't think most people other than Chef Support folks reference the logs under /var/opt/opscode/rabbitmq/log. They are valuable though, offering output you cannot get in /var/log/opscode/rabbitmq/current and that helps to debug and solve problems. The files are referenced by the gather-logs script at https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-scripts/gather-logs#L87

**Comment by bplessis** [comment]
It would be nice to fix this ....

**Comment by PrajaktaPurohit** [comment]
Closing this because our near term roadmap is to get rid of rabbitmq.
