### ISSUE TITLE
No chef-server-core source rpm

### ISSUE THREAD

**Issue by ylvmw** [chef/chef-server#619]
Hello,

Is there any chef-server-core source rpm provided? We do need the source rpm to build for our work. 

Thanks!

**Comment by stevendanna** [comment]
@ylvmw I don't think our omnibus build system creates source RPMs at the moment.  A complete package; however, can be built using this repository using the instructions in `omnibus/README.md`.  These directions may be a bit stale, I'll take a look at them today to make sure they are up to date.  I'm not sure off-hand how easy/hard it would be for us to produce SRPMs; mind adding some details on what you need and whether building directly from this source repo is an option for you?

**Comment by ylvmw** [comment]
Thanks for you reply! I'm trying to build the source, but it is hard for there are so many dependencies, you know, ruby, gem, builder, etc, I need to install them one by one and the versions of them also bring troubles. So a SRPM would be a great choice. Anyway, more details will also give help to me.

**Comment by ylvmw** [comment]
Hi, @stevendanna. I met an issue when build the chef server following the omnibus/README.md, could please you give some hints on how to fix it? 

[Builder: ohai] I | $ /opt/opscode/embedded/bin/bundle install --without development
                    [Builder: ohai] I | bundle `install --without development': 116.1399s
                    [Builder: ohai] I | Build ohai: 116.1409s
The following shell command exited with status 6:

    $ CFLAGS=-I/opt/opscode/embedded/include CPPFLAGS=-I/opt/opscode/embedded/include CXXFLAGS=-I/opt/opscode/embedded/include LDFLAGS=-Wl,-rpath,/opt/opscode/embedded/lib -L/opt/opscode/embedded/lib LD_RUN_PATH=/opt/opscode/embedded/lib PATH=/opt/opscode/bin:/opt/opscode/embedded/bin:/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bin:/opt/rubies/ruby-2.1.3/bin/:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin PKG_CONFIG_PATH=/opt/opscode/embedded/lib/pkgconfig /opt/opscode/embedded/bin/bundle install --without development

Output:

    Your Gemfile lists the gem chef (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Updating git://github.com/chef/chef.git
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Bundler could not find compatible versions for gem "net-ssh":
  In Gemfile:
    chef (>= 0) ruby depends on
      net-ssh (~> 2.6) ruby

    chef (>= 0) ruby depends on
      net-ssh (3.0.1)

Error:

    (nothing)


/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/util.rb:101:in `rescue in shellout!'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/util.rb:97:in `shellout!'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:701:in `shellout!'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:259:in `block in bundle'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:888:in `instance_eval'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:888:in `run'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:719:in `block (3 levels) in execute'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:741:in `call'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:741:in `with_retries'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:718:in `block (2 levels) in execute'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/instrumentation.rb:23:in `call'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/instrumentation.rb:23:in `measure'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:717:in `block in execute'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:791:in `call'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:791:in `with_clean_env'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:716:in `execute'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:612:in `block (2 levels) in build'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:611:in `each'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:611:in `block in build'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/instrumentation.rb:23:in `call'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/instrumentation.rb:23:in `measure'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/builder.rb:610:in `build'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/software.rb:904:in `execute_build'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/software.rb:784:in `build_me'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/project.rb:1006:in `block in build'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/project.rb:1005:in `each'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/project.rb:1005:in `build'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/cli.rb:83:in `build'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/cli/base.rb:33:in `dispatch'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/lib/omnibus/cli.rb:41:in `execute!'
  /opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/bundler/gems/omnibus-c9937e6d3729/bin/omnibus:11:in `<top (required)>'
  ./bin/omnibus:16:in `load'
  ./bin/omnibus:16:in `<main>'

**Comment by stevendanna** [comment]
Heya, just noticed your other ticket.  Are you still seeing this issue as well?

**Comment by ylvmw** [comment]
Not now. But I met another issue, could you also give some help? https://github.com/chef/chef-server/issues/636

**Comment by PrajaktaPurohit** [comment]
Hey does not look like we will be supporting source RPM's. Closing for that reason.
