### ISSUE TITLE
Chef 12.3.0: Settings Validation

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#621]
Zendesk 7008

As a customer, I do not expect isolated reconfigures or reconfigures run as a part of an upgrade to fail when I have not changed my /etc/opscode/chef-server.rb settings.

If I start out with a Chef Server < 12.3.0 and upgrade to 12.3.0 while having the following set in /etc/opscode/chef-server.rb, my upgrade will fail on the embedded reconfigure, and I will be left wondering what just happened

```
rabbitmq['vip'] = 'API_FQDN'
```

It will succeed if I happen to have the following setting

```
rabbitmq['vip'] = 'ANY_VALID_IP_ADDRESS'
```

A possible fix might be validation of ip addresses only for this config item while reading /etc/opscode/chef-server.rb

**Comment by PrajaktaPurohit** [comment]
Closing this because our near term roadmap is to get rid of rabbitmq.
