### ISSUE TITLE
Can't upload cookbook when server uses a non-standard port

### ISSUE THREAD

**Issue by kkeane** [chef/chef-server#634]
I'm opening this as a new issue even though #50 already covers the same thing, because #50 has been open for a year with nobody assigned to it, and may have fallen through the cracks.

The actual issue is that when you configure the chef server to listen on any other port but 443, cookbook uploads will always fail with an error 500. #50 identifies the details and the root cause.

**Comment by stevendanna** [comment]
Hi @kkeane.  Thanks for opening this.  I agree this fell off the radar.

I'm going to go ahead and close it since the other ticket has most of the technical info; however, thanks again for pointing it out.

**Comment by kkeane** [comment]
Has #50 fallen off the radar screen a second time? There now is a PR (thanks), but no action since November. The problem still exists in 12.5.0.
