### ISSUE TITLE
Instructions are incorrect after installing a package during upgrade

### ISSUE THREAD

**Issue by andy-dufour** [chef/chef-server#646]
After installing an upgrade package, the post-install instructions reference performing 'chef-server-ctl upgrade' followed by 'chef-server-ctl cleanup'.

After a chef-server-ctl upgrade, services remain down. We should either have chef-server-ctl upgrade start services or explicitly tell users to perform a chef-server-ctl start afterwards.

/cc @jaymzh

**Comment by jaymzh** [comment]
I don't think the instructions are correct - I think it's a bug. `chef-server-ctl` should ideally leave the services in whatever state it found them in, or barring that, leave them up.

**Comment by tylercloke** [comment]
The documentation does say to run `chef-server-ctl start` [here](https://docs.chef.io/upgrade_server.html#standalone) so we should be consistent between the two at the very least. 

Interestingly, it also says to run a `chef-server-ctl stop` before the upgrade which means everything should be down going into an upgrade, so it seems like the sane behavior would actually be to leave everything down by default.

Long-term, we should probably detect what is up, handle bringing everything down in the upgrade command, and then bring back up what was up before upgrade was run.

**Comment by jaymzh** [comment]
The RPM explicitly states to run upgrade and then cleanup when you install it. the instructions the RPM tell me superceed everythign else :)

**Comment by tylercloke** [comment]
Agreed that the two should be consistent. Easy enough to fix.

**Comment by MathildeBarr** [comment]
@tylercloke @andy-dufour Any update here?

**Comment by sdelano** [comment]
Closed by #689
