### ISSUE TITLE
Chef Server 12: View Public Keys of all Users, including clients

### ISSUE THREAD

**Issue by http-418** [chef/chef-server#649]
We have been using chef-vault to deploy secrets to our Chef clients.  Specifically, we often generate secrets in recipes, then encrypt them for other nodes and users by reading their public keys via the Chef API.

This is not currently working in Chef 12, because clients cannot read public keys for users. 

This issue was originally reported here:
https://github.com/chef/chef-server/issues/20

A partial fix was implemented in PR 244:
https://github.com/chef/chef-server/pull/244

The changes in PR #244 allow users to read client keys.  Unfortunately, it still doesn't work the other way around: clients cannot read user keys. 

Authenticated as a client, I would like to be able to read users' public keys via the API.

**Comment by http-418** [comment]
Issue #20 was re-opened, so this is now a duplicate issue.

**Comment by stevendanna** [comment]
Thanks @http-418 sorry for the confusion!

**Comment by pburkholder** [comment]
A team I work with mentions:

> The team is looking to encrypt chef-vault items with keys during a Chef run. They are using the Chef Client runs and likely executing some kind of search to update a vault item. I would need to get the specifics, but we’re considering this a regression as it is something that was working prior.

**Comment by http-418** [comment]
Yes, this worked fine in Chef 11.  The chef-vault resources could read users' public keys.

I've been moving the codebase to Chef 12, and this feature is now broken.

**Comment by marcparadise** [comment]
It's worth mentioning that under Open Source Chef Server 11, there was no RBAC , so nothing would prevent this. 

Did it work under Enterprise Chef Server 11?

**Comment by http-418** [comment]
I don't know whether it works with Enterprise Chef Server 11.   I have not attempted it.

**Comment by tylercloke** [comment]
This PR adds `GET /organizations/:organization/users/:user/keys(/:key)` to the API, adds a new group `public_key_read_access` that controls its permissions, and changed the permissions on `GET /organizations/:organization/clients/:client/keys(/:key)` to also be controlled by that group.

Now, GET on both those endpoints can be accessed by members of the group `public_key_read_access`. This group can be modified by admin users per org but defaults to containing the users and clients groups. So now, by default, org scoped user and client key GETs will be accessible by users and clients within the same org as the requested key.

Update for Chef Vault to leverage this work coming soon.

**Comment by tylercloke** [comment]
Being fixed for vault in this PR: https://github.com/chef/chef-vault/pull/209

Note that you will need to be on Chef Server 12.5+ to see the benefits of this though.
