### ISSUE TITLE
Not able to add domain user to organization

### ISSUE THREAD

**Issue by sasideveloper** [chef/chef-server#650]
Hi,

I tried integration of chef server with active directory. I am able to login in chef console where i am getting only 2 options "Link Account" and "Link Existing Account". Not able to understand how to proceed further from console. Then i tried adding user to organization using below command.   Please find the error log below.

chef-server-ctl org-user-add org_name user_name
ERROR: The object you are looking for could not be found
Response: Could not find user user_name

**Comment by stevendanna** [comment]
@sasideveloper My apologies that no one responded to this issue.  Given the age of this, I'm assuming that you no longer require assistance with this issue.  I'm going to close this ticket, but please if you still require assistance, please let me know and I can reopen it.
