### ISSUE TITLE
Updating a user account (resetting a key) breaks LDAP/AD authentication

### ISSUE THREAD

**Issue by yves-vogl** [chef/chef-server#66]
Hi,

to reproduce the bug:

1. Configure Chef Server to support ActiveDirectory autentication
2. Login with your ActiveDirectory account the first time
3. Click the button on the left side for creating a new user
4. Let someone invite you and accept the invitation
5. Logout

Now this happens every time you login now:

6. Login
7. You'll be directed to _Link an Existing Chef Account_
8. If you now try to login with your password (as this is your account), you'll get a 500
9 If you call the "/" path of the installation (instead of producing the step which leads to 500), you're logged in

**Comment by smith** [comment]
@sean-horn could you check to see if this is this a duplicate of #41 or if it's a different thing? I'm not sure.

**Comment by bjfelton** [comment]
I can also reproduce this bug using the following steps (Clean install of a 12.0.3 HA cluster):

1. Configure Chef Server to use AD authentication
2. Log in with AD creds
3. Create a new user (link accounts)

At this point, if you check opscode_chef.users, you should see that external_authentication_uid for the newly-created account is properly linked.  

```
SELECT username, email, external_authentication_uid
FROM users
WHERE username = 'first_last'

      username      |             email             | external_authentication_uid
--------------------+-------------------------------+-----------------------------
first_last          | first.last@domain.com         | first_last  

```

Now, back to the console:

1. Create a new org
2. Download the starter pack (you don't actually have to download it, just click through the 'reset keys' warning
3. Check opscode_chef.users again.  The external_authentication_uid column has been reset to nothing.

```
SELECT username, email, external_authentication_uid
FROM users
WHERE username = 'first_last'

      username      |             email             | external_authentication_uid
--------------------+-------------------------------+-----------------------------
first_last          | first.last@domain.com         | 

```

For users banging their head against this, you can work around the problem by logging into the opscode_chef db and resetting external_authentication_uid to what it should be.  

And counter to the original report, on a clean install of 12.0.3, simply removing the 'link-account' portion of the URI no longer allows me to circumvent the issue and continue using the console; instead, I am taken back to the login page.

**Comment by tenyo** [comment]
Thanks @bjfelton, this was driving me crazy! 
Everything was working fine for me on 12.0.2 standalone with AD authentication until I reset my key. After that I wasn't able to log back in as it said there was an existing account but it wouldn't let me link to it. 
I upgraded to 12.0.3 hoping that may fix it but I had the same issue (and couldn't just remove the /link in the URL to avoid it).
Just followed your recommendation to re-add my uid under external_authentication_uid in the database and it's working again. Good to know what's actually happening and how to work around it!

**Comment by yves-vogl** [comment]
@bjfelton Thanks. Updating the empty fields solved my issue.

**Comment by stevendanna** [comment]
@bjfelton Thank you for the excellent investigation.  I'll take a look at what the starter pack download is doing to see if we can nail this down further.

> And counter to the original report, on a clean install of 12.0.3, simply removing the 'link-account' portion of the URI no longer allows me to circumvent the issue and continue using the console; instead, I am taken back to the login page.

Closing off this workaround was partially my fault.  Allowing the user to log in (by editing the URI) without having the password of the user they want to link against was considered a security issue so we fixed it.  It likely did work in versions of opscode-manage prior to 1.8.1 (https://manage.chef.io/changelog#1.8.1)

**Comment by yves-vogl** [comment]
@stevendanna By the way… downloading the starter kit also resets the organizational key. We've 12 users and everytime someone downloaded the starter pack, we had to distribute a new organizational key to all users.

**Comment by bjfelton** [comment]
As a follow-up, resetting one's personal key also causes the external_authentication_uid to reset.  Since resetting the organizational pem does not cause this behavior, this is probably the true root cause behind the behavior when downloading the starter pack.

**Comment by stevendanna** [comment]
@bjfelton Yup.  The user's API endpoint currently expects the external_authentication_uid as part of the request body:

https://github.com/chef/oc_erchef/blob/master/apps/chef_objects/src/chef_user.erl#L350

Unfortunately, that field isn't returned when you issue a GET, so most API clients will not have anything for that field in the json they put/post.

**Comment by Tech356** [comment]
I have also been seeing this issue. Once users reset their key, they cannot log back in.

**Comment by Tech356** [comment]
Is this a Chef Server issue or a Chef Manage issue? Is there a fix in the works for this?

**Comment by sdelano** [comment]
@bjfelton @Tech356 - The code for this issue has been merged into the oc_erchef repository and will get released with the next version of the Chef Server. We're shooting to have a release out by the end of day PST tomorrow, February 25.

**Comment by kcorupe** [comment]
I installed chef-server-core 12.0.5-1 and I am still receiving a 500 server error after regenerating the users key. The external_authentication_uid field in postgres does not get reset anymore like it did in chef-server-core-12.0.4-1.

Same steps as OP to reproduce, this is on a fresh install Ubuntu 14.04 / chef-server-core_12.0.5 / opscode-manage_1.10.0-1. Setup AD LDAP, invite a user to the org, and once they generate their user key and log back in it fails.

**Comment by stevendanna** [comment]
@kcorupe Can you check `/var/log/opscode/opscode-erchef/current` on your chef-server after reproducing this error?  If you see error output there, please include it here.

**Comment by kcorupe** [comment]
```
2015-03-03_20:36:13.48057 [error] {<<"method=POST; path=/authenticate_user; status=500; ">>,{error,{error,badarg,[{erlang,iolist_to_binary,[[null,"--",<<"PASSWORD">>,"--"]],[]},{crypto,hash,2,[{file,"crypto.erl"},{line,228}]},{chef_password,sha1,3,[{file,"src/chef_password.erl"},{line,104}]},{chef_password,verify,2,[{file,"src/chef_password.erl"},{line,92}]},{oc_chef_wm_authenticate_user,verify_user,5,[{file,"src/oc_chef_wm_authenticate_user.erl"},{line,99}]},{oc_chef_wm_authenticate_user,process_post,2,[{file,"src/oc_chef_wm_authenticate_user.erl"},{line,87}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,186}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,142}]}]}}}
```

Thats the error I get when logging in after a user key has been reset.

**Comment by stevendanna** [comment]
@kcorupe Thanks.  I believe a few others have seen this as well.  We'll try to dig into it.

**Comment by stevendanna** [comment]
@kcorupe Could you email me a copy of your /etc/opscode/chef-server.rb and /var/opt/opscode/opscode-erchef/etc/app.config (feel free to scrub creds).  My email address is steve@chef.io.

**Comment by stevendanna** [comment]
@kcorupe I've fined a new bug about your issue here: https://github.com/chef/chef-server/issues/119
