### ISSUE TITLE
CS12: LDAP Doesn't Allow Anonymous Bind

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#67]
This is potentially a bug, as we have customers that use anonymous binds to contact their LDAP servers.

I believe this says that we always perform a bind and try to use credentials that may or may not be there.
https://github.com/opscode/oc_erchef/blob/95d80e2af0b143e66c111584ed4626db8cfa6663/apps/oc_chef_wm/src/oc_chef_wm_authn_ldap.erl#L79-L120

This is a regression from EC 11.x

When a customer tries an anonymous bind (no bind_dn or bind_password specified in /etc/opscode/chef-server.rb), they get the following

    2015-01-19 11:24:13.559 [error] FORMAT ERROR: "Could not bind as ~p, please check private-chef.rb for correct bind_dn, bind_password, host, port and encrpytion values. Error: " [[],anonymous_auth]

We see this when tracing "find_and_authenticate_user", even with bind_dn and bind_password set to be empty strings like this in /etc/opscode/chef-server.rb

    ldap['bind_dn'] = ''
    ldap['bind_password'] = ''

    % 08:19:20 <0.764.0>({mochiweb_acceptor,init,3}) 
    % oc_chef_wm_authn_ldap:find_and_authenticate_user/4 -> {error, 
    {badmatch, 
    {error, 
    anonymous_auth}}}

**Comment by marcparadise** [comment]
Agreed this is a regression, though it's worth trying to use empty strings in those fields. I've added to our backlog.

**Comment by stevendanna** [comment]
Fixed in 12.04: https://github.com/chef/opscode-omnibus/blob/master/RELEASE_NOTES.md#1204-2014-02-19
