### ISSUE TITLE
oc-bifrost-pedant not merged into the repository

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#670]
Bifrost (the authorization service) has its own set of pedant tests.  They can be found here:

https://github.com/chef/oc-bifrost-pedant (still private for some reason).

These tests also don't run in CI as far as I can see.  Are these tests still important?  If so, we should merge them into this repository and make sure we run them in the CI pipeline.

**Comment by tylercloke** [comment]
Fixed by https://github.com/chef/chef-server/pull/761
