### ISSUE TITLE
chef-server-ctl tail: cannot follow ‘-’ by name

### ISSUE THREAD

**Issue by umang1912** [chef/chef-server#672]
I've symlinked /var/log/opscode to another volume (because of root disk space issues), and `chef-server-ctl tail` isnt working for me anymore. Chef server is behaving normally and all log files are getting written.

Quick online search showed similar issue with [gitlab-ctl](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/726). Is this a code bug?

**Comment by stevendanna** [comment]
It definitely looks like a bug to me.

**Comment by virtuman** [comment]
i have the same issue. although everything worked during the first couple of days properly. i'm running chef in docker container.

**Comment by stevendanna** [comment]
@balasankarc Seems reasonable.
