### ISSUE TITLE
LDAP user name mojibake

### ISSUE THREAD

**Issue by takkawai** [chef/chef-server#675]
https://github.com/chef/chef-server/blob/master/src/oc_erchef/apps/oc_chef_wm/src/oc_chef_wm_authn_ldap.erl#L176

About this line, when the value of eladp_entry includes multibyte characters, it will be mojibake (corrupted).
(1) Could you fix it not to be mojibake?
(2) I think that this code uses "displayname" or "display_name" attribute of LDAP.
Can we use "displayNamePrintable" in stead of it?

**Comment by echohack** [comment]
To +1 what @takkawai is saying here: When you have an Active Directory user that is populated into Chef via LDAP(s) that has Japanese characters (mojibake) it causes the username to become corrupted. It appears that Chef Server is using US-ascii encoding, and not UTF-8 to translate these user names.

@takkawai Can you provide an example (screenshot) of the problem to help highlight this issue?
