### ISSUE TITLE
Issue with Postgres DB?

### ISSUE THREAD

**Issue by magpi** [chef/chef-server#678]
Hello, I'm seeing the following errors in my "chef-server-ctl tail" when I'm trying to update a node using knife:

==> /var/log/opscode/postgresql/9.2/current <==
2015-12-29_05:43:05.29641 ERROR:  column "policy_name" of relation "nodes" does not exist at character 35
2015-12-29_05:43:05.29647 STATEMENT:  UPDATE nodes SET environment= $1, policy_name= $2, policy_group= $3, last_updated_by= $4, updated_at= $5, serialized_object= $6 WHERE id= $7

==> /var/log/opscode/opscode-erchef/erchef.log <==
2015-12-28 22:43:05.301 [error] {<<"method=PUT; path=/organizations/myorg/nodes/APP-1; status=500; ">>,"Internal Server Error"}

==> /var/log/opscode/opscode-erchef/crash.log <==
2015-12-28 22:43:05 =ERROR REPORT====
{<<"method=PUT; path=/organizations/myorg/nodes/APP-1; status=500; ">>,"Internal Server Error"}

==> /var/log/opscode/opscode-erchef/current <==
2015-12-29_05:43:05.30572 [error] {<<"method=PUT; path=/organizations/myorg/nodes/APP-1; status=500; ">>,"Internal Server Error"}

Do you have any ideas or suggestions on how I might resolve this?  I'm guessing that there's a DB issue with the Postgres DB, but I'm not entirely sure.  For some prior background, I had been running Chef 11 for awhile and then upgraded to Chef 12 (the package was automatically upgraded as a part of the Ubuntu apt-get upgrade process).

Thanks in advance for any ideas/ and help on getting this resolved.

**Comment by irvingpop** [comment]
`column "policy_name" of relation "nodes" does not exist`  - this implies that the database schema is older than the version Chef expects -  try running `chef-server-ctl upgrade`

**Comment by magpi** [comment]
That did the trick (`chef-server-ctl upgrade`)!  After completing the upgrade, I did have to manually start the server with `chef-server-ctl restart` (for anyone else's benefit who might see this).

Seems that I got into this situation via a "routine" package upgrade (`apt-get upgrade`).  I'm not sure if I made a newbie mistake (in not doing the DB upgrade by hand) or if this should've been taken care of during the apt-get process.  I don't recall seeing any instructions on what else should be done to ensure that Chef was functioning (from the package upgrade process from Chef 11 -> 12).

Either way, I'm working now - thanks for your time and help!

**Comment by irvingpop** [comment]
anytime!

For reference, the [upgrade instructions](https://docs.chef.io/upgrade_server.html) tell you to `upgrade`, `start` and `cleanup` every time you upgrade the package.   It's not something we recommend doing by `apt-get upgrade` or `yum upgrade`
