### ISSUE TITLE
Error while installing Chef server 12.3 on Red hat 6.7

### ISSUE THREAD

**Issue by smargechef** [chef/chef-server#681]
Hi All ,
Getting below issue while installing chef server 12.3 on RHEL 6.7 server.
## Can you please help to resolve this?

Recipe: private-chef::opscode-erchef
- runit_service[opscode-erchef] action enable
  Recipe: <Dynamically Defined Resource>

```
* directory[/opt/opscode/sv/opscode-erchef] action create (up to date)
* template[/opt/opscode/sv/opscode-erchef/run] action create (up to date)
* directory[/opt/opscode/sv/opscode-erchef/log] action create (up to date)
* directory[/opt/opscode/sv/opscode-erchef/log/main] action create (up to date)
* template[/opt/opscode/sv/opscode-erchef/log/run] action create (up to date)
* template[/opt/opscode/sv/opscode-erchef/log/config] action create (up to date)
* link[/opt/opscode/init/opscode-erchef] action create (up to date)
 (up to date)
```

Recipe: private-chef::bootstrap
- template[/opt/opscode/embedded/service/chef-server-bootstrap/bootstrapper-config/config.rb] action create (up to date)
- template[/opt/opscode/embedded/service/chef-server-bootstrap/bootstrapper-config/pivotal.yml] action create (up to date)
- execute[/opt/opscode/bin/private-chef-ctl start] action run
  - execute /opt/opscode/bin/private-chef-ctl start
- execute[bootstrap-platform] action run
  # 
  # Error executing action `run` on resource 'execute[bootstrap-platform]'
  ## Mixlib::ShellOut::ShellCommandFailed
  
  Expected process to exit with [0], but received '1'
  ---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
  STDOUT:
  STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9463 (Errno::ECONNREFUSED)
      from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in`open'
      from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
      from /opt/opscode/embedded/lib/ruby/2.1.0/timeout.rb:76:in`timeout'
      from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
      from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:863:in`do_start'
      from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
      from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in`transmit'
      from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
      from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in`execute'
      from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in `post'
      from ./bin/bootstrap-platform:101:in`create_object_in_authz'
      from ./bin/bootstrap-platform:47:in `bootstrap'
      from ./bin/bootstrap-platform:120:in`<main>'
  ---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
  Ran /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml returned 1
  ## Resource Declaration:
  # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb
  
   45: execute "bootstrap-platform" do
   46:   command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
   47:   cwd opscode_test_dir
   48:   retries 3
   49:   not_if { OmnibusHelper.has_been_bootstrapped? }
   50:   notifies :restart, 'service[opscode-erchef]'
   51: end
   52:
  ## Compiled Resource:
  # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/bootstrap.rb:45:in `from_file'
  
  execute("bootstrap-platform") do
    action [:run]
    retries 3
    retry_delay 2
    default_guard_interpreter :execute
    command "/opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml"
    backup 5
    cwd "/opt/opscode/embedded/service/chef-server-bootstrap"
    returns 0
    declared_type :execute
    cookbook_name "private-chef"
    recipe_name "bootstrap"
    not_if { #code block }
  end

Running handlers:
[2016-01-05T18:03:30+05:30] ERROR: Running exception handlers
Running handlers complete
[2016-01-05T18:03:30+05:30] ERROR: Exception handlers complete
Chef Client failed. 22 resources updated in 01 minutes 04 seconds
[2016-01-05T18:03:30+05:30] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
[2016-01-05T18:03:32+05:30] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[bootstrap-platform](private-chef::bootstrap line 45) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
STDOUT:
STDERR: /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "127.0.0.1" port 9463 (Errno::ECONNREFUSED)
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in`open'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
        from /opt/opscode/embedded/lib/ruby/2.1.0/timeout.rb:76:in`timeout'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:878:in `connect'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:863:in`do_start'
        from /opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in`transmit'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in`execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in `post'
        from ./bin/bootstrap-platform:101:in`create_object_in_authz'
        from ./bin/bootstrap-platform:47:in `bootstrap'
        from ./bin/bootstrap-platform:120:in`<main>'
---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----

**Comment by stevendanna** [comment]
My apologies no one responded to this issue.  I'm going to close this for now; however, if you still require help please feel free to reopen this issue or open a new issue.
