### ISSUE TITLE
Set rabbitmq_management listener IP to `node['private_chef']['rabbitmq']['node_ip_address']`

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#686]
Please set the `rabbitmq_management` listener IP to `node['private_chef']['rabbitmq']['node_ip_address']` in [the omnibus configuration](https://github.com/chef/chef-server/blob/12.3.1/omnibus/files/private-chef-cookbooks/private-chef/templates/default/rabbitmq.config.erb#L11) asap.

The current behavior breaks Chef Servers that run version 12.3+ and set `rabbitmq['vip']` to an FQDN. This is especially true of Chef Servers installed by the delivery-cluster cookbook because its default behavior is to set `rabbitmq['vip']` to an FQDN.

The `rabbitmq_management` listener IP setting only takes an IP address as a value so if `rabbitmq['vip']` is set in chef-server.rb to an FQDN rabbitmq_management refuses to come up which prevents rabbitmq from coming up which ultimately breaks the Chef Server API.

```
Error description:
   {could_not_start,rabbitmq_management,
       {could_not_start_listener,
           [{ip,"chef.lxc"},{port,15672},{ssl,true}],
           {'EXIT',
               {{badmatch,{error,einval}},
                [{mochiweb_socket_server,parse_options,2,[]},
                 {mochiweb_socket_server,start_link,1,[]},
                 {supervisor,do_start_child,2,
                     [{file,"supervisor.erl"},{line,314}]},
                 {supervisor,handle_start_child,2,
                     [{file,"supervisor.erl"},{line,685}]},
                 {supervisor,handle_call,3,
                     [{file,"supervisor.erl"},{line,394}]},
                 {gen_server,try_handle_call,4,
                     [{file,"gen_server.erl"},{line,607}]},
                 {gen_server,handle_msg,5,
                     [{file,"gen_server.erl"},{line,639}]},
                 {proc_lib,init_p_do_apply,3,
                     [{file,"proc_lib.erl"},{line,237}]}]}}}}
```

The `rabbitmq['node_ip_address']` setting is specifically available for defining what IP address rabbitmq should bind to. rabbitmq_management should bind to the same IP address.

The `rabbitmq['vip']` setting is specifically available for defining what IP address or FQDN services should use to connect to rabbitmq and should not be used in this case.

**Comment by irvingpop** [comment]
For Analytics we tell customers to set `rabbitmq['node_ip_address']` to '0.0.0.0'  - will that value work for the rabbitmq_management listener IP?

**Comment by metadave** [comment]
@irvingpop *probably*, I had to wrangle the mgmt plugin ssl params a bit so I don't fully trust the mgmt config. 

Possibly related: https://github.com/mochi/mochiweb/blob/master/src/mochiweb_socket_server.erl#L110

**Comment by jeremiahsnapp** [comment]
@irvingpop yes i've confirmed that the typical values of 127.0.0.1 and 0.0.0.0 both work fine for rabbitmq_management

**Comment by irvingpop** [comment]
@jeremiahsnapp Awesome!   Can you whip up a PR for that (0.0.0.0) and run a build through CI so we can test it out?

**Comment by stevendanna** [comment]
I'd prefer `rabbitmq['node_ip_address']` over 0.0.0.0 being hard coded.
