### ISSUE TITLE
rabbitmq['management_enabled'] setting doesn't actually do anything

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#688]
The `rabbitmq['management_enabled']` setting doesn't actually do anything.

https://github.com/chef/chef-server/blob/12.3.1/omnibus/files/private-chef-cookbooks/private-chef/attributes/default.rb#L127

The ability to easily disable rabbitmq management would be really nice especially when trying to avoid other issues such as https://github.com/chef/chef-server/issues/686

**Comment by stevendanna** [comment]
Looks like this was solved in https://github.com/chef/chef-server/commit/83ba83552a34d41f55f40f56c5b969174c3fdd8c  Thanks for reporting it!
