### ISSUE TITLE
Organizations starting with "bookshelf" are unusable

### ISSUE THREAD

**Issue by stevendanna** [chef/chef-server#694]
If you try to create an organization named "bookshelf" or "bookshelf-test" or "bookshelfANYTHING", the organization will be largely unusable.  For example, you won't be able to associate users to it:

```
root@api:/tmp# chef-server-ctl org-user-add bookshelf-test uploader -a
ERROR: Method Not Allowed
Response: <html><head><title>405 Method Not Allowed</title></head><body><h1>Method Not Allowed</h1>Method Not Allowed<p><hr><address>mochiweb+webmachine web server</address></body></html>
```

The root cause is a bad nginx rule that routes all the traffic to the bookshelf service rather than nginx:

```
    # bookshelf
    location ~ "/bookshelf/{0,1}.*$" {
      proxy_pass http://bookshelf;
    }
```

**Comment by ameir** [comment]
Per our discussion over the mailing list, this also impacts cookbooks whose names match the bookshelf or bucket name:
https://discourse.chef.io/t/issues-with-new-chef-server-and-s3-bookshelf/10462

It sounds like it'd also affect creating an organization that matches an S3 bucket name, when not using the built-in bookshelf.

For the S3 case, simply removing that block should fix it.

**Comment by stevendanna** [comment]
This is fixed and should be available in the next release.
