### ISSUE TITLE
pivotal.pem Missing on New Chef Server Install (HA Topology)

### ISSUE THREAD

**Issue by nathan-lochala** [chef/chef-server#727]
When setting up a new high-availability chef-server installation, `chef-server-ctl reconfigure` fails claiming it is missing the /etc/opscode/pivotal.pem file. Below is the output when running `chef-server-ctl reconfigure` a second time on a new chef server installation.

```
Starting Chef Client, version 12.6.0
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - enterprise (0.5.1)
  - chef-sugar (3.1.1)
  - private-chef (0.1.0)
  - apt (2.7.0)
  - yum (3.6.0)
  - openssl (4.4.0)
  - runit (1.6.0)
  - packagecloud (0.0.18)
Compiling Cookbooks...
/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/preflight_checks.rb:139: warning: already initialized constant PreflightChecks::LINE_SEP
/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/preflight_checks.rb:139: warning: previous definition of LINE_SEP was here
Recipe: private-chef::default
  * directory[/etc/opscode] action create
    - change owner from 'vagrant' to 'root'
    - change group from 'vagrant' to 'root'
    - restore selinux security context
  * directory[/etc/opscode/logrotate.d] action create
    - change owner from 'vagrant' to 'root'
    - change group from 'vagrant' to 'root'
    - restore selinux security context
[2016-02-01T18:41:20+00:00] FATAL:

-----------------------------------------------------------------------
BOOT007: The secrets file (/etc/opscode/private-chef-secrets.json) is present
         but the file /etc/opscode/pivotal.pem is missing.

         Ensure that private-chef-secrets.json is copied into /etc/opscode from the
         first Chef Server node that you brought online, then run
         'chef-server-ctl reconfigure' again.
-----------------------------------------------------------------------
```

**Comment by thanizebra** [comment]
root@chs:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
root@chs:~# 

root@chs:~# chef-server-ctl reconfigure
Starting Chef Client, version 12.7.0
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - enterprise (0.5.1)
  - apt (2.7.0)
  - yum (3.6.0)
  - openssl (4.4.0)
  - runit (1.6.0)
  - chef-sugar (3.1.1)
  - packagecloud (0.0.18)
Compiling Cookbooks...
/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/preflight_checks.rb:139: warning: already initialized constant PreflightChecks::LINE_SEP
/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/preflight_checks.rb:139: warning: previous definition of LINE_SEP was here
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)
[2016-02-09T17:13:48+05:30] FATAL: 

-----------------------------------------------------------------------
BOOT007: The secrets file (/etc/opscode/private-chef-secrets.json) is present
         but the file /etc/opscode/pivotal.pem is missing.

         Ensure that private-chef-secrets.json is copied into /etc/opscode from the
         first Chef Server node that you brought online, then run
         'chef-server-ctl reconfigure' again.
-----------------------------------------------------------------------
root@chs:~# 


same error occur on docker container.

**Comment by marcparadise** [comment]
Howdy @nathan-lochala , sorry to hear you're running into this. 
Could you provide a bit more info about what you mean with 'second run on a chef server installation'?  Which node(s) in the HA install are seeing it after the first reconfigure is complete? (Backend 1/ 2, front-end, or all).

**Comment by marcparadise** [comment]
@thanizebra  what topology are you installing, and which node(s) are you seeing this on?

**Comment by marcparadise** [comment]
Finally - if you could also both confirm that both pivotal.pem and private-chef-secrets.json are in /etc/opscode of the node(s) reporting the error, it would help in recreating.

**Comment by nathan-lochala** [comment]
I'll try and explain this as best I can. 
Here are the steps to reproducing. 

- Created a VM (CentOS 6.7)
- mkdir /etc/opscode
- Created chef-server.rb file. 

```
topology "ha"

keepalived['vrrp_instance_interface'] = "ethic
keepalived['vrrp_instance_ipaddress_dev'] = "ethic

server "be1.localnet",
  :ipaddress => "192.168.0.20",
  :role => "backend",
  :bootstrap => true,
  :cluster_ipaddress => "192.168.1.20"

server "be2.localnet",
  :ipaddress => "192.168.0.21",
  :role => "backend",
  :cluster_ipaddress => "192.168.1.21"

backend_vip "bevip.localnet",
  :ipaddress => "192.168.0.100",
  :device => "ethic

server "fe1.localnet",
  :ipaddress => "192.168.0.10",
  :role => "frontend"

server "fe2.localnet",
  :ipaddress => "192.168.0.11",
  :role => "frontend"

api_fqdn "vip.localnet"
```

- Download chef-server.rpm (https://packagecloud.io/chef/stable/packages/el/6/chef-server-core-12.4.1-1.el6.x86_64.rpm/download)
- Installed DRBD

```
rpm --import http://elrepo.org/RPM-GPG-KEY-elrepo.org
rpm -Uvh http://elrepo.org/elrepo-release-6-5.el6.elrepo.noarch.rpm
yum install -y drbd84-utils kmod-drbd84
```

- Installed Chef Server
```
rpm -Uvh chef-server-core-12.4.1-1.el6.x86_64.rpm
```

- Ran chef reconfigure
```
chef-server-ctl reconfigure
```
**NOTE: This is where I am faced with the message to stop the chef run by pressing CTRL-C**
```
[2016-02-10T22:09:45+00:00] WARN: Please defer to your Private Chef manual for instructions on initializing the device.
[2016-02-10T22:09:45+00:00] WARN: Cannot find /var/opt/opscode/drbd/drbd_ready - please bootstrap DRBD and run 'touch /var/opt/opscode/drbd/drbd_ready'.
[2016-02-10T22:09:45+00:00] WARN: Press CTRL-C to abort.
```

- I press CTRL-C and stop the run.
**Up to this point, I'm following instructions outlined in the docs.**

- Let's say, I reconfigure the chef-server again. Theoretically, I should be able to run `chef-server-ctl reconfigure` as many times as I want in a row and the results should be the same. 
```
chef-server-ctl reconfigure
```
**However, this time I'm faced with a different message:**
```
Starting Chef Client, version 12.7.0
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - enterprise (0.5.1)
  - yum (3.6.0)
  - packagecloud (0.0.18)
  - chef-sugar (3.1.1)
  - runit (1.6.0)
  - openssl (4.4.0)
  - apt (2.7.0)
  - private-chef (0.1.0)
Compiling Cookbooks...
/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/preflight_checks.rb:139: warning: already initialized constant PreflightChecks::LINE_SEP
/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/libraries/preflight_checks.rb:139: warning: previous definition of LINE_SEP was here
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create (up to date)
[2016-02-10T22:09:53+00:00] FATAL:

-----------------------------------------------------------------------
BOOT007: The secrets file (/etc/opscode/private-chef-secrets.json) is present
         but the file /etc/opscode/pivotal.pem is missing.

         Ensure that private-chef-secrets.json is copied into /etc/opscode from the
         first Chef Server node that you brought online, then run
         'chef-server-ctl reconfigure' again.
-----------------------------------------------------------------------
```

- It looks like the problem is here: [https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/recipes/default.rb](url) between lines 59 and 154. My guess is one of the include_recipe lines is running a `preflight_check` that looks for the existence of the `pivotal.pem` file before the actual resources are running to create the file. In `default.rb:176` the file `pivotal.pem` is created. Does that make sense?

**Comment by thanizebra** [comment]
@marcparadise i am installing on docker container ubuntu -14.04

**Comment by marcparadise** [comment]
Excellent, thanks for the detail @nathan-lochala , I will be looking into this by tomorrow morning.

**Comment by marcparadise** [comment]
@nathan-lochala in the interim, would you be able to validate that making the change below allows you to continue, and you run into no further issues? 


In /opt/opscode/embedded/cookbooks/lprivate-chef/libraries/preflight_bootstrap_validator.rb, line 26 - could you change this: 
```
  def run!
    # Sanity checks: for any configuration we should expect that
    # neither pivotal.pem nor private-chef-secrets.json exists, or that both exist.
    validate_sane_state
```

To 
```
  def run!
    # Sanity checks: for any configuration we should expect that
    # neither pivotal.pem nor private-chef-secrets.json exists, or that both exist.
    validate_sane_state unless node['topology'] == 'ha'
```
(Full file/location can be viewed here: https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/libraries/preflight_bootstrap_validator.rb#L26) 

Thanks again!

**Comment by nathan-lochala** [comment]
@marcparadise I made the below change to the `file: /opt/opscode/embedded/cookbooks/private-chef/libraries/preflight_bootstrap_validator.rb`

```
preflight_bootstrap_validator.rb:23

  def run!
    # Sanity checks: for any configuration we should expect that
    # neither pivotal.pem nor private-chef-secrets.json exists, or that both exist.
   validate_sane_state unless node['topology'] == 'ha'
```
After I made that change, I ran `chef-server-ctl reconfigure` again. However, the result was the same. I then made an additional change:
```
preflight_bootstrap_validator.rb:23

  def run!
    # Sanity checks: for any configuration we should expect that
    # neither pivotal.pem nor private-chef-secrets.json exists, or that both exist.
   Chef::Log.fatal(node['topology'])
   validate_sane_state unless node['topology'] == 'ha'
```

The resulting output was: 
```
[2016-02-11T17:13:20+00:00] FATAL: nil
```
So, it would seem that `topology` isn't set on the node when it hits the preflight check. Not sure why. The node is set with a large number of parameters. Example: `Chef::Log.fatal(node.inspect)` returns many set values, but none that specify `topology`. 

Thank you for your help!

**Comment by marcparadise** [comment]
My bad, I missed part of the key. Can you change that to `node['private_chef']['topology']`?

**Comment by sbstnbr** [comment]
Dear both,

I faced the same issue after trying to install Chef Server a first time and having faced an issue with RabbitMQ because Qpid was still active. 

To fix it, I deleted `/etc/opscode/private-chef-secrets.json` and run again `chef-server-ctl reconfigure`

**Comment by rossedman** [comment]
@sbstnbr This worked for me. Thank you!

**Comment by rossedman** [comment]
@sbstnbr Alright, never mind. It worked once for me. Keep running into this problem and am beating my head against the wall.

**Comment by dushan566** [comment]
Hi,

For /etc/opscode/pivotal.pem is missing error use following command.
cp /opt/opscode/embedded/service/omnibus-ctl/spec/fixtures/pivotal.pem  /etc/opscode/

**Comment by isurfbecause** [comment]
Thank you, after hours of searching this helped!

**Comment by ben-nz** [comment]
Copying in pivotal.pem worked for me as well, thanks

**Comment by rjlohman** [comment]
@dushan566 Thanks. Worked like a charm.

**Comment by srenatus** [comment]
@dushan566 @ben-nz @isurfbecause @rjlohman **Please reconsider this.** That `pivotal.pem` in the `omnibus-ctl` spec directory *is a test fixture* and should not be used under any circumstances. I suspect the error message is incorrect, [as it should ask you to copy the `pivotal.pem` *from the first installed chef-server*](https://github.com/chef/chef-server/blob/a4af7ac38bb6fedac3c9baa6bc682821776b04cf/omnibus/files/private-chef-cookbooks/private-chef/libraries/preflight_bootstrap_validator.rb#L198) (the one you've copied `private-chef-secret.json` from).

**Comment by bklnnet** [comment]
@srenatus what first installed chef-server? In my case this is the first one and I have the same issue and that pivotal.pem key is the only one I can find

**Comment by bklnnet** [comment]
Anyway, didn't work, got some errors running handlers, got the stacktrace so I will include it in the report. Just wondering whether that pem file copy was just a miss or we have a bigger problem here like where the initial key comes from (or should come from).

**Comment by srenatus** [comment]
@bklnnet If this is a fresh install, that key would be generated. If you've got no data to lose, you can also do `chef-server-ctl cleanse` to start over (this will wipe out all data, use it with care).

**Comment by PrajaktaPurohit** [comment]
We do not support the HA Topology going forward. Closing this.
