### ISSUE TITLE
upgrade from 11 to 12 fails, Sequel::ForeignKeyConstraintViolation

### ISSUE THREAD

**Issue by santhoshjavapro** [chef/chef-server#73]
Hi,
     I m quite new to chef and I m trying to upgrade a chef-server-11 to chef-server-12, 

OS: CentOS release 6.4 (Final)
old chef version: 11.0.8
new chef version: 12.0.2
Instructions used for upgrade: 
https://docs.chef.io/upgrade_server.html#from-chef-server-osc
https://github.com/chef/chef-server/issues/61 (to upgrade to 11.1.x and then to 12 as per Mark's comments)

and the error I got is
....
...
Chef Client finished, 30/394 resources updated in 38.417940844 seconds
opscode Reconfigured!
Ensuring Chef 12 server components are started
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
ok: run: bookshelf: (pid 7349) 0s
ok: run: nginx: (pid 7381) 0s
ok: run: oc_bifrost: (pid 7385) 1s
ok: run: oc_id: (pid 7412) 0s
ok: run: opscode-chef-mover: (pid 7417) 0s
ok: run: opscode-erchef: (pid 7423) 0s
ok: run: opscode-expander: (pid 7466) 1s
ok: run: opscode-expander-reindexer: (pid 7493) 0s
ok: run: opscode-solr4: (pid 7523) 1s
ok: run: postgresql: (pid 7219) 21s
ok: run: rabbitmq: (pid 6734) 38s
ok: run: redis_lb: (pid 7329) 6s
Chef 12 server started
Writing knife-ec-backup config to /tmp/knife-ec-backup-config.rb
Uploading transformed open source Chef 11 server data to Chef 12 server
WARNING: WebUI not specified. Using /etc/opscode/webui_priv.pem
Detected Enterprise Chef Server version: 12.0.2
Restoring users ...
Updating key for user1
Updating key for user2
Updating key for user3
Updating key for user4
Updating key for user5
Updating key for user6
ERROR: Sequel::ForeignKeyConstraintViolation: PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "org_user_associations_user_id_fkey" on table "org_user_associations"
DETAIL:  Key (id)=(000000000000e0f69d505e5228dc022b) is still referenced from table "org_user_associations".
Failed uploading transformed data to the Chef 12 server

p.s: It was chef-server-11.0.8, I upgraded to chef-server-11.1.3 and then tried to update for chef-server-12.

**Comment by stevendanna** [comment]
@santhoshjavapro Had you previously had chef-server-12 installed on the server in question?  The most likely cause of this is that you already had a partially populated chef-server-12 users table in the Chef 12 data directory /var/opt/opscode.

**Comment by santhoshjavapro** [comment]
@stevendanna yes I installed and upgraded to chef-server-12  from chef-server-11.0.8 and it didn't work so installed chef-server-11.1.3 and then tried to upgrade to chef-server-12 for auto upgradation as mentioned by mike in issue#61, so how can fix this issue?

TIA

**Comment by santhoshjavapro** [comment]
@stevendanna sorry its mark not mike. :D

**Comment by santhoshjavapro** [comment]
@stevendanna I uninstalled chef-server-core-12 package and delete the opscode folder and reinstalled, upgraded and it worked like charm :) 
Thanks for the clue. 
Closing this issue.
