### ISSUE TITLE
Self-signed Nginx SSL key has unnecessarily open permissions

### ISSUE THREAD

**Issue by elyscape** [chef/chef-server#731]
The self-signed SSL key (and certificate and dhparam file) generated for Nginx [is created with permissions of `0644`](https://github.com/chef/chef-server/blob/12.4.1/omnibus/files/private-chef-cookbooks/private-chef/recipes/nginx.rb#L56-L76). This is unnecessarily wide. The parent directory does disallow access to users not in the `opscode` group, but it's still best practice to set the permissions on the SSL key to `0600`. The key only needs to be able to be read by the Nginx master process, which runs as root, for things to work correctly.

**Comment by PrajaktaPurohit** [comment]
@elyscape Sorry this has taken us so long to get back to you. We will test if this remains the case with the new chef-server and fix accordingly. Thank you for reporting the bug!

**Comment by kaorihinata** [comment]
This issue has been fixed for certificates (see commit: 7e7e0a8), but not for dhparams. I don't believe this will affect any other services as, unlike with the certificates, the dhparams are not shared with other services.

**Comment by kaorihinata** [comment]
This issue has been fixed for certificates (see commit: 7e7e0a8), but not for dhparams. I don't believe this will affect any other services as, unlike with the certificates, the dhparams are not shared with other services.
