### ISSUE TITLE
Update default TLS versions config

### ISSUE THREAD

**Issue by coderanger** [chef/chef-server#738]
The current default value for `nginx['ssl_protocols']` is `'TLSv1 TLSv1.1 TLSv1.2'`. We really shouldn't have 1.0 in there due to weak IV issues and really is there any reason to support 1.1?

Disclaimer: FIPS-mode might need different defaults, no idea what it mandates.

**Comment by stevendanna** [comment]
I'm :+1: on this.  We can clearly document the configurable for those who require supporting older platforms.  @coderanger any thoughts on our current ssl_ciphers value?

**Comment by coderanger** [comment]
For Nginx the default is `ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA`

That can be reduced to `ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;` but I don't see anything hugely wrong with the current one.

It is also worth noting that we are _not_ setting a cipher list for Postgres and it's defaults probably unsafe (i.e. RC4 is not disable).

**Comment by stevendanna** [comment]
Thanks for reporting this Noah.  In Chef 12.10 we've moved to a much more aggressive default install based on Mozilla's "modern" recommendation: https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/attributes/default.rb#L469-L472

Going to close this for now, but it is something that we'll need to keep on eye on over time.
