### ISSUE TITLE
chef-server-ctl install fails on Amazon Linux

### ISSUE THREAD

**Issue by jamesc** [chef/chef-server#741]
The yum. repos.d  is written as:

`* template[/etc/yum.repos.d/chef-stable.repo] action create
       [chef-stable]
       name=Chef Stable Repo
      baseurl=https://packagecloud.io/chef/stable/el/2015/$basearch
       enabled=0
       gpgcheck=1
       gpgkey=file:///opt/opscode/embedded/keys/packages-chef-io-public.key`

this is due to platform_family being e.g `2016.09` instead of `7.X`

Responsible code is https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/recipes/add_ons_repository.rb#L29

This needs to have special casing for amazon linux (always use 7 ?)

**Comment by juliandunn** [comment]
I'm going to assume this is no longer an issue given that we are shipping it as part of the AIO on Opsworks which is on Amazon Linux.
