### ISSUE TITLE
chef-server components should not store cleartext passwords

### ISSUE THREAD

**Issue by pburkholder** [chef/chef-server#750]
Some organizations have security requirements that frown upon software components storing clear-text passwords in configuration files, e.g. the various `sys.config` files generated in `/var/opt/opscode` by `chef-server-ctl reconfigure`

I'm opening this issue to generate a tracking id for discussions with users.

**Comment by markan** [comment]
I believe this has been addressed with the chef-secrets work merged in 12.14.0
