### ISSUE TITLE
Cookbook upload missing subdirectories in libraries

### ISSUE THREAD

**Issue by jmccann** [chef/chef-server#751]
If I try to upload a cookbook with subdirectories in libraries (such as https://supermarket.chef.io/cookbooks/f5-bigip, https://github.com/target/f5-bigip-cookbook/tree/master/libraries/load_balancer) it does not seem to include all the subdirectory files on the Chef Server.

Our Chef server is 2.1.2 I think (based on it's /changelog)

So if I `knife cookbook upload f5-bigip` it does create the cookbook in my org on the Chef Server but does not contain `/libraries/load_balancer/**/*`.

I would expect it to contain the subdirectories contained in [libraries](https://github.com/target/f5-bigip-cookbook/tree/master/libraries/load_balancer).

I'm assuming this is supposed to work based on https://github.com/chef/chef/pull/2129 and the fact it uploads everything fine to supermarket and that the cookbook runs fine as well in a chef zero environment.

Thanks!

**Comment by gkra** [comment]
How is this this cookbook being used internal to Target? Is it running in Chef Zero?
