### ISSUE TITLE
ubuntu_supported_codenames should include trusty instead of natty

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef-server#759]
The [Chef Server Downloads site for Ubuntu](https://downloads.chef.io/chef-server/ubuntu/) only lists 10.04 (lucid), 12.04 (precise) and 14.04 (trusty) so the `ubuntu_supported_codenames` attribute defined in the code linked below should be set to `%w{lucid precise trusty}`.

https://github.com/chef/chef-server/blob/12.4.1/omnibus/files/private-chef-cookbooks/private-chef/attributes/default.rb#L55-L56

The current value of `%w{lucid natty precise}` is causing people using `chef-server-ctl install` on Ubuntu 14.04 to fallback to the lucid repository, as seen in the code linked below, which ultimately results in the wrong add on package to be installed in some cases.

https://github.com/chef/chef-server/blob/12.4.1/omnibus/files/private-chef-cookbooks/private-chef/recipes/add_ons_repository.rb#L18

An example of a problematic package

```
$ apt-cache policy chef-ha 
chef-ha: 
Installed: 1.0.0-1 
Candidate: 1.0.0-1 
Version table: 
*** 1.0.0-1 0 
500 https://packagecloud.io/chef/stable/ubuntu/ trusty/main amd64 Packages 
100 /var/lib/dpkg/status
```

vs.

```
$ apt-cache policy chef-ha 
chef-ha: 
Installed: (none) 
Candidate: 1.0.0-rc.3-1 
Version table: 
1.0.0-rc.3-1 0 
500 https://packagecloud.io/chef/stable/ubuntu/ lucid/main amd64 Packages 
1.0.0-rc.2-1 0 
500 https://packagecloud.io/chef/stable/ubuntu/ lucid/main amd64 Packages 
1.0.0-rc.1-1 0 
500 https://packagecloud.io/chef/stable/ubuntu/ lucid/main amd64 Packages 
1.0.0-1 0 
500 https://packagecloud.io/chef/stable/ubuntu/ lucid/main amd64 Packages
```

Note that apt wants to "upgrade" to the "rc" package.

**Comment by charlesjohnson** [comment]
Resolved by #778.
