### ISSUE TITLE
Cannot download data from remote server during upgrade

### ISSUE THREAD

**Issue by jonlives** [chef/chef-server#76]
Despite being able to pass --chef11-server-url to the `chef12-upgrade-download` subcommand, it looks like some parts of that script are still expecting the chef 11 server to be running on localhost.

The use case here is that while upgrading to Chef Server 12, I'd also like to migrate our chef server to newer hardware - essentially, download the data to the new server, then transform and upload to chef-server 12 locally.

Here's the error I get when running the command:

```
 $>time chef-server-ctl chef12-upgrade-download --download-only --chef11-data-dir /var/chef_11_data --chef11-server-url https://chef.mydomain.com --key /etc/chef-server/admin_old.pem 

Proceeding with options #<OpenStruct skip_setup=true, skip_download=false, skip_cleanup=true, chef11_server_url="https://chef.mydomain.com", chef11_admin_client_name="admin", chef11_admin_client_key="/etc/chef-server/admin_old.pem", chef11_data_dir="/var/chef_11_data">

Timeout waiting for Chef 11 server to start. Received exception Address family not supported by protocol - socket(2)

real    2m1.830s
user    0m1.287s
sys 0m0.161s
```

**Comment by stevendanna** [comment]
At least the following is blocking running the command against a remote Chef 11 server.

## wait_for_ready_server 

Hardcoded localhost here

```
  def wait_for_ready_server(server_version)
    max_count = 120
    1.upto(max_count) do |count|
      begin
        server_status = JSON.parse(open('http://localhost:8000/_status').read)
        fail unless server_status['status'] == 'pong'
      # If the server isn't up trying to open the status endpoint throws an error
      rescue StandardError => e
        sleep 1
        if count == max_count
          log "Timeout waiting for #{server_version} server to start. Received exception #{e.message}"
          exit 1
        end
      end
    end
  end
```

## pull_chef11_db_creds

Here we assume the chef11 config is local and can be read:

```
  def pull_chef11_db_credentials
    # This code pulled from knife-ec-backup and adapted
    log "Pulling open source Chef 11 database credentials"
    if !File.exists?("/etc/chef-server/chef-server-running.json")
      log "Failed to find /etc/chef-server/chef-server-running.json"
      exit 1
    end

    running_config = JSON.parse(File.read("/etc/chef-server/chef-server-running.json"))
    sql_host = running_config['chef_server']['postgresql']['vip']
    sql_port = running_config['chef_server']['postgresql']['port']
    sql_user = running_config['chef_server']['postgresql']['sql_user']
    sql_password = running_config['chef_server']['postgresql']['sql_password']
    [sql_host, sql_port, sql_user, sql_password]
  end
```

I think we should just skip wait_for_ready_server when skip_setup is true and provide flags for the sql connection information.  Theses were the only two problems I could find on my read through, but we should test this case specifically.

**Comment by mmzyk** [comment]
Yeah, there is an expectation in the code of localhost. It was a failure on my part that my hope and dreams for being able to hit remote servers was never fully implemented, but I also did not remove those options as I should have, which gives a bad user experience. The mea cupla is on me for this one.

However, there is the tried and true download it and rsync it over method, but this of course isn't as satisfying.

**Comment by jonlives** [comment]
I'd def rather see things head in the direction of implementing remote download rather than removing the options :p

**Comment by stevendanna** [comment]
Initial, untested PR: https://github.com/chef/opscode-omnibus/pull/683

**Comment by PrajaktaPurohit** [comment]
https://blog.chef.io/migrating-chef-server-knife-ec-backup-knife-tidy/ is this the recommended upgrade path. Closing this since it is no longer relevant.
