### ISSUE TITLE
chef-server-ctl commands hangs

### ISSUE THREAD

**Issue by melezhik** [chef/chef-server#773]
## Description

chef-server-ctl  install opscode-manage
chef-server-ctl opscode-manage-ctl reconfigure
chef-server-ctl reconfigure 

And so on

Whatever command I run using chef-server-ctl  , it hangs.

I mean all I see at my console is "Chef Client started" and nothing happens then, for dozens of minutes. A weird thing though that if run "ps aux | grep chef-client" I can see a chef client running and doing it's job. If then I press CTRL+C and stopping chef-server-ctl  script _then_ I start to get output from running chef client and finally have "Chef Client finished" at my console telling me that chef client get it's job done.

So whatever command I run using chef-server-ctl and those running chef-client under the hood I need to "alive" chef-server-ctl script hitting CTRL+C
## Chef Version

chef-server-core-12.2.0-1.el6.x86_64.rpm
## Platform Version

Red Hat Enterprise Linux Server release 6.7 (Santiago)
Kernel \r on an \m
## Replication Case

See description
## Client Output

See description
## PS

This issue is based on https://discourse.chef.io/t/chef-server-ctl-install-opscode-manage-takes-too-much-time/7946

**Comment by jjasghar** [comment]
What is the size of the machine? RAM CPU etc?

**Comment by melezhik** [comment]
```
bash-4.1$ free -m

total used free shared buffers cached
Mem: 7868 6332 1536 80 317 3264
-/+ buffers/cache: 2750 5117
Swap: 2047 0 2047

-bash-4.1$ cat /proc/cpuinfo | grep processor
processor : 0
processor : 1
processor : 2
processor : 3
processor : 4
processor : 5
processor : 6
processor : 7

```

And disk:

```
Size Used Avail Use% Mounted on

                   20G  5.6G   14G  30% /

                  976M  1.3M  924M   1% /admhome

                 488M   75M  389M  17% /boot

                  2.0G  7.7M  1.8G   1% /tmp

                  9.8G  1.5G  7.9G  16% /var

                   20G  2.7M   19G   1% /apps
```

**Comment by melezhik** [comment]
if it helps then:

```
-bash-4.1$ sudo sestatus
SELinux status: disabled


-bash-4.1$ sudo cat /etc/sysconfig/selinux
# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - SELinux is fully disabled.
SELINUX=disabled
# SELINUXTYPE= type of policy in use. Possible values are:
#       targeted - Only targeted network daemons are protected.
#       strict - Full SELinux protection.
SELINUXTYPE=targeted

```

**Comment by jjasghar** [comment]
Can you confirm for me that:
```
chef-server-ctl install opscode-manage
chef-server-ctl opscode-manage-ctl reconfigure
chef-server-ctl reconfigure
```

Are the correct commands, we deprecated the `opscode` for `chef` a few releases ago. What version of the Chef server are you running/trying to run?

**Comment by jjasghar** [comment]
Ah, missed this: `chef-server-core-12.2.0-1.el6.x86_64.rpm`

**Comment by melezhik** [comment]
yes , this is exactly rpm installed

**Comment by jjasghar** [comment]
I have seen issues with `chef-manage` installations.

https://discourse.chef.io/t/undefined-method-for-nil-nilclass-when-instaling-opscode-manage/7489

It's possible you're running into a version of this. Do you see any other symptoms like that link?

**Comment by melezhik** [comment]
more detailed info on rpms:

```
-bash-4.1$ yum list installed | grep chef
chef.x86_64                       11.16.4-1.el6             installed
chef-manage.x86_64                2.2.0-1.el6               @chef-stable
chef-server-core.x86_64           12.2.0-1.el6              @/chef-server-core-12.2.0-1.el6.x86_64
```

**Comment by melezhik** [comment]
> https://discourse.chef.io/t/undefined-method-for-nil-nilclass-when-instaling-opscode-manage/7489

This is not look like my issue. My situation is about things gets installed only after hitting CTRL+C. If I don't do this a _primary_ script hangs for ever ( chef-server-ctl for example )

**Comment by jjasghar** [comment]
Can you try uninstalling the `chef.x86_64 11.16` and run the commands again?

**Comment by melezhik** [comment]
I am afraid I can't it is production server and already in use ):

**Comment by jjasghar** [comment]
Could you take a snapshot of this machine and spin it up somewhere else?

**Comment by melezhik** [comment]
Sorry, I can't for privacy reasons. Sorry if I can't help you more with this. At least now crtl+c works for me, I just wanted to let opscode be informed

**Comment by jjasghar** [comment]
I think I'm going to report this to the QA team, I actually don't know if there is a test case with Chef 11 installed attempting to run Chef 12 on RHEL. Thanks for the report and usecase!

**Comment by melezhik** [comment]
Sure! HTH

**Comment by melezhik** [comment]
HI guys. A news from our side. It seem [centrify](https://www.centrify.com/express/linux-unix/download/) on linux playing bad things with running chef client ( not only it ? ), as we noticed that when AD client runs, and then we run a chef-client it hangs. Restarting AD client makes chef-client "unhangs" and shows us all it's output ...

**Comment by stevendanna** [comment]
I'm going to go ahead and close this one out.  We have an open issue for reducing the ohai plugins in use which might have avoided this, but it doesn't sound like there is anything actionable here we could have done other than that.  Thanks for investigating this and reporting it!
