### ISSUE TITLE
Bootstrapping a Chef server should not delete databases

### ISSUE THREAD

**Issue by glasschef** [chef/chef-server#79]
It's far too easy to delete the bootstrap sentinel file, and accidental wipes of production data happen entirely too often. It would be delightful if the cookbook detected existing data and refused to remove it, but instead required the user to manually delete the files with a warning and suggestion for backups.

**Comment by sdelano** [comment]
@glasschef - Can you provide a bit more detail here about the version of the Chef Server and what exactly it is that you're seeing? In older versions with CouchDB, the first part of executing the bootstrap was (unfortunately) a force-delete of the authorization database [here](https://github.com/chef/opscode-omnibus/blob/11.1-stable/files/private-chef-cookbooks/private-chef/templates/default/bootstrap-script.rb.erb#L1).

Is this related to Enterprise Chef 11, or does a similar bit occur during a Chef 12 bootstrap?

**Comment by marcparadise** [comment]
Confirmed in that Chef Server 12.6, a 'reconfigure' run will fail non-destructively if the sentinel file is deleted.
