### ISSUE TITLE
Rabbitmq var/ directory misconfigured during 12.4.1 install 

### ISSUE THREAD

**Issue by clintoncwolfe** [chef/chef-server#792]
After a chef-server 12.4.1 install on a clean ubuntu 14.04 via the chef-ingredient cookbook, rabbitmq failed to start.  Its runit log revealed:

```
2016-03-29_13:38:55.90528 mkdir: cannot create directory '/opt/opscode/embedded/service/rabbitmq/sbin/../var': Permission denied
```

I think it's just a missing symlink, so as a workaround, I did:

```
ln -s /var/opt/opscode/rabbitmq /opt/opscode/embedded/service/rabbitmq/var
```

rmq then started fine.

**Comment by pubyun** [comment]
same error in 12.5

**Comment by acholt** [comment]
Hi Guys

See this is still open. I got the same error in upgrading to chef-server-core-12.11.1-1 from chef-server-core-12.10.0-1.

**Comment by stevendanna** [comment]
RabbitMQ is no longer included in Chef Infra Server.
