### ISSUE TITLE
Deleting An Org Should Delete Any Pending Invites To The Org

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#81]
As a customer, I would like chef servers to cleanup associated objects upon deletion.

ZenDesk 2752 "User cannot accept org invites after delete of bogus organization"
The deleted organization had pending invites on it for users still in existence.

https://github.com/chef/support-docs/blob/master/tools/cleanup_orphaned_invites.rb

Ran the following script on the primary backend in orgmapper

```
orgmapper:0 > load 'cleanup_orphaned_invites.rb' 
Deleted association request for user 65a260d4339a11e4ac790050560038cd 
Deleted association request for user 780cd6e6cf6d11e3988e0050560038cd 
Deleted association request for user 780cd6e6cf6d11e3988e0050560038cd 
Deleted association request for user 780cd6e6cf6d11e3988e0050560038cd 
Deleted association request for user 780cd6e6cf6d11e3988e0050560038cd 
Deleted association request for user dad07a8e33af11e4ac790050560038cd 
orgmapper:0 >
```

After the deletions, the users were once again able to accept invites.

**Comment by sdelano** [comment]
@sean-horn this is fixed in Chef 12. Seeing `orgmapper` here makes me think this applies to Enterprise Chef 11 only, is that correct?

**Comment by sean-horn** [comment]
@sdelano Yes, this ticket applies to Enterprise Chef

**Comment by PrajaktaPurohit** [comment]
Closing since this has been fixed is Chef Infra Server 12.
