### ISSUE TITLE
Readline module missing in embedded Ruby in chef server 12.5.0

### ISSUE THREAD

**Issue by andrenaumann** [chef/chef-server#810]
After upgrading the open source chef server from version 12.2.0-1 to 12.5.0-1 on a Ubuntu 14.04 machine, the embedded Ruby was missing the readline module, disabling knife commands like "ssh" or "bootstrap".

This is on one of our older chef servers:

root@host:~# dpkg -l|grep chef-server-core
ii chef-server-core 12.2.0-1 amd64 The full stack of chef-server
root@~# grep readline.so /var/lib/dpkg/info/chef-server-core.list
/opt/opscode/embedded/lib/ruby/2.1.0/x86_64-linux/readline.so

On the updated server, readline.so is missing:
root@chef:~# dpkg -l|grep chef-server-core
ii chef-server-core 12.5.0-1 amd64 The full stack of chef-server
root@chef:~# grep readline.so /var/lib/dpkg/info/chef-server-core.list
root@chef:~#

When trying to run a knife ssh or knife bootstrap command, we get an exception complaining about the missing readline module:
require': cannot load such file -- readline (LoadError)

After I copied the readline.so library from the 12.2.0 server to the 12.5.0 server, everything is working again(luckily, the Ruby binaries are similar enough).

**Comment by stevendanna** [comment]
The upstream omnibus-software ruby definition stopped building with readline with the intent to moving to rb-readline everywhere.  I opened a PR to include rb-readline here: https://github.com/chef/chef-server/pull/809

However, it ran into some failures in our build environment that I haven't worked through yet.

**Comment by andrenaumann** [comment]
Good to see someone taking care of it..

It was just bad to see it after a server upgrade :D

**Comment by stevendanna** [comment]
https://github.com/chef/chef-server/pull/809 has been merged so readline should be available again in the next release.

**Comment by stevendanna** [comment]
This has been fixed for a few releases now.  Thanks for reporting it.
