### ISSUE TITLE
Omnibus builds requires nodejs from host

### ISSUE THREAD

**Issue by elthariel** [chef/chef-server#813]
Hi,

I'm building the chef-server omnibus on an arm7l box (yes it's quite long) and I stumbled across this small problem:

oc_id failed because of an ExecJS error. Since I've seen this error on the past, I've routinely installed nodejs on my build machine to see if it fixed the issue... It did.

It seems quite weird as the omnibus built nodejs is in the PATH.

Here's my host node js on an Ubuntu 14

```
$> nodejs --version
v0.10.25
$> which nodejs
/usr/bin/nodejs
```

**Comment by stevendanna** [comment]
@elthariel Based on your other PR, I'm guessing you were able to work past this?  If not, let me know and I can take a look. Apologies no one responded to this sooner.

**Comment by elthariel** [comment]
I think I just installed nodejs on my box. tbh, i totally forgot about this problem.
It might still be there :-/

**Comment by stevendanna** [comment]
I'm going to close this for now.  I haven't hit this problem in my few recreation attempts and it appears to be working well in the test-kitchen omnibus build environment which doesn't include nodejs by default.
