### ISSUE TITLE
Upgrade from Chef 12.0.1 to 12.0.2 errors on upgrade

### ISSUE THREAD

**Issue by Tech356** [chef/chef-server#82]
When trying to run the `sudo chef-server-ctl upgrade` I get the following error. 

    usermod: user opscode-pgsql is currently used by process ####

It happens even if I kill the process before starting the upgrade.

    [user@server ~]$ sudo chef-server-ctl upgrade
    ok: down: bookshelf: 119s
    ok: down: chef-expander: 118s
    ok: down: chef-server-webui: 118s
    ok: down: chef-solr: 114s
    ok: down: erchef: 114s
    ok: down: nginx: 114s
    ok: down: postgresql: 77s
    ok: down: rabbitmq: 112s, normally up
    Starting Chef Client, version 11.12.2
    Compiling Cookbooks...
    Converging 8 resources
    Recipe: chef-server::pre_11.1_upgrade_setup
      * execute[pkill -9 -f epmd] action run
        - execute pkill -9 -f epmd

      * execute[/opt/chef-server/bin/chef-server-ctl start postgresql] action run
        - execute /opt/chef-server/bin/chef-server-ctl start postgresql

      * ruby_block[check-for-sqitch] action run (skipped due to only_if)
      * execute[apply-widen-cookbook-version] action nothing (skipped due to action :nothing)
      * execute[sqitchfy_database] action nothing (skipped due to action :nothing)
      * execute[migrate_database] action nothing (skipped due to action :nothing)
      * execute[/opt/chef-server/bin/chef-server-ctl stop postgresql] action run
        - execute /opt/chef-server/bin/chef-server-ctl stop postgresql

      * ruby_block[sleep 5] action run
        - execute the ruby block sleep 5

    Running handlers:
    Running handlers complete

    Chef Client finished, 4/4 resources updated in 9.822390922 seconds
    [2015-02-04T17:13:51-05:00] WARN:
    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    SSL validation of HTTPS requests is disabled. HTTPS connections are still
    encrypted, but chef is not able to detect forged replies or man in the middle
    attacks.

    To fix this issue add an entry like this to your configuration file:

    ```
      # Verify all HTTPS connections (recommended)
      ssl_verify_mode :verify_peer

      # OR, Verify only connections to chef-server
      verify_api_cert true
    ```

    To check your SSL configuration, or troubleshoot errors, you can use the
    `knife ssl check` command like so:

    ```
      knife ssl check -c /opt/chef-server/embedded/cookbooks/solo.rb
    ```

    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

    Starting Chef Client, version 11.12.2
    Compiling Cookbooks...
    Recipe: chef-server::default
      * directory[/etc/chef-server] action create (up to date)
    [2015-02-04T17:13:56-05:00] WARN: Cloning resource attributes for directory[/var/opt/chef-server/chef-server-webui/etc] from prior resource (CHEF-3694)
    [2015-02-04T17:13:56-05:00] WARN: Previous directory[/var/opt/chef-server/chef-server-webui/etc]: /opt/chef-server/embedded/cookbooks/chef-server/recipes/chef-server-webui.rb:31:in `block in from_file'
    [2015-02-04T17:13:56-05:00] WARN: Current  directory[/var/opt/chef-server/chef-server-webui/etc]: /opt/chef-server/embedded/cookbooks/chef-server/definitions/unicorn_config.rb:21:in `block in from_file'
    Converging 197 resources
      * directory[/etc/chef-server] action nothing (skipped due to action :nothing)
    Recipe: chef-server::users
      * user[chef_server] action create (up to date)
      * group[chef_server] action create (up to date)
    Recipe: chef-server::default
      * directory[/etc/chef] action create (up to date)
      * directory[/var/opt/chef-server] action create (up to date)
    Recipe: runit::upstart
      * execute[initctl stop opscode-runsvdir] action run (skipped due to only_if)
      * file[/etc/init/opscode-runsvdir.conf] action delete (up to date)
      * cookbook_file[/etc/init/chef-server-runsvdir.conf] action create (up to date)
      * execute[initctl status chef-server-runsvdir] action run
        - execute initctl status chef-server-runsvdir

      * execute[initctl start chef-server-runsvdir] action run (skipped due to only_if)
    Recipe: chef-server::sysctl-updates
      * execute[sysctl-reload] action nothing (skipped due to action :nothing)
      * bash[dual ip4/ip6 portbind] action run (skipped due to only_if)
    Recipe: chef-server::rabbitmq
      * directory[/var/opt/chef-server/rabbitmq] action create (up to date)
      * directory[/var/opt/chef-server/rabbitmq/etc] action create (up to date)
      * directory[/var/opt/chef-server/rabbitmq/db] action create (up to date)
      * directory[/var/log/chef-server/rabbitmq] action create (up to date)
      * link[/var/opt/chef-server/rabbitmq/db] action create (skipped due to not_if)
      * link[/opt/chef-server/embedded/bin/rabbitmqctl] action create (up to date)
      * link[/opt/chef-server/embedded/bin/rabbitmq-env] action create (up to date)
      * link[/opt/chef-server/embedded/bin/rabbitmq-multi] action create (up to date)
      * link[/opt/chef-server/embedded/bin/rabbitmq-server] action create (up to date)
      * template[/opt/chef-server/embedded/service/rabbitmq/sbin/rabbitmq-env] action create (up to date)
      * template[/var/opt/chef-server/rabbitmq/etc/rabbitmq.conf] action create (up to date)
      * directory[/opt/chef-server/sv/rabbitmq] action create (up to date)
      * directory[/opt/chef-server/sv/rabbitmq/log] action create (up to date)
      * directory[/opt/chef-server/sv/rabbitmq/log/main] action create (up to date)
      * template[/opt/chef-server/sv/rabbitmq/run] action create (up to date)
      * template[/opt/chef-server/sv/rabbitmq/log/run] action create (up to date)
      * file[/opt/chef-server/sv/rabbitmq/down] action delete (up to date)
      * link[/opt/chef-server/init/rabbitmq] action create (up to date)
      * link[/opt/chef-server/service/rabbitmq] action create (up to date)
      * ruby_block[supervise_rabbitmq_sleep] action run (skipped due to not_if)
      * service[rabbitmq] action nothing (skipped due to action :nothing)
    Recipe: chef-server::postgresql
      * user[opscode-pgsql] action create
    ================================================================================
    Error executing action `create` on resource 'user[opscode-pgsql]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '8'
    ---- Begin output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
    STDOUT:
    STDERR: usermod: user opscode-pgsql is currently used by process 1750
    ---- End output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
    Ran ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] returned 8

    Resource Declaration:
    ---------------------
    # In /opt/chef-server/embedded/cookbooks/chef-server/recipes/postgresql.rb

     24: user node['chef_server']['postgresql']['username'] do
     25:   system true
     26:   shell node['chef_server']['postgresql']['shell']
     27:   home node['chef_server']['postgresql']['home']
     28: end
     29:

    Compiled Resource:
    ------------------
    # Declared in /opt/chef-server/embedded/cookbooks/chef-server/recipes/postgresql.rb:24:in `from_file'

    user("opscode-pgsql") do
      action :create
      supports {:manage_home=>false, :non_unique=>false}
      retries 0
      retry_delay 2
      guard_interpreter :default
      username "opscode-pgsql"
      home "/var/opt/chef-server/postgresql"
      shell "/bin/sh"
      system true
      cookbook_name :"chef-server"
      recipe_name "postgresql"
    end

    Running handlers:
    [2015-02-04T17:13:57-05:00] ERROR: Running exception handlers
    Running handlers complete

    [2015-02-04T17:13:57-05:00] ERROR: Exception handlers complete
    [2015-02-04T17:13:57-05:00] FATAL: Stacktrace dumped to /opt/chef-server/embedded/cookbooks/cache/chef-stacktrace.out
    Chef Client failed. 1 resources updated in 5.779168325 seconds
    [2015-02-04T17:13:57-05:00] ERROR: user[opscode-pgsql] (chef-server::postgresql line 24) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '8'
    ---- Begin output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
    STDOUT:
    STDERR: usermod: user opscode-pgsql is currently used by process 1750
    ---- End output of ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] ----
    Ran ["usermod", "-d", "/var/opt/chef-server/postgresql", "opscode-pgsql"] returned 8
    [2015-02-04T17:13:57-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by stevendanna** [comment]
@Tech356 Was this Chef Server upgraded from Chef 11 in the past?  The recipes you are running seem to be from Chef 11.

**Comment by Tech356** [comment]
@stevendanna yes. It was upgraded from Chef 11.

**Comment by stevendanna** [comment]
@Tech356 What does your PATH look like on that machine? Also what is the output of:

   ls -al $(which chef-server-ctl)
   file $(whcih chef-server-ctl)

I think the issue is that somehow the reconfigure command that you are running is actually the Chef 11 reconfigure command.

**Comment by Tech356** [comment]
I rebuilt the server so I don't have that information anymore. I'll close this since there isn't anything more to do.
