### ISSUE TITLE
push jobs won't install on vanilla chef server

### ISSUE THREAD

**Issue by nathan-lochala** [chef/chef-server#842]
## Description

As I'm setting up a brand-new instance of chef server, hosted locally, and I can install all add-ons except for push jobs.
## Chef Version

chef-server-core_12.6.0-1
## Platform Version

Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-86-generic x86_64) 
## Replication Case

Followed the instructions found on https://docs.chef.io/release/server_12-6/install_server.html#standalone. 

I can successfully install the chef server and chef manage. However, when I attempt to install push jobs I get an error.

Specifically:
`chef-server-ctl install opscode-push-jobs-server` -- Successfully runs. 
`chef-server-ctl reconfigure` -- Successfully runs.
`opscode-push-jobs-server-ctl reconfigure` -- Fails.
It fails on the line:
`execute[/opt/opscode/embedded/bin/createdb -T template0 -E UTF-8 opscode_pushy] action run`
## Client Output

Client output: https://gist.github.com/nathan-lochala/eb71ac053025316b8bf0d6f5db38e3af
## Stacktrace

stack trace: https://gist.github.com/nathan-lochala/1aefdd047c628dca0ed12a218491228f

**Comment by stevendanna** [comment]
@nathan-lochala Apologies no one responded to this.  Is this still an issue for you?
