### ISSUE TITLE
Embedded Logrotate Not Rotating Nginx Access Logfiles

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#843]
**Problem**

The issue is that the logrotate embedded with Chef Server doesn't properly postrotate, so it never calls the `nginx -s reopen` command to release the files after doing the rotation.

```
[root@delivery-GE-chef-server /]#  /opt/opscode/embedded/sbin/logrotate --version
logrotate 3.8.5

[root@delivery-GE-chef-server /]# /usr/sbin/logrotate -v
logrotate 3.7.8 - Copyright (C) 1995-2001 Red Hat, Inc.
The system logrotate package on RHEL/CentOS does postrotate properly.
```

**Solution**

You can workaround this issue by commenting out or removing the PATH in the file /etc/cron.hourly/opc_logrotate . In this way, the embedded logrotate command is not used.

I ran a few test forced logrotates on my own 12.6.0 system with the system logrotate, and it's definitely working.

```
[root@delivery-GE-chef-server /]# ls -al /var/log/opscode/nginx/
total 456

-rw-r--r-- 1 opscode opscode   1350 May 26 16:04 access.log
-rw-r--r-- 1 opscode opscode  22950 May 26 16:04 access.log.1
-rw-r--r-- 1 opscode opscode 355913 May 26 16:04 access.log.2.gz

[root@delivery-GE-chef-server /]# ls -al /var/log/opscode/nginx/
total 440

-rw-r--r-- 1 opscode opscode      0 May 26 16:05 access.log
-rw-r--r-- 1 opscode opscode   9000 May 26 16:05 access.log.1
-rw-r--r-- 1 opscode opscode   1011 May 26 16:05 access.log.2.gz
-rw-r--r-- 1 opscode opscode 355913 May 26 16:04 access.log.3.gz
```

**Comment by stevendanna** [comment]
I believe this is fixed in Chef 12.10.0 (perhaps 12.9 as well, but I just checked 12.10)
