### ISSUE TITLE
[chef-server-ctl] Incorrect error messages with `user-create`

### ISSUE THREAD

**Issue by dmccown** [chef/chef-server#844]
Given you have a user created already with the following ctl command:
```
$ chef-server-ctl user-create testuser-1234 Test User test@example.com password
$ chef-server-ctl user-list
pivotal
testuser-1234
```
If you try to create a second user with the following command:
```
$ chef-server-ctl user-create testuser-4567 Test User test@example.com password
ERROR: Conflict
Response: User 'testuser-4567' already exists
```

Through trial and error I figured out the email address was causing the conflict. Could we improve the error message to make it clear what field has the conflict? Maybe show 'email address already in use'?

Version detected in: chef-server-core-12.6.0-1.el6.x86_64

**Comment by tylercloke** [comment]
What does the API return? Does it return the conflicting field? Otherwise, this will be pretty difficult without some API work.

**Comment by stevendanna** [comment]
Going to close this as a dup of: https://github.com/chef/chef-server/issues/59

**Comment by github0100** [comment]
you may created the org-username my mistake, but every problem  has some solution.

sudo -s
chef-server-ctl org-delete learndevops   

learndevops is my org-name you may have different org
