### ISSUE TITLE
chef repo should be configured as skippable

### ISSUE THREAD

**Issue by vinyar** [chef/chef-server#849]
Currently AWS marketplace images are not able to update because they still point to packagecloud.

bug:
The issue is that packagecloud repo was not configured as skippable by default.

expected behavior:
`yum install wget` should not fail due to configurations made by chef. Repositories added by chef should be configured as skippable by default.

yum-config-manager --save --setopt=chef-stable.skip_if_unavailable=true

**Comment by vinyar** [comment]
maybe this is better suited for chef-ingredient or mixlib-install 😕

**Comment by stevendanna** [comment]
In 12.10 we no longer install repositories as part of `chef-server-ctl install`, going to close this one out.
