### ISSUE TITLE
Chef server's API auth failed then updated 12.0.2 to 12.0.3

### ISSUE THREAD

**Issue by urasoko** [chef/chef-server#85]
Ohai, 
I updated chef server 12.0.2 to 12.0.3, then API auth by "pivotal.pem" is failed.

On 12.0.2
```
[root@db01 tmp]# chef-server-ctl user-list 
the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM 
falling back to ffi which might work (or might not, no promises) 
d-user 
dd-user 
h-arai 
h-arai-test 
h-urasoko 
pivotal
```

On 12.0.3 
```
[root@db02 ~]# chef-server-ctl user-list 
ERROR: Failed to authenticate to https://127.0.0.1:443 as pivotal with key /etc/opscode/pivotal.pem 
Response: An error occurred while trying to find 'pivotal'. Please contact support.
```

Sincerely.

**Comment by stevendanna** [comment]
@urasoko Thanks.  Can you briefly describe the steps you took to upgrade this cluster?  For instance, did you run chef-server-ctl upgrade after installing the 12.0.3 package?

**Comment by urasoko** [comment]
@stevendanna Thanks for your quick reply.
 And I didn't run chef-server-ctl upgrade then, only run chef-server-ctl reconfigure.

Now I tried again  install 12.0.3 to a machine that be installed 12.0.2, and run chef-server-ctl upgrade.
The error is changed, but not fixed.
```
[root@db01 tmp]# chef-server-ctl user-list
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 1/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 2/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 3/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 4/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 5/5
ERROR: Network Error: Connection refused - Connection refused connecting to https://127.0.0.1/users, giving up
Check your knife configuration and network settings
```
Regards.

**Comment by stevendanna** [comment]
@urasoko Please run `chef-server-ctl status` and ensure that all of the services are started.  If any are listed as `down` try running a `chef-server-ctl start`.

**Comment by urasoko** [comment]
@stevendanna Oh, very sorry... you are right, and error has just fixed.
Thank you for your help and sorry about my operation's lack.
Cheers.

**Comment by pradeepaasuri** [comment]
I tried all the steps mention below, but unable to create user admin.

**Comment by pradeepaasuri** [comment]
I have started all the services which were down
[root@chefserver ~]# chef-server-ctl start
ok: run: bookshelf: (pid 14391) 0s
ok: run: nginx: (pid 14428) 0s
ok: run: oc_bifrost: (pid 14430) 1s
ok: run: oc_id: (pid 14459) 0s
ok: run: opscode-chef-mover: (pid 14461) 0s
ok: run: opscode-erchef: (pid 14463) 0s
ok: run: opscode-expander: (pid 14466) 0s
ok: run: opscode-expander-reindexer: (pid 14491) 0s
ok: run: opscode-solr4: (pid 14494) 1s
ok: run: postgresql: (pid 14354) 44s
ok: run: rabbitmq: (pid 14503) 0s
ok: run: redis_lb: (pid 14505) 0s
[root@chefserver ~]# chef-server-ctl status
run: bookshelf: (pid 14391) 39s; run: log: (pid 7413) 4344s
run: nginx: (pid 14850) 1s; run: log: (pid 7595) 4324s
run: oc_bifrost: (pid 14430) 32s; run: log: (pid 7156) 4360s
run: oc_id: (pid 14459) 31s; run: log: (pid 7200) 4355s
run: opscode-erchef: (pid 14463) 31s; run: log: (pid 7452) 4343s
run: opscode-expander: (pid 14466) 31s; run: log: (pid 7361) 4346s
run: opscode-expander-reindexer: (pid 14491) 31s; run: log: (pid 7367) 4345s
run: opscode-solr4: (pid 14494) 31s; run: log: (pid 7255) 4350s
run: postgresql: (pid 14354) 74s; run: log: (pid 7089) 4361s
run: rabbitmq: (pid 14503) 30s; run: log: (pid 7074) 4362s
run: redis_lb: (pid 14505) 30s; run: log: (pid 7562) 4338s

**Comment by pradeepaasuri** [comment]
But still showing the same error 

chef-server-ctl user-list
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 1/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 2/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 3/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 4/5
ERROR: Connection refused connecting to https://127.0.0.1/users, retry 5/5
ERROR: Network Error: Connection refused - Connection refused connecting to https://127.0.0.1/users, giving up
Check your knife configuration and network settings

**Comment by nozino** [comment]
$chef-server-ctl tail nginx
2015-07-03_07:38:21.24862 nginx: [emerg] server name "*" is invalid in /var/opt/opscode/nginx/etc/chef_https_lb.conf:3
2015-07-03_07:38:22.27220 nginx: [emerg] server name "*" is invalid in /var/opt/opscode/nginx/etc/chef_https_lb.conf:3
2015-07-03_07:38:23.30000 nginx: [emerg] server name "*" is invalid in /var/opt/opscode/nginx/etc/chef_https_lb.conf:3
....

if the server does not use public IP or DNS, check /etc/hosts.
add "IP HOSTNAME" onto that file. and restart nginx

chef-server-ctl restart nginx
