### ISSUE TITLE
Chef-server Nginx does not implement HSTS

### ISSUE THREAD

**Issue by mmailhos** [chef/chef-server#857]
Chef HTTPS server is not enforcing HTTP Strict Transport Security (HSTS).
It represents an unnecessary risk to the overall security posture.

Concretely, there is no _['nginx']['sts_max_age']_ variable to set the “Strict-Transport-Security” header
( _add_header Strict-Transport-Security "max-age=" XXX_ ) for nginx on /etc/opscode/chef-server.rb

References
HSTS on Wikipedia: https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
HSTS for Nginx: https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/
Nginx cookbook mentions it: https://supermarket.chef.io/cookbooks/nginx

**Comment by MathieuMailhos** [comment]
Work around:
Add the header in nginx addons:  
```
cat /opt/var/opscode/nginx/etc/addon.d/10_external.conf
add_header Strict-Transport-Security "max-age=31536000" always;
```

Restart Nginx:
_/opt/opscode/embedded/bin/sv restart nginx_

Verify that you get HSTS: 
`curl  https://127.0.0.1 -k -v | grep Strict`
