### ISSUE TITLE
Chef 12: Tiered Install backend_vip Association

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#86]
As a customer, I expect a tier topology install to associate a `backend_vip` address with the correct interface on the backend host just as in an HA topology, keepalived handles this task.

**Comment by stevendanna** [comment]
@sean-horn Do you have any more context for this one?  In the HA topology, managing that IP is required.  However, in the tier topology it is completely possible that the user has something else managing that IP address.

**Comment by ryancragun** [comment]
I agree with @stevendanna on this one.  The VIP should never change in the Tiered install so I don't think it's the job of the Chef Server to manage it.

**Comment by stevendanna** [comment]
@sean-horn Thanks for taking the time to report this and the other issues you've been filing.  I'm going to close this as we think it is outside of what our application should manage in the tiered context.  It may be a good addition, however, to something like a preflight or system-readiness check.

**Comment by sean-horn** [comment]
It's confusing that we have to hand associate a floating IP in Tier and not in HA.
Should we change the docs to say "Don't use a floating IP and just set the backend_vip to whatever the backend has now"?

**Comment by stevendanna** [comment]
@sean-horn Thanks for the follow up. I reviewed our tiered installation instructions (https://docs.chef.io/install_server_tiered.html) and agree we likely need some improvements.

Quoting from the docs:

> " A virtual IP address is created and managed by the Chef server, but will also need to be added to the DNS so that all machines in the tiered configuration may access it."

This is incorrect.  We should remove "is created and managed by the Chef server" and replace it with a clear statement about the requirements of the IP address used as the backend VIP:

- The backend is reachable at that IP address by the frontends
- All required ports can be accessed using that IP address by the frontends

By quick inspection, I don't actually think it is a requirement that you can even bind() to that address on the backend, but I'm not willing to bet the farm on that so it might require some follow up research and thought.

> Load-balancing should be used with frontend machines, along with a DNS entry for the virtual IP address used for load balancing. This virtual IP address is added to the chef-server.rb file as the api_fqdn.

The api_fqdn does not need to be a virtual IP address.  It could be one of many things:

- the IP address of a load balancer
- the FQDN of a load balancer
- a round-robin DNS entry

The requirement is that a chef-client will be able to reliably make HTTPS requests to that FQDN or IP and that a Chef Server will be listening on the other side.

**Comment by pburkholder** [comment]
Doesn't the manage UI need session, so round-robin DNS would not necessary work, and LBs need to be sticky?
