### ISSUE TITLE
[knife upload] ERROR: Server returned error 500 for sandboxes

### ISSUE THREAD

**Issue by ThatsNinja** [chef/chef-server#864]
**Chef Server Version**
12.6.0

**Chef Client Version**

``` bash
$ knife --version
Chef: 12.5.1
```

**Environment**
Ubuntu 14.04

**What I'm Trying to Do**
Successfully execute `knife upload` on the results of a `knife download` from another server.

**Steps to Reproduce**
1.) Take a dump of a server using knife:

``` bash
$ knife download --chef-repo-path ./ --repo-mode hosted_everything
```

2.) Upload the resulting dump to a newly created, empty Chef Server:

``` bash
$ knife upload . --chef-repo-path ./ --repo-mode hosted_everything --concurrency 1
```

**Expected Results**
I'd been given to expect that the downloaded cookbooks, roles, acls, environments, data_bags, et cetera would be created in the new, empty server.

**Actual Results**
Things begin uploading, and creating successfully. Then, the process begins to ERR-out with these messages:

``` bash
ERROR: Server returned error 500 for https://chef.example.com/organizations/my-org/sandboxes, retrying 1/5 in 3s
```

The above repeats five times, and then the process finally dies.

Meanwhile, this is what's passing on the server-side:

``` bash
2016-06-17_00:03:23.82442 [error] {<<"method=POST; path=/organizations/my-org/sandboxes; status=500; ">>,{error,{error,badarg,[{erlang,tl,[{invalid_s3_url,[]}],[]},{inets_regexp,first_match,3,[{file,"inets_regexp.erl"},{line,80}]},{inets_regexp,first_match,2,[{file,"inets_regexp.erl"},{line,68}]},{http_uri,split_uri,5,[{file,"http_uri.erl"},{line,181}]},{http_uri,parse_scheme,2,[{file,"http_uri.erl"},{line,136}]},{http_uri,parse,2,[{file,"http_uri.erl"},{line,88}]},{mini_s3,format_s3_uri,2,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/mini_s3/src/mini_s3.erl"},{line,444}]},{mini_s3,s3_url,6,[{file,"/var/cache/omnibus/src/oc_erchef/_build/default/lib/mini_s3/src/mini_s3.erl"},{line,491}]}]}}}
```

I note that it's complaining about an `invalid_s3_url`. Not certain if this is the root of the issue, but I `cat`'d my repo, and can't see what cause it would have to complain.

Any advice or other assistance would be greatly appreciated.

**Comment by ThatsNinja** [comment]
The issue turns out to be with bookshelf, and the Chef Server having an incorrect listen address. The address being provided as the public URL was `localhost` in my tests, and it needed to be `https://localhost`.

**Comment by marcparadise** [comment]
Closing as it seems this was a setup/config change, please re-open if I'm misunderstanding.

**Comment by stevendanna** [comment]
Per @marcparadise's message I'm gonna close this, but please feel free to reopen if you are still having an issue.

**Comment by ThatsNinja** [comment]
Thanks @marcparadise, @stevendanna. Sorry if it wasn't clear, but the issue was in my configuration.

I was hitting the server at `localhost`, which was trying to use a non-existent, non-secure listener. It might be cool for other idiots like me if this could bubble up an intelligible error message to the client, but this issue is closed in terms of my immediate problem.

**Comment by robertkaucher** [comment]
@ThatsNinja any way you could explain how you modified your config... I too appear to be an idiot.

**Comment by ThatsNinja** [comment]
@robertkaucher Sorry for the slow response. Trying to recall at this point, but by re-reading I'm reminded that when I was providing the address for the Chef server I needed to be furnishing the `https://` in front, rather than just `localhost` as I was.

Hope this helps, and wish I could be more informative, but I had to clear space in my brain for a ton of non-Chef stuff this last year 😄

**Comment by daytonpa** [comment]
I just recently ran into this and (with some help from the lovely folks at Fast Robot) resolved it for myself.  My Chef Server is a Standalone in AWS, and the problem came down to my `/etc/hosts` file. What I did was:
- Get your public IP
  - `curl icanhazip.com`
- Add the public IP and DNS to the `/etc/hosts` file
  - My file looks like this below:
```
127.0.0.1 localhost
<your_instance_public_ip>  chef-server.company.com

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
```
- Run `sudo chef-server-ctl reconfigure`

After that, I was able to push my cookbooks.  I hope this helps.
