### ISSUE TITLE
Chef-Server error creating user

### ISSUE THREAD

**Issue by JonasTavares** [chef/chef-server#879]
Hey,

I've installed chef-server 12.7 on a machine running on CentOS 7.
Everything goes as expected until I try to create a user:

chef-server-ctl user-create foo foo1 foo2 foo@gmail.com 12345--filename /root/.chef
ERROR: The object you are looking for could not be found
Response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>

<h1>Not Found</h1>

<p>The requested URL /users/ was not found on this server.</p>

</body></html>

I've installed Chef Server on a Vagrant VM before with no problems

Any clues?

**Comment by zosocanuck** [comment]
I am also able to duplicate this.

**Comment by stevendanna** [comment]
Can you try the same command that is failing but with the addition of `-VV` for debug logging?  Also, can you include the output of `chef-server-ctl status`.

**Comment by stevendanna** [comment]
Apologies you hit this issue.  As we haven't gotten more information about this and haven't seen this ourselves, I'm going to close this for now.  If you can still reproduce it and can provide more information we can reopen it at any time.  Thanks for taking the time to file an issue!
