### ISSUE TITLE
Disable org creation for users

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#88]
As a customer, having the ability to cleanly create a user that has standard admin privs in an org but cannot create orgs would help out when doing org automations.
This would avoid clashes with users autonomously creating orgs around automated creations.

Brought over from https://github.com/opscode-cookbooks/chef-server/issues/60

ZenDesk 1033

**Comment by marcparadise** [comment]
This can partially be done via redis flags today, which can disable all org creation. If automated creation were to clear the flag, make the org, and set it again it would be a workaround. I agree though, a more direct means of control would be best.

**Comment by sdelano** [comment]
I'm not following along with this ticket. Currently the only user that can create orgs outside of the Manage Console is `pivotal`. Every user created by the Manage Console or `chef-server-ctl user-create` does not have permissions to create an organization. Can you expand a bit upon the desired behavior?

**Comment by charlesjohnson** [comment]
@stevendanna suggests that this can be addressed most easily by disabling org-creation for users in the Manage console. This would still leave the ability for users to create organizations if they have access to the console via chef-server-ctl, but I think that's probably fine.

**Comment by jeremiahsnapp** [comment]
During a conversation today @marcparadise indicated that the redis way of disabling org creation no longer works and at least the following code needs to fixed to get it working again.

https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-cookbooks/private-chef/templates/default/nginx/scripts/route_checks.lua.erb#L59-L66

**Comment by jeremiahsnapp** [comment]
I opened the following issue to track disabling org creation within the Manage interface.

https://github.com/chef/chef-manage-issues/issues/64

**Comment by sean-horn** [comment]
Closed in favor of https://github.com/chef/chef-manage-issues/issues/64
