### ISSUE TITLE
(Gem::ConflictError) on running chef-server-ctl reconfigure

### ISSUE THREAD

**Issue by vaibhavaingankar09** [chef/chef-server#880]
[2016-07-14T11:56:05+00:00] WARN: Please install an English UTF-8 locale for Chef to use, falling back to C locale and disabling UTF-8 support.
/opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate rspec-3.5.0, because rspec-core-3.4.4 conflicts with rspec-core (~> 3.5.0), rspec-expectations-3.4.0 conflicts with rspec-expectations (~> 3.5.0), rspec-mocks-3.4.1 conflicts with rspec-mocks (~> 3.5.0) (Gem::ConflictError)
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1280:in`activate'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems.rb:216:in `block in finish_resolve'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems.rb:215:in`each'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems.rb:215:in `finish_resolve'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/rdoc.rb:14:in`<top (required)>'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in`require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/uninstaller.rb:10:in `<top (required)>'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in`require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.13.1/lib/chef/provider/package/rubygems.rb:37:in`<top (required)>'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.13.1/lib/chef/providers.rb:79:in `<top (required)>'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in`require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.13.1/lib/chef.rb:25:in`<top (required)>'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in`rescue in require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /opt/opscode/embedded/service/omnibus-ctl/open_source_chef12_upgrade.rb:7:in`<top (required)>'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /opt/opscode/embedded/service/omnibus-ctl/chef12_upgrade_upload.rb:7:in `load_file'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:187:in`eval'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:187:in `load_file'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:182:in`block in load_files'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:181:in `each'
        from /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:181:in`load_files'
        from /opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl:235:in `<main>'

**Comment by marcparadise** [comment]
Hi @vaibhi9 - have you installed any gems into the embedded ruby that ships with Chef Server? THat's the usual cause for this type of error.

**Comment by PrajaktaPurohit** [comment]
@vaibhavaingankar09 Please feel free to reopen this issue if you are still seeing it after trying out @marcparadise's suggestion. Thank you!
