### ISSUE TITLE
chef-server-ctl reconfigure with HA back-end

### ISSUE THREAD

**Issue by zimmma00** [chef/chef-server#890]
I am trying to install the second front end server on the new HA infrastructure.

My environment:
frontend (2 servers rhel 6.6 (also get the same thing on rhel 6.7))
backends (3 servers with chef-backend-1.0.9-1.el6.x86_64 installed.  rhel 6.7)

Here are my steps:
rpm -Uvh chef-server-core-12.8.0-1.el6.x86_64.rpm
cp -p chef-server.rb.infdev0207 /etc/opscode/chef-server.rb (this file was generated from the first backend server)
scp -p root@infdev0204:/etc/opscode/private-chef-secrets.json /etc/opscode/
scp -p root@infdev0204:/etc/opscode/webui_priv.pem /etc/opscode/
scp -p root@infdev0204:/etc/opscode/webui_pub.pem /etc/opscode/
scp -p root@infdev0204:/etc/opscode/pivotal.pem /etc/opscode/
(infdev0204 is my first front end server)
mkdir -p /var/opt/opscode/upgrades
scp -p root@infdev0204:/var/opt/opscode/upgrades/migration-level /var/opt/opscode/upgrades/
touch /var/opt/opscode/bootstrapped
chef-server-ctl reconfigure

At this point the reconfiguration fails. 

Here is the output:
[root@INFDEV0207 ~]# chef-server-ctl reconfigure
Starting Chef Client, version 12.12.19
resolving cookbooks for run list: ["private-chef::default"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - enterprise (0.10.1)
  - apt (2.9.2)
  - yum (3.11.0)
  - openssl (4.4.0)
  - runit (1.6.0)
  - chef-sugar (3.3.0)
  - packagecloud (0.2.4)
Installing Cookbook Gems:
Compiling Cookbooks...
[2016-07-26T13:35:48-04:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2016-07-26T13:35:48-04:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
Recipe: private-chef::default
  * directory[/etc/opscode] action create (up to date)
  * directory[/etc/opscode/logrotate.d] action create
    - create new directory /etc/opscode/logrotate.d
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
  Converging 209 resources
  * link[/usr/bin/private-chef-ctl] action create (up to date)
  * link[/usr/bin/chef-server-ctl] action create (up to date)
  * directory[/etc/opscode] action nothing (skipped due to action :nothing)
  * directory[/etc/opscode/logrotate.d] action nothing (skipped due to action :nothing)
  * log[opscode_webui deprecation notice] action write (skipped due to only_if)
Recipe: private-chef::users
  * user[opscode] action create (up to date)
  * group[opscode] action create (up to date)
Recipe: private-chef::default
  * file[/etc/opscode/dark_launch_features.json] action create
    - create new file /etc/opscode/dark_launch_features.json
    - update content in file /etc/opscode/dark_launch_features.json from none to a61cec
    --- /etc/opscode/dark_launch_features.json  2016-07-26 13:35:48.873789516 -0400
    +++ /etc/opscode/.chef-dark_launch_features.json20160726-12572-9fa2gg      2016-07-26 13:35:48.873789516 -0400
    @@ -1 +1,17 @@
    +{
    +  "quick_start": false,
    +  "new_theme": true,
    +  "private-chef": true,
    +  "sql_users": true,
    +  "add_type_and_bag_to_items": true,
    +  "reporting": true,
    +  "actions": false,
    +  "503_mode": false,
    +  "couchdb_containers": false,
    +  "couchdb_groups": false,
    +  "couchdb_acls": false,
    +  "couchdb_association_requests": false,
    +  "couchdb_organizations": false,
    +  "couchdb_associations": false
    +}
    - change mode from '' to '0644'
    - change owner from '' to 'opscode'
    - change group from '' to 'root'
  * file[/etc/opscode/webui_pub.pem] action create (up to date)
  * file[/etc/opscode/webui_priv.pem] action create
    - change owner from 'root' to 'opscode'
  * directory[/etc/chef] action create (up to date)
  * directory[/var/opt/opscode] action create (up to date)
  * directory[/var/log/opscode] action create
    - create new directory /var/log/opscode
    - change mode from '' to '0755'
    - change owner from '' to 'opscode'
    - change group from '' to 'opscode'
  * private_chef_keepalived_safemode[warmfuzzy] action create (skipped due to only_if)
Recipe: enterprise::runit
  * component_runit_supervisor[private_chef] action create
    * execute[initctl stop opscode-runsvdir] action run (skipped due to only_if)
    * file[/etc/init/opscode-runsvdir.conf] action delete (up to date)
    * template[/etc/init/private-chef-runsvdir.conf] action create (up to date)
    * execute[initctl status private-chef-runsvdir] action run
      - execute initctl status private-chef-runsvdir
    * execute[initctl start private-chef-runsvdir] action run
      - execute initctl start private-chef-runsvdir

Recipe: private-chef::sysctl-updates
  * execute[sysctl-reload] action nothing (skipped due to action :nothing)
  * bash[dual ip4/ip6 portbind] action run (skipped due to only_if)
Recipe: private-chef::plugin_chef_run
  * chef_run[recipe[chef-ha-drbd::disable]] action run[2016-07-26T13:35:48-04:00] WARN: Class Chef::Provider::ChefRun does not declare 'provides :chef_run'.
[2016-07-26T13:35:48-04:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 0 resources

    - Running chef-run with run list recipe[chef-ha-drbd::disable]
Recipe: private-chef::haproxy
  * directory[/var/opt/opscode/haproxy] action create
    - create new directory /var/opt/opscode/haproxy
    - change mode from '' to '0750'
    - change owner from '' to 'opscode'
    - change group from '' to 'opscode'
  * directory[/var/log/opscode/haproxy] action create
    - create new directory /var/log/opscode/haproxy
    - change mode from '' to '0750'
    - change owner from '' to 'opscode'
    - change group from '' to 'opscode'
  * template[/var/opt/opscode/haproxy/haproxy.cfg] action create
    - create new file /var/opt/opscode/haproxy/haproxy.cfg
    - update content in file /var/opt/opscode/haproxy/haproxy.cfg from none to eaee9a
    --- /var/opt/opscode/haproxy/haproxy.cfg    2016-07-26 13:35:49.260801848 -0400
    +++ /var/opt/opscode/haproxy/.chef-haproxy.cfg20160726-12572-5e404q 2016-07-26 13:35:49.260801848 -0400
    @@ -1 +1,30 @@
    +global
    +        stats socket /var/opt/opscode/haproxy/haproxy.sock mode 600
    +
    +frontend postgresql
    +         bind 0.0.0.0:5432
    +         mode tcp
    +         default_backend chef_backend_postgresql
    +
    +frontend elasticsearch
    +         bind 0.0.0.0:9200
    +         mode tcp
    +         default_backend chef_backend_elasticsearch
    +
    +backend chef_backend_postgresql
    +        mode tcp
    +        option httpchk GET /leader HTTP/1.1\r\nHost:localhost:7331\r\n\r\n
    +        default-server inter 2s rise 1 fall 1
    +        server 0c8f0e31ed06c5dc1838d25b4cb92523 10.253.17.85:5432 check port 7331
    +        server 58377b4006c2aabcadc9775f871e0ead 10.253.17.60:5432 check port 7331
    +        server ffb465689c05747b020536de578e881d 10.253.17.54:5432 check port 7331
    +
    +backend chef_backend_elasticsearch
    +        mode tcp
    +        option httpchk GET /leader HTTP/1.1\r\nHost:localhost:7331\r\n\r\n
    +        default-server inter 2s rise 1 fall 1
    +        server 0c8f0e31ed06c5dc1838d25b4cb92523 10.253.17.85:9200 check port 7331
    +                server 58377b4006c2aabcadc9775f871e0ead 10.253.17.60:9200 check port 7331
    +                server ffb465689c05747b020536de578e881d 10.253.17.54:9200 check port 7331
    +
    - change mode from '' to '0600'
    - change owner from '' to 'opscode'
    - change group from '' to 'opscode'
  * execute[restart_haproxy_log_service] action nothing (skipped due to action :nothing)
  * template[/var/log/opscode/haproxy/config] action create
    - create new file /var/log/opscode/haproxy/config
    - update content in file /var/log/opscode/haproxy/config from none to 5e16ac
    --- /var/log/opscode/haproxy/config 2016-07-26 13:35:49.271802200 -0400
    +++ /var/log/opscode/haproxy/.chef-config20160726-12572-1qq03lh     2016-07-26 13:35:49.271802200 -0400
    @@ -1 +1,4 @@
    +# svlogd configuration
    +s104857600
    +n10
    - change mode from '' to '0644'
    - change owner from '' to 'root'
    - change group from '' to 'root'
Recipe: <Dynamically Defined Resource>
  * service[haproxy] action nothing (skipped due to action :nothing)
Recipe: private-chef::haproxy
  * runit_service[haproxy] action enable
  Recipe: <Dynamically Defined Resource>
    * directory[/opt/opscode/sv/haproxy] action create
      - create new directory /opt/opscode/sv/haproxy
      - change mode from '' to '0755'
    * template[/opt/opscode/sv/haproxy/run] action create
      - create new file /opt/opscode/sv/haproxy/run
      - update content in file /opt/opscode/sv/haproxy/run from none to 04a873
      --- /opt/opscode/sv/haproxy/run   2016-07-26 13:35:49.286802678 -0400
      +++ /opt/opscode/sv/haproxy/.chef-run20160726-12572-1e4q3ev       2016-07-26 13:35:49.286802678 -0400
      @@ -1 +1,5 @@
      +#!/bin/sh
      +exec 2>&1
      +cd /var/opt/opscode/haproxy
      +exec chpst -P -u opscode -U opscode /opt/opscode/embedded/sbin/haproxy -f haproxy.cfg
      - change mode from '' to '0755'
    * directory[/opt/opscode/sv/haproxy/log] action create
      - create new directory /opt/opscode/sv/haproxy/log
      - change mode from '' to '0755'
    * directory[/opt/opscode/sv/haproxy/log/main] action create
      - create new directory /opt/opscode/sv/haproxy/log/main
      - change mode from '' to '0755'
    * template[/opt/opscode/sv/haproxy/log/run] action create
      - create new file /opt/opscode/sv/haproxy/log/run
      - update content in file /opt/opscode/sv/haproxy/log/run from none to 1898d6
      --- /opt/opscode/sv/haproxy/log/run       2016-07-26 13:35:49.299803092 -0400
      +++ /opt/opscode/sv/haproxy/log/.chef-run20160726-12572-z7n841    2016-07-26 13:35:49.299803092 -0400
      @@ -1 +1,4 @@
      +#!/bin/sh
      +exec chpst -U opscode -u opscode \
      +  svlogd -tt /var/log/opscode/haproxy
      - change mode from '' to '0755'
    * template[/opt/opscode/sv/haproxy/log/config] action create
      - create new file /opt/opscode/sv/haproxy/log/config
      - update content in file /opt/opscode/sv/haproxy/log/config from none to e3b0c4
      (no diff)
      - change mode from '' to '0644'
    * link[/opt/opscode/init/haproxy] action create
      - create symlink at /opt/opscode/init/haproxy to /opt/opscode/embedded/bin/sv
    * link[/opt/opscode/service/haproxy] action create
      - create symlink at /opt/opscode/service/haproxy to /opt/opscode/sv/haproxy

Recipe: private-chef::haproxy
  * ruby_block[wait for haproxy status socket] action run
    - execute the ruby block wait for haproxy status socket
  * ruby_block[wait for backend leader to stabilize] action run
    - execute the ruby block wait for backend leader to stabilize
Recipe: <Dynamically Defined Resource>
  * service[rabbitmq] action nothing (skipped due to action :nothing)
Recipe: private-chef::default
  * runit_service[rabbitmq] action disable (up to date)
Recipe: private-chef::erchef_database
  * private_chef_pg_user[opscode_chef] action create[2016-07-26T13:35:57-04:00] WARN: Error from postgresql: FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off. Retrying after 1s. Retries remaining: 5
[2016-07-26T13:35:58-04:00] WARN: Error from postgresql: FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off. Retrying after 2s. Retries remaining: 4
[2016-07-26T13:36:00-04:00] WARN: Error from postgresql: FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off. Retrying after 4s. Retries remaining: 3
[2016-07-26T13:36:04-04:00] WARN: Error from postgresql: FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off. Retrying after 8s. Retries remaining: 2
[2016-07-26T13:36:12-04:00] WARN: Error from postgresql: FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off. Retrying after 16s. Retries remaining: 1
[2016-07-26T13:36:28-04:00] ERROR: Error from postgresql: FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off. Retries have been exhausted.

    ================================================================================
    Error executing action `create` on resource 'private_chef_pg_user[opscode_chef]'
    ================================================================================

    PG::ConnectionBad
    -----------------
    FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
    FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off

    Cookbook Trace:
    ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:21:in `initialize'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:21:in `new'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:21:in `with_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/providers/pg_user.rb:16:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/erchef_database.rb

      5: private_chef_pg_user erchef['sql_user'] do
      6:   password erchef['sql_password']
      7:   superuser false
      8: end
      9:

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/erchef_database.rb:5:in `from_file'

    private_chef_pg_user("opscode_chef") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :private_chef_pg_user
      cookbook_name "private-chef"
      recipe_name "erchef_database"
      password "2b903b0739e6b39a673554f6657f53585010f0fd2b5d45b2cbc819b738b5"
    end

    Platform:
    ---------
    x86_64-linux

Recipe: private-chef::haproxy
  * runit_service[haproxy] action restart
    - restart service runit_service[haproxy]
  * execute[restart_haproxy_log_service] action run
    - execute /opt/opscode/embedded/bin/sv restart /opt/opscode/sv/haproxy/log

Running handlers:
[2016-07-26T13:36:29-04:00] ERROR: Running exception handlers
Running handlers complete
[2016-07-26T13:36:29-04:00] ERROR: Exception handlers complete
Chef Client failed. 25 resources updated in 45 seconds
[2016-07-26T13:36:29-04:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2016-07-26T13:36:29-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-26T13:36:29-04:00] FATAL: PG::ConnectionBad: private_chef_pg_user[opscode_chef] (private-chef::erchef_database line 5) had an error: PG::ConnectionBad: FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL on
FATAL:  no pg_hba.conf entry for host "10.253.7.250", user "chef_pgsql", database "template1", SSL off

I am also including the stacktrace.

[chef-stacktrace.out.txt](https://github.com/chef/chef-server/files/384427/chef-stacktrace.out.txt)

**Comment by stevendanna** [comment]
```

**Comment by marcparadise** [comment]
By default, PostgreSQL on chef-backend is configured to accept connections from `samehost` and `samenet`.  If `10.253.7.250` (and any other front-ends) are not is not on the same subnet, you can add a configuration entry as follows to chef-backend.rb: 

```
postgresql.md5_auth_cidr_addresses = %w{samehost samenet 10.253.7.250/32}
```

Or if you'll have more than one you're adding: 

```
postgresql.md5_auth_cidr_addresses = %w{samehost samenet 10.253.7.0/24}
```

Then run `chef-backend-ctl reconfigure` to pick up the change. 

You'll need to do this on each chef-backend node.    Because this change will trigger a postgresql restart, you should expect a change in cluster leadership to occur. To avoid triggering more than one of these, I'd recommend first upating the follower nodes first (you can check current leader/follower state   via `chef-backend-ctl cluster-status`).

**Comment by zimmma00** [comment]
Thank you.  That fixed my issue. I appreciate your help.
