### ISSUE TITLE
trying to add reporting onto my chef HA servers

### ISSUE THREAD

**Issue by zimmma00** [chef/chef-server#892]
We just installed the new chef HA.  When I lookup the doc to see what needs to be done, I think that I am seeing the doc for the old HA installation of reporting.
https://docs.chef.io/install_reporting.html
It wants me to use the chef-server-ctl command which does not exist on the back-end servers.  Do you have the url for the doc to install reporting on the new HA?

**Comment by marcparadise** [comment]
Reporting is not currently supported on Chef Server HA, but work on this is in progress and it should be available soon.

**Comment by zimmma00** [comment]
What about push jobs and analytics are they support with Chef Server HA?

**Comment by charlesjohnson** [comment]
Push Jobs and Analytics are not currently supported with Chef Server HA.

**Comment by zimmma00** [comment]
Thanks for the information.
