### ISSUE TITLE
Problems creating new nodes after restoring Chef 12 server from backup

### ISSUE THREAD

**Issue by klutarevich** [chef/chef-server#893]
I have an old EC2 server running 12.1.2 Chef server that I'd like to replace with the new one running Chef server 12.8.0. I created a backup on 12.1.2 using standard [instructions](https://docs.chef.io/server_backup_restore.html) (first option where I just tar/zip files) and restored it successfully on 12.8.0 or so I thought. Everything worked well including editing of existing environments and nodes until I tried to create a new node using knife from 12.8 client. It returned error 500 and I don't even know where to start looking on the server. Please, help

**Comment by marcparadise** [comment]
Hi @klutarevich - 
 
Restoring data from an older version to a new version is likely to cause the kinds of issues that you have observed - the upgrade process includes schema and data migrations that will nopt get processed in a direct restore from a prior versiion. 


If you're still having trouble, please make sure that you've done the following:

1. the new server should be the same version as the old server 
2. restore the data
3. Install the 12.8 package
3. run `chef-server-ctl upgrade` 
4. run `chef-server-ctl start`

From that point, everything should be fully operational.

**Comment by klutarevich** [comment]
Thanks. I followed your advice and it helped
