### ISSUE TITLE
Searches don't respect ACL read permission

### ISSUE THREAD

**Issue by nhurel** [chef/chef-server#897]
Hello,

I try to setup ACLs on my chef server instance and notice a strange behavior.
I want to remove read permission on some specific nodes for generic users.
Using knife acl, I remove all permissions on some specific nodes to all users :
```
knife acl bulk remove group users nodes 'forbidden*' create,update,delete,read,grant 
```
Then, running knife node show returns error 
```
knife node show -c knife_user.rb forbidden_node1
Response:  missing read permission
```

But if run a search, knife will show me all information I want : 
```
knife search node -c knife_user.rb "name:forbidden_node1" 
```
Using `-a attribute_name`, I can read all the attributes.

Is it possible to completely hide a node to users ?
Note :  the same issue happens when trying to hide an environment

Info : 
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
chef server : 12.8.0

**Comment by thommay** [comment]
Hi, the fix for this was released in chef server 12.0.7, but is not enabled by default. Please see https://github.com/chef/chef-server/blob/b5a1f8eed024b8a9dba7abb0d334be38787cd85a/PRIOR_RELEASE_NOTES.md#1207-2015-03-26 for how to enable ACLs for search.
