### ISSUE TITLE
Chef Server API should not allow usernames with spaces

### ISSUE THREAD

**Issue by charlesjohnson** [chef/chef-server#90]
Quoted: "One of my colleagues seems to have broken my chef user id using the chef API. He changed my user name from “Bobbob” to “Bob 2”.

Chef doesn’t seem to be able to handle this user (presumably the space), and I cannot log in, and using the chef website other users cannot even see any users in the chef organizations I belong to.

We cannot change my user again because none of the api’s will accept “Bob 2” as a user name."

More details in Zendesk ticket: https://getchef.zendesk.com/agent/tickets/2906

**Comment by marcparadise** [comment]
I was looking at this one in conjunction with #124.  In both cases, we have strict validation when the change is done through the API. I attempted to reproduce and got a 400 response with " {"error":["Field 'username' invalid"]} " 

Is it possible this change was done outside of the API - either directly in the DB, or through a different tool that uses direct DB access?

**Comment by manderson26** [comment]
I'm pretty sure it wasn't done outside the API; I was the only one on the ticket with database access to hosted.

**Comment by manderson26** [comment]
Wondering if there's a difference in validation between POST (create) and PUT (rename) paths. 
Or if we are just behind in hosted.

**Comment by stevendanna** [comment]
This is possible via the API:

```
> cat min.json
{
  "name": "m i n",
  "username": "min",
  "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAry5vgK5zWlZHu1ByyAdU\n9M8apAbrVjS+MA3Kc51udQ8fEmKI4f6Q/LDrncTBksyacO0J9thIzJrE9XwRSP6X\nbcVY5YhJWkZbshSj95WsBxIl36nw5FjpFNAE0/nTPVjDG5m/7Pea7I8tl2MUDBl9\n/S4w8bpdlL1qcD879lW4JES6Xj4hzl+RJXFZwyg2F7v/Pxx8CPnZTooc+HZSYo0N\n9bW8WjCi2aO/tshAGdnrJTIcfuRP+BHydFJO2K3PDgO5PQTftZZVMCZmkIHXPwJ2\nRVi7xGwaWa7ER4JD8Sr40Y+h5U+/Uo8FEEWYXTdzadbO00D5O1SD8mg3ZtEcJgJV\nIQIDAQAB\n-----END PUBLIC KEY-----\n\n",
  "email": "bob@acme.com",
  "display_name": "min widgeteer",
  "first_name": "min",
  "last_name": "widgeteer",
  "middle_name": ""
}
> knife raw -m PUT -i min.json "/users/min" -c .chef/chef-shell.rb
{
  "uri": "https://api.opscode.piab/users/m i n"
}
```

The key is that my JSON body includes both a `name` field and a `username` field.  When we validate the username, we prefer the username field:

https://github.com/chef/oc_erchef/blob/master/apps/chef_objects/src/chef_user.erl#L322-L323

but when we pull the username out late, we prefer the name field:

https://github.com/chef/oc_erchef/blob/master/apps/chef_objects/src/chef_user.erl#L100-L106

**Comment by charlesjohnson** [comment]
:clap: That is one hell of a catch.

**Comment by marcparadise** [comment]
Ah, nice catch!
