### ISSUE TITLE
Chef-server-ctrl fails on any command

### ISSUE THREAD

**Issue by flybd5** [chef/chef-server#915]
After updating chef using apt-get, I am getting the following error any time I try to use chef-server-ctl with any command:

**/opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- redis (LoadError)
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /opt/opscode/embedded/service/omnibus-ctl/reindex.rb:21:in `load_file'
        from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:187:in `eval'
        from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:187:in `load_file'
        from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:182:in `block in load_files'
        from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:181:in `each'
        from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:181:in `load_files'
        from /opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl:235:in `<main>'**

gem list chef returns the following:

***** LOCAL GEMS ***

chef (12.12.19, 12.5.0.current.0)
chef-api (0.6.0)
chef-config (12.12.19, 12.12.13, 12.11.18, 12.5.0.current.0)
chef-provisioning (1.8.0)
chef-provisioning-aws (1.10.0)
chef-rewind (0.0.9)
chef-sugar (3.3.0)
chef-zero (4.7.0, 4.5.0, 4.2.3)
chef_backup (0.0.1)
cheffish (2.0.4, 1.2)
chefspec (4.7.0)**

Any ideas?

**Comment by flybd5** [comment]
I've used strace to track it down to a missing redis.so in /opt/opscode/embedded/lib/ruby/2.1.0/x86_64-linux/. 

??

**Comment by marcparadise** [comment]
I'm sorry to hear the upgrade is giving you trouble.What version were you upgrading from, and on which platform?

**Comment by flybd5** [comment]
Platform is Ubuntu 14.04. 

I think I managed to resolve it by commenting out the require redis from reindex.rb. It works now, running the chef-server-ctl upgrade now.

**Comment by flybd5** [comment]
That fixed it.
