### ISSUE TITLE
12.7+ breaks nginx url

### ISSUE THREAD

**Issue by jaymzh** [chef/chef-server#922]
Chef-server-core 12.7 breaks default nginx URL. A reconfigure gives you this:

```
  URI::InvalidURIError
  --------------------
  the scheme https does not accept registry part: :443 (or bad hostname?)
...
   71:    def nginx_ssl_url
   72:      # Using URI#to_s to strip ":443" for https and ":80" for http
   73>>     URI("#{node['private_chef']['nginx']['url']}:#{node['private_chef']['nginx']['ssl_port']}").to_s
   74:    end
```

The default for this is correct in the `private-chef` cookbooks (`/opt/opscode/embedded/cookbooks/private-chef/attributes/default.rb`):

```
default['private_chef']['nginx']['url'] = "https://#{node['fqdn']}"
```

And I verified it gets set to something sane there, **however** it is then nuked later (in `/opt/opscode/embedded/cookbooks/private-chef/libraries/private_chef.rb`):

```
      PrivateChef["nginx"]["url"] ||= "https://#{PrivateChef['api_fqdn']}"
```

Which if `api_fqdn` isn't set (which, it's not required), this then gets set to empty string. Which then results in the above error. This wasn't the case on 12.0 - 12.3 at least. I don't know when this actually broke.

**Comment by vaibhi9** [comment]
I am facing same issue on s390x machine



```
./configure: error: ngx_http_lua_module requires the Lua or LuaJIT library and LUA_LIB is defined as /opt/opscode/embedded/lib/lib and LUA_INC (path for lua.h) is /opt/opscode/embedded/lib/include, but we cannot find standard Lua there.

Error:

    ERROR: failed to run command: sh ./configure --prefix=/opt/opscode/embedded/nginx \...
```

**Comment by srenatus** [comment]
@vaibhi9 your comment doesn't seem like it related to this issue -- or do I just fail to see it?

**Comment by thommay** [comment]
@vaibhi9 that looks like a totally different issue. Please file a new issue with your details.

**Comment by srenatus** [comment]
`api_fqdn` is not _required per se_ -- it would use your node name (unless overridden, it's the FQDN, or rather, the output of `hostname -f` on the node) if unset ([see here](https://github.com/chef/chef-server/blob/4ec1d014c9a4945398c6baa550c71f7e3a7e69e0/omnibus/files/private-chef-cookbooks/private-chef/libraries/private_chef.rb#L720)).

I'd suspect the error comes from `hostname -f` being empty (returning nothing) on your machine. This is one of the cases where _not setting `api_fqdn`_ will not be an option, I'm afraid.

This has been around for some time, so I'd think you've probably already set `api_fqdn` and moved on? Please re-open this if you need further assistance 😃
