### ISSUE TITLE
Failed to restore backup data using chef-backend-ctl 1.1.2

### ISSUE THREAD

**Issue by klausyoum** [chef/chef-server#926]
Dear Chef development team,

I love chef solution and think that it is very powerful to configure various servers automatically.

Now I just set up backend cluster(2 front-end servers and 3 back-end servers) using chef-backend package and made a backup file successfully. Then I executed the restore command at a leader instance of back-end cluster, an error occurred during the operation. It seems that there is a missed or undefined method whose name is "**restore_secrets**". Here is my environment and attached log while chef-backend-ctl command was executing.
1. Chef Server version: https://packages.chef.io/stable/el/5/chef-server-core-12.8.0-1.el5.x86_64.rpm
2. Chef HA version: https://packages.chef.io/stable/el/5/chef-backend-1.1.2-1.el5.x86_64.rpm
3. OS: Amazon Linux based on Cent OS 
---

$ sudo chef-backend-ctl restore chef-backup-2016-09-06-11-01-49.tgz --verbose
Restoring a backup will remove all data currently on this Chef Backend
node.
Would you like to proceed? (y/n)
y
✓ Unpacking backup to temporary directory
✓ Removing existing data directories
✗ Restoring basic configuration
   Restoring Elasticsearch data
   Reconfiguring Chef Backend
   Restoring PostegreSQL data
   Starting up Chef Backend
✓ Cleaning Up Temporary Files

An error occurred during this operation:

   **undefined method `restore_secrets' for #LibCB::Command::Restore:0x000000016c3418**

The log from the backup follows:

   Expanding tarball: /home/ec2-user/chef-backup-2016-09-06-11-01-49.tgz
Cleaning up any old files
---

I just executed the command following the Chef HA page, https://docs.chef.io/install_server_ha.html If I should check my infrastructures, please let me know it.

Thanks in advance.

**Comment by stevendanna** [comment]
@klausyoum Apologies no one responded to this issue.  I believe this issue is fixed on the "current" build: https://bintray.com/chef/current/chef-backend/1.1.37 

This build (or a subsequent build) will eventually be promoted to stable.

**Comment by charlesjohnson** [comment]
@klausyoum Glad you're liking the Chef HA solution!

Because chef-backend is a proprietary product, any issues should be reported to the Chef support team, rather than routed through Github. Since we believe that 1.1.37 will resolve the issue you're seeing, I'm going to close this issue. If you still have trouble, please contact Chef support and we'll help you get sorted.
