### ISSUE TITLE
chef-manage-ctl hangs with chef server version 12 

### ISSUE THREAD

**Issue by rashbhat** [chef/chef-server#933]
Hi, 

I am trying to install chef-manage on my chef server (ubuntu 14.04).  chef manage install command doesn't throw any error, but on running chef-manage-ctl reconfigure terminal hangs at - 

chef-manage 2.4.3 license: "Chef-MLSA"

Use of Chef Manage is subject to the terms of the Chef Master License and
Services Agreement. You can find the latest copy of the agreement here:
https://www.chef.io/online-master-agreement/

This product bundles berkshelf v4.2.3,
which is available under a "Apache-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/berkshelf-LICENSE

This product bundles bundler ,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/bundler-LICENSE.md

This product bundles bzip2 1.0.6,
which is available under a "BSD-2-Clause" License.
For details, see:
/opt/chef-manage/LICENSES/bzip2-LICENSE

This product bundles cacerts 2016.01.20,
which is available under a "MPL-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/cacerts-README.md

This product bundles chef-gem 12.4.1,
which is available under a "Apache-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/chef-gem-LICENSE

This product bundles config_guess master,
which is available under a "GPL-3.0 (with exception)" License.
For details, see:
/opt/chef-manage/LICENSES/config_guess-config.guess
/opt/chef-manage/LICENSES/config_guess-config.sub
:

This product bundles curl 7.47.1,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/curl-COPYING

This product bundles dep-selector-libgecode 1.2.0,
which is available under a "Apache-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/dep-selector-libgecode-LICENSE.txt

This product bundles libarchive 3.1.2,
which is available under a "BSD-2-Clause" License.
For details, see:
/opt/chef-manage/LICENSES/libarchive-COPYING

This product bundles libffi 3.2.1,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/libffi-LICENSE

This product bundles libiconv 1.14,
which is available under a "LGPL-2.1" License.
For details, see:
/opt/chef-manage/LICENSES/libiconv-COPYING.LIB

This product bundles liblzma 5.2.2,
which is available under a "Public-Domain" License.
For details, see:
/opt/chef-manage/LICENSES/liblzma-COPYING

This product bundles libtool 2.4,
which is available under a "GPL-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/libtool-COPYING

:
This product bundles libxslt 1.1.28,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/libxslt-COPYING

This product bundles libyaml 0.1.6,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/libyaml-LICENSE

This product bundles makedepend 1.0.5,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/makedepend-COPYING

This product bundles ncurses 5.9,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/ncurses-ncurses-license.html
/opt/chef-manage/LICENSES/ncurses-ncurses.faq.html

This product bundles nodejs 0.10.35,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/nodejs-LICENSE

This product bundles nokogiri ,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/nokogiri-LICENSE.txt

This product bundles omnibus-ctl v0.5.0,
which is available under a "Apache-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/omnibus-ctl-LICENSE
:

which is available under a "OpenSSL" License.
For details, see:
/opt/chef-manage/LICENSES/openssl-LICENSE

This product bundles pkg-config-lite 0.28-1,
which is available under a "GPL-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/pkg-config-lite-COPYING

This product bundles python 2.7.9,
which is available under a "Python-2.0" License.
For details, see:
/opt/chef-manage/LICENSES/python-LICENSE

This product bundles rb-readline master,
which is available under a "BSD-3-Clause" License.
For details, see:
/opt/chef-manage/LICENSES/rb-readline-LICENSE

This product bundles redis 3.0.4,
which is available under a "BSD-3-Clause" License.
For details, see:
/opt/chef-manage/LICENSES/redis-COPYING

This product bundles ruby 2.2.2,
which is available under a "BSD-2-Clause" License.
For details, see:
/opt/chef-manage/LICENSES/ruby-BSDL
/opt/chef-manage/LICENSES/ruby-COPYING
/opt/chef-manage/LICENSES/ruby-LEGAL

This product bundles rubygems 2.4.8,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/rubygems-LICENSE.txt

This product bundles runit 2.1.1,
which is available under a "BSD-3-Clause" License.
:

This product bundles util-macros 1.18.0,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/util-macros-COPYING

This product bundles xproto 7.0.25,
which is available under a "MIT" License.
For details, see:
/opt/chef-manage/LICENSES/xproto-COPYING

This product bundles zlib 1.2.8,
which is available under a "Zlib" License.
For details, see:
/opt/chef-manage/LICENSES/zlib-README

(END)

On pressing CTRL-C the following message is displayed -
opt/chef-manage/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:549:in `system': Interrupt
        from /opt/chef-manage/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:549:in`ask_license_acceptance'
        from /opt/chef-manage/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:526:in `check_license_acceptance'
        from /opt/chef-manage/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:507:in`reconfigure'
        from /opt/chef-manage/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/lib/omnibus-ctl.rb:731:in `run'
        from /opt/chef-manage/embedded/lib/ruby/gems/2.2.0/gems/omnibus-ctl-0.5.0/bin/omnibus-ctl:31:in`<top (required)>'
        from /opt/chef-manage/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/chef-manage/embedded/bin/omnibus-ctl:23:in`<main>'

**Comment by stevendanna** [comment]
@rashbhat Apologies that no one responded to this issue.  I believe that chef-manage-ctl is opening your system pager (likely the program `less`) in order to show you the license information. You can exit that by pressing `q` and then proceed by agreeing to the license.  I'm going to close this for now, but if you are still having an issue feel free to reopen it or contact support@chef.io.

**Comment by xxxkrogoth** [comment]
You can just put a "q" to quit in the license agreement so people know
