### ISSUE TITLE
deb package of bad quality on install

### ISSUE THREAD

**Issue by trivalik** [chef/chef-server#934]
Ubuntu Software Center is hold the deb package of bad quality on install.
This was occured for install of chef server version 12.8.0.
The Ubuntu Version was as fresh installed 14.04.5
I believe the root cause is that mail address is missing behind "Maintainer:"
like here described https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Maintainer
![be0e328a-7e56-11e6-9a1e-f2769f4edf89](https://cloud.githubusercontent.com/assets/3148279/18639917/164568c6-7e96-11e6-9426-6e5b72de3010.png)

**Comment by marcparadise** [comment]
Thanks for opening this.  12.9 will be released shortly and we will correct it from that.

**Comment by stevendanna** [comment]
This was fixed in 87de38ef.
