### ISSUE TITLE
Placeholder for user acl update tracking

### ISSUE THREAD

**Issue by marcparadise** [chef/chef-server#938]
In 12.8 and later, attempting to update user ACE when that ACE contains a global group (such as `server-admins`) fails because ACL logic doesn't currently know how to handle global groups.
In 12.9, attempting to update a user ACE fails uniformly because of the new ACL constraint that requires actors to belong to the org of the object being updated.  Users are global objects, and in this context no organization is expected. 

These issues are  currently resolved in #886

**Comment by stevendanna** [comment]
We believe this should be fixed with 12.15.3
