### ISSUE TITLE
Document Load Balancer Requirements for Chef Server

### ISSUE THREAD

**Issue by sean-horn** [chef/chef-server#94]
ZenDesk 2614 
Chef 12 + Manage 1.6.2

As a customer, I would like these requirements, like sticky sessions and NATing for frontend connections through the LB to be documented at docs.chef.io

Our customer in ZenDesk 2614 had this to say about their findings with Chef 12 + Manage 1.6.2

Hitting the chef FQDN in the chef-server.rb, static content would load fine, but when trying to do anything that would talk to the API - it would fail with a generic "Smell Something burning" error message - see ZenDesk 1943: [Chef] [1943] Re: Smell something burning?

the FE's, instead of just accessing localhost for their api - would try to talk to the FQDN, , when the traffic passed through the lb, to the FEs, the shortest return path then is direct communication - resulting in a async connection...with the originating FE thinking the traffic was lost to the void.

EG: NODEX -> LB -> FE1 -> LB -> NODEX == work 
FE1 -> LB -> FE2 - > FE1 == no workie

The fix was to nat connections from the FE network, so they appear as a normal node and traffic returns via the LB

**Comment by stevendanna** [comment]
I believe most of the requirements mentioned here are imposed by Chef Manage.  Could someone on @chef/chef-visual-interaction comment on what the requirements are?

**Comment by sean-horn** [comment]
The related issue is https://github.com/chef/chef-manage-issues/issues/22

**Comment by smith** [comment]
Sticky sessions are not needed if the instances share the same secret key, which can be shared by copying the /etc/opscode-manage/secrets.rb file that gets generated on the first reconfigure around to all of the nodes. Pretty sure this isn't documented anywhere, we could work with @jamescott on that.

The next release of Manage should use localhost instead of the api_fqdn, which should solve this problem.

**Comment by mmzyk** [comment]
@smith with the merging of the above referenced PR, does this still need to be open or can this be closed?

**Comment by smith** [comment]
@mmzyk are the load balancer requirements for chef server documented? That's what the ticket was asking for. This fixes the NAT problem referenced, but it's up to @sean-horn whether or not that is sufficient for the customer.

**Comment by mmzyk** [comment]
Documentation around this has been added and will be available once this doc snippet is done building. https://github.com/chef/chef-docs/commit/885fcefff0a34f1f9a23475e7cf3f38b4e2ee1a1

I'm going to close this out as fulfilled.
