### ISSUE TITLE
chef-server-ctl reconfigure fails when ldap['bind_password'] is not set

### ISSUE THREAD

**Issue by tonyflint** [chef/chef-server#947]
**Environment details**
chef server: 12.9.1
OS: Ubuntu 12.04

**Description**

We ran into this problem upgrading chef-server from 12.2 to 12.9. The helper code in [private-chef/libraries/helpers.rb](https://github.com/chef/chef-server/blob/3a08949406859c4bbae4575ff9414cf223cc1fba/omnibus/files/private-chef-cookbooks/private-chef/libraries/helper.rb#L159) isn't nil-safe:

```
def self.escape_characters_in_string(string)
    pattern = /(\'|\"|\.|\*|\/|\-|\\)/
    string.gsub(pattern){|match|"\\"  + match}
  end
```

**Steps to reproduce the problem**
1. Modify `chef-server.rb` to enable LDAP logins using an LDAP server that allows anonymous binds. We set the following parameters:
   
   ```
   ldap['base_dn']
   ldap['host']
   ldap['login_attribute']
   ldap['tls_enabled']
   ```
2. Run `chef-server-ctl reconfigure`

**Expected result**

Success

**Actual result**

The following error is shown, and the reconfigure fails:

```
Chef::Mixin::Template::TemplateError:

Chef::Mixin::Template::TemplateError (undefined method `gsub' for nil:NilClass) on line #88:

 86:             {timeout, <%= node['private_chef']['ldap']['timeout'] || 60000 %> },
 87:             {bind_dn, "<%= node['private_chef']['ldap']['bind_dn'] || "" %>" },
 88:             {bind_password, "<%= @helper.escape_characters_in_string(node['private_chef']['ldap']['bind_password']) || "" %>" },
 89:             {base_dn, "<%= node['private_chef']['ldap']['base_dn'] || "" %>" },
 90:             {group_dn, "<%= node['private_chef']['ldap']['group_dn'] || "" %>" },

  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/helper.rb:161:in `escape_characters_in_string'
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/helper.rb:165:in `escape_characters_in_string'
```

**Comment by stevendanna** [comment]
Fixed in https://github.com/chef/chef-server/pull/974 (not yet released, new release coming soon)

**Comment by stevendanna** [comment]
Chef 12.10.0 has been released which fixes this issue.
