### ISSUE TITLE
[chef-server-reconfigure] chef server does not support providing your own pivotal.pem

### ISSUE THREAD

**Issue by foram31k** [chef/chef-server#952]
Hey,
 I've installed Chef-server 12.9.1 on Ubuntu-14.04 VM
 I run the command chef-server-ctl reconfigure and got ERROR
The error is as follows:
![bootstrap_error](https://cloud.githubusercontent.com/assets/12700004/19063855/d834de10-8a23-11e6-938a-0924f38fba08.png)
 StackTrace:

> > > > Caused by NoMethodError: undefined method `[]' for nil:NilClass
> > > > /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:97:in`create_superuser_in_erchef'
> > > > /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:50:in `block in bootstrap'
> > > > /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:55:in`block in with_service_connection'
> > > > /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:44:in `with_connection'
> > > > /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:52:in`with_service_connection'
> > > > /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:49:in `bootstrap'
> > > > /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:35:in`block (2 levels) in from_file'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/provider/ruby_block.rb:35:in `call'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/provider/ruby_block.rb:35:in`block in action_run'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/mixin/why_run.rb:52:in `add_action'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/provider.rb:176:in`converge_by'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/provider/ruby_block.rb:34:in `action_run'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/provider.rb:145:in`run_action'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource.rb:603:in `run_action'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:69:in`run_action'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `block (2 levels) in converge'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in`each'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:97:in `block in converge'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/resource_list.rb:94:in`block in execute_each_resource'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:114:in `call'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:114:in`call_iterator_block'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:103:in`iterate'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/resource_collection/resource_list.rb:92:in`execute_each_resource'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/runner.rb:96:in `converge'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:669:in`block in converge'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:664:in `catch'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:664:in`converge'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:703:in `converge_and_save'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/client.rb:283:in`run'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:260:in`block in run_chef_client'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/local_mode.rb:44:in `with_server_connectivity'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:243:in`run_chef_client'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application/client.rb:427:in `run_application'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/lib/chef/application.rb:60:in`run'
> > > > /opt/opscode/embedded/lib/ruby/gems/2.2.0/gems/chef-12.14.98/bin/chef-client:26:in `<top (required)>'
> > > > /opt/opscode/embedded/bin/chef-client:22:in`load'

**Comment by mikhels** [comment]
Faced the same problem on CentOS 6. RPM version: chef-server-core-12.9.1-1.el6.x86_64.

**Comment by foram31k** [comment]
@mikhels  You found any solution ?

**Comment by mikhels** [comment]
Worked for me but I'm not sure that it's a correct workaround.

```
--- /opt/opscode/embedded/cookbooks/private-chef/recipes/private_keys.rb.bak    2016-10-04 11:21:41.091957829 +0000
+++ /opt/opscode/embedded/cookbooks/private-chef/recipes/private_keys.rb        2016-10-04 11:21:56.760467902 +0000
@@ -28,7 +28,11 @@
 pivotal_key = OpenSSL::PKey::RSA.generate(2048) if new_pivotal
 
 # Setting at the top level so that we don't export this to chef-server-running.json
-node.set['bootstrap']['superuser_public_key'] = pivotal_key.public_key.to_s if new_pivotal
+if new_pivotal
+  node.set['bootstrap']['superuser_public_key'] = pivotal_key.public_key.to_s
+else
+  node.set['bootstrap']['superuser_public_key'] = File.read(pivotal_key_path)
+end
 
 file pivotal_key_path do
   owner OmnibusHelper.new(node).ownership['owner']
```

**Comment by marcparadise** [comment]
Did you have any settings in `chef-server.rb` and/or an existing `pivotal.pem` in `/etc/opscode`? 
If you did have `chef-server.rb` could you post contents (redacted if needed)?

**Comment by foram31k** [comment]
@marcparadise Yes, chef-server.rb and pivotal.pem does exist. But, chef-server.rb is empty and pivotal.pem has the RSA key.

**Comment by marcparadise** [comment]
At this time bringing your own pivotal key is not supported - pivotal.pem is for internal use by the chef server and the server expects to generate and own it. 

I've tagged this as `enhancement` and will update the title. It would be possible to add support for this, but because of the way the bootstrap process has grown over time it would also require a fair bit of testing and validation to make sure it didn't break more standard use cases.

**Comment by geethasitaraman** [comment]
I am facing the same issue when trying to install Chefserver 12.9.1 on Red Hat 7 . I am running the chef-server-ctl reconfigure, when I get the following error : 
 Error executing action `run` on resource 'ruby_block[bootstrap-chef-server-data]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass

    Cookbook Trace:
    ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:97:in `create_superuser_in_erchef'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:50:in `block in bootstrap'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:55:in `block in with_service_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:44:in `with_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/ec_postgres.rb:52:in `with_service_connection'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:49:in `bootstrap'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:35:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb

     33: ruby_block "bootstrap-chef-server-data" do
     34:   block do
     35:     ChefServerDataBootstrap.new(node).bootstrap
     36:   end
     37:   not_if { OmnibusHelper.has_been_bootstrapped? }
     38:   notifies :restart, 'service[opscode-erchef]'
     39: end
     40:

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:33:in `from_file'

    ruby_block("bootstrap-chef-server-data") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "bootstrap-chef-server-data"
      declared_type :ruby_block
      cookbook_name "private-chef"
      recipe_name "bootstrap"
      block #<Proc:0x00000006de4080@/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:34>
      not_if { #code block }
    end

    Platform:
    ---------
    x86_64-linux

Whats the fix for this issue?

**Comment by marcparadise** [comment]
Chef Server does not support bringing your own pivotal.pem at this time. The only fix at present is to remove your pivotal.pem from `/etc/opscode` and allow the `reconfigure` to create one.

**Comment by geethasitaraman** [comment]
I did try the above fix but it lead to the below error :
-----------------------------------------------------------------------
BOOT007: The secrets file (/etc/opscode/private-chef-secrets.json) is present
         but the file /etc/opscode/pivotal.pem is missing.

         Ensure that private-chef-secrets.json is copied into /etc/opscode from the
         first Chef Server node that you brought online, then run
         'chef-server-ctl reconfigure' again.
-----------------------------------------------------------------------
May be its related to this error : https://github.com/chef/chef-server/issues/727
Thanks

**Comment by sean-horn** [comment]
Another thing that should work is install Chef Server 12.8.0, then upgrade to 12.9.1

**Comment by DarwinJS** [comment]
I get the original PEM error Chef 12.8.0, however, copying the pem then works on 12.8.0, unlike 12.9.1 that generates.  Installing on Ubuntu 14 on AWS.

**Comment by cosmocaan** [comment]
Having the same problem on RHEL 6.8.  Tried installing 12.8.0 with and without pem and get the same Error executing action `run` on resource 'ruby_block[bootstrap-chef-server-data]' error.
` * ruby_block[bootstrap-chef-server-data] action run[2016-10-21T19:40:18-05:00] WARN: Error from bifrost: {"error":"requesting actor id of 'd60aeae71b3a8453e0ccc6cdb76991ff' does not exist"}, retrying after 1s. Retries remaining: 4
[2016-10-21T19:40:19-05:00] WARN: Error from bifrost: {"error":"requesting actor id of 'd60aeae71b3a8453e0ccc6cdb76991ff' does not exist"}, retrying after 2s. Retries remaining: 3
[2016-10-21T19:40:21-05:00] WARN: Error from bifrost: {"error":"requesting actor id of 'd60aeae71b3a8453e0ccc6cdb76991ff' does not exist"}, retrying after 4s. Retries remaining: 2
[2016-10-21T19:40:25-05:00] WARN: Error from bifrost: {"error":"requesting actor id of 'd60aeae71b3a8453e0ccc6cdb76991ff' does not exist"}, retrying after 8s. Retries remaining: 1
[2016-10-21T19:40:33-05:00] WARN: Error from bifrost: {"error":"requesting actor id of 'd60aeae71b3a8453e0ccc6cdb76991ff' does not exist"}, retrying after 16s. Retries remaining: 0
[2016-10-21T19:40:49-05:00] ERROR: Error from bifrost {"error":"requesting actor id of 'd60aeae71b3a8453e0ccc6cdb76991ff' does not exist"}, retries have been exhausted


    ================================================================================
    Error executing action `run` on resource 'ruby_block[bootstrap-chef-server-data]'
    ================================================================================

    RestClient::Unauthorized
    ------------------------
    401 Unauthorized

    Cookbook Trace:
    ---------------
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:187:in `bifrost_request'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:154:in `create_object_in_authz'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:146:in `create_actor_in_authz'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:36:in `bootstrap'
    /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:46:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb

     44: ruby_block "bootstrap-chef-server-data" do
     45:   block do
     46:     ChefServerDataBootstrap.new(node).bootstrap
     47:   end
     48:   not_if { OmnibusHelper.has_been_bootstrapped? }
     49:   notifies :restart, 'service[opscode-erchef]'
     50: end
     51:

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:44:in `from_file'

    ruby_block("bootstrap-chef-server-data") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "bootstrap-chef-server-data"
      declared_type :ruby_block
      cookbook_name "private-chef"
      recipe_name "bootstrap"
      block #<Proc:0x000000057a2330@/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:45>
      not_if { #code block }
    end`

Stacktrace:
`Generated at 2016-10-21 19:40:49 -0500
RestClient::Unauthorized: 401 Unauthorized: {"error":"requesting actor id of 'd60aeae71b3a8453e0ccc6cdb76991ff' does not exist"}
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
/opt/opscode/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:187:in `bifrost_request'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:154:in `create_object_in_authz'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:146:in `create_actor_in_authz'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/libraries/chef_server_data_bootstrap.rb:36:in `bootstrap'
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/bootstrap.rb:46:in `block (2 levels) in from_file'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider/ruby_block.rb:35:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider/ruby_block.rb:35:in `block in action_run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider.rb:176:in `converge_by'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider/ruby_block.rb:34:in `action_run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/provider.rb:145:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource.rb:591:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/runner.rb:69:in `run_action'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/runner.rb:97:in `each'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/runner.rb:97:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/runner.rb:96:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/client.rb:669:in `block in converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/client.rb:664:in `catch'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/client.rb:664:in `converge'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/client.rb:703:in `converge_and_save'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/client.rb:283:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/application.rb:268:in `run_with_graceful_exit_option'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/application.rb:227:in `run_chef_client'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/application/client.rb:419:in `run_application'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/lib/chef/application.rb:59:in `run'
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.19/bin/chef-client:26:in `<top (required)>'
/opt/opscode/embedded/bin/chef-client:23:in `load'
/opt/opscode/embedded/bin/chef-client:23:in `<main>'`

**Comment by danielsdeleo** [comment]
What are you attempting to do? You can use the key rotation feature to _add_ a key to pivotal after the server is bootstrapped which would give more or less the same functionality.

**Comment by cosmocaan** [comment]
I'm installing for the first time following the installation guide  [.](https://docs.chef.io/install_chef_automate.html)  This happens when I execute `chef-server-ctl reconfigure`

**Comment by danielsdeleo** [comment]
Is the installation guide telling you to create a RSA key and put it in `/etc/opscode/pivotal.pem`? Why is that there?

**Comment by cosmocaan** [comment]
There is no mention in the installation guides to create `/etc/opscode/pivotal.pem` . I copied it from `/opt/opscode/embedded/service/omnibus-ctl/spec/fixtures/` and at least get a different error now.  I'll look into this one this evening.

`================================================================================
    Error executing action `run` on resource 'execute[/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '2'
    ---- Begin output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
    STDOUT: Waiting for rabbit@localhost ...
    pid is 63576 ...
    STDERR: Error: process_not_running
    ---- End output of /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid ----
    Ran /opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid returned 2

    Resource Declaration:
    ---------------------
    # In /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/rabbitmq.rb

    121:   execute "#{rmq_ctl_chpst} wait #{rabbitmq_data_dir}/#{rabbitmq['nodename']}.pid" do
    122:     environment rabbitmq_env
    123:     retries 10
    124:   end
    125:

    Compiled Resource:
    ------------------
    # Declared in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/rabbitmq.rb:121:in `from_file'

    execute("/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid") do
      action [:run]
      retries 10
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/opscode/embedded/bin/chpst -u opscode -U opscode /opt/opscode/embedded/bin/rabbitmqctl wait /var/opt/opscode/rabbitmq/db/rabbit@localhost.pid"
      backup 5
      environment {"ETPKIHOME"=>"/opt/CA/SharedComponents/ETPKI", "HOSTNAME"=>"tlgsaschefs01", "TERM"=>"xterm", "SHELL"=>"/bin/bash", "HISTSIZE"=>"1000", "QTDIR"=>"/usr/lib64/qt-3.3", "QTINC"=>"/usr/lib64/qt-3.3/include", "USER"=>"root", "LS_COLORS"=>"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.tbz=01;31:*.tbz2=01;31:*.bz=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:", "LD_LIBRARY_PATH"=>"/opt/CA/SharedComponents/ETPKI/../lib:/opt/CA/SharedComponents/lib:/opt/CA/CAlib:/usr/lib:/opt/CA/SharedComponents/Csam/SockAdapter/lib", "CSAM_SOCKADAPTER"=>"/opt/CA/SharedComponents/Csam/SockAdapter", "TMOUT"=>"7200", "CSAM_LOGGER_CONF"=>"/opt/CA/SharedComponents/Csam/SockAdapter/cfg/logger.cfg", "PATH"=>"/opt/opscode/bin:/opt/opscode/embedded/bin:/usr/bin:/bin", "MAIL"=>"/var/spool/mail/root", "CA_LOCALE"=>"enu", "CA_CAILANGUAGE"=>"enu", "PWD"=>"/etc/opscode", "INPUTRC"=>"/etc/inputrc", "TIMEOUT"=>"7200", "LANG"=>"en_US.UTF-8", "SVWAIT"=>"30", "HOME"=>"/root", "SHLVL"=>"2", "CANOLOG_flag"=>"", "LOGNAME"=>"root", "CVS_RSH"=>"ssh", "QTLIB"=>"/usr/lib64/qt-3.3/lib", "LESSOPEN"=>"||/usr/bin/lesspipe.sh %s", "CASHCOMP"=>"/opt/CA/SharedComponents", "CABIN"=>"/opt/CA/SharedComponents/bin", "CALIB"=>"/opt/CA/SharedComponents/lib", "G_BROKEN_FILENAMES"=>"1", "_"=>"/opt/opscode/embedded/service/omnibus-ctl/chef-server-ctl"}
      returns 0
      declared_type :execute
      cookbook_name "private-chef"
      recipe_name "rabbitmq"
    end
`

**Comment by danielsdeleo** [comment]
If you're not specifically trying to install a Chef Server with a predetermined `pivotal.pem` key, then you should create a new ticket or start a discussion on https://discourse.chef.io

This ticket is specifically for creating a Chef Server with a user-supplied pivotal key. Copying the key from the fixtures is unlikely to give you a usable system and would cause security problems besides.

**Comment by jeremymv2** [comment]
I experienced this same issue with a customer using RHEL 6.8 and they did NOT supply their own pivotal key.

**Comment by danielsdeleo** [comment]
@jeremymv2 can you create a new ticket please?

**Comment by jeremymv2** [comment]
@danielsdeleo sure thing
https://github.com/chef/chef-server/issues/987
