### ISSUE TITLE
chef-server-ctl restore fails with "No such file or directory - opscode-analytics-ctl"

### ISSUE THREAD

**Issue by markan** [chef/chef-server#959]
On a fresh Centos 7.2 host
- Install chef server 12.9.1
- chef-server-ctl reconfigure
- chef-server-ctl backup, and move backup to safe place
  On a fresh Centos 7.2 host
- Install chef server 12.9.1
- chef-server-ctl reconfigure
- chef-server-ctl restore backup.tgz
  Fails, with 
  No such file or directory - opscode-analytics-ctl

Chain of events:
- chef-server-ctl restore invokes the chef-backup gem
- The chef-backup gem runs a reconfigure on chef-server
  This creates the directory /etc/opscode-analytics with two files,
  but the config file '/etc/opscode-analytics/opscode-analytics.rb'
  see:
  - https://github.com/chef/chef_backup/blob/master/lib/chef_backup/strategy/restore/tar.rb
  - https://github.com/chef/chef-server/blob/master/omnibus/files/private-chef-cookbooks/private-chef/recipes/actions.rb
- The chef-backup gem later runs a reconfigure on add-ons
  This uses 'enabled_addons' to determine which addons are present; that
  uses the presence of the base dir that should contain the add on config file to
  indicate the add on is there, e.g. '/etc/opscode-analytics' for 'opscode-analytics.rb'
  However in this case, opscode-analytics isn't installed.
  Believing it is installed, we run 'opscode-analytics-ctl reconfigure',
  and fail.
  see:
  https://github.com/chef/chef_backup/blame/master/lib/chef_backup/helpers.rb

I suspect that this has been broken for a while, as most of this code hasn't changed recently.

**Comment by kbruner** [comment]
In fact, I was just trying to test restoring a backup made with `chef-server-ctl backup` on a 12.5.0-1 chef server to another server running the same version, and I get that same error.

**Comment by stevendanna** [comment]
@markan So do we think this is fixed in the latest release based on your fix in chef_backup?

**Comment by markan** [comment]
It should be. @kbruner If you have a chance to grab the latest chef server and try it we would love feedback.

**Comment by PrajaktaPurohit** [comment]
@kbruner Hope this issue if fixed for you. Closing this issue since analytics is no longer supported.
