### ISSUE TITLE
 Can't connect to the PG SQL during the reconfigure

### ISSUE THREAD

**Issue by heaton88** [chef/chef-server#966]
I tried to run chef-server-ctl reconfigure on the RH6.6 OS. The chef server package is chef-server-core-12.9.1-1.el6.x86_64.rpm.
 But after I installed the package and tried to reconfigure the error occurred as below:
 [2016-10-13T04:14:10-07:00] FATAL: PG::ConnectionBad: private_chef_pg_database[opscode-pgsql](private-chef::postgresql line 164) had an error: PG::ConnectionBad: could not connect to server: Connection refused
Is the server running on host "127.0.0.1" and accepting
TCP/IP connections on port 5432?
 So I tried to modify the PG SQL Port in the file /etc/opscode/chef-server.rb but the problem still exist

**Comment by marcparadise** [comment]
Hi @heaton88 - when you encountered this error, was it on the very first `reconfigure`
you ran, or was it on a subsequent reconfigure after an earlier error?

**Comment by zimmertr** [comment]
I'm currently experiencing this error on my first run on RedHat 7.2.

**Comment by PrajaktaPurohit** [comment]
@heaton88 and @zimmertr We are very sorry you ran into these issues and it has taken us very long to get back to you. Could you let us know if you are seeing the same issues with the newer versions of Chef Infra Server? ([ChefInfraServer-13.0.17](https://downloads.chef.io/chef-server/stable/13.0.17)). I will close this issue for now. But in case the issue still occurs, feel free to repoen it with a copy of the /etc/hosts file. Thank you!

**Comment by zimmertr** [comment]
Lol I think I was just a nub. Sorry
