### ISSUE TITLE
undefined method `url' for []:Array

### ISSUE THREAD

**Issue by dongwon** [chef/chef-server#969]
## Description

Unable to install 'opscode-reporting' due to "undefined method `url' for []:Array".
## Chef Version

```

dpkg -l | grep chef
ii  chef-manage                      2.4.3-1                           amd64        The full stack of chef-manage
ii  chef-server-core                 12.9.1-1                          amd64        The full stack of chef-server

```
## Platform Version

```

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```
## Replication Case

```
curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -c stable -P chef-server

sudo chef-server-ctl reconfigure

sudo chef-server-ctl user-create admin admin admin admin@example.com 'chefadmin' --filename admin.pem
sudo chef-server-ctl org-create devops 'DevOps' --association_user admin --filename admin.pem

sudo chef-server-ctl install chef-manage
sudo chef-server-ctl reconfigure
sudo chef-manage-ctl reconfigure --accept-license

sudo chef-server-ctl install opscode-push-jobs-server
sudo chef-server-ctl reconfigure
sudo opscode-push-jobs-server-ctl reconfigure

sudo chef-server-ctl install opscode-reporting
```
## Stacktrace

```

sudo chef-server-ctl install opscode-reporting
Starting Chef Client, version 12.14.98
resolving cookbooks for run list: ["private-chef::add_ons_wrapper"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)
  - enterprise (0.10.1)
  - apt (2.9.2)
  - yum (3.13.0)
  - openssl (6.0.0)
  - runit (1.6.0)
  - packagecloud (0.2.5)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb
================================================================================

NoMethodError
-------------
undefined method `url' for []:Array

Cookbook Trace:
---------------
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:58:in `block in from_file'
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:51:in `each'
  /var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:51:in `from_file'

Relevant File Content:
----------------------
/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb:

 51:    node['private_chef']['addons']['packages'].each do |pkg|
 52:      artifact_info = Mixlib::Install.new(
 53:        channel: :stable,
 54:        product_name: pkg.split(/(chef-|opscode-)(.*)/).last,
 55:        product_version: :latest,
 56:      ).detect_platform.artifact_info
 57:  
 58>>     pkg_file = File.join(addon_path, File.basename(artifact_info.url))
 59:  
 60:      remote_file pkg_file do
 61:        source artifact_info.url
 62:        checksum artifact_info.sha256
 63:      end
 64:    end
 65:  else
 66:    addon_path = node['private_chef']['addons']['path']
 67:  end

Platform:
---------
x86_64-linux


Running handlers:
  - #<Class:0x00000006f6c9c0>::AddonInstallHandler
Running handlers complete
Chef Client failed. 0 resources updated in 42 seconds
[2016-10-14T11:06:34+09:00] FATAL: Stacktrace dumped to /var/opt/opscode/local-mode-cache/chef-stacktrace.out
[2016-10-14T11:06:34+09:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-10-14T11:06:34+09:00] FATAL: NoMethodError: undefined method `url' for []:Array


```

**Comment by wrightp** [comment]
@stevendanna The `Mixlib::Install` in  `add_ons_wrapper` needs to be instantiated with the `platform_version_compatibility_mode` option. https://github.com/chef/mixlib-install#use-an-artifact-released-for-an-earlier-version-of-the-platform

**Comment by JHBoricua** [comment]
@wrightp Can you elaborate on how to accomplish this, exactly? While your reply might make perfect sense to a seasoned chef user, for someone like me who just want to start and is trying to setup a local chef server it is not providing much value in overcoming the obstacle of not being able to install the reporting component. Do I need to pass some parameter? Do I need to edit some file? I'm not sure what to do with the info.

**Comment by wrightp** [comment]
This needs to be fixed in the source code. To force this locally you could edit file `/var/opt/opscode/local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb`

Line 52 needs to be updated like this:
```ruby
artifact_info = Mixlib::Install.new(
  channel: :stable,
  product_name: pkg.split(/(chef-|opscode-)(.*)/).last,
  product_version: :latest,
  platform_version_compatibility_mode: true
).detect_platform.artifact_info
```
Notice the additional param `platform_version_compatibility_mode`

**Comment by JHBoricua** [comment]
Thanks @wrightp . But it seems the add_ons_wrapper.rb file gets overwritten as soon as I try the install of the reporting package because it still fails and when I look at it again my edits are gone. So I guess I'll wait for the opscode-reporting package to get a Ubuntu Xenial release, which is really the crux of the issue.

**Comment by wrightp** [comment]
Ok, right. I pointed to the file that gets converged. It's still possible to force this to work by updating the source cookbook locally. I don't know the exact path off the top of my head, but a system search would find it. Of course, it's not recommended as we just need to get the fix in. I'll create a PR and reference this ticket.

**Comment by GeetP** [comment]
Hi all,
I am having VM with same configuration stated above. But while installing opscode-reporting, it again failes for the same issue "FATAL: NoMethodError: undefined method `url' for []:Array
". I modifiled "/var/opt/opscode//local-mode-cache/cookbooks/private-chef/recipes/add_ons_wrapper.rb" file as mentioned above. But issue still persist.

**Comment by stevendanna** [comment]
@GeetP Can you confirm which version of chef-server you experienced this on and provide the entire output of the command that is failing?

**Comment by bereti** [comment]
I have the same issue. Just installed the latest versions and I face the same issue. I checked the add_ons_wrapper.rb and the code is fixed "platform_version_compatibility_mode: true".

```
artifact_info = Mixlib::Install.new(
      channel: :stable,
      product_name: pkg.split(/(chef-|opscode-)(.*)/).last,
      product_version: :latest,
      platform_version_compatibility_mode: true
    ).detect_platform.artifact_info
```

The problem still persist. Any idea what might be the issue?
Using : Suse Leap 42.1 and Chef server : chef-server-core-12.11.1-1.el7.x86_64

**Comment by wrightp** [comment]
@bereti which addon are you trying to install?

**Comment by wrightp** [comment]
There are two issues in this thread. One is platform version backward compatibility. This has been fixed. The other issue is when the detected platform which gets mapped in the platform_detection scripts is used to query for an artifact in artifactory where that specific platform is not available in the artifact repo. For example, Suse Leap is detected as `suse`, but the artifact repository for a specific artifact may only contain` el` or `debian` platforms. In this case suse needs to map to el and download those files.

**Comment by bereti** [comment]
I was about to install the Chef-Manage addon. The solution was to download the addon and reconfigure the chef server after the install. Most probably the SUSE > is not mapped correctly and an empty URL is returned.

**Comment by wrightp** [comment]
Our suggestion at this time is to download and install the addon package as described above.
