### ISSUE TITLE
chef server welcome page cannot be disabled

### ISSUE THREAD

**Issue by theckman** [chef/chef-server#972]
Hello,

I'm running an open source version of the Chef server, with nodes that connect to the Chef server over the WAN. Current versions (`12.x+`?) of the Chef server have a web page that's displayed to the world indicating it's a Chef server. I've included the contents of the page below.

I've done some digging, and I haven't found a way to disable it, without the equivalent of `echo '' >` in to the `index.html` file. I hope I haven't missed the docs, if so I apologize for the waste of time.

Would it be possible to add an option to disable this landing page? Although I suppose one could argue I'm asking for a layer of security by obscurity, I'd prefer not to announce to the world that this endpoint is a Chef server.

My initial idea is that blank `index.html` page being rendered during the `chef-server-ctl reconfigre` run, based on an attribute in the Chef server config file, would be one way to solve this.

Thank you for your time!

```
Are You Looking For the Chef Server?

Hello! It looks like you were trying to browse to your Chef Server but you haven't installed the Management Console.

If you prefer, you can access the server programmatically with the Chef Server API. To learn how to do this, head over to our API Documentation pages.

If you do want to use your browser to manage your server, then install the Management Console. It's free for up to 25 nodes.

One way to install the Management Console is to log in as root and type this command:

 # chef-server-ctl install chef-manage 

Alternatively, you can download the Management Console as an installable package from the Management Console downloads page.

You may also be interested in our other add-ons. These are available as packages from our Chef Server downloads page or you can type chef-server-ctl install. Without arguments, the command lists the packages available for installation.
```

**Comment by stevendanna** [comment]
👍 on being able to turn this page off.  I think it is helpful to have on by default for people who get confused by the lack of a web interface, but we should be able to toggle it off.

**Comment by ketank-new** [comment]
one way to also to obtain the chef-server landing page is as follows

1) install chef-server rpm
2) run the chef-server on specific port number <port no>
3) re check if the chef-server process is running in process manager using 'ps' command
4) to obtain the landing page use ' wget localhost:<port no>' .. you should get indx.html


Let me know if this helps

**Comment by theckman** [comment]
@ketank-new I'm not sure your comment is relevant. This ticket is asking for a way to *disable* the page from being displayed by the Chef server. How would downloading it from a Chef server help you not display it on the public Internet?
