### ISSUE TITLE
Disabling redirect with "non_ssl_port" and "enable_non_ssl" does not work as expected.

### ISSUE THREAD

**Issue by vskubriev** [chef/chef-server#973]
I tried to setup chef-server version "12.9.1-1" on ubuntu 14.04.

I found that some variables can help me to solve this issue. I successfully set their in "/etc/opscode/chef-server.rb":

```
nginx['enable_non_ssl']  = true
nginx['non_ssl_port'] = "80"
```
Also I have done reconfiguring server by `chef-server-ctl reconfigure` nginx 
Nginx became to listen 80 port.

But unfortunately server redirects to https port. So I cannot setup my own nginx server with valid ssl certificates and point upstream to internal machine.

Disabling redirect with "non_ssl_port" and "enable_non_ssl" does not work as expected.

**Comment by rbecheras** [comment]
@vskubriev why did you closed your issue ? I get the same one. 

Did you fixed it ? If so, please let me know how you did it.

**Comment by vskubriev** [comment]
This is fixed. But:

at first: use more recent version of chef-server cookbook
at second: I forgot exact actions to resolv issue

Maybe this will help:

```
 41     "chef-server": {
 42       "version": "latest",
 43       "addons" : [ "manage" ],
 44       "accept_license" : true,
 45       "api_fqdn" : "chef.example.com",
 46       "configuration": 
 47         "nginx['enable_non_ssl'] = true\n"
 48         }
 49     },

 51   "run_list": [
 52     "recipe[sudo]",
 53     "recipe[openssh]",
 54     "recipe[chef-server::default]",
 55     "recipe[chef-server::addons]"
```

part of node config of chef solo:

```
  5   "automatic": {
  6     "ipaddress": "chef.example.internal"
  7   }
```

This is data from latest configs. Pay attention on line 47.

There is my nginx site conf:

```
upstream backend-chef {
    server 10.2.5.6:80;
}

server {
  listen 80;
  server_name chef.example.com;
  return 301 https://$server_name$request_uri;
}

server {

	listen 443 ssl;

	server_name chef.example.com;
	client_max_body_size 0;

	keepalive_timeout   60;
	
	; here are ssl settings of certificates

	access_log  /valid/path;
	error_log  /valid/path;


	location / {
		proxy_pass http://backend-chef;
		include /valid/path;
	}
}
```

Hope this help.  Good luck!
