### ISSUE TITLE
Replication should support push/publish as well as a pull model

### ISSUE THREAD

**Issue by pburkholder** [chef/chef-server#98]
I have a customer for whom the enterprise security requirements are easier to meet when the secondary Chef servers run a sync service, instead of sync client. Just like we allow knife to upload cookbooks, it would be preferable in certain circumstance to have the primary push policy to the secondaries.  I suppose it could work like this:

    PRIMARY                              SECONDARY

    C ->          establish connection         -> S
    C <-          ok                           <- S

    C ->          GET /update/latest           -> S
    C <-          200 OK 12345                 <- S

    C ->          POST /update/data {new data} -> S
    C <-          200 OK 23456 received        <- S

Would that be feasible?

**Comment by stevendanna** [comment]
@pburkholder Internally, I think you should talk with Charles Johnson re the roadmap for v2 of federation.  What you seem to be asking for is a consistent, synchronous sync rather than the asynchronous model of chef-sync currently.  It is possible, but would require significant work (likely a redesign of Chef Sync).

**Comment by charlesjohnson** [comment]
Clarification: "Have the primary push policy to the secondaries," rather than the secondaries pulling policy from the primaries?

Or do we mean bi-directional sync, and "have the secondary publish policy to the primary?"

**Comment by pburkholder** [comment]
@charlesjohnson In this case, the former: "Have the primary push policy to the secondaries,"

**Comment by charlesjohnson** [comment]
Added this to my backlog for consideration, but I have to say I'm not convinced we should implement this.

It seems much less secure to me to have an outside actor reaching into a security realm to touch an API to initiate change, rather than having actors reach out of that security domain to poll a data API.

**Comment by pburkholder** [comment]
That's cool. I'd rather have an issue closed as "Won't Fix (anytime soon)"
than never have it brought up at all.

On Mon, Feb 23, 2015 at 1:33 PM, Charles Johnson <notifications@github.com>
wrote:

> Added this to my backlog for consideration, but I have to say I'm not
> convinced we should implement this.
>
> It seems much less secure to me to have an outside actor reaching into a
> security realm to touch an API to initiate change, rather than having
> actors reach out of that security domain to poll a data API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef-server/issues/98#issuecomment-75602224>.
>



-- 

*Peter Burkholder* — Customer Success Engineer

Availability: no travel/OOO scheduled

301-204-5767 – pburkholder@chef.io – *my: *Linkedin
<http://www.linkedin.com/in/pburkholder>  Twitter
<http://www.twitter.com/pburkholder>  Cal
<https://www.google.com/calendar/embed?src=pburkholder%40chef.io&mode=WEEK>
endar

*CHEF*

CHEF.IO <http://www.chef.io/>

TM

*chef.io* <http://www.chef.io/>   Blog <http://www.chef.io/blog/>   Facebook
<https://www.facebook.com/getchefdotcom>   Twitter
<https://twitter.com/chef>   Youtube <https://www.youtube.com/getchef>
